### ISSUE TITLE
Missing support for Decisions["registrationDecisions"] in ProgramEncounterCancel

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-client#1000]
We currently update Decisions["encounterDecisions"] in ProgramEncounterCancel to ProgramEncounterCancel.observations and Decisions["enrolmentDecisions"] to ProgramEncounterCancel.ProgramEnrolment.observations.

But we are missing support for Decisions["registrationDecisions"] in ProgramEncounterCancel.
This is not the case with ProgramEncounter.

Check the missing functionality by comparing ProgramEncounterCancelState.executeRule() and ProgramEncounterState.executeRule() methods.

**Comment by vinayvenu** [comment]
### Testing notes
- Write a rule to add registrationDecisions for ProgramEncounterCancel
- Ensure rule works in avni-client
- Ensure rule works in avni-webapp
- Ensure rule works during csv upload (optional)

**Comment by vinayvenu** [comment]
On avni-webapp, registration decisions are not added

On avni-client, I get this error




![Image](https://github.com/avniproject/avni-client/assets/344222/946c00df-09cc-4f0d-ab96-cd69a7cf2882)

**Comment by 1t5j0y** [comment]
Fixed crash on client. Moving to ready to implement support on webapp.
