### ISSUE TITLE
Issues with notes dataType concept in questionGroup

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-client#1001]
**Describe the bug**

1. In the summary page this concept value is not shown
2. Not showing value in the edit scenario

**To Reproduce**
Steps to reproduce the behaviour:
- Create QuestionGroup add Notes data type question
- Fill up the encounter and check the summary
- Edit the form and see(the value will not be there)

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing? - No
- [x] Are you mentioning the required scenarios that could be affected?

**Scenarios to test:**
- Notes datatype with non-primitive datatypes and only primitive datatypes used in form(non-primitive datatype - eg: phone number)
- readonly 
- inside question group and without question group and with repeatable question group

**Comment by mahalakshme** [comment]
changes in models and client

**Comment by vinayvenu** [comment]
@mahalakshme how did notes datatype work without the addition to the Primitives list? Was this related to the issue or more of a refactoring?

**Comment by AchalaBelokar** [comment]
- [ ]  when I added Phone number  on question. 
- [ ] Organisation name Image issue User Id : AchalaB@im.
- [ ] when I am trying to edit the individual app is getting crashed
- [ ] try to edit the Gjj Vn individual click on next button app is getting crashed

**Comment by mahalakshme** [comment]
@AchalaBelokar this is not a bug. The crash is happening because you have saved the individual "Gjj Vn" when "Required document" question group was not repeatable. So it is crashing after making it repeatable.
