### ISSUE TITLE
Support Locations in Dashboard filters

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1002]
Location concept datatype is not currently supported in the Dashboard. As an implementer, I would like to support these filters on the dashboard

### Acceptance criteria
- When a Location concept is provided as a filter on Dashboard Filters, then the relevant visualisation is shown on avni-client
- The visualisation will be similar to how the concept is displayed on filling in the form (metadata present in the concept will be useful to figure this out
- Selection will be multiselect
- Values chosen in the Location fields are available for non-standard filters
- Standard filters will be able to filter these concepts

**Comment by petmongrels** [comment]
- Subject filter to support selection based off fixed list (not search)?
- We store locations in two ways. Catchment locations and outside catchment locations. Should the filter show both set of options?

**Comment by vinayvenu** [comment]
@petmongrels 

- We have a default visualisation for Subject select when filling a form. It is search-based
- The filter should show both inside and outside catchment locations since the search is on an observation. These details (the lowest and highest address levels, whether the value should be within catchment or not) are available in the concept metadata.

**Comment by vinayvenu** [comment]
Removed subject support from the card.

**Comment by himeshr** [comment]
Included Location DataType concept in ConceptDataType.dashboardFilterSupportedTypes of Avni-server.
