### ISSUE TITLE
Search does not work well when address levels are at a different level

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#1003]
### How to reproduce
- Create an address level structure like this - Country -> State
- Create a subject type with address level Country (not the lowest level)
- Create 2 countries - India and Srilanka. Create some states under it
- Create a user with a catchment that contains both countries
- Sync on client, create a subjects of the type mentioned before. 
- Hit the search button and search with location "India". Remember, search button will be available only if there are atleast 5 subjects on the device
- Notice that the search does not return the correct values

Search typically works when the address level is at lower levels, but does not when the address levels are at a higher level

**Comment by Dinesh2019** [comment]
If we give the search with the country we are not getting search result .
env: Staging
User : dinesh@testrule
Step to reproduce
1.Create the address level country -- >state
2.Sync the client
3.Click on the search click on the country result should displayed with relevant date 
https://images.zenhubusercontent.com/64590403/aab87241-0a78-449e-8f0a-9331356d2d13/record_2023_06_13_16_20_14.mp4

**Comment by 1t5j0y** [comment]
@Dinesh2019 Issue seems to be due to incorrect location type hierarchy setup in the org used for testing
![image.png](https://images.zenhubusercontent.com/5d8a51c647755200010d2fda/32f2aa2d-2f3e-4db9-bee8-ac3c3c2dfe7e)

Please retest with a fresh org with a correct location hierarchy.

**Comment by Dinesh2019** [comment]
If we create the subject with the address level country and state. And if we try to search at the country level search result is not displayed 
Steps to reproduce
1.Create the subject type address level till state
2.Register the individual
3.Go to search and search at high level
Excepted : search should display the indvidual register at the address
Actual : showing result as zero at high level

https://images.zenhubusercontent.com/64590403/28822f83-0d63-42a0-8371-ce82cc2d7be8/record_2023_06_14_18_24_37.mp4

**Comment by 1t5j0y** [comment]
Reverted the earlier fix (which did not handle all scenarios) in master and pushed a new fix to 3.40

**Comment by Dinesh2019** [comment]
Still we face the same issue as mentioned above

**Comment by Dinesh2019** [comment]
we have the search filter shows different search result if we select the state and  after that changing the subject .



https://github.com/avniproject/avni-client/assets/127730126/84b1145b-8bb4-4e2e-ade8-7279c76e5f69

**Comment by 1t5j0y** [comment]
The latest reported bug is a pre-existing bug and not directly related to this issue but have added a fix to update the state with previously selected search filters if they are applicable to the new subject type as well (since the UI continues to show the previously provided values in this case).

**Comment by nupoorkhandelwal** [comment]
https://images.zenhubusercontent.com/64590403/df57d4f7-3e7d-468c-bd8b-941b87d592d1/whatsapp_video_2023_07_20_at_16_14_40.mp4

**Comment by nupoorkhandelwal** [comment]
@vinayvenu  There is still some issue with the Search, not sure how to reproduce this on an another instance, but here when i am select NA District under Assam then the search is not working properly. please refer video attached,

**Comment by vinayvenu** [comment]
Moved to 4.0.0 because of issues reported.

**Comment by Dinesh2019** [comment]
@Vinay The issue arises when we have the hierarchy as country, state, district, and city as the lowest level. If we create the location up to the city and register the individual up to the district, the search works as expected. However, if we create the location up to the district without specifying the city, the search does not work as expected.
sample data with district as city as lowest hierarchy:
web app;
![Image](https://github.com/avniproject/avni-client/assets/127730126/f4676384-8026-4677-9be5-978dfabfc45b)

client app:
https://github.com/avniproject/avni-client/assets/127730126/e22a465c-c0c2-417b-893a-da2c0c63478d

webapp;
![Image](https://github.com/avniproject/avni-client/assets/127730126/7fe0a6c2-20e4-419c-9d4a-42205677b8e2)


client app:
https://github.com/avniproject/avni-client/assets/127730126/e4831232-0ec5-4ecc-9066-1b79509699ea

Note : i think we have to fix this for all hierarchy level

**Comment by ashusvnath** [comment]
Search results return the correct value for the use case specified above

**Comment by ashusvnath** [comment]
The search filter component for address hierarchy seems to be broken.

Creating a new bug #1059 for this as it is not because of  the bugfix being verified based on a discussion with @1t5j0y 

![Image](https://github.com/avniproject/avni-client/assets/568925/7079b523-bccd-4c81-8939-462a7468e089)
![Image](https://github.com/avniproject/avni-client/assets/568925/0e68097a-e59e-4a56-a6fe-45b94bcb6c31)

**Comment by ashusvnath** [comment]
If a subject type allows multiple levels of address, and a search is performed across multiple levels, only the lowest levels are returned as part of search results.
Eg:
Subject type CitizenOfState -> allows Country, State, District for lowest level of address
on client, when a search is initiated, the filter behaves in the manner shown in the screenshot in the previous comment.
For more understanding: try using user@suhaz login on staging.

**Comment by ashusvnath** [comment]
The behaviour observed when searching across different address levels is that only the lowest address levels are being honoured in the search and the higher levels are being ignored.

eg:
If search filters for location is selected as  'India' and 'Jaffna' (sri lanka->northern->jaffna), only results matching Jaffna are returned.

**Comment by Dinesh2019** [comment]
Testing Notes:

1. Register the individual from higher to lower levels (country, State, District, City)
2. create the location as country, state, District,city
3. create the location as country, state,district, None
4. create the location as country, state, None
5. create the location as a country, None
6. create the subject types which the lowest address level as a country alone like creating the subject type of rest all 
7. Now search the individual as step 2 it should display the relevant data for eg: the city is selected as Chennai it should display only the Chennai data
8. search the individual as step 3 t should display the relevant data for eg: the city is selected as Kanchipuram it should display only the Kanchipuram data
