### ISSUE TITLE
Show and remember Dashboard applied filters

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1004]
As a user of Dashboard Filters, I need to be able to
- See if a filter has been applied and
- Remember the filter so that if I go to a different screen and come back, it is retained

### Acceptance criteria

- [x] When a dashboard filter is applied, then it is saved until a user removes that filter
- [x] Saved Filters are applied to the dashboard cards when the Dashboard is loaded
- [x] Filters applied on the dashboard are visible on the dashboard so that the user is aware that there is a filter applied on the dashboard cards
- [x] Changes in filter setup from the App designer should not break the app
- [x] "Clear all filters" button is present in  "AppliedFilters" section
- [x] Filters are retained even when we switch across different dashboards and should be persisted across app restarts

>  - Save it with checksum based on DashboardFilterConfig
>  - Refactor AppliedFiltersV2
>  - Save in DB
>  - On checksum mismatch thrash old cached values and start afresh

- [x] Fix support for different dataTypes
> - Locations (working)
> - Time (Range and specific value) (Working)
> - DateTime (Working)
> - Gender (Working)
> - Number (Range and specific value) (Working)
> - Coded concepts (Working)

**Comment by himeshr** [comment]
## Test Offline Report card rule for Gender and 'Age at marriage':

`// Documentation - https://docs.mongodb.com/realm-legacy/docs/javascript/latest/index.html#queries
'use strict';
({params, imports}) => {
     let individualList = params.db.objects('Individual')
     .filter((individual) => individual.voided === false && individual.subjectType.name === 'Individual');
     if (params.ruleInput) {
       let genderFilter = params.ruleInput.filter(rule => rule.type === "Gender");
       let genderValues = genderFilter[0].filterValue.map(fv => fv.name);        
       individualList = individualList.filter( (individual) => {
         return _.includes(genderValues, individual.gender.name);
       });
       let marriageAgeFilter = params.ruleInput.find(rule => rule.type === "Concept" && rule.observationBasedFilter.concept.name === 'Age at marriage');
       if(!marriageAgeFilter) {
         return individualList;
       }
       let marriageAgeFilterValue = marriageAgeFilter.filterValue;  
       return individualList.filter( (individual) => {
         return individual.getObservationValue('Age at marriage') && marriageAgeFilterValue == individual.getObservationValue('Age at marriage');
       }); 
     } else {
       return individualList;
     }
};`

**Comment by himeshr** [comment]
We have not persisted the filters in DB for customDashboards, we have only made use of state to store the current CustomDashboard's filter.
Code changes in avni-client(3.39) branch and avni-models(3.39) branch.
Made use of Pre-release "Sakhiapp" organisation for dev testing. https://images.zenhubusercontent.com/64590403/98397ba6-08a7-41c2-be60-5fc27b467b46/screen_recording_2023_06_14_at_10_04_26_am.mov


https://github.com/avniproject/avni-client/assets/72493481/f0b6f41f-432d-418e-9a5c-211660109d49

**Comment by petmongrels** [comment]
In FilterActionsV2 what is the requirement for transformFilters? The filter values already can be populated based on the filledFilterValues state field, so not clear the reason for transformation.

There are few other issues in the code but need to understand this first.

**Comment by himeshr** [comment]
FiltersActionsV2.transformFilters() is used to generate objects with the format expected by AppliedFilters props : 
- selectedCustomFilters
- selectedLocations and
- selectedGenders

**Comment by petmongrels** [comment]
We need a V2 of AppliedFilters that uses DashboardFilter and DashboardFilterConfig like FilterViewV2. And deprecate the current AppliedFilters component. This will mean rewrite of the story, so we can do it some other time.

We should remove usage of == in AppliedFilters.renderCustomFilters. FiltersActionsV2.transformFilters should not be anonymous function.

**Comment by himeshr** [comment]
Absorbed following code review comments:
_We should remove usage of == in AppliedFilters.renderCustomFilters. FiltersActionsV2.transformFilters should not be anonymous function._

**Comment by petmongrels** [comment]
@himeshr we will have to pair on this code once.

**Comment by himeshr** [comment]
Pending corrections:
- [ x]  double-equals replace with type strict equals check "==="
- [ x]  refactor name of cachedData method
- [ x] minimize selectedLocations content in transformedFiltersJSON


**Didn't do:**

- We'll continue to retain the full content for selectedValuesJSON and ruleInputJSON, as we do not control their init and population as part of a single function but is dependant on the various FilterElements of different dataTypes.
- the transformedFilters switch statement retained as is, since we have large number of dataTypes with different logical mappings as seen in other methods.

**Comment by AchalaBelokar** [comment]
This is happening on Staging for user dinesh@apf 

- [ ] but in the dashboard filter object object is coming

![Image](https://github.com/avniproject/avni-client/assets/104890488/23bfdcb3-657a-4526-9a3c-27566d5e9b0e)

**Comment by himeshr** [comment]
Fixed the bug for Display of Coded concepts as seen below for "Povert line" concept:


![Image](https://github.com/avniproject/avni-client/assets/72493481/bc11e021-14ce-474a-a84d-4ed646a168df)

**Comment by AchalaBelokar** [comment]
- [ ] Unable to see the Individual when clicking on the offline dashboard card. it is showing me error

![Image](https://github.com/avniproject/avni-client/assets/104890488/e6dcdb12-52ee-423a-b1fa-f95d11a4ecd9)

on prerelease env..

Also filter is not working

**Comment by himeshr** [comment]
Issue was caused by missing update of ruleInput.ruleInputArray in CustomDashboardActions.refreshCount().
And wrong attribute usage in CustomDashboardActions.onCardPress().

https://github.com/avniproject/avni-client/assets/72493481/20d458f8-252b-40b1-9adc-383a2e9d13b9

**Comment by himeshr** [comment]
Also made code changes to handle Location DataType Concept.

https://github.com/avniproject/avni-client/assets/72493481/d8d0ce7a-e1da-4bd4-b6f1-3ef7bfc038b5
