### ISSUE TITLE
Duplication of subjects in Subject Program Eligibility Check on groups

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1005]
### To reproduce
- Set up an Subject Program Eligibility Check from the Subjects screen of the App designer for a group subject type
- Run the check once. Ensure there is atleast one program for the check
- Remove a member and add the member once again
- Notice that the removed member is present twice in the eligibility results section

Also, documentation for subject program eligibility check rule needs to be added

**Expected** - Show eligibility of current members of the group only

**Comment by nupoorkhandelwal** [comment]
https://images.zenhubusercontent.com/64590403/621c5520-6ff3-4e0e-bec8-0bfe4d582975/whatsapp_video_2023_07_20_at_16_30_56.mp4

**Comment by nupoorkhandelwal** [comment]
@vinayvenu The issue is still reproducible on PoWER, the app still shows eligibility of old/removed members.

**Comment by vinayvenu** [comment]
@nupoorkhandelwal please wait for the 4.0.0 release for the changes to show up.

**Comment by nupoorkhandelwal** [comment]
@vinayvenu not sure why this was marked as 3.40 --
https://avni.freshdesk.com/a/tickets/2661

**Comment by vinayvenu** [comment]
We moved out a lot of scope from 3.40 to 4.0. This would have been one of them. Moving back to closed. Open if you feel it is not working in staging.
