### ISSUE TITLE
Numeric concepts need not be allowed to type space

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1008]
Steps to reproduce:
When space entered stores as zero but in observations shows empty space.
https://images.zenhubusercontent.com/64590403/643067d3-7690-4474-838b-4199d45e1fe3/screen_recording_2023_06_05_at_7_51_31_pm.mov

Expectation:
- Try entering characters. It gets removed immediately. Similarly space can also get removed.

Analysis:
It doesn't get removed because in _valueFromString() in PrimitiveValue.js in avni-models `!isNaN(parseInt(this.value))` returns false, and hence `toNumber` doesn't get executed.

**Comment by himeshr** [comment]
@mahalakshme please prioritize this, as it could easily cause ETL failure in multiple orgs for a simple user typo.

**Comment by himeshr** [comment]
After discussion with Maha decided that,  this needs to be reproduce on latest version of client and then see if needs to be prioritized..

**Comment by himeshr** [comment]
Unable to reproduce this issue using Prod APKs for 6.0.2 or 5.0.4..


https://github.com/avniproject/avni-client/assets/72493481/19d1ccc4-3a36-49ba-ba31-f3d899fe6f4d
