### ISSUE TITLE
[bug] Issue with add relative for non individual subject type.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-client#1013]
- If user try to all a non individual as relative, app crashes w/o any warning.

- Also, when a relative is added, it does not show on sync button.

![Screen Shot 2021-11-18 at 3.46.38 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/6ac1b4e7-c223-4dbb-ab7f-c703d624d3c4)

**Solution Approach**
When a user searches for subjects to link as relatives, restrict the user selection of subject types to person subject types

**Testing Notes**
All flows where relatives can be added. Regression test other flows where subjects are searched.

**Comment by ghost** [comment]
Any update on this?

**Comment by 1t5j0y** [comment]
Test: All flows where relatives can be added. Regression test other flows where subjects are searched.

**Comment by AchalaBelokar** [comment]
- there is already bug in subject search https://github.com/orgs/avniproject/projects/2/views/1?pane=issue&itemId=30755958
