### ISSUE TITLE
Clearer age display for children

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1016]
When we deal with growth of children, accuracy of the age is important. Between 1 and 6 years, it will be useful to show the age in years and months (eg: "1 year 2 months" instead of "1 year" as shown now). 

### Acceptance criteria
1. The following logic is used to show the age
Under 1 week  - Age in Unit 'days'
Under 1 year - Age in Unit 'weeks'
Under 2 years - Age in Unit 'months'
Under 6 years - Age in Unit 'years' and 'months'
After 6 years - Age in Unit 'years'

eg: 
```
    0 days
    2 days
    6 days
    1 week (week format starts here)
    12 months
    16 months 
    5 years 11 months (last value with months)
    6 years
    7 years
```

2. The change in logic is shown on the Search results, Subject Dashboard and Dashboard search results

**Comment by mahalakshme** [comment]
for less than 2 years currently we are showing in months. Eg: we show as "14 months" not as "1 year 2 months". Since the threshold to show in months is now 6 years, will change that as well to show as "1 year 2 months".

**Comment by mahalakshme** [comment]
Arjun suggested to retain displaying in months for less than 2 years child since it was done for some reason and it could be that they refer the child as say 14 months child. So for less than 2 years we will continue to display in months and from 2 years - 6 years we will display in "n years n months" format.

**Comment by 1t5j0y** [comment]
Reopening as this needs to be retested as there were changes to the fix based on code review comments

**Comment by AchalaBelokar** [comment]
- [ ] Individual summary page the months is not reflecting...same as web app

![Image](https://github.com/avniproject/avni-client/assets/104890488/7280a932-650a-4102-bcce-1e2834a138d5)

**Comment by mahalakshme** [comment]
Enough to review this commit: cf35328bc2559a23a2fe67b4c538bdaab38ae753 alone

**Comment by AchalaBelokar** [comment]
- [ ] Bcz of this power engine is failing..we  need to fix this issue

**Comment by mahalakshme** [comment]
Need to only review commit: ae67485cda86783a73e92eb56eeb7f0c3ce72218 in avni-models

**Comment by AchalaBelokar** [comment]
- [ ] Eligibility engine is failing not able to test that scenario ...it is having network issue network issue
