### ISSUE TITLE
Entities that are approved are showing as pending on dashboard 

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-client#1018]
https://avni.freshdesk.com/a/tickets/2773

### How to reproduce
- Set up approvals for a subject type
- Approve from one device
- Sync on another device
- The entity should show as approved in the second device, however it shows up as pending. Looking at the database, approvalStatuses are correct, however the latestApprovalStatus on the Individual is marked as "Pending". 

### Analysis
We had recently moved ```EntityApprovalStatus``` from being a separate entity to the child of the parent entity that it is associated with (as an array ```Entity.approvalStatuses```). This change was to ensure clean retrieval of ```EntityApprovalStatus``` wherever it was needed instead of going through a service call. While doing this, we still maintained the existing "latestApprovalStatus" on the entities (Individual, ProgramEnrolment, Encounter, ProgramEncounter and ChecklistItem). This was mainly for performance reasons - fast rendering of the Dashboard cards and Approval Listing screen.

Since we moved away from an independent table to a child table of entities, the ```Entity.approvalStatuses``` was being stored using the```merge()``` method of the Entity. This method takes a list of ```Entity``` objects coming from the page that is being synced, and merges the ```Entity.approvalStatuses``` array. It pickes one of the parents in the array and returns to be saved. This ensures that there is just a single save of the ```Entity```. However, the ```latestEntityApprovalStatus``` of this parent entity can be different, therefore the value that is stored can be incorrect. 

There is no "bad data" impact of this since entities wrongly showing as approved or pending cannot be modified from the app. The issue here is that this reporting field used for the dashboards needs to be fixed with the right value. 

### Solution
- Update ```Entity.latestApprovalStatus``` with correct values with a migration
- Modify sync logic to correctly populate ```Entity.latestApprovalStatus

**Comment by vinayvenu** [comment]
App has been uploaded to Beta on the playstore. version 3.39.2

**Comment by petmongrels** [comment]
Code written by three people. Moving to QA ready.
