### ISSUE TITLE
Not able to select the gender option in Search and Filter screen

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/avni-client#1020]
**Describe the bug**
Not able to select Gender option (Male/Female/Other) in Search screen and on the Filter screen as well.

**Steps to Reproduce**
- Login to any implementation app on prod which has Gender filter configured.
- Click on the Search option.
- On the Search screen, try to select Male, Female or Other in the Gender option.
- Not able to select any of the options.
- The same output is observed when clicking on Filter from Home screen and while trying to select the gender in the options.

**Expected behavior** 
- The option should be selected as per the choice.

**Comment by AchalaBelokar** [comment]
- [ ] I search on prerelease env in adsr org the app is getting crashed. dinesh@adsr
- [ ] I used this apk https://app.circleci.com/pipelines/github/avniproject/avni-client/1791/workflows/4efc4294-4d50-4c5b-9e3e-dc75a338c0c0/jobs/11185
- [ ] I uploaded server also
- [ ] Also app is crashing while adding individual  to household if there is search screen present

**Comment by ashusvnath** [comment]
Tested

1. top level filter for default dashboard
2. search filter for individuals
3. filtering of dashboards assigned to user


The gender filter works in the above 3 places.

Code changes available in master.
