### ISSUE TITLE
For some entities approval entry is not present in entity_approval_status.

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-client#1022]
## Ticket related: https://avni.freshdesk.com/a/tickets/2775

**Describe the bug**
For some entities approval entry is not present in entity_approval_status. due to this, some summary rules are breaking.
Found this issue in rwb2023, rwbngos2023 and gdgsgom implementations.

Script to get a list of encounters which don't have approval entry.
`select *
from encounter where id not in (
select entity_id
from entity_approval_status  where entity_type='Encounter' )`

Script to get a list of individuals which don't have approval entry.
`select *
from individual where id not in(
    select entity_id
    from entity_approval_status  where entity_type='Subject'
    )`

**To Reproduce**
Steps to reproduce the behaviour:
Not able to reproduce.

**Comment by vinayvenu** [comment]
Closing and creating multiple other cards

https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/1024

https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-server/563
