### ISSUE TITLE
Location Filter  are not deselected properly according to the hieracrchy

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1023]
We have to hide or deselect the location according to the hierarchy but we found the issue if we deselect the hierarchy level 3 we can able to see the level 1 is selected and displayed.
issue tested in both staging and UAT
Staging user : dinesh@Testdin
UAT user : dinesh@dfad_trial
Steps to reproduce
1. Add the location is the lowest hierarchy level 3,2,1
2.Go to search
3.Select all the level 
4.deselect the 2 level 
Excepted result : 2 and 1 should be deselected and should not displayed
Actual result : 1 is selected and displayed 

refer below video:
https://images.zenhubusercontent.com/64590403/78bede3b-bacb-423e-91bd-5b2c9413567f/record_2023_06_14_18_51_01.mp4

**Comment by mahalakshme** [comment]
@Dinesh2019 this was fixed in 7.0 release. Let me know if you think otherwise.
