### ISSUE TITLE
Introduce new method IndividualService.getSubjectByUUID() in avni client, webapp and rules-server

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-client#1033]
- There is a requirement in one of the implementations to access a different SubjectType's instance observation values during FormElementStatus rule evaluation.

- To support such scenarios we currently follow the approach specified [here](https://avni.readme.io/docs/writing-rules#using-service-methods-in-the-rules
 ) to fetch Subjects of different type, by invoking IndividualServiceFacade.getSubjectsInLocation(addressLevel, subjectTypeName);

- But in this implementation's case the addressLevel info is not available.
Therefore, we need a getSubjectByUUID(uuid, subjectTypeName) to be exposed in avni client, webapp and rules-server.

- Draft method to be used in avni-client:
// IndividualService.js:
    getSubjectByUUID(uuid) {
        return this.findByUUID(uuid);
    }
// Expose this in IndividualServiceFacade.

- IndividualService in webapp should only have dummy method.
- IndividualService in rules-server should use api calls to fetch the info
- Update documentation on using this new method when needed.

**Comment by ashusvnath** [comment]
Code changes complete.

Tested on dev machine with @BEULAHEVANJALIN  and lots of help from @mahalakshme and @himeshr .
Need to figure out how and which environment to deploy these changes to.

Code changes available on : 

avni-client - 3.39.2
avni-webapp - 3.39
rules-server - 3.39

**Comment by ashusvnath** [comment]
Dropped `AndType` part from all code implementation.

**Comment by petmongrels** [comment]
Question about this message "getSubjectsInLocation method is not supported for DEA" and others like this

we are supporting these methods by RulesServer which supports the DEA. Hence the message doesn't seem clear (although can understand the purpose of throwing error). We should perhaps be explicit about we don't support for which type of rules.

**Comment by ashusvnath** [comment]
Discussion outcome:
Decision rule and Subject summary rules are evaluated in the rules-server, rest are evaluated on the web-app itself.
Need to document what rules are supported and where @ https://avni.readme.io/docs/writing-rules.
The error message can then read "Not supported please see https://avni.readme.io/docs/writing-rules"

**Comment by ashusvnath** [comment]
Created table : https://avni.readme.io/docs/writing-rules#types-of-rules-and-their-supportavailability-in-data-entry-app


Reviewed once with @petmongrels . Need to validate if the entries are correct in webapp.

**Comment by ashusvnath** [comment]
Code review comment addressed.
