### ISSUE TITLE
The last two card not displayed fully in the offline dashboard 

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1034]
When we have the more card in the offline dashboard the last row card is getting cut or not displayed properly.We able to see the card name and it is interactable.
ENV: UAT
org :apfodishauat
user ; dinesh@apfodishauat
Step to reproduce: 
1.login to the client app
2.Click on the more
3.Cick on the Dashboards
4.Click on the Dashboard tab
5.Scroll down you can able to see the card displayed improperly
Expected result : card should be displayed properly
![image](https://github.com/avniproject/avni-client/assets/127730126/9db1e6bc-9f7b-4d28-bb9e-59c7e849f017)

org ; dinesh@dineshbootcamp
![image](https://github.com/avniproject/avni-client/assets/127730126/7b69f962-1ea6-4a41-8312-c27161e472d0)

**Comment by himeshr** [comment]
In some cases the text is not at all seen, so becomes difficult to know what numbers the card is pointing at..
<img width="543" alt="Screenshot 2023-06-26 at 3 43 17 PM" src="https://github.com/avniproject/avni-client/assets/72493481/f9496e83-f072-4f44-b4df-d2d118f7f448">

**Comment by himeshr** [comment]
Code changes made in avni-client 3.39 branch.


https://github.com/avniproject/avni-client/assets/72493481/e2b71b73-e086-408e-baaf-a9a6b447de70

**Comment by himeshr** [comment]
Prerelease APK is available at https://app.circleci.com/pipelines/github/avniproject/avni-client/1814/workflows/122845b3-692e-4d53-9d4d-3bcb1d8ca6fb/jobs/11327/artifacts
