### ISSUE TITLE
Show full hierarchy on addresses

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1035]
### Acceptance criteria
- The full hierarchy of addresses should be available in the following places
1. Search results
2. Subject Dashboard (Summary section)
3. Summary and Recommendations screen
4. Search results when adding a subject observation (should be same as 1)
5. Dashboard results

Format: 

- ~Option 1 - Sample - ```District Bengaluru Urban, Block 23, Saddeguntapalya```. (Verify if this will work with long addresses, especially on search results screen~
- ~Option 2 - Try doing an expand in-place with an ellipsis~
- Option 3 - Show only first 2 levels. Sample - ```Block 23, Saddeguntapalya```: 
~- ~Option 4 - Our regular format ```Saddeguntapalya (District Bengaluru Urban->Block 23```~

### Testing notes
- Test with search result fields
- Test with person subject type (where there is name and gender)
- Test with programs
- Test without parents
- Test with multiple hierarchies

**Comment by vinayvenu** [comment]
Choose option 3

**Comment by mahalakshme** [comment]
changes in models and client in 3.39 branch
