### ISSUE TITLE
Edit an autocalculated value

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1037]
### Motivation:
As a user, I would like to edit a field value populated by a rule to correct it since populated field value is on a best effort basis and need not be always correct.

### Acceptance criteria:
- Have the rule mentioned below/some other rule for value of a numeric form element
- I should be able to erase the value completely and enter a new value. What happens now: 
https://github.com/avniproject/avni-client/assets/10369963/53c7494f-e308-418c-92d0-404f4368f728 . Need to do workaround to retain a no, add new no and then remove old one.
- After editing when I move to a new screen and comeback the value should be retained, and it is the new value that should be saved. What happens now: https://github.com/avniproject/avni-client/assets/344222/62dea1ce-bc8e-414b-b113-245371243cc2
- Evaluation of rules - form_element or form_element_group, etc should be based on the newly entered value
- This could be an issue with other data types as well, just showing numeric values here. So, should work with all data types.

### Rule
```
'use strict';
({params, imports}) => {  
  return new imports.rulesConfig.FormElementStatus(params.formElement.uuid, true, "20", [], []);
};
```

### Tech solutioning
- Add a new field called `answerSource` to `PrimitiveValue`, `SingleCodedValue` and `MultipleCodedValues` in avni-models with values as `auto` or `manual`
- Set value of `answerSource` to 'auto' if setting value for the first time and the value is provided by rules
- Only update values from rules if `answerSource` is 'auto'

**Comment by mahalakshme** [comment]
not a priority since the part that was priority was fixed. moving this to 7.0

**Comment by petmongrels** [comment]
as discussed - move General.AnswerSource to maybe Observation class.

**Comment by petmongrels** [comment]
I think we are not saving observation source to the server database.
Without this I think providing support for edit form and maintaining its source is not very useful. The auto sync will happen very soon after create and the source information will be lost.

If we want to support this then we will have to keep this information out of Observation and sync to server.
Seems like much bigger piece of work.
