### ISSUE TITLE
Show full addresses need a proper alignment and spacing

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1042]
Show full addresses need a proper alignment and spacing
The address contain a many location type. the location name is short and long so we need to arrange it properly .

**To Reproduce**
1. Go to 'serach tab'
2. Select a Individual  
3. List should be appear and list contains a locations

**Expected behavior**
Locations should be in proper format
**Screenshots**
![unknown](https://github.com/avniproject/avni-client/assets/104890488/fca69fba-ecf9-426b-98f0-ed26f44400cd)

![Image](https://github.com/avniproject/avni-client/assets/104890488/060c24b5-6c05-40d0-8a5f-a909e2cea2be)

**Comment by himeshr** [comment]
Need to wait for 3.39 avni-client branch to be merged to master before working on this code change.

Patch content:

Index: packages/openchs-android/src/views/common/SubjectInfoCard.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/openchs-android/src/views/common/SubjectInfoCard.js b/packages/openchs-android/src/views/common/SubjectInfoCard.js
--- a/packages/openchs-android/src/views/common/SubjectInfoCard.js	
+++ b/packages/openchs-android/src/views/common/SubjectInfoCard.js	
@@ -74,6 +74,7 @@
         const enrolledPrograms = _.filter(this.props.individual.nonVoidedEnrolments(), (enrolment) => enrolment.isActive)
             .map((x: ProgramEnrolment) => x.program);
 
+      const subjectAddressText = _.replace(this.props.individual.subjectAddressText(i18n),new RegExp(",","g"),",\n");
         return (
             <View style={{
                 flexDirection: 'row',
@@ -122,7 +123,7 @@
                 }}>
                     <View style={{justifyContent: 'flex-end'}}>
                         <Text
-                            style={[{opacity: 0.6}, Styles.textStyle]}>{this.props.individual.subjectAddressText(i18n)}</Text>
+                            style={[{opacity: 0.6, textAlign: 'right'}, Styles.textStyle]}>{subjectAddressText}</Text>
                     </View>
                     {!this.props.hideEnrolments &&
                     <View style={{

**Comment by AchalaBelokar** [comment]
1. The location should contain lower two level but it is not showing me
2. I use this apk https://app.circleci.com/pipelines/github/avniproject/avni-client
