### ISSUE TITLE
Customise Dashboard is taking lot of time to show the result

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1043]
**Describe the bug**
Customise Dashboard is taking lot of time to show the result

**To Reproduce**
1. Go to the more
2. Click on '.Dashboard'
4. result taking a lot of time

**Expected behaviour 
Result should be show in minimum time

*"No of pregnant women took 7934 ms (result: 212)
No of deliveries took 1196 ms (result: 0)
No of births took 901 ms (result: 0)
No of children for post natal visits took 478 ms (result: 0)
No of mothers for post partum visits took 531 ms (result: 0)
No of child deaths (all) took 525 ms (result: 0)
ANC visits due took 1873 ms (result: 124)
PNC visits due took 3145 ms (result: 5)
Lab visits due took 1264 ms (result: 0)
Number of cancelled visits took 1630 ms (result: 0)
Number of completed visits took 1483 ms (result: 0)
No of maternal deaths took 924 ms (result: 4)"
This happing with jsscp

**Comment by vinayvenu** [comment]
@AchalaBelokar can you confirm if this is a regression or a new issue?

**Comment by mahalakshme** [comment]
since no reply closing this
