### ISSUE TITLE
BugSnag Error - Minified Redux Error

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#1048]
Error Fatal error: Minified Redux error #9; visit https://redux.js.org/Errors?code=9 for the full message or use the non-minified dev environment for full errors.  
    /home/circleci/avni-client/packages/openchs-android/node_modules/redux/lib/redux.js:291:62 dispatch
    /home/circleci/avni-client/packages/openchs-android/src/framework/view/AbstractComponent.js:65:63 value
    /home/circleci/avni-client/packages/openchs-android/src/views/LoginView.js:348:28 _class
    /home/circleci/avni-client/packages/openchs-android/src/views/LoginView.js:359:80 _class
    /home/circleci/avni-client/packages/openchs-android/src/action/LoginActions.js:96:40 
    /home/circleci/avni-client/packages/openchs-android/src/service/BackupRestoreRealm.js:91:11 _class
    /home/circleci/avni-client/packages/openchs-android/src/action/LoginActions.js:93:31 value
    /home/circleci/avni-client/packages/openchs-android/src/action/LoginActions.js:120:33 value
    /home/circleci/avni-client/packages/openchs-android/src/reducer/Reducer.js:22:44 
    /home/circleci/avni-client/packages/openchs-android/node_modules/redux/lib/redux.js:568:36 
    /home/circleci/avni-client/packages/openchs-android/node_modules/redux/lib/redux.js:296:36 dispatch
    /home/circleci/avni-client/packages/openchs-android/src/framework/view/AbstractComponent.js:65:63 value
    /home/circleci/avni-client/packages/openchs-android/src/views/LoginView.js:159:55 _class
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Alert/Alert.js:90:53 
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:463:12 value
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:125:28 
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:368:8 value
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:124:17 value
    [native code] value

https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/65043c7fbbb9d70007a7e068?filters[event.since]=30d&filters[app.release_stage][]=prod&filters[app.release_stage][]=production&filters[app.release_stage][]=uat&filters[error.status]=open

**Comment by petmongrels** [comment]
when dump restore fails for some reason and the user retries then this error happens and user sees white screen

**Comment by 1t5j0y** [comment]
QA notes:
White screen not shown anymore on dump restore retry. However, at the end of the retried attempt, user gets stuck with a different error - 'successCb is not a function (it is undefined)'.

https://github.com/avniproject/avni-client/assets/54208632/e5ecc1fa-9454-4481-afe5-d90ec98ef594
