### ISSUE TITLE
Numeric form element does not accept zero the very first time

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1049]
See video from 1:15

https://github.com/avniproject/avni-client/assets/344222/2a62b559-5e3d-4339-9057-0649106eae61

### Testing notes. Regression testing on
- Verify with empty values
- Zero
- Negative values
- Positive integers
- Decimals (1.50, 1.05)
- Optionals
- Rule with values
- non-numeric characters

**Comment by AchalaBelokar** [comment]
1. I am able to enter the value  negative number.. 
2. https://github.com/avniproject/avni-webapp/issues/1000 moving to the qa  fail because of this
