### ISSUE TITLE
Unable to see the more than 50 encounter and after that not able to edit that encounter

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1050]
**Describe the bug**
Unable to see the more than 50 encounter and after that not able to edit that encounter

**To Reproduce**
1. Go to any Individual who is having the more than 50 encouter
2. Click on 'view all.'
3. Scroll down to encounter  but we are not able to see the more than 50 and after 50 we are not able to edit that encounter 

**Expected behavior**
User should able to see and edit the encounter after 50 also

*

**Comment by himeshr** [comment]
We are now displaying the Previous encounters using ScrollList and have removed the restriction of showing only 50 encounters.
<img width="751" alt="Screenshot 2023-07-11 at 8 35 23 PM" src="https://github.com/avniproject/avni-client/assets/72493481/fa728d69-b2b5-4026-b3a6-71996cd3db18">

**Comment by himeshr** [comment]
Replaced SectionList with FaltList, as we dont have sections here.
