### ISSUE TITLE
Encounter and Program encounter location is not getting captured in the database

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1054]
### To reproduce
- Enable "Track Location" for a user
- Create an encounter
- Look at Realm DB for that encounter. The encounterLocation field is empty. It should have been filled. 

### Notes
This is happening for Individual and program enrolment, but not for encounter or program encounter.

**Comment by himeshr** [comment]
Issue was caused due to missing getter/setter for encounterLocation in Models AbstractEncounter.
