### ISSUE TITLE
[Spike] - Change targetSdkVersion to 33

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1056]
Caused by https://developer.android.com/google/play/requirements/target-sdk

There are changes in version 33 that might affect behaviour. See [here](https://developer.android.com/about/versions/13/behavior-changes-13) for details. 

### Testing
- General regression
- Media upload behaviour

**Comment by petmongrels** [comment]
the app seems to work fine (didn't do full regression).
the camera control via rn image picker module is not working. it crashes the app.

RN upgrade will be required as per this -
https://github.com/react-native-image-picker/react-native-image-picker/issues/2013

**Comment by petmongrels** [comment]
[sdkVersion33.txt](https://github.com/avniproject/avni-client/files/12172134/sdkVersion33.txt)
