### ISSUE TITLE
Location search filter broken, does not consider location hierarchy during display

### ISSUE THREAD

**Issue by ashusvnath** [avniproject/avni-client#1059]
**Describe the bug**
Location search filter is broken. The search filter does not consider location hierarchy during display, and shows locations out of order with some selections and deselections.

**To Reproduce**
1. Create a 2 level location hierarchy Country(10) -> State(7) -> District(5)
2. Create a Subject Type whose lowest address level can be all 3 parts of above heirarchy
3. Create a search result filter for the above subject type
4. Sync to client
5. Create some subjects of above subject type
6. Start a search for subjects of above subject type
7. Notice the strange behaviour of the location filter**Expected behavior**

**Screenshots**

![Image](https://github.com/avniproject/avni-client/assets/568925/a6ecfa85-77d0-423e-b760-d7c2694677f5)
![Image](https://github.com/avniproject/avni-client/assets/568925/fb52f096-df7b-4cea-89ef-4f1c897d7f71)

**Comment by petmongrels** [comment]
This issue seems to be related to multiselect prop being true.
Reproducible steps are:
- Select an item in all three levels and then unselect the top level item.

**Comment by vinayvenu** [comment]
Pushed to 5.0.0 because impact is only on Search, and when multiple address levels are set up for an organisation.

**Comment by mahalakshme** [comment]
fixed as part of https://github.com/avniproject/avni-client/issues/1302
