### ISSUE TITLE
Backwards compatibility check for avni-client

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1060]
Ensure avni-client v3.39 works with avni-server v4.0.0 for the following scenarios
  - Custom privileges for a user and start sync
  - Regular user with All Privileges turned on
  - Organisation admin (similar to second scenario)

Validate for the following functionalities
- [x] Subject registration
- [x] Program enrolment
- [x] Program Exit
- [x] Program Encounter
- [x] General Encounter
- [x] Checklists
- [x] Documentation
- [x] Image/Video upload
- [x] Fast Sync
- [x] Upload database
- [x] Individual Assignment
- [x] Group subjects / Household
- [x] Relationships
- [x] Tasks
- [x] Subject migration
- [x] Videos
- [x] Custom Dashboards
- [x] Approvals
- [x] Regular sync progress bar
- [x] Growth Chart

We currently know that there is an issue with subjectUuids being mandatory on privileges that is causing trouble when syncing a user with custom privileges. This will be taken care as part of this card. Any other changes are noted down here for testing purposes

Refer https://docs.google.com/spreadsheets/d/1KTkZOYLpFS__eNse2Bkuj9wa4alkovtrqKPBlJvN7ns/edit?usp=sharing for testing details

**Comment by himeshr** [comment]
Analysis / testing info available at https://docs.google.com/spreadsheets/d/1KTkZOYLpFS__eNse2Bkuj9wa4alkovtrqKPBlJvN7ns/edit?usp=sharing

**Comment by vinayvenu** [comment]
Remove unused method GroupPrivilegeRepository.findByLastModifiedDateTimeIsBetweenOrderByLastModifiedDateTimeAscIdAsc()

**Comment by himeshr** [comment]
@vinayvenu Removed the unused method GroupPrivilegeRepository .findBySubjectTypeIsNotNullAndLastModifiedDateTimeIsBetweenOrderByLastModifiedDateTimeAscIdAsc() as that is what i think you were referring to in the comment above.. and not GroupPrivilegeRepository.findByLastModifiedDateTimeIsBetweenOrderByLastModifiedDateTimeAscIdAsc(), as that doesnot exist.

**Comment by petmongrels** [comment]
no code change done. nothing to test.

**Comment by himeshr** [comment]
@petmongrels we do have server side code change done for this.. 
The primary test scenario for this card is to test compatibility of older version of client APK with 4.0 avni-server.
 - 3.39 Playstore APK link: https://play.google.com/apps/test/com.openchsclient/4228208
 - 3.40 CircleCI : https://app.circleci.com/pipelines/github/avniproject/avni-client/1841/workflows/dd8ce6b1-729f-48a1-8569-90132cc43457/jobs/11540/artifacts

**Comment by petmongrels** [comment]
@AchalaBelokar you have done the testing with older APK as part of regression. if so then we don't need to do this again.

**Comment by vinayvenu** [comment]
This was a mostly testing story for regression, skipping QA.
