### ISSUE TITLE
App breaking when using the call button

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1070]
Please see video attached. This doesn't look like a consistent issue, could be due to the size of the list, kind of phone etc

Phone model  - IQOO Z7

https://drive.google.com/file/d/1lsayv0-1ATQZ0tLIdU_vPCzkuBxDaHSB/view?usp=sharing

**Comment by 1t5j0y** [comment]
Code changes at https://github.com/avniproject/avni-client/commit/f3b2d6f58ed210320c816ba88a7c07b1a32b221f

**Comment by himeshr** [comment]
Reproduced the issue in pre-release with nupoork@poweruat user, with an apk without the fix.
Using apk with the fix, we are able to make the call successfully, from the Task list screen as well as Individual dashboard screen.
