### ISSUE TITLE
App breaks on Applying Filter for Section

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1073]
Environment:
Pre release APK for 4.0.0

Organization:
Adolescent Sewa Rural

Steps to Reproduce:
1. Login with a user on Android app for Adolescent Sewa Rural.
2. Click on Filter option on home screen.
3. Select options A/B/C/F  in Section filter and click on Apply.
4. App breaks.
**Note**It is not reproduced when other options are selected for Section in filter. 

Attaching screenshot:
![Image](https://user-images.githubusercontent.com/97434810/259297712-7ccf5c9b-ad7c-4b90-b476-d03178cc2ce8.jpg)

**Comment by 1t5j0y** [comment]
Bug introduced due to #929. Test scope should include testing of the functionality of this story as well.
