### ISSUE TITLE
Dashboard filter needs performance improvement

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#1075]
Currently the performance of the dashboard filters is very poor, making it almost difficult to use. Attaching a video/screenshot from the APF Odisha organisation, where a location filter is added on one of the custom dashboard -

![Image](https://github.com/avniproject/avni-client/assets/37863085/faecaa53-8d30-4853-b281-997621b49a0c)
https://github.com/avniproject/avni-client/assets/37863085/407b7b01-b07f-4fce-afd2-03c1f00b70b8

**Comment by vinayvenu** [comment]
@nupoorkhandelwal This is a known issue that we've looked at before. This cannot be solved by improving performance of the report cards. You can do one of the following. 
1. Remove the SAM children and MAM children report cards
2. Push out the nutritional status to the enrolment and write the entire query there. 

@Gojo-Taqi and @arjunk might have more information on how to proceed with this. Closing this card.
