### ISSUE TITLE
Worklist updation rule not working for Registration to Encounter/Program Encounter flows

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#1079]
Somehow, the work list updation is not woking for the following flows -
1. Registration to General Encounter - (Sample rule is there on Shelter prod org)
2. Registration to Program Encounter - (Sample rule is there on Adolescent Sewa Rural pre release org)

For the first flow, error details are there in the ticket - https://avni.freshdesk.com/a/tickets/2974
and for the second flow, there is no error but the rule is not working - https://avni.freshdesk.com/a/tickets/2895

**Comment by petmongrels** [comment]
I have looked at both the rules. They look fine to me.
Need to be investigated in the product. The documentation for WorkList Updation rule needs to more detailed outside the example (all fields must be elaborated and possible values should be put).

**Comment by petmongrels** [comment]
The rule in the second flow is wrong.

**Comment by mahalakshme** [comment]
@AchalaBelokar whats the status of testing this. Why is this moved back and forth? Do u need any help on this.

**Comment by AchalaBelokar** [comment]
@mahalakshme there are 5.0.1 card this is 5.1.0 thats the reason this card is there today I am picking this card
