### ISSUE TITLE
Unable to sync some organisation on 4.0.0 version

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1082]
**Describe the bug**
Unable to sync some organisation on 4.0.0 version

**To Reproduce**
1. Download the beta version
3.login with user id  singrauli  user
4.See error

https://github.com/avniproject/avni-client/assets/104890488/70efda20-6fea-44fb-b32c-a193ea730c34

**Expected behavior**
user is able to sync the orgnisation

**Comment by vinayvenu** [comment]
Verified with 

1. 3.40 apk with fast sync, sync and then upgrade
2. 3.40 apk without fast sync, sync and then upgrade
3. Direct 4.0 apk with fast sync
4. Direct 4.0 without fast sync


Verified for scenarios where there are rows for VideoTelemetric, and for rows that do not have them. Fix works for both scenarios, and deletes rows where applicable. 

All good to go.
