### ISSUE TITLE
In older version in the singrauli the association error is coming

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1084]
**Describe the bug**
In older version in the singrauli the association error is coming
same user which is in this card 
https://github.com/avniproject/avni-client/issues/1082

**To Reproduce**
1. Login with user id 
2. and password
3. See error

**Expected behavior**
User should able to login this organisation 

**Screenshot
![Screenshot_2023-08-22-17-34-48-77_e67de974eab1ae435bf1faa372eb4549](https://github.com/avniproject/avni-client/assets/104890488/88ea10d7-257f-4794-9973-68268a61f58b)
s**

**Comment by himeshr** [comment]
Unable to reproduce this, for me it works correctly, reopen if required.
