### ISSUE TITLE
Unique validation does not prevent user from proceeding with form

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1090]
### How to reproduce

- Create a form with text field and unique validation on
- Fill in the form on avni-client
- Notice that there is an error, but the user is allowed to go to the next screen

**Comment by ashusvnath** [comment]
QA observation;
An error message is displayed when unique constraint is violated, but the form proceeds to the next page and i can save the encounter

**Comment by ashusvnath** [comment]
![FailingUniqueConstraint](https://github.com/avniproject/avni-client/assets/568925/7c5dd5a1-5d1b-4790-81e3-91efca036cc1)

**Comment by ashusvnath** [comment]
QA Observation:
When a duplicate value is entered for a form field marked unique, the form cannot be saved.
The error is displayed clearly.

Would be nice to have:
Some indication that the form cannot be saved. Right now, the app just looks like it is stuck.
