### ISSUE TITLE
Identifier assignment not working as expected when an intermediate one is moved out of catchment

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1092]
### Steps to reproduce:
- For user say, maha@jscsuat, Anuppur catchment, create individuals test123, test456, test789 and enrol them to sickle cell
- As  another user, say suhas@jscsuat, Anuppur enlarged catchment(Anuppur + some village say, Pindari which doesn't belong to Anuppur), change the address of test456 to Pindari.
- As maha@jscsuat sync, and then create a individual and enrol them in sickle cell. Enrolment id of test456 will appear. But the next enrolment id of test789 should appear.

### Description in short:
Actual: When a subject is migrated out of a catchment, enrolment_identifier of the subject is listed again when a new program enrolment is attempted.

Expected: The enrolment_identifier of the subject moved out of catchment should not be used, since the subject still exists. Hence the next identifier from the last used identifier should be used.

**Comment by vinayvenu** [comment]
Tests required
1. Scenario mentioned in steps to reproduce
2. With fast sync setup (verify the database)
3. Upgrade

**Comment by vinayvenu** [comment]
Change - introducing a variable that mentions if an identifier has been used. Since the individual cannot be relied upon since it goes away, but the identifier stays in the db, we need to keep this state elsewhere.

**Comment by mahalakshme** [comment]
@vinayvenu what do we do for already existing duplicates? Since we dont have more than 20 duplicates, I think we can let the implementation team to decide on handling it by communicating as necessary with the client.

**Comment by vinayvenu** [comment]
Tested with subjects alone, and with subjects, encounters, program enrolments and program encounters. 
Verified with both less than 10k and more than 10k rows

On prerelease, the export takes about 20-30 minutes. The db is smaller, but db is more free, so cannot say how much this is expected to take in production. In any case, we should not expect hours for the same job. 

All good.
