### ISSUE TITLE
Add ability to generate apks for different flavors via circle-ci for live stage

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1096]
Currently apk generated in the live stage is not signed with the right keystore. This causes confusion when for some reason this apk need to be shared with external client or need to be used for internal testing.

Analysis notes - options:
1. Try using ```make release_prod_universal_without_clean``` instead of using ```bundletool.jar``` to generate universal apk from bundle
2. or use the right parameters for keystore, key password and keystore password

Additionally, deploy platform translations while building live stage.

**Comment by 1t5j0y** [comment]
Related: #1028

**Comment by 1t5j0y** [comment]
Renamed keystore files to `<flavor>-release-key.keystore`
Standardised keystore password env var to `<flavor>_KEYSTORE_PASSWORD` (i.e. `lfe_KEYSTORE_PASSWORD`, `lfeTeachNagaland_KEYSTORE_PASSWORD`, `generic_KEYSTORE_PASSWORD` etc)
Standardised key password env var to `<flavor>_KEY_PASSWORD`
Added env var for key alias with the format `<flavor>_KEY_ALIAS`

**Comment by petmongrels** [comment]
does this need update - https://avni.readme.io/docs/release-process-for-the-cloud#circleci-build

also this - https://avni.readme.io/docs/flavouring-avni#steps-to-do-to-get-build-via-circle-ci

objective - can I follow these steps and generate my own apk?

**Comment by 1t5j0y** [comment]
No changes to the steps required for building apks via circleci. Updated both the above docs for changes in steps for building prod APK locally.

**Comment by mahalakshme** [comment]
@1t5j0y I think upload translations not done for live stage. Just realised recently.

**Comment by 1t5j0y** [comment]
Added into scope of this card and implemented.
