### ISSUE TITLE
Some variables accessible before in rules not accessible now

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1097]
### Description:
Refer the below links for description:
https://github.com/avniproject/avni-security/issues/1#issuecomment-1717464830
https://github.com/avniproject/avni-security/issues/1#issuecomment-1719097094

### Acceptance criteria:
Understand how this formElement was accessible before. Identify if there is possibility for any other variables to be accessible without being passed as parameters to the rules. Ideally variables not passed as parameters to the rule should not be accessible. Fix the necessary rules and the code accordingly.

**Comment by petmongrels** [comment]
https://prerelease.avniproject.org/#/appdesigner/forms/ed2c239a-00ca-439c-8f2b-76543fdc55cf -> 'Average Scores and Feedback' FEG -> 'Average Scores' FE (QuestionGroup) -> All the rules for the questions under that

Prod - https://app.avniproject.org/#/appdesigner/forms/ed2c239a-00ca-439c-8f2b-76543fdc55cf

'lfeteach' org in both environments

**Comment by petmongrels** [comment]
LFE branch seems incorrect. it has commits upto feb 23. but the apk release is only upto Jan.

**Comment by vinayvenu** [comment]
I think we planned to release lfe to fix some of the bigger items that came from our post-upgrade issues, but never got around to deploying. 

In any case, the lfe branch is not required anymore since we have moved all features from lfe to our main branches.

**Comment by petmongrels** [comment]
### Number of form elements that use formElement via params.formElement: 25449

select count(*) from form_element
      join organisation o on form_element.organisation_id = o.id
where rule like '%params.formElement%' and rule like '%formElement%' and form_element.is_voided = false;


### Number of form elements that use formElement without params.formElement: only a few form elements in LFE Teach. LFE Teach instance our main hosting is not the real prod.

select o.name, form_element.group_id from form_element
    join organisation o on form_element.organisation_id = o.id
    where rule not like '%params.formElement%' and rule like '%formElement%' and form_element.is_voided = false;

**Comment by mahalakshme** [comment]
@petmongrels we had discussed in standup(u were not there) that we 'll identify why the issue happened now - how the global variables are not accessible now to identify like `formElement` if there are some other variables as well. Just updating.

**Comment by petmongrels** [comment]
JS globals had stopped working sometime beginning of this year, after last react native upgrade I think. we had to explicitly exposed globals as in the following commits. But we also deprecated this approach. So it has been a while now that accessing things from global do not work and using from lib is deprecated.

https://github.com/avniproject/rules-config/commit/cf6990765a8a3aa326fc8816d9376d7fb74cd884
https://github.com/avniproject/avni-client/commit/e40ff6c4684c08da105537681aabdcd62c185843
LFE in use from before this, because the timer wasn't working after the previous react native upgrade.

moving back to analysis

**Comment by vinayvenu** [comment]
Verified. This is not an issue in the primary production organisation. There are issues on the lfeTeach which will need to be fixed. 

Queries
```
select o.name, fe.name, fe.rule, fe.declarative_rule from form_element fe
                                                              inner join organisation o on fe.organisation_id = o.id
where fe.rule ~ '.*[^.]formElement.*' and fe.rule !~ '.*params.formElement.*' and fe.is_voided is false;

select distinct o.name from form_element fe
                                inner join organisation o on fe.organisation_id = o.id
where fe.rule ~ '.*[^.]formElement.*' and fe.rule !~ '.*params.formElement.*' and fe.is_voided is false;


select rule from form_element where rule ~ '.*[^.]common.*';
select rule from form_element where rule ~ '.*[^.]motherCalculations.*';
select rule from form_element where rule ~ '.*[^.]models.*';
select rule from form_element where rule ~ '.*[^.]entity.*';


select enrolment_eligibility_check_rule from program where program.enrolment_eligibility_check_rule ~ '.*[^.]common.*';
select enrolment_eligibility_check_rule from program where program.enrolment_eligibility_check_rule ~ '.*[^.]motherCalculations.*';
select enrolment_eligibility_check_rule from program where program.enrolment_eligibility_check_rule ~ '.*[^.]models.*';
select enrolment_eligibility_check_rule from program where program.enrolment_eligibility_check_rule ~ '.*[^.]entity.*';


select manual_enrolment_eligibility_check_rule from program where program.manual_enrolment_eligibility_check_rule ~ '.*[^.]common.*';
select manual_enrolment_eligibility_check_rule from program where program.manual_enrolment_eligibility_check_rule ~ '.*[^.]motherCalculations.*';
select manual_enrolment_eligibility_check_rule from program where program.manual_enrolment_eligibility_check_rule ~ '.*[^.]models.*';
select manual_enrolment_eligibility_check_rule from program where program.manual_enrolment_eligibility_check_rule ~ '.*[^.]entity.*';


select encounter_eligibility_check_rule from encounter_type where encounter_type.encounter_eligibility_check_rule ~ '.*[^.]common.*';
select encounter_eligibility_check_rule from encounter_type where encounter_type.encounter_eligibility_check_rule ~ '.*[^.]motherCalculations.*';
select encounter_eligibility_check_rule from encounter_type where encounter_type.encounter_eligibility_check_rule ~ '.*[^.]models.*';
select encounter_eligibility_check_rule from encounter_type where encounter_type.encounter_eligibility_check_rule ~ '.*[^.]entity.*';


select subject_summary_rule from subject_type where subject_type.subject_summary_rule ~ '.*[^.]common.*';
select subject_summary_rule from subject_type where subject_type.subject_summary_rule ~ '.*[^.]motherCalculations.*';
select subject_summary_rule from subject_type where subject_type.subject_summary_rule ~ '.*[^.]models.*';
select subject_summary_rule from subject_type where subject_type.subject_summary_rule ~ '.*[^.]entity.*';


select program_eligibility_check_rule from subject_type where subject_type.program_eligibility_check_rule ~ '.*[^.]common.*';
select program_eligibility_check_rule from subject_type where subject_type.program_eligibility_check_rule ~ '.*[^.]motherCalculations.*';
select program_eligibility_check_rule from subject_type where subject_type.program_eligibility_check_rule ~ '.*[^.]models.*';
select program_eligibility_check_rule from subject_type where subject_type.program_eligibility_check_rule ~ '.*[^.]entity.*';

```

**Comment by vinayvenu** [comment]
@mahalakshme output - we need to fix rules for all organisations within lfeTeach for them to be using the rules.

**Comment by mahalakshme** [comment]
@vinayvenu I added it in release 5.0 card yesterday - since implementation team can do it as part of the release

**Comment by mahalakshme** [comment]
@nupoorkhandelwal @salilsamanvay @vedfordev  Is there a reason why the "Average scores and Feedback" is hidden for AP Teach and Teach NL UAT? 

There is a problem with the rules on form elements of this page. It will break if we ever try to enable it.

**Comment by mahalakshme** [comment]
Closing this since when the rule is enabled and tested it will anyways get identified.
