### ISSUE TITLE
Fatal Error is coming when apppliying a location filter on apfodisha

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1105]
**Describe the bug**
Fatal Error is coming when apppliying a location filter on apfodisha
<img width="324" alt="fatal error" src="https://github.com/avniproject/avni-client/assets/104890488/ff39e480-f65d-4d1c-9711-ab5cc91d45d4">

**To Reproduce**
1. login with dinesh@apfodisha
2. click on filter
3. Click on location
5. submit
6. See error

**Expected behavior**
filter should be displayed 
**Screenshots**

https://github.com/avniproject/avni-client/assets/104890488/b3a84816-5e06-44e3-ad8c-32868d2326b4

**Comment by mahalakshme** [comment]
structured-clone npm module was used to prevent this error, need to see why it is still occurring.

**Comment by 1t5j0y** [comment]
Rule for one of the cards on this dashboard had some `JSON.stringify`s which were causing the breakage.
https://prerelease.avniproject.org/#/appDesigner/reportCard/820/show
