### ISSUE TITLE
Main dashboard filters not remembered

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1106]
**Describe the bug**
Main dashboard filters not remembered

**To Reproduce**
1. login with himeshr@jsscp
2. Click on filter apply that filter
4. kill the app
5. open the app
6. filter should be visible 
**Expected behavior**
filter should be present

https://github.com/avniproject/avni-client/assets/104890488/f728a61b-edd2-44bb-8548-bd83d4e3463f

**Comment by mahalakshme** [comment]
@AchalaBelokar can u add a video for this? Asking since this was working recently and you also tested this as part of react native upgrade card.

**Comment by mahalakshme** [comment]
there were some issues with respect to dashboard filters after react-native upgrade - and it was fixed as part of react-native upgrade card.

**Comment by ashusvnath** [comment]
@AchalaBelokar , @mahalakshme , @vinayvenu 
This is probably not a bug and is by design. I see the same behaviour in 4.0 release APK.
I wonder if the filters are only persisted on custom dashboards and not the default dashboard.

**Comment by ashusvnath** [comment]
Based on discussions with @himeshr , the default dashboard (landing view) only saves the selected subjectType (if there are many) across pages. It does not remember the filters applied across app restarts.

**Comment by mahalakshme** [comment]
oh yeah but if the custom dashoard is made the home dashboard filters should get retained.If thats also working then this is not an issue.

**Comment by ashusvnath** [comment]
@mahalakshme : The custom dashboard filters are getting retained.
