### ISSUE TITLE
Login into 4.0 version app not working as expected

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1108]
**Describe the bug**
some user is not support in 4.0 version 
when I am trying to login maha@stccv with version 5.0 I can login successfully.
And when I am trying to login with version 4 It will give me login page
same thing happen with utkarsh@lahi

**To Reproduce**
1. login with maha@stccv
2.put password .
3. Click on submit button 
6. See error

4.0 apk link: https://output.circle-artifacts.com/output/job/1e4fff15-bd9d-49d6-ac1f-21a5427dd0d7/artifacts/0/generic-prerelease-8a56c782cfe48088c0ae79e5ecb080a963cdb81e.apk

**Expected behavior**
user is able to successfully login to particular user 
home page should be shown
**Screenshots**

https://github.com/avniproject/avni-client/assets/104890488/667c192d-6886-4101-a17a-a2e9906612a2

**Comment by AchalaBelokar** [comment]
"Log error content:
TypeError: Cannot read property 'getLineage' of null

This error is located at:
in IndividualProfile"

**Comment by himeshr** [comment]
Erroring out from server side even before it hits anyof the Avni code interceptor filtes like:
AuthenticationFilter.java
MetadataResourceInterceptor.java
TransactionalResourceInterceptor.java
 

[ErrorLog.txt](https://github.com/avniproject/avni-client/files/12724632/ErrorLog.txt)

**Comment by himeshr** [comment]
> "Log error content: TypeError: Cannot read property 'getLineage' of null
> 
> This error is located at: in IndividualProfile"

These logs are not corresponding to this issue. They belong to avniproject/avni-client#1110

**Comment by himeshr** [comment]
Root-cause: AVNI_CSRF_ENABLED was enabled, resulting in spring rejecting any protectedURL without CSRF token.
Fixed this by setting, AVNI_CSRF_ENABLED to false in pre-release(to be done in prod as well for a few months)
```
export AVNI_CSRF_ENABLED=false
```

**Comment by himeshr** [comment]
@AchalaBelokar config change made to fix the issue reported in this card has resulted in Avni-client 4.0 apk being able to sync to avni-server 5.0 version.
Therefore as part of its QA, we should perform detailed regression testing in pre-release environment with 4.0 apk..
4.0 apk link: https://output.circle-artifacts.com/output/job/1e4fff15-bd9d-49d6-ac1f-21a5427dd0d7/artifacts/0/generic-prerelease-8a56c782cfe48088c0ae79e5ecb080a963cdb81e.apk

**Comment by AchalaBelokar** [comment]
This issue is happening with shelter org maha@shelter this is happening with 5.0.1

**Comment by ashusvnath** [comment]
@AchalaBelokar : I used the 4.01.0 APK from play store console and I'm able to log into maha@shelter.
I also used the 5.0.1 apk independently and upgraded from 4.01.0. All flows worked. Nowhere was i logged out.
