### ISSUE TITLE
Fast sync is not working for sakhi

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1111]
**Describe the bug**
we alredy set a fast sync for sakhi app
and then try to login again after deleting the app cashe and data
then error
**To Reproduce**
1. login with AchalaB@sakhi app
2. Enter a password
3.See error

**Expected behavior**
User is able login. without performing slow sync
 **Screenshots**\

https://github.com/avniproject/avni-client/assets/104890488/b708c0a7-2eb4-47f1-a4fb-cb89f31cc131

**Comment by vinayvenu** [comment]
Cannot reproduce this error.

**Comment by AchalaBelokar** [comment]
can you check for himeshr@jsscp

**Comment by vinayvenu** [comment]
works fine for jsscp as well.
