### ISSUE TITLE
Sync getting stuck

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1115]
Ticket: https://avni.freshdesk.com/a/tickets/3098
Env prod, below analysis made using the login details of the first user, Kadmbini Garadia 

- 
- - After all the subject migrations are get, sync is getting stuck before proceeding to getting next entity as shown in the below images. Able to reproduce the issue easily.
 

![Image](https://github.com/avniproject/avni-client/assets/10369963/11288672-2585-4a92-8535-1495d023a69d)
As shown In the above image, even after waiting for an hour until 8:10pm the sync didn't continue.

![Image](https://github.com/avniproject/avni-client/assets/10369963/619acc54-707f-43a5-9d97-d3f6866c7e40)
In the above image, there is a gap of 5 minutes between the complete of subject migration and next set of calls.

### Observations:
- In both the above cases, found that sync has got stuck after retreiving subject migrations for all subject types in apf odisha
- For one of the subject type, Individual there is retrieval of 277 pages, and the realm db had 29575 entries
- Subject migration sync is already scoped.
- Looks like one of the reasons for no of subject migrations  being more is duplicate syncs that have created duplicate entries
- After subject migration sync, sync of transaction data is expected to start. In between that we are only updating the  data based on the new privileges, and this should not take much time since the testing was made with fresh sync and there was no data to delete as part of updating privileges

### To do:
Analyse and fix the reason for sync getting stuck, this should not happen even if the no of pages are more.

### Out of scope:
Analysing the cause and fixing of duplicate sync - this is part of different story.

**Comment by petmongrels** [comment]
removed to avoid confusion

**Comment by mahalakshme** [comment]
@petmongrels What was the old query? In the new query when only address of the individual changes and sync attribute remains the same - I see subject migration with new query might not work as expected. This is because in the db when the sync attribute doesn't change(and only address changes) it is null(for old_sync_concept_value and new_sync_concept_value) from what I see. but the in clause will have user's sync attribute value. That is why previously OR was used. I dont know if I am missing something.

**Comment by mahalakshme** [comment]
@petmongrels But I can see there is good amount of optimisation possible in the old query. To make the above new query work I think we need to populate always the old column values in the subject_migration table irrespective of whether it changes or not(so that we can use it for AND to match with user sync attributes), and we should do the deleting of old data in client only when both old and new columns are present.  cc: @vinayvenu

**Comment by petmongrels** [comment]
removed to avoid confusion

**Comment by petmongrels** [comment]
removed to avoid confusion

**Comment by mahalakshme** [comment]
@petmongrels How is this different from old query? I thought this was the old query and in new query irresepective of sync attribute or address has changes we need to AND with old columns(which should be populated with latest values - not done currently)

**Comment by mahalakshme** [comment]
I see the new query needs to be like below:

select ...and individual1_.subject_type_id = 672
and (subjectmig0_.old_sync_concept_1_value in (?, ?) and subjectmig0_.old_sync_concept_2_value in (?, ?) and 
subjectmig0_.old_address_level_id in (331176, 331179, 335260) or subjectmig0_.new_address_level_id in (331176, 331179, 335260) or subjectmig0_.new_sync_concept_1_value in (?, ?)  or subjectmig0_.new_sync_concept_2_value in (?, ?));

For the above to work, we need to do the following:
- always populate old values(with latest value of individuals') irrespective of address/atrribute change in subject_migration table
- change avni_client code - s.t delete old data only when new value(address/sync concept) also present
- changes subject migration indices accordingly to work with the new query

**Comment by mahalakshme** [comment]
@petmongrels Actually what I told will not work. Will think through it.

**Comment by petmongrels** [comment]
### Consolidated changes

1. Added integration tests to verify various scenarios.
2. Test and prod changes in separate commit to be able to apply changes to 4.0 if required. Tests will give difficult merges.
3. Missing optimisation described here - https://github.com/avniproject/avni-server/blob/457163a47ec843d57efd3307dd686adaebfcec8c/avni-server-api/src/main/java/org/avni/server/service/SubjectMigrationService.java#L61
4. Number of rows returned much lesser now < 100 instead of tens of thousands
5. If a user doesn't have sync attributes setup for subject type that requires sync attributes to be setup then the user will not get any subject migration.
6. SQLselect subjectmig0_.*
from subject_migration subjectmig0_
         left outer join public.individual individual1_ on subjectmig0_.individual_id = individual1_.id
where subjectmig0_.last_modified_date_time > '1900-01-01'
  and (individual1_.subject_type_id = 672)
  and ((subjectmig0_.new_sync_concept_1_value in ('8ebbf088-f292-483e-9084-7de919ce67b7', 'a77bd700-1409-4d52-93bc-9fe32c0e169b'))
    or subjectmig0_.new_sync_concept_1_value is null
    or (subjectmig0_.old_sync_concept_1_value in ('8ebbf088-f292-483e-9084-7de919ce67b7', 'a77bd700-1409-4d52-93bc-9fe32c0e169b', null))
    or subjectmig0_.old_sync_concept_1_value is null
    )
  and ((subjectmig0_.old_address_level_id in (331176, 331179, 335260))
    or (subjectmig0_.new_address_level_id in (331176, 331179, 335260)));

6. For code review combine commits and then review.

**Comment by mahalakshme** [comment]
Oh wonderful, before we were doing OR with address level which would have returned many rows. Though subject migration sync service was scoped, it was not working as expected. Just a small thing: search for null in new_sync_concept_1_value can also be merged in the IN clause like old_sync_concept_1_value if not already done.

**Comment by vinayvenu** [comment]
Testing Note: Additional change in avni-client to the sync to show the current page so that sync doesn't look stuck

**Comment by vinayvenu** [comment]
### Test cases
1. FIrst time login. Ensure subject migrations only sync for that catchment
2. Add a new subject migration (based on sync attributes). Ensure migration takes place
3. Login as another user with slightly different sync attributes (but will sync). Ensure it syncs
4. Ensure new migration does not sync to someone in a different catchment
5. Change location of subject. Ensure it syncs only to those in same catchment



### Observations
1. The change to avni-client is not part of 5.0, so this card is kind of half released in this release
2. Not directly related to this change, but avni-client always creates 2 subject_migration entries. This needs to be handled as a separate bug.
