### ISSUE TITLE
Sync should stop when app loses focus

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1116]
## Steps to reproduce:
user:9791217078@apfodisha, password: u know it, env: prod
- Login - when syncing(in between of when getting many pages of an entity), close the app, reopen and click on sync again
- When you check the logs you will find, duplicate entries with different nows
- In the db, duplicate sync_telemetry rows with same start_time but different end_time would have been created.
- There could be some similar reason behind duplicate automatic sync.

## Analysis details:
The above is because sync continues when the app is reopened, but is not visible to the user and the user will click on sync button again resulting in duplicate sync telemetry entries since it uses the same state.

## Acceptance criteria:
- When app is closed, both automatic and manual sync should be stopped
- Create sync telemetry before stopping the sync
- The sync data state with EntitySyncStatus and EntityQueue need to be consistent

## The below logs in avni-client might indicate duplicate sync:

`registerHeadlessTask or registerCancellableHeadlessTask called multiple times for same key 'syncJob'`

**Comment by 1t5j0y** [comment]
Also consider that screen timeout due to inactivity (Android OS level setting) shouldn't interrupt sync.

We should probably focus on showing the sync that is already in progress when app is refocused rather than interrupting sync when app loses focus.

**Comment by mahalakshme** [comment]
duplicate: https://github.com/avniproject/avni-client/issues/1149
