### ISSUE TITLE
Subject datatype not showing all the members in attendance forms

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#1119]
**Describe the bug**
Currently, in around 3-4 implementations we show all the members in group as a multi select concept in the attendance form (in case of Phulwari). But somehow, the number of subjects in the form  is one less to the number of members in the group.

**To Reproduce**
1. Go to pre release env >> JSS singrauli >> mobile app
2. Login and go to any Phulwari
3. See the count of members in any one phulwari and then try to fill in the attendance form
4. The number of subjects displayed are one lesser to the number of members in the grp subject.

**Expected behavior**
Ideally, all the members should have been displayed in the attendance form.

**Screenshots**

![Image](https://github.com/avniproject/avni-client/assets/37863085/0ea2c9da-4b5a-40a3-83b8-45aa03d072e0)
![Image](https://github.com/avniproject/avni-client/assets/37863085/6e7b63e0-45f9-4860-b369-b14fafaf2f48)

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing? Answer: No
- [ ] Are you mentioning the required scenarios that could be affected? Answer: Yes

**Comment by 1t5j0y** [comment]
Not a bug. For the cases where members are missing, either the member is voided or the membership is voided.

https://github.com/avniproject/avni-client/assets/54208632/10823a88-29df-4980-9443-0a52ada999c2

**Comment by mahalakshme** [comment]
@1t5j0y I ll move this to Hold. Will confirm with implementation team regarding if voided members need to be removed from the Members list, since this confusion might come for users as well.

**Comment by vinayvenu** [comment]
Voided = Deleted. These should be removed from all kinds of display, and if displayed, should visibly say voided. We should proceed and remove the member from the membership list.

**Comment by mahalakshme** [comment]
Moved back to Ready

**Comment by himeshr** [comment]
## Summary
### Debug information 
 - The missing entries were either due to voided GroupSubjectMemberships or voided Members itself
 
### Acceptance criteria after discussion
 - On voiding an individual, void all its GroupSubjectMemberships as well
 - In Membership list shown on GroupSubject profile, do not display entries corresponding to
> - voided GroupSubjectMemberships
> - voided Members with non-voided GroupSubjectMemberships
> - non-voided ex-members with voided GroupSubjectMemberships

**Comment by mahalakshme** [comment]
should we add a migration to void GroupSubjectMemberships where members are voided to ensure consistency of data? cc: @vinayvenu

**Comment by vinayvenu** [comment]
@mahalakshme don't think so. We still don't have a way to prevent them from happening
