### ISSUE TITLE
Logout and login as different user not working as expected

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-client#1125]
**Steps to simulate**
On 5.0 prod apk, login as AchalaB@sncu. This user has a fast sync db setup. The fast sync db is downloaded and after some time sync fails due to avniproject/avni-server#621. Cancel the sync and logout. Login as dineshg@rwb2023.

**Issues**:
1. The multiUserWarning popup is not shown
2. Login goes through, default dashboard is shown with some values already prefilled and sync initiates but the sync is for AchalaB@sncu and the sync fails with the error in avniproject/avni-server#621

**Additional notes**:
Sync after clearing storage and logging in as dineshg@rwb2023 completes successfully.
Not happening on 4.01.0 apk

**Comment by 1t5j0y** [comment]
Code looks good but pushed on wrong branch.

**Comment by himeshr** [comment]
Oh ya, i thought this was needed for 5.0 release.
