### ISSUE TITLE
Add a client migration to remove subject migrations that doesn't belong to users catchment

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1126]
Since subject migrations outside of the user's catchment were also synced, for consistency of data in user's mobile db, we will add a client migration, to remove the entries with both old and new address uuid outside of user's catchment.

**Comment by vinayvenu** [comment]
How do we identify duplicates? Also, what is the value of running this?

**Comment by mahalakshme** [comment]
- Not duplicates, this is for removing the rows where address levels where not part of user's catchment. 
- can be identified using: when both old and new address level in subject migration table are not part of address levels table in realm db. 
- value: 
1.  we are doing this get on realm db for every sync, after fetching transaction data - this might be faster considering user will have around 20k subject Migrations - this.findAll().filtered('hasMigrated = false ') 
2. Fast sync/upload db will be faster
3. Since the above is lot easier than finding duplicates, I thought we can do it to clean up user's mobile db independent of how much performance improvement we get
