### ISSUE TITLE
Skip answer ignores translation

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#1128]
**Describe the bug**
A key with same language translation (in english) ignores displaying the translated string when skip Answer rule is applied on it. Check the video to understand the issue better.

**To Reproduce**
1. Go to App Designer
2. Add a coded concept form element, add some english translation for the answers
3. Add a skip answers rule on these elements based upon some condition
4. See the translation is not showing up, instead the actual concept names show up.

**Expected behavior**
In any scenario, the respective translation should show up in the client.

**Screenshots**

https://github.com/avniproject/avni-client/assets/37863085/1ad1747e-b535-4e0a-b9ee-c0eb5003da55

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This can be reproduced on Teach NL in observation encounter.

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by himeshr** [comment]
Added translation method invocation while rendering singleValue in SelectionItemGroup.
Simple code change, no review required.
Standard "1" was translated to "One".
After fix video.

https://github.com/avniproject/avni-client/assets/72493481/7ab605bc-c107-497b-b1e8-3abd5554e74e
