### ISSUE TITLE
Old rules not working

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1129]
#### Steps to reproduce:
- Login with taqi@ihmp, env: prod
- Disable automatic upload sync
- Go to the individual "Kanchan Aakash Thikone"
- Try to do monthly needs assessment encounter
- On 3rd page for "whether any family planning method used?", Enter No
- Even then questions regarding "what family planning method used" appears.

#### Analysis:
In the rules table, 'IHMP EC Monthly needs assessment View Filter' is present. In the [IHMP repo](https://github.com/avniproject/ihmp) - in the file, "monthlyNeedsAssessmentHandler.js" you can find the rules. To deploy the rules to staging/prod use the commands: `make deploy-staging-rules` and `make deploy-prod-rules` after doing `make deps`. Deploying to prod should be avoided.
![Screenshot_2023-10-10-16-22-26-559_com openchsclient](https://github.com/avniproject/avni-client/assets/10369963/e17401da-bc28-4b75-aa26-e366506f5e95)

For normal rules(rules added via app designer) is working. Issue not occurring in 4.0.1 prod.

Looks like not only skip rules none of the old rules are working - Worklist updation rule is also not working.After completing "Monthly needs Assessment"  should show the option of "save and enrol in pregnancy program". But only Save option is currently shown.

**Comment by AchalaBelokar** [comment]
Tested on ihmp and Calcutta kids the skip logic is working fine there also check with org which is having new   rules
