### ISSUE TITLE
[Analysis and fix] [Production issue] - Worklist updation rule not working for old organisations

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1133]
Worklist updation rules for enrolling into a program based on form output is not working in forms with older rules. See screenshot below

![Image](https://github.com/avniproject/avni-client/assets/344222/576d0a26-06a6-4bf8-9d39-8741e3b1900a)

**Comment by vinayvenu** [comment]
![Image](https://github.com/avniproject/avni-client/assets/344222/9a87986e-b5b1-49a6-b6e8-e07ee1c6465b)

**Comment by mahalakshme** [comment]
@vinayvenu @arjunk  why does this need an emergency patch release? Why cant it go as part of early next week release since this will not be blocking the users.

**Comment by vinayvenu** [comment]
@mahalakshme We should not trust the dates on regular releases, and we need the flexibility to decide how slow or fast we need it to be. 

Also, this was noticed by people immediately after the release, which means it must be important to the workflow of regular users.
