### ISSUE TITLE
Not able to enrol individuals in child program.

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-client#1134]
**To Reproduce**
In org mobilecrechetrial, register an individual subject type and enroll in a child program.
Env - prod
version of client - 4.01.0

**Expected behavior**
There are a bunch of form elements / questions which should appear, instead, it gives **Fatal error: undefined is not an object (evaluating 'e.uuid')**

**Stacktrace**
Notifying Bugsnag TypeError: Fatal error: undefined is not an object (evaluating 'e.uuid')
10-12 12:44:13.679 15804 18610 I ReactNativeJS: 'App', 'renderError', 'Fatal error: undefined is not an object (evaluating \'e.uuid\')\nStacktrace:[{"columnNumber":23963,"lineNumber":743,"functionName":"value","source":"value@index.android.bundle:743:23963","fileName":"index.android.bundle:743:23963"},{"columnNumber":17530,"lineNumber":743,"functionName":"getNextScheduledVisits","source":"getNextScheduledVisits@index.android.bundle:743:17530","fileName":"index.android.bundle:743:17530"},{"columnNumber":4223,"lineNumber":1035,"functionName":"value","source":"value@index.android.bundle:1035:4223","fileName":"index.android.bundle:1035:4223"},{"columnNumber":5555,"lineNumber":1018,"functionName":"value","source":"value@index.android.bundle:1018:5555","fileName":"index.android.bundle:1018:5555"},{"columnNumber":2859,"lineNumber":1034,"functionName":"value","source":"value@index.android.bundle:1034:2859","fileName":"index.android.bundle:1034:2859"},{"columnNumber":648,"lineNumber":1031,"source":"index.android.bundle:1031:648","fileName":"index.android.bundle:1031:648"},{"columnNumber":3442,"lineNumber":1119,"source":"index.android.bundle:1119:3442","fileName":"index.android.bundle:1119:3442"},{"columnNumber":1557,"lineNumber":1119,"functionName":"b","source":"b@index.android.bundle:1119:1557","fileName":"index.android.bundle:1119:1557"},{"columnNumber":2758,"lineNumber":595,"functionName":"value","source":"value@index.android.bundle:595:2758","fileName":"index.android.bundle:595:2758"},{"columnNumber":3475,"lineNumber":732,"functionName":"value","source":"value@index.android.bundle:732:3475","fileName":"index.android.bundle:732:3475"},{"columnNumber":7454,"lineNumber":732,"functionName":"func","source":"func@index.android.bundle:732:7454","fileName":"index.android.bundle:732:7454"},{"columnNumber":2403,"lineNumber":2141,"functionName":"onPress","source":"onPress@index.android.bundle:2141:2403","fileName":"index.android.bundle:2141:2403"},{"columnNumber":9098,"lineNumber":201,"functionName":"value","source":"value@index.android.bundle:201:9098","fileName":"index.android.bundle:201:9098"},{"columnNumber":8354,"lineNumber":201,"functionName":"value","source":"value@index.android.bundle:201:8354","fileName":"index.android.bundle:201:8354"},{"columnNumber":6288,"lineNumber":201,"functionName":"onResponderRelease","source":"onResponderRelease@index.android.bundle:201:6288","fileName":"index.android.bundle:201:6288"},{"columnNumber":171,"lineNumber":27,"functionName":"c","source":"c@index.android.bundle:27:171","fileName":"index.android.bundle:27:171"},{"columnNumber":314,"lineNumber":27,"functionName":"m","source":"m@index.android.bundle:27:314","fileName":"index.android.bundle:27:314"},{"columnNumber":368,"lineNumber":27,"functionName":"v","source":"v@index.android.bundle:27:368","fileName":"index.android.bundle:27:368"},{"columnNumber":679,"lineNumber":27,"functionName":"w","source":"w@index.android.bundle:27:679","fileName":"index.android.bundle:27:679"},{"columnNumber":14319,"lineNumber":27,"functionName":"Le","source":"Le@index.android.bundle:27:14319","fileName":"index.android.bundle:27:14319"},{"functionName":"forEach","source":"forEach@[native code]","fileName":"[native code]:0:0"},{"columnNumber":5346,"lineNumber":27,"functionName":"X","source":"X@index.android.bundle:27:5346","fileName":"index.android.bundle:27:5346"},{"columnNumber":14667,"lineNumber":27,"source":"index.android.bundle:27:14667","fileName":"index.android.bundle:27:14667"},{"columnNumber":95482,"lineNumber":27,"functionName":"Ce","source":"Ce@index.android.bundle:27:95482","fileName":"index.android.bundle:27:95482"},{"columnNumber":14129,"lineNumber":27,"functionName":"ze","source":"ze@index.android.bundle:27:14129","fileName":"index.android.bundle:27:14129"},{"columnNumber":14506,"lineNumber":27,"functionName":"Me","source":"Me@index.android.bundle:27:14506","fileName":"index.android.bundle:27:14506"},{"columnNumber":15299,"lineNumber":27,"functionName":"receiveTouches","source":"receiveTouches@index.android.bundle:27:15299","fileName":"index.android.bundle:27

**Comment by mahalakshme** [comment]
Rootcause is duplicate form mappings. Will be addressed as part of: https://github.com/avniproject/avni-server/issues/628
