### ISSUE TITLE
Create circle-ci pipeline to generate prod-dev and prerelease-dev apk

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1135]
- This is to facilitate debugging of the app with prod build.
- Whenever prod and prerelease apks are deployed, also generate the corresponding dev apks and upload them to s3 - with the folder format - `{build_no}_{7_letter_commit_hash}/{envName}/apk_file`
- Eg: when deployment of 5.0 app to prod env is done - upload prod apk to `buildNo_first7LettersOfCommitHash/prod/apk_file` and upload prod_dev apk as well to `buildNo_first7LettersOfCommitHash/prod_dev/apk_file`
- The above needs to be uploaded to the bucket, `samanvay/openchs`
- Only uploading of the universal apk for the above is sufficient.

### Out of scope:
Doing the above for staging env is not needed because we mostly use it for development purposes and run from local.

**Comment by vinayvenu** [comment]
@mahalakshme in case someone wants to debug the current release, do you expect them to figure out the right circleci build, approve it and then take the apk? 
Also, not everyone has approve access, so people will be dependent on others to figure out the build and generate the apk.

**Comment by mahalakshme** [comment]
@vinayvenu no I meant it will be helpful for us also to get the generated prod dev apk and also every release we can upload the prod apk to the drive so that implementation team can use it from there.

**Comment by 1t5j0y** [comment]
If we want this for every prod release, it shouldn't be approval type (so we don't have to go look for the build when we need the dev apk).
Also, the upload to s3 can happen directly from circleci.

**Comment by vinayvenu** [comment]
I think it makes sense to always upload all apks to s3 since they get deleted after a month.

**Comment by 1t5j0y** [comment]
Suggestions for a couple of changes to scope (could be a separate card or add to this card) if it there is agreement:
1. Any value in generating both dev and non dev apk for prerelease? Just dev should be sufficient for us.
2. For prod dev, shall we also store the apk as an artifact on circleci so it is available in both s3 and circleci?
@vinayvenu @mahalakshme

**Comment by vinayvenu** [comment]
1. Yes
2. Yes, though we know the artifact will go away in  a month. 

@mahalakshme would you add point 1 to the acceptance criteria?

**Comment by mahalakshme** [comment]
i. For the first point, we give prerelease apk for release sign-off. There are some conditions in our code for dev apk. So I felt for release sign-off prerelease apk should be given and not prerelease-dev.
ii. Yeah we can store both the actual and the dev apks of prerelease and prod in circle-ci as well
iii. Now I feel for staging we can just generate the dev apk(instead of the actual), since Achala also looks at the logs and adds it in card. No need to upload this to s3 

@ashusvnath Let me know if fixing them will take more than 30 mins - will create a new card. Summarising:
- for prod and prerelease - both actual and dev apks - store in AWS and circle-ci (so just need to add storing dev apks in circle-ci)
- for staging - just generate dev apk instead of actual apk and store in circle-ci alone like now.(so need to generate dev for staging instead of actual)

**Comment by ashusvnath** [comment]
@mahalakshme : The code changes don't take long. The testing takes time.
The only change needed right now looks like uploading staging_dev apk's to circle ci. Is that correct ?
