### ISSUE TITLE
Tag 5.0.2 and 5.0.3 release

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1138]
In avni-client - tag the commits associated with the below releases, with the right releases.

https://github.com/avniproject/avni-client/issues/1129 - 5.0.2
https://github.com/avniproject/avni-client/issues/1133 - 5.0.3
Also tag the commit for 5.0.1 release.

**Comment by himeshr** [comment]
@mahalakshme , i just retagged the commit for #1133 - 5.0.3 on playstore with v5.0.0
So that, ppl who wanna get 5.0.0 release will create apk using that commit

**Comment by himeshr** [comment]
No code review or testing required.
