### ISSUE TITLE
bugsnag - Group subject unable to find individual

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1139]
Bugsnag link:

https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/6527b10bceb5570008d18da4?event_id=6529078500c7276591340000&i=em&m=fq

### Analysis:
- The individual registration decision rule seems to be correct.
- Lately(as of 16/10/23) many individuals doesn't have sync_concept1 value; - there are 155 individuals - this seems to be the issue since the individuals in the bugsnag coincides with the individuals without sync_concept_1 value - didn't check everything
- https://docs.google.com/document/d/1pNI28rNW6xcKdzy4qgVetHZRSeqVanEb6ed2uHdlUyQ/edit?usp=sharing - for older association error of this kind added some analysis

**Comment by ashusvnath** [comment]
For `8144346528@apfxxxxx`. There is a sync_concept_1 that is setup.



![Image](https://github.com/avniproject/avni-client/assets/568925/eb5948fe-92f9-46f6-a6a4-7e2e4bd68c4a)

**Comment by mahalakshme** [comment]
created the ticket for implementation team to fix: https://avni.freshdesk.com/a/tickets/3155
