### ISSUE TITLE
Unable to set a fast sync at power organisation

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1146]
**Describe the bug**
Unable to set a fast sync at power organisation
when I am trying to sync it is showing me one sync data is reaming, after perform fast sync it is giving me this message  "You have local unsaved data which should be save to server.Please perform a full sync , before trying this."
After doing this I try to sync. Even after sync the one pending is not getting synced.
Aws s3 data 
https://s3.console.aws.amazon.com/s3/object/prerelease-user-media?region=ap-south-1&prefix=power/adhoc-dump-as-zip-88e8fd0d-6fa9-47d4-9b78-cc5b49e35aa5
prerelease-user-media
power Achala@power
<img width="325" alt="error  entity sync" src="https://github.com/avniproject/avni-client/assets/104890488/e5eb64db-13dd-40d7-8cae-48db15b2deb8">
**To Reproduce**
1. Go to more
2. click on setup fast sync
3. message is coming cannot set up fast sync 
4. click on home 
5. click on sync button 
6. see the error 
escription of what you expected to happen.

**Screenshots**

https://github.com/avniproject/avni-client/assets/104890488/36a33af9-ec05-4770-85d2-c94e780b4792

**Comment by AchalaBelokar** [comment]
- [ ] fast sync is stuck on 10% with same user

**Comment by petmongrels** [comment]
cannot reproduce
