### ISSUE TITLE
Disable manual sync when auto sync is in progress

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1149]
### Background
Multiple syncs happening from the same phone is causing issues with the integrity of data in the system and also registering errors on Bugsnag. These are the known issues
1. Duplicate images being saved - (https://github.com/avniproject/avni-client/issues/1132) (**Most important**)
2. Item to delete is undefined in entityQueue issue in Bugsnag - https://github.com/avniproject/avni-client/issues/843
3. Multiple rows in entity_approval_status table due to multiple POSTs for approval enabled transactions
4. Parallel syncs causing increased load on the server

### Story
As a user, I dont want the changes I ve made in my app, to be uploaded multiple times, so that the app behaves in an expected manner.

Currently automatic sync is disabled when manual sync is started. But we dont disable the manual sync when automatic sync is in progress.

### Tech Recommnedation
- There is existing state SyncActions.syncing to indicate whether a sync is currently in progress. This is currently not being set when the automatic sync is going on. We can change logic to set this to true even for automatic sync.

### Acceptance criteria

- When automatic background sync is in-progress show a different 'Sync' icon and when someone clicks on it, show the message "Automatic sync is in progress. Try again after sometime." 
- Additionally avoid triggering automatic Background sync, if a sync had been completed within the last half an hour.

### Solution Notes
See spike notes here: https://github.com/avniproject/avni-client/issues/1150#issuecomment-1776531064 have added the AC below:

**Comment by himeshr** [comment]
Had tried using the SyncActions.syncing field to implement the fix as suggested in https://github.com/avniproject/avni-client/issues/1150#issuecomment-1776531064, but it resulted in issue due to the Background-sync being re-configured at the end of Manual-sync and overriding the SynComponent.ProgressBarView.onPress action.
Therefore, made use of a separate SyncActions.backgroundSyncInProgress field to make this work as required.


https://github.com/avniproject/avni-client/assets/72493481/a7e12318-bf00-4864-815f-3c1a6862b46c

**Comment by himeshr** [comment]
Made additional code changes to:
 - Skip background-sync if we had recently synced within the last half an hour
 - Show toast message when user clicks on sync button during automatic sync
 


https://github.com/avniproject/avni-client/assets/72493481/d61fc132-42bc-45d5-bd50-0202f5eaadac


https://github.com/avniproject/avni-client/assets/72493481/b42f3d6e-0921-4d7a-8200-d7bdd25ce42f

**Comment by petmongrels** [comment]
SyncService.reset and MenuView.reset code are same. We can move it to GlobalContext.

For QA Purpose (assuming it is developer)
------------------------------------------
- do check logs if there are errors of any type

**Comment by himeshr** [comment]
> SyncService.reset and MenuView.reset code are same. We can move it to GlobalContext.

@petmongrels , i did attempt to move the reset() method to GlobalContext, but the app fails to launch due to cyclic dependency.
I could attempt to make use of the SyncService.reset() in MenuView as well.

**Comment by himeshr** [comment]
@petmongrels , retained only SyncService.reset code and modified menuView to also invoke the same. 
Cannot move to GlobalContext due to cyclicDependency issue.

**Comment by himeshr** [comment]
[Patch_to_perform_full_sync_everytime,_modify_the_commented_code_as_needed_for_testing.patch](https://github.com/avniproject/avni-client/files/13201077/Patch_to_perform_full_sync_everytime._modify_the_commented_code_as_needed_for_testing.patch)

**Comment by mahalakshme** [comment]
@himeshr why do we need this for testing. when there are media observations, its easily identifiable from the logs and auto sync take a long time to complete and making manual sync to overlap is easy. We should try to do testing without code changes so that we can make sure we are testing with the right apk. I will unmark it as Tech for now. Let me know if you still think otherwise.

**Comment by mahalakshme** [comment]
Have made it back tech card after discussion with Himesh.

**Comment by ashusvnath** [comment]
![Image](https://github.com/avniproject/avni-client/assets/568925/5d72fb70-83fa-41d6-8145-3bff22c16775)

Cannot force a manual sync from foreground when a background sync is in progress
