### ISSUE TITLE
Wrong address and address level for subject being stored and displayed on DEA

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#1151]
**Describe the bug**
In avni-client, a subject registered on address level type A  is getting stored in DB on address level type B

**To Reproduce**
1. Go to DEA ,this is an individual subject whose lowest address for registeration is Village/Hamlet but in DEA and as per DB the address_id corresponds to an AWC which is another address level type and not used in individual registeration anywhere.
2. DEA link to subject - https://app.avniproject.org/#/app/subject?uuid=b4869afa-7083-4e74-a351-f69ceefbda13
3. See the address in the DB as well 

```
select * from address_level
left join address_level_type alt on address_level.type_id = alt.id
where address_level.id =334781;
```

4. See the screenshots from mobile app which clearly shows the right village address
5. Attaching other screenshots as well.

**Screenshots**

![Image](https://github.com/avniproject/avni-client/assets/37863085/5a25b7dd-8e50-4bcd-8804-3ec6e9642d59)
![Image](https://github.com/avniproject/avni-client/assets/37863085/9fc527d4-d426-4417-be3d-ae389f440bb7)

![Image](https://github.com/avniproject/avni-client/assets/37863085/c84b9e1d-75b4-43b5-bb5d-5d90653a84b2)
![Image](https://github.com/avniproject/avni-client/assets/37863085/36ffaa81-20ba-425e-89d9-c935e4ddf221)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Metabase report to view all other such individuals - https://reporting.avniproject.org/question/2641-apf-individuals-who-are-registered-in-awc-heirarchy

Users dont have a way to fix the data as it is right in mobile app!

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by mahalakshme** [comment]
according to the reporter, this issue doesn't exist.
