### ISSUE TITLE
Android 13 - Image and Video selection from camera is buggy

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-client#1152]
**Describe the bug**
1. User is not prompted for camera permission and needs to go to OS settings for Avni app and explicitly provide permission for camera to work.
2. For form element of type video, after recording the video, there is no way to go back to the app.

**To Reproduce**
See video:
https://github.com/avniproject/avni-client/assets/54208632/bd311c34-1247-43b1-97ae-d616c95e85f6

### Analysis details:
- Issue exists in 5.0.4(already released) as well
- User can continue uploading image/video from folder
- Issue not occurring in android 10 version and might not occur in other versions as well
- So not a high priority for 5.1.0 release

**Expected behavior**
User should be prompted for camera permission in app if not already provided.
User should be able to come back to the Avni app after recording a video triggered from a video form element.

**Smartphone (please complete the following information):**
 - OS: Android 13

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by ashusvnath** [comment]
@mahalakshme  This seems to be the case with current 5.1.0 build also

**Comment by ashusvnath** [comment]
The first media capture succeeds (be it image or video), all following media captures fail.

**Comment by ashusvnath** [comment]
This problem exists both on emulator and actual phones

**Comment by ashusvnath** [comment]
exception captured from Android logs.
```
FATAL EXCEPTION: main

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.ContentValues.put(java.lang.String, java.lang.Long)' on a null object reference

FATAL EXCEPTION: main
Process: com.android.camera2, PID: 11529
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.ContentValues.put(java.lang.String, java.lang.Long)' on a null object reference
	at com.android.camera.VideoModule.saveVideo(VideoModule.java:1263)
	at com.android.camera.VideoModule.stopVideoRecording(VideoModule.java:1513)
	at com.android.camera.VideoModule.onStopVideoRecording(VideoModule.java:656)
	at com.android.camera.VideoModule.onInfo(VideoModule.java:1296)
	at android.media.MediaRecorder$EventHandler.handleMessage(MediaRecorder.java:1622)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by ashusvnath** [comment]
Similar issue found in Android 13 : https://github.com/flutter/flutter/issues/118443

**Comment by ashusvnath** [comment]
Video capture returns a response where `didCancel` is `true`. Root cause seems to be Exception listed above.

**Comment by ashusvnath** [comment]
A workaround exists.
User can record video directly using camera and choose the appropriate media file for the form element.

**Comment by ashusvnath** [comment]
Issue persists after upgarding to `react-native-image-picker` version `7.0.2`.

**Comment by ashusvnath** [comment]
Created issue #1174 to track inability to capture video from app.
The code changes are in branch 5.1.0 because that is affected too.
