### ISSUE TITLE
Rescheduled task date not displaying immediately

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1153]
env: prod, 
user: maha@poweratuat

### Steps to reproduce:
https://github.com/avniproject/avni-client/assets/10369963/ccfcaf23-2809-40b2-91b9-2518455684ea

1. try to reschedule a task date
2. It doesn't display the updated date.
3. Move out of the screen and come back. It displays the updated date.

### Analysis details:
Happens in 4.0.1 as well. need to fix as part of 5.1.0 before starting to work on major features as part of 6.0.

**Comment by himeshr** [comment]
ScreenRecording after fix.

https://github.com/avniproject/avni-client/assets/72493481/c1aac11e-e541-42fa-9c3b-40bf71a2ac48
