### ISSUE TITLE
Support for devices without telephony enabled

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1157]
### Context
Many devices are disabled from using Avni because they don't have telephony enabled. However, most Avni use-cases do not require telephony. 

### Acceptance criteria
As a user of a device without telephony enabled, when I search for Avni on the playstore, I need to be able to find and install it. 

![Image](https://github.com/avniproject/avni-client/assets/344222/202069e0-f272-40b3-884f-d77ba289cde5)

**Comment by himeshr** [comment]
As per documentation, https://developer.android.com/guide/topics/manifest/uses-permission-element, android:required="false" has to be set in <uses-feature>.

**Comment by himeshr** [comment]
## For this entry,
```
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```
There is a warning about following:
```
Caution: If your app targets Android 5.0 (API level 21) or higher and uses the ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to receive location updates from the network or a GPS, respectively, you must also explicitly declare that your app uses the android.hardware.location.network or android.hardware.location.gps hardware features.
```
------------------
## For this entry,
```
 <uses-permission android:name="android.hardware.telephony" android:required="false"/>
```

The value android:name="android.hardware.telephony" might not be accepted, as it refers to a Implied feature requirement and not a type of Permission.
See https://developer.android.com/guide/topics/manifest/uses-feature-element#permissions-features
and https://developer.android.com/reference/android/Manifest.permission#CALL_PHONE

**Comment by vinayvenu** [comment]
![Image](https://github.com/avniproject/avni-client/assets/344222/3cb41f42-3360-40ed-a505-d9fcda45c723)
