### ISSUE TITLE
Fix invocations to RuleEvaluationService.validateSummaries() to pass valid individualUUID

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-client#1159]
**Describe the bug**

Created for issue reported in ticket [3179](https://avni.freshdesk.com/a/tickets/3179 )
On any SubjectType's Summary rule failure, currently we fail to capture the actual Summary rule failure, due to missing individualUUID value in invocations to RuleEvaluationService.validateSummaries().

**To Reproduce**
1. Go to any SubjectType SummaryRule and add a errorneous logic, storing a value for invalid concept name
2. Sync to client
3. Create an Individual of that subjectType and open the individual
4. The error recorded in RuleFailureTelemetry would be about "Exception in HostFunction: Missing value for property 'RuleFailureTelemetry.individualUuid'", rather than the Summary Rule exception

**Expected behavior**
A ruleFailureTelemetry for SubjectType SummaryRule  exception should be created instead

**Smartphone (please complete the following information):**
 - Version 5.0.3 (Playstore version) 

**Additional context**
Issue occurs for Goonj "Dispatch" SubjectType Summary Rule.

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [x ] Does the fix require extensive regression testing? No
- [x] Are you mentioning the required scenarios that could be affected?

## Test Scenarios
- Go to any SubjectType's SummaryRule and add the following :
```
"'use strict';
({params, imports}) =>  {
  const {summaries, individual} = params;

     summaries.push({
       name: ""Invalid Concept name"",
       value: individual.that.lowestAddressLevel.locationMappings[0].parent.name
     });
    
    console.log(summaries);
    return summaries;
};"
```
This should result in a RuleFailureTelemetry to be created about SubjectType SummaryRule  exception, rather than creating RuleFailureTelemetry about "Exception in HostFunction: Missing value for property 'RuleFailureTelemetry.individualUuid'", 

## Reference SQL commands
```
set role goonj;

select id, uuid, name, subject_summary_rule  from subject_type; /* where uuid = 'bc0a4ae3-77b3-4620-81c4-2d02d1c62280';*/

select error_message, count(*) from rule_failure_telemetry
-- where id > 54640
group by error_message
-- order by error_date_time desc;

select error_date_time from rule_failure_telemetry
where error_message = 'Cannot read property ''name'' of null'
-- group by error_message;
```

**Comment by mahalakshme** [comment]
@himeshr the implementation rule is fixed right? @cc: @nupoorkhandelwal

**Comment by himeshr** [comment]
> @himeshr the implementation rule is fixed right? @cc: @nupoorkhandelwal

Yes, rule has been fixed in goonj and goonjUat orgs

**Comment by AchalaBelokar** [comment]
I tried with apfodishauat but summery rule is showing there.
