### ISSUE TITLE
After sync, on opening app, Custom Dashboard page load fails 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1164]
**Describe the bug**
After sync, on opening app, Custom Dashboard page load fails 
user Ach@sakhiapp
for this we need to use 5.0 release apk
prev release 5.0: https://output.circle-artifacts.com/output/job/98580645-7e17-44d3-bb4a-0458005fda91/artifacts/0/generic-prerelease-2f3bad8809ea044e3d1229177a5266097b04fc3a.apk

error shows after this
Fatal error: Exception in HostFunction: 'Individual' has no property 'individual'
Stacktrace:[{"fileName":"(native):0:0","functionName":"filtered","source":"    at filtered (native)"},{"fileName":"(native):0:0","functionName":"apply","source":"    at apply (native)"},{"columnNumber":1065391,"lineNumber":1,"fileName":"address at index.android.bundle:1:1065391","functionName":"filtered","source":"    at filtered (address at index.android.bundle:1:1065391)"},{"columnNumber":52,"lineNumber":4,"fileName":"JavaScript:4:52","functionName":"anonymous","source":"    at anonymous (JavaScript:4:52)"},{"columnNumber":1459135,"lineNumber":1,"fileName":"address at index.android.bundle:1:1459135","functionName":"executeDashboardCardRule","source":"    at executeDashboardCardRule (address at index.android.bundle:1:1459135)"},{"columnNumber":1459172,"lineNumber":1,"fileName":"address at index.android.bundle:1:1459172","functionName":"getDashboardCardCount","source":"    at getDashboardCardCount (address at index.android.bundle:1:1459172)"},{"columnNumber":2400026,"lineNumber":1,"fileName":"address at index.android.bundle:1:2400026","functionName":"getReportCardCount","source":"    at getReportCardCount (address at index.android.bundle:1:2400026)"},{"columnNumber":2394723,"lineNumber":1,"fileName":"address at index.android.bundle:1:2394723","functionName":"anonymous","source":"    at anonymous (address at index.android.bundle:1:2394723)"},{"columnNumber":1065513,"lineNumber":1,"fileName":"address at index.android.bundle:1:1065513","functionName":"anonymous","source":"    at anonymous (address at index.android.bundle:1:1065513)"},{"fileName":"(native):0:0","functionName":"forEach","source":"    at forEach (native)"},{"fileName":"(native):0:0","functionName":"apply","source":"    at apply (native)"},{"columnNumber":2136454,"lineNumber":1,"fileName":"address at index.android.bundle:1:2136454","functionName":"value","source":"    at value (address at index.android.bundle:1:2136454)"},{"columnNumber":1065475,"lineNumber":1,"fileName":"address at index.android.bundle:1:1065475","functionName":"forEach","source":"    at forEach (address at index.android.bundle:1:1065475)"},{"columnNumber":2394607,"lineNumber":1,"fileName":"address at index.android.bundle:1:2394607","functionName":"refreshCount","source":"    at refreshCount (address at index.android.bundle:1:2394607)"},{"columnNumber":2336449,"lineNumber":1,"fileName":"address at index.android.bundle:1:2336449","functionName":"anonymous","source":"    at anonymous (address at index.android.bundle:1:2336449)"},{"columnNumber":2499403,"lineNumber":1,"fileName":"address at index.android.bundle:1:2499403","functionName":"combination","source":"    at combination (address at index.android.bundle:1:2499403)"},{"columnNumber":2498507,"lineNumber":1,"fileName":"address at index.android.bundle:1:2498507","functionName":"dispatch","source":"    at dispatch (address at index.android.bundle:1:2498507)"},{"columnNumber":1201740,"lineNumber":1,"fileName":"address at index.android.bundle:1:1201740","functionName":"dispatchAction","source":"    at dispatchAction (address at index.android.bundle:1:1201740)"},{"columnNumber":4022082,"lineNumber":1,"fileName":"address at index.android.bundle:1:4022082","functionName":"anonymous","source":"    at anonymous (address at index.android.bundle:1:4022082)"},{"fileName":"(native):0:0","functionName":"apply","source":"    at apply (native)"},{"columnNumber":245444,"lineNumber":1,"fileName":"address at index.android.bundle:1:245444","functionName":"anonymous","source":"    at anonymous (address at index.android.bundle:1:245444)"},{"columnNumber":244774,"lineNumber":1,"fileName":"address at index.android.bundle:1:244774","functionName":"_callTimer","source":"    at _callTimer (address at index.android.bundle:1:244774)"},{"columnNumber":246512,"lineNumber":1,"fileName":"address at index.android.bundle:1:246512","functionName":"callTimers","source":"    at callTimers (address at index.android.bundle:1:246512)"},{"fileName":"(native):0:0","functionName":"apply","source":"    at apply (native)"},{"columnNumber":97357,"lineNumber":1,"fileName":"address at index.android.bundle:1:97357","functionName":"__callFunction","source":"    at __callFunction (address at index.android.bundle:1:97357)"},{"columnNumber":95850,"lineNumber":1,"fileName":"address at index.android.bundle:1:95850","functionName":"anonymous","source":"    at anonymous (address at index.android.bundle:1:95850)"},{"columnNumber":96790,"lineNumber":1,"fileName":"address at index.android.bundle:1:96790","functionName":"__guard","source":"    at __guard (address at index.android.bundle:1:96790)"},{"columnNumber":95808,"lineNumber":1,"fileName":"address at index.android.bundle:1:95808","functionName":"callFunctionReturnFlushedQueue","source":"    at callFunctionReturnFlushedQueue (address at index.android.bundle:1:95808)"}]

**To Reproduce**
1.login with Ach@sakhiapp
2. Click on after sync
3. See error

**Expected behavior**
User is able to see the dashboard 

**Screenshots**

https://github.com/avniproject/avni-client/assets/104890488/bdc99ea1-49e1-4d59-9b83-dad5dd999982

**Comment by himeshr** [comment]
The issue was that one of the ReportCard rules was erroring due to incorrect RealmQuery Syntax.
We have fixed the query.

Code fix done as part of this card, is to not crash the app on a dashboard card query failure, but rather show only that card as an error.

<img width="751" alt="Screenshot 2023-11-01 at 4 25 18 PM" src="https://github.com/avniproject/avni-client/assets/72493481/7b6840be-9fba-4c51-9ae3-4c39bab299f3">
<img width="751" alt="Screenshot 2023-11-01 at 4 25 03 PM" src="https://github.com/avniproject/avni-client/assets/72493481/77ab3c3c-2152-4db4-8b62-feee06332d06">

**Comment by mahalakshme** [comment]
added this to product release notes.
