### ISSUE TITLE
getting sync issue Mobile crcehes 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1165]
**Describe the bug**
getting sync issue Mobile crcehes 
Login with test@mobilecreches
also this happen with dinesh@jscs

**To Reproduce**
1. Go to test@mobilecreches
2. Click on login
3. See error

**Expected behavior**
User is able to login to home screen

**Screenshots**

https://github.com/avniproject/avni-client/assets/104890488/197c155b-07ee-4de6-bc60-799845f4f327

**Comment by vinayvenu** [comment]
Added a migration to ensure all organisations have an organisation_config. This was missing in some organisations.

**Comment by AchalaBelokar** [comment]
Jscs is present in the org config still it is giving me error

**Comment by vinayvenu** [comment]
unrelated error. The user in question did not have idPrefix setup.
