### ISSUE TITLE
After sync, on opening app, home page loading takes very long (>5 minutes)

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1166]
**Describe the bug**
Login with vinay@stccv
the dashboard qurey is 12.8 min to load the data

**To Reproduce**
1. login with vinay@stccv
2.see the dashboard

**Expected behavior**
Dashboard card no should less time

**Screenshots**

**Comment by mahalakshme** [comment]
check if this is the case with prod. But generally such cards that will take more time are moved under More menu and not kept at home page level. could be that auto refresh is not disabled for these users. Doesn't look like a product bug. But just need to make sure since happening on home page.

**Comment by 1t5j0y** [comment]
Verified with prod client v5.0.4 and the dashboard takes 12 mins there as well.
