### ISSUE TITLE
navigation issue

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1167]
User is not able to enroll the child into the program.
steps to reproduce the issue
1. register a child,
2. click on enroll the child into the program button.
3. fill the first page,
4. once you click to move to next page, the app stops working and shows the white screen.

video of the process is attached for reference.

https://github.com/avniproject/avni-client/assets/134054506/b7466311-f07d-4721-9e09-8938ebdbd4bd

For SNCU only, unable to do the child follow up as well.
steps to reproduce:
1. go to the child profile,
2. click on the planned visit "Do" button,
3. keep filling the form,
4. At the last page, when you click on the "Next" button the app screen goes white.

For JSSCP also we are facing the same issue.
Steps to Reproduce:
1. Register the individual
2. Try to enroll in the program (eg : i have tried for pregnancy program)
3. Fill the form 
4. once we click on the next page ,the app gets crash

Error code from log :

11-03 14:39:54.860 14420 14466 D ReactNativeJS: [2:39:54:860] [RuleEvaluationService][Debug] {"enrolmentDecisions":[],"encounterDecisions":[],"registrationDecisions":[]}
11-03 14:39:54.864 14420 14466 D ReactNativeJS: [2:39:54:864] [RuleService][Debug] Getting Rules of Type Checklists for Form - Hypertension Enrolment 227c6d34-8094-41d0-acec-41e2d30ab8f4
11-03 14:39:54.864 14420 14466 D ReactNativeJS: [2:39:54:864] [ErrorHandler][Debug] IsFatal=true TypeError: Cannot read property 'schema' of undefined
11-03 14:39:54.864 14420 14466 D ReactNativeJS: [2:39:54:864] [ErrorHandler][Debug] Cannot read property 'schema' of undefined
11-03 14:39:54.867 14420 14466 D ReactNativeJS: [2:39:54:867] [ErrorHandler][Debug] Creating frame array
11-03 14:39:54.867 14420 14466 D ReactNativeJS: [2:39:54:867] [ErrorHandler][Debug] Notifying Bugsnag TypeError: Fatal error: Cannot read property 'schema' of undefined
11-03 14:39:54.868 14420 14466 E ReactNativeJS: 'App', 'undefined, "renderError: Fatal error: Cannot read property \'schema\' of undefined\\nStacktrace:[{\\"columnNumber\\":2359990,\\"lineNumber\\":1,\\"fileName\\":\\"address at index.android.bundle:1:2359990\\",\\"functionName\\":\\"getNextScheduledVisits\\",\\"source\\":\\"    at getNextScheduledVisits (address at index.android.bundle:1:2359990)\\"},{\\"columnNumber\\":2337488,\\"lineNumber\\":1,\\"fileName\\":\\"address at index.android.bundle:1:2337488\\",\\"functionName\\":\\"handleNext\\",\\"source\\":\\"    at handleNext (address at index.android.bundle:1:2337488)\\"},{\\"columnNumber\\":2356807,\\"lineNumber\\":1,\\"fileName\\":\\"address at index.android.bundle:1:2356807\\",\\"functionName\\":\\"onNext\\",\\"source\\":\\"    at onNext (address at

**Comment by himeshr** [comment]
Issue is caused due to mismatch in models version for 5.1.0 branch avni-client, we should have used models version built using 5.1.0 branch.

After using the correct models, program enrolment for the first case worked as expected, suspecting other issues to also have been resolved with this fix.

After fix screen recording:

https://github.com/avniproject/avni-client/assets/72493481/ce11b9ed-2bca-49a2-97b6-c31e69fd26e0
