### ISSUE TITLE
Task assignments not getting synced

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1168]
Raising the issue on behalf of Nupoor
User: nupoork@power, password: u know it

### How to reproduce:
Assign Call tasks to nupoork@power user
On login with that user, MissedCalls dashboard is empty and the assigned tasks are not synced.

### Screenshots for the same:

![Image](https://github.com/avniproject/avni-client/assets/10369963/f8082576-2d24-4149-a113-f63631c6a4b3)

![Image](https://github.com/avniproject/avni-client/assets/10369963/9f4cf97b-413b-47c9-a927-9bfae6fd0c6a)

**Comment by vinayvenu** [comment]
<img width="368" alt="image" src="https://github.com/avniproject/avni-client/assets/344222/bf7af197-7ba7-4c8e-8bc5-e170d6ae703a">

After assigning a few more missed calls
<img width="366" alt="image" src="https://github.com/avniproject/avni-client/assets/344222/c7956b9f-a35e-4c52-a316-0df1b2f40c93">

<img width="369" alt="image" src="https://github.com/avniproject/avni-client/assets/344222/9fb6be48-eedf-45e8-b766-a490ccf24f52">

<img width="360" alt="image" src="https://github.com/avniproject/avni-client/assets/344222/bfd9a0f0-10cc-46bc-a740-7f22f755c468">



Please reverify.

**Comment by mahalakshme** [comment]
@vinayvenu @nupoorkhandelwal checked with this latest apk: https://output.circle-artifacts.com/output/job/2e851bd6-1383-40f8-95f7-7838c101f4ca/artifacts/0/generic-prerelease_dev-a3ceba0e8e865d855e4d09f2224994b1f5abf38d.apk

**Comment by mahalakshme** [comment]
@AchalaBelokar test the above with the latest apk
