### ISSUE TITLE
Custom dashboard extra buttons visible while processing data

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1170]
for Sewa Rural ADSR
when accessing the custom dashboard under more options:extra info is visible at the bottom of the screen "Register", "Search" & "More" - doesn't happen once the dashboard nos are loaded.
[](url)

![Image](https://github.com/avniproject/avni-client/assets/134054506/b1879640-d169-40c2-b668-17761915bc4c)

A screenshot is attached for reference.

**Comment by 1t5j0y** [comment]
[Navigator.SceneConfigs.FadeAndroid](https://github.com/facebookarchive/react-native-custom-components/blob/d5201e53221a2460b096ee82ff4480f3b0de7fe4/src/NavigatorSceneConfigs.js#L646) works well too.

Went with reusing and speeding up current animation (PushFromRight) to minimise change in UX.
