### ISSUE TITLE
Sync button stays disabled if background sync fails

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-client#1177]
**Steps to reproduce**
Login with a user for whom sync is failing.
Background sync gets triggered (some scenarios mentioned below).
Sync button stays disabled even though background sync attempt has completed (has failed).

The above is an _easier_ way to reproduce the issue but the issue could occur from any temporary failure during automatic sync as well which would lead to user being unable to sync manually (for at least an hour when the next automatic sync runs and completes successfully).

**Expected behaviour**
Sync button should only be disabled while background sync is ongoing. It should be enabled when background sync completes (either succeeds or fails) so that users can sync when they want.

**Scenarios**
Login -> Automatic foreground sync -> Automatic background sync
Update from older version of app -> Launch app -> automatic background sync

**Comment by mahalakshme** [comment]
@1t5j0y kindly add steps to reproduce. Since u have already seen the issue, would be easier for u.

**Comment by ashusvnath** [comment]
### Dev Testing:
**Setup**:  The sync schedule timings was reduced to 15 minutes. Avni client was started in dev mode. Log into the application. The lastSyncExecution check was bypassed. The local avni server was stopped.  
**Observation**: The sync icon on the app was not disabled even after multiple intervals of 15 minutes.
