### ISSUE TITLE
Bugnsnag error: Cannot read property 'syncEndTime' of null

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-client#1178]
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/654b8b8ced7ec300080c5707

```
TypeError Fatal error: Cannot read property 'syncEndTime' of null 
    /home/circleci/avni-client/packages/openchs-android/src/task/Sync.js:75:57 wasLastCompletedSyncDoneMoreThanHalfAnHourAgo
    /home/circleci/avni-client/packages/openchs-android/src/task/Sync.js:41:66 ?anon_0_
    native next
    /home/circleci/avni-client/packages/openchs-android/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:23 asyncGeneratorStep
    /home/circleci/avni-client/packages/openchs-android/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:26 _next
    /root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16 tryCallOne
    /root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27 anonymous
    native apply
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:247:22 anonymous
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:111:14 _callTimer
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:161:14 _callReactNativeMicrotasksPass
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:415:41 callReactNativeMicrotasks
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:392:41 __callReactNativeMicrotasks
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:132:38 anonymous
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:368:10 __guard
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:131:16 flushedQueue
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:116:28 callFunctionReturnFlushedQueue
```

**Testing notes**
This issue does not break the UI currently as it is within a try/catch.
Needs to be tested with non dev apk (bugsnag not notified in dev apk) or if testing in dev APK following line should not be printed:
`[ErrorHandler][Debug] Cannot read property 'syncEndTime' of null`
Can simulate this by testing with a user with no fast sync setup, first login on a device (no previous sync telemetry records) and background sync enabled.
- Login
- Interrupt the sync that starts on login by killing data/wifi.
- Wait for a minute till sync times out.
- Background sync should trigger which should not throw the above error

**Comment by 1t5j0y** [comment]
Was unable to simulate this locally. Changed the logic to be in line with other similar existing checks to hopefully prevent this from occurring.

**Comment by himeshr** [comment]
wasLastCompletedSyncDoneMoreThanHalfAnHourAgo() was supposed to return true to allow automatic sync in following scenarios:
 - After fresh login, before even the first time Manual sync is performed
 - After atleast half an hour has passed since the last sync was performed (To avoid auto-sync on every app start and Manual Sync Completion)
 
 As per the code fix done as part of this card, we'll miss out on the first case.

**Comment by 1t5j0y** [comment]
Able to simulate the original error if there are no completed records in sync telemetry.
Issue was because realm still returns a non 'empty' result in this case.
Restored original check logic and changed the retrieval to fetch the latest record. Fixed the 12 hour similar check as well.
