### ISSUE TITLE
Sort content display of pending, approved and rejected cards

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1181]
### Motivation:
As a user, when I try to approve the cards, I would like to see all the cards related to a subject together, to be able to easily approve.

### Current status:
- cards not sorted in any order

### Acceptance criteria:
- Sort by the name of the subject(we display on the card) in ascending order(independent of difference in subject type), so that all requests related to a subject get grouped
- Order within the same subject name based on request type: First, 'Registration request', 'Encounter request', 'Program Enrolment Request','Program Encounter Request', then 'Checklist Item Request'
- The sorting should be applied to all Approval related cards - Pending, Rejected and Approved.

**Comment by petmongrels** [comment]
made assumption that a program cannot be under two subject types and encounter type cannot be under different programs or subject types.

video - https://avni.readme.io/docs/approval-workflow#updates-to-the-approval-status-ui-in-development

**Comment by AchalaBelokar** [comment]
- [ ] I login with AchalaB@akrsp then I created ward with name Xgh then I fill the 1st jal chupal encounter and aggain I fell same encounter then card showing me exact count but in the card it is showing me only one encounter ..
- [ ] And sorting is not working
