### ISSUE TITLE
Filter by location for approval cards

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1183]
### Motivation:
- As a user, I want to filter **"Approval"** cards by location since I get many approval requests per day. And this will ease my job to find all requests from a location and hence speedup my work.
- And adding these filters will take us closer to deprecating MyDashboard and replacing it with CustomDashboards.

### Analysis:
- We have added filter support for custom report cards. But we dont have filters support for all standard report cards. My dashboard which has filters support doesn't include approval related cards as well. 

### Acceptance criteria:
- I should be able to filter all approval request types(Registration, Encounter, ProgramEnrolment, ProgramEncounter) by Location when approval related standard report cards are added to a custom dashboard and when Location filter is configured on the custom dashboard
- The filtered results should be visible on all approval cards 'Pending', 'Approved' and 'Rejected'.
- I should be able to filter on any level in location hierarchy. Say users catchment has 2 talukas, and each taluka has 2 villages. Though say a waterbody subject is registered at village level, I should be able to filter at taluka level.

### Dependency:
Pickup this after: https://github.com/avniproject/avni-client/issues/1185 is done

**Comment by himeshr** [comment]
Most of the code changes for this have already been done as part of #1185.
Only adding some additional test to validate the new functionality.

**Comment by AchalaBelokar** [comment]
I added address filter on approval  on rwbnitiuat but filter is not showing selected address record.. same for lahi.. there is one record on student which is from washim location in maharashtra I filtered  with other location still that student  is showing to me
