### ISSUE TITLE
Filter by location for default cards in custom dashboard

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1185]
### Motivation:
- As a user, when default cards **(ScheduledVisits, OverdueVisits, Last 24 hour registerations, Last 24 hour enrolments, Last 24 hours visits, Total and DueChecklist)** of standard report card type are added to the custom dashboard, I am unable to filter the result.
- And adding these filters will take us closer to deprecating MyDashboard and replacing it with CustomDashboards.

### Analysis:
- What is default card? Standard report cards that display on MyDashboard. Note: We dont display all standard report cards on MyDashboard.
- Currently, filters for default cards in MyDashboard already support filtering by address. The logic for adding locationQuery is in `MyDashboardActions.js`

### Acceptance criteria:
- Should support filtering at all locations levels in the hierarchy for all the default cards.
- Existing filters of Mydashboard should continue to work as before. 
- Performance should be within reasonable level. Test the same with prod data.
- MyDashboard will eventually be deprecated. Keep that in mind, when deciding to take on any big refactorings.

### Known Issues to be fixed in this card:
 - Fix issue with first time login for Power user nupoork@power on staging / local

### Tech tasks
 - We have been working on this using Power org
 - We have made use of OR filter on locationAddressLevel UUID to do the reduction
 - Wherever the impacted methods are also invoked by MyDashboard, we send empty arrayList to make it a no filter operation
 - Has to be done for all standard ReportCards
            - case standardReportCardType.isDefaultType() :
            - case standardReportCardType.isChecklistType() :
                
 - Has to be done for all subTypes within each of the above standard report cards
 - Tests have to be created for each of the standardReportCardType and their subtypes

**Comment by mahalakshme** [comment]
@himeshr @petmongrels there are other cards to take care of approval, comment, task and checklist. this card deals with only default type. I ve mentioned in the description. This is to parallelise work once this card is done and to not block the release and to group by complexity.

**Comment by himeshr** [comment]
Code changes done and test created to support filter by location for following:
(ScheduledVisits, OverdueVisits, Last 24 hour registerations, Last 24 hour enrolments, Last 24 hours visits, Total and DueChecklist)

Pending work:
Fix issue with first time login for Power user nupoork@power on staging / local

**Comment by himeshr** [comment]
Unable to reproduce the first time login failure for Power user nupoork@power on local.
There were minor regression issues fixed as part of earlier commits, which might have resolved this.
Moving to CodeReviewReady.
