### ISSUE TITLE
Filter by location for Comment and Task standard report cards

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1186]
### Motivation:
Being able to filter will complement with the filters applied to other standard report cards

### Acceptance criteria:
- Comments and tasks should be filtered by the subjects location
- Should work with all task type cards - Tasks, Call tasks and Open Subject tasks
- If subject is not present for a task/comment entry, when filtered by location that entry should not appear in filter results. 
- Should work with filtering at all address levels
- Performance should be within reasonable level. Test the same with prod data.
- MyDashboard will eventually be deprecated. Keep that in mind, when deciding to take on any big refactorings related to it.

### Dependency:
- Pickup this after: https://github.com/avniproject/avni-client/issues/1185 is done

**Comment by petmongrels** [comment]
these two commits as well
- https://github.com/avniproject/avni-client/commit/972060865b198579317b42eb0c83c530d03c1522
- https://github.com/avniproject/avni-client/commit/7558574e34173a0efeb66d63d440bd7796612ede

**Comment by Dinesh2019** [comment]
we still able to see the filter is not applying for standard card attached the video for the reference.
Use master branch latest commit as of 03 Jan 2024, Staging APK for testing.
APK Link: https://app.circleci.com/pipelines/github/avniproject/avni-client/2206/workflows/09629395-3431-4aa8-b8cb-150c70db9869/jobs/13621/artifacts



https://github.com/avniproject/avni-client/assets/127730126/f3b606e4-18ef-4803-b6f8-5ef2952ab088

**Comment by petmongrels** [comment]
This is not a bug, tested with actual address filter (which is saved now)
The dashboard filter is misleading and this implementation is good for testing this.
- the dashboaord filter says location but is pointing to concept
- the registration for also doesnt work in this impl because the saving the observation in the form for "location" not address doesnt save the data.

**Comment by Dinesh2019** [comment]
@petmongrels Issue happens in  pre-release 

org: power

Steps to reproduce:
1.Login in the app
2.enabled the comment in the org
3.added the card and added the filter in the offline dashboard 
4.add the applying the filter count becomes zero


https://github.com/avniproject/avni-client/assets/127730126/f9ba2a96-6141-4846-8af6-43cb3979aa0b

**Comment by mahalakshme** [comment]
@petmongrels looks like a bug found on a 6.1.0 card

**Comment by petmongrels** [comment]
The subject is registered to Test01->Test01 that is why it is not showing when only Test01 is selected. This is how the feature has been implemented. I have added a subtext to clarify this.
