### ISSUE TITLE
Ability to configure the server url for fresh installation

### ISSUE THREAD

**Issue by deeptirawat1510** [avniproject/avni-client#1191]
### Motivation
We don't need to build different environments separately in same flavour. 

### Acceptance Criteria
As a user installing the application for the first time, I want to see a new UI before the login screen.

### Visual Design
<img width="316" alt="Screenshot 2023-11-20 at 5 39 53 PM" src="https://github.com/avniproject/avni-client/assets/111413203/dcc85d23-100d-415d-a3c3-18d17528f806">

### Tech Approach

1. If a URL is present in the async storage, the modified settings service should retrieve it.
2. If no URL is present in async storage, the application should display the default UI.

**Comment by AchalaBelokar** [comment]
I install the latest apk https://app.circleci.com/pipelines/github/avniproject/avni-client/2111/workflows/4fe1d0c8-5118-475e-bae3-1deb940cb95e/jobs/13017
 but I am not able to see the url page

**Comment by ashusvnath** [comment]
@AchalaBelokar : This wont work for the apk's currently being built in our pipeline.
A new apk needs to be built with `no_env`.

**Comment by vinayvenu** [comment]
@AchalaBelokar please follow instructions in https://avni.readme.io/docs/release-process-for-the-cloud#circleci-build with the value of flavor set to no_env.

**Comment by AchalaBelokar** [comment]
@vinayvenu I tried with generate flavour set to no_env , circle ci don’t allow me to add flavour .

**Comment by 1t5j0y** [comment]
As I understand it, `no_env` is not a flavor, it is an environment, so we will either need to:
- add circleci config to add an entry to generate no_env apks if this is going to be regularly required
OR
- someone generates a no_env apk for Achala to test this story

**Comment by ashusvnath** [comment]
@1t5j0y , @vinayvenu : I'm going create a gated stage that builds with `no_env` config and `generic` flavor on CI
