### ISSUE TITLE
MainActivity undefined not a function

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1193]
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/6555bfb0a21d4e0007c9ef13?filters[error.status]=for_review&filters[event.since]=7d&filters[app.release_stage]=prod

https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/65544fcaf0e4ba000896f69e?filters[error.status]=for_review&filters[event.since]=7d&filters[app.release_stage]=prod

https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/655451da71f813000784e1c9?event_id=655c4ac600cd1de2128d0000&i=em&m=fq&pivot_tab=user.id

In all the above cases, it is failing in state.clone() across orgs.
Found happening in 5.1.1 and 5.1.0 release

**Comment by ashusvnath** [comment]
Cannot reproduce issue trivially with any multi-select form element on any form.

**Comment by ashusvnath** [comment]
@1t5j0y  and I paired on understanding this issue.
We tried to create a user (suhasv@power) in the same catchment as affected user ankit@power.
After logging in as  suhasv@power, we registered an individual and then filled the identification encounter form.
We didn't get the "Fatal error: undefined is not a function" error on the emulator.

**Comment by mahalakshme** [comment]
@ashusvnath can you try with actual phone. Also checking the device details of the user might help

**Comment by vinayvenu** [comment]
This is not expected to be easily reproducible. It is happening across
forms and organisations at a low scale

**Comment by ashusvnath** [comment]
@mahalakshme : Tried with actual device version 5.1.1. Issue not reproducible.
