### ISSUE TITLE
MainActivity MediaQueueService syncTimeoutError bugsnag issue

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1196]
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/655610c4ac29810008fbc094?event_id=655d7c0800cd055884e60000&i=em&m=fq

```
Error syncTimeoutError 
    /home/circleci/avni-client/packages/openchs-android/src/service/MediaQueueService.js:231:51 anonymous
    /root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16 tryCallOne
    /root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27 anonymous
    native apply
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:247:22 anonymous
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:111:14 _callTimer
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:161:14 _callReactNativeMicrotasksPass
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:415:41 callReactNativeMicrotasks
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:392:41 __callReactNativeMicrotasks
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:132:38 anonymous
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:368:10 __guard
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:131:16 flushedQueue
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:116:28 callFunctionReturnFlushedQueue

```

### Acceptance criteria:
- Decide on linear or limited parallelisation based on how fast sync is on complete linearlisation
- Update media upload progress to users like we show for other entities

**Comment by ashusvnath** [comment]
Noticed some users from 'hdka' were facing this issue, so I created a test user in their catchments to see if could re-create the issue on my device. Could not re-create the issue.

**Comment by ashusvnath** [comment]
`sync_telemetry` for one user does not contain entry for today for user `srustita@hdka` even though Bugsnag shows one failure in the last 3 hours.

**Comment by ashusvnath** [comment]
- Sync failed 44 times for sunitab@mukti between 26th and 27th of November according to sync_telemetry, Bugsnag reports only 33 of these events . Sync then started working again.
- Sync failed 7 times for user rupesha@mukti between 5:30 and 9:30 UTC on 27th of November, all failures recorded in sync_telemetry . Sync then started working again.
- Sync failure reported >10 times to Bugsnag but recorded sync_telemetry incomplete only 5 times on 23rd November for user nandini@hdka. Sync then started working again.
- 14 Intermittent failures recorded for pankaj.aavishakar@gdgsgom in SyncTelemetry on 25h Nov UTC, Bugsnag reports only 10 of those event. Sync has worked intermittently for user.

**Comment by mahalakshme** [comment]
@ashusvnath have updated the AC based on what we discussed.

**Comment by ashusvnath** [comment]
A constant set of 12 media files was chosen to test how parallelism affects upload time:
| Parallellism | Time taken | Failures Observed at low Bandwidth / poor connection |
|---|---|---|
| 1 | ~8.8s | None |
| 2 | ~7.5s | Multiple failures at low bandwidth|

Based on above data, choosing to do the uploads linearly

**Comment by vinayvenu** [comment]
1. Translations for statusMessageCallback
2. Take a look at the comments, some of them have become wrong now. 
3. We usually import moment as 'moment', not Time in the rest of the repo (around 40 times). Makes it hard to recognise when you call it Time in one place alone.

**Comment by AchalaBelokar** [comment]
while using with 2g it is not working

**Comment by 1t5j0y** [comment]
@AchalaBelokar what is happening while using 2g?

**Comment by 1t5j0y** [comment]
Checked using 2G network and didn't find any issues.

Did some refactoring around the media upload logic:
- Go back to Promise.all instead of Promise.allSettled since we are now doing sequential chunks and to simplify code
- Update comments to reflect behaviour
- Update callback message to show total count while first media chunk is being processed
- Notify bugsnag of underlying failure so we can differentiate failure causes
