### ISSUE TITLE
Z-score mismatch

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1197]
https://avni.freshdesk.com/a/tickets/3216

Context: Seems like Avni Z- score calculation is not matching with the WHO calculator

https://github.com/avniproject/avni-health-modules/tree/master/src/health_modules - this has the code to calculate z-score.

### Process:
- Understand the impact to see how this mismatch might categorise say a child as normal instead of SAM
- Analyse why the difference is
- Discuss with the team - since the z-score calculation doesn't seem to be touched for more than a year now
- Based on the discussion code changes if necessary

**Comment by 1t5j0y** [comment]
Gaps:
1. [weight for length data on WHO website](https://www.who.int/tools/child-growth-standards/standards/weight-for-length-height) has 2 separate set of standard data based on age. These sets of data have some overlap as well. Age is not considered in Avni wflh calculation.
2. weight-for-length data in Avni has some overlaps of weight data points but we use _.find so the overlaps are always ignored. (Eg: Lines 1095 and 1996 in [wflh_girls.json](https://github.com/avniproject/avni-health-modules/blob/29e0d42c8733a1bc569c5c726df30bf373603aff/src/health_modules/child/anthropometry/wflh_girls.json#L1095) )


No other gaps found during preliminary investigation. Moving to on hold to discuss solutioning.

**Comment by 1t5j0y** [comment]
Update from Vinay: Avni z-score calculation is based on WHO standards from 2017 which have since changed. Separate product feature to decide how to handle this in Avni given it will impact a few organisations.

For APF, details to be gathered on what their expectation is.

**Comment by vinayvenu** [comment]
Correction - there has not been a change in the values since 2017. We should probably fix this in our code. There will be a change in nutritional status for those who are in the borders (the values will increase for those between 2-5 years old and under 110 cm).
