### ISSUE TITLE
Prevent uuid collisions

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-client#1201]
Use a library like https://github.com/uuidjs/uuid

Acceptance criteria:
- Replace manual UUID generation with a more robust library like above to prevent UUID collisions
- Also identify how and why recently the no of UUID collisions have increased.

**Comment by mahalakshme** [comment]
https://github.com/facebook/hermes/issues/1169 - possible cause of issue - just added to keep track

**Comment by 1t5j0y** [comment]
Likely root cause - https://github.com/facebook/hermes/issues/1169
Used 'uuid' library in both models and client.
