### ISSUE TITLE
Weight for age zscore mismatch

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1217]
Related ticket: https://avni.freshdesk.com/a/tickets/3216

### Steps to reproduce:
- On doing the following,
```
select * from jss.individual_phulwari_growth_monitoring where individual_id=1299188 order by id desc;
```
you will find that the 'Weight for age z-score' is -8.5 for the first encounter visit.
- But when using these values in the WHO provided anthro software [here](https://www.who.int/tools/child-growth-standards/software) the value is -6.71
![Image](https://github.com/avniproject/avni-client/assets/10369963/736cf50b-7243-40da-8e6d-2ab275783ab8)
- The above discrepancy exists when zscore is less than -3 or greater than 3

### Preliminary Analysis:
A different formula is used for calculation of zscore is less than -3 or greater than 3
For the formula check page no:300 in here: [924154693X_eng.pdf](https://github.com/avniproject/avni-client/files/13673258/924154693X_eng.pdf) or check ```compute_zscore_adjusted``` method in the file ```z-score-helper.R``` in the repository [here](https://github.com/worldhealthorganization/anthro) 

### Why this needs to be fixed:
- For the org in focus though for grading/categorising the severity for the child, the above fix doesn't matter, the org mainly focusses on childern where zscore is less than -3  and hence they need reliable values to understand the improvement, to gain confidence to continue the program and to answer their funders.

### Acceptance criteria:
- Fix according to the above formula. After fixing, the values should be inline with the expected values in the  ```Who anthro analysis.xlsx``` sheet attached by the client in the ticket.
- Round the zscore value to 2 digits instead of current one.

**Comment by vinayvenu** [comment]
It looks like the calculation is slightly different for zscores beyond the -3 SD range (see attached document page 301). This might be the reason for the discrepancies. 

I am not sure how important the exact zscore really matters for those beyond the -3 range since there are no real decisions being made at this level from a primary health perspective. Either ways, it is good to correct the calculations and verify that it exactly matches the document for zscores beyond +-3SD

[924154693X_eng.pdf](https://github.com/avniproject/avni-client/files/13601439/924154693X_eng.pdf)

**Comment by mahalakshme** [comment]
@vinayvenu I didn't add 2 decimal points round-off to this story since looks like we have done it intentionally. The comment in our code says ```Weight/height measurements are available only for the nearest single digit, so
the final figure can only have one degree of accuracy.``` So need to make sure before adding it to a card.

**Comment by petmongrels** [comment]
.

**Comment by mahalakshme** [comment]
@petmongrels  The below data can be used to test for cases where zscore is greater than 3
For id 1110369 in jss.individual_phulwari_growth_monitoring, existing "Weight for age z-score" value is 8.7, but looks like actual is 11.08
![Image](https://github.com/avniproject/avni-client/assets/10369963/0d1af75e-d263-4c1b-83ef-414ae2266949)

For id 1233198, existing is 11.6, but looks like actual is 27.08
![Image](https://github.com/avniproject/avni-client/assets/10369963/25aaa2e9-89f1-4e25-85dd-2f271a0b6b4e)

The weight values in the above entries are not realistic/seems wrong. But  this should not be an issue to verify the correctness of zscores.

**Comment by petmongrels** [comment]
it seems this tool uses decimal month age as well, which I haven't implemented - so the numbers are slightly off. but I think it is fine, as the numbers are quite close to adjusted zScores now.

**Comment by mahalakshme** [comment]
@petmongrels how much off it is? The LMS values in WHO website itself is available only for whole months and not for decimal months. I think the same is used in anthro R package which is probably used in anthro WHO calculator exe. wondering we have missed somewhere else like rounding of months? Were the values off for less than -3 as well?

**Comment by petmongrels** [comment]
@mahalakshme 
from the example in this story.......
For id 1233198, existing is 11.6, but looks like actual is 27.08.........our actual value now is 27.57

there is nothing in code that I can make out.
