### ISSUE TITLE
sync is occurring consistently for every module or page in Shift

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1223]
Steps to reproduce 
1.login to any implementation
2.Fresh sync happen
3.Click on the register on the bottom page of the app
4.Click on home again 
5.Again the sync happens

Excepted result : sync should be happen manually or automatically after period of time 
Actual result : sync happens regularly

https://github.com/avniproject/avni-client/assets/127730126/736c8741-a39a-4c30-8e3f-00526486f296

**Comment by petmongrels** [comment]
@himeshr can you test doing manual sync twice after fresh sync. I was seeing a blank screen earlier when I made some of these changes.

**Comment by himeshr** [comment]
@petmongrels , Just now, did attempt freshSync for user dinesh from chashma_uat org.
After fresh sync, clicked on sync button immediately.
Sync completed successfully, no issues were observed.
