### ISSUE TITLE
Save button is not responding 

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1229]
When i register the individual unable to save since the save button is not responding as expected 

env:per-release
org : saahas
User : vaijayanthis@saahas

Steps to reproduce:
1.Login to app
2.click on the register
3.click on the project or organisation
4.Complete the form 
5.click on save or save and another project

Expected : Page should saved and directed to the dashboard page
Actual : save is not responding 

### Analysis:
Though it is happening in specific organisation, looks like we have not handled it right, since we dont show any error as well on the screen. So need to identify the issue.

https://github.com/avniproject/avni-client/assets/127730126/235f17d6-7b7a-4af9-9895-3094d7707570

**Comment by 1t5j0y** [comment]
Issue is because Visit schedule rule to schedule 'Impact Indicator - Yearly' is resolving to 'Invalid Date' (also visible in the video around the 30 second mark).
To be retested once rule is fixed.
