### ISSUE TITLE
After clicking card on Standard dashboard  app is getting crashed 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1230]
**Describe the bug**
After clicking card on Standard dashboard  app is getting crashed 
I tried on sncu user taqim@sncu
After clicking on dashboard card blank screen is coming.

**To Reproduce**
1. login with taqim@sncu
2. standard dashboard is present
3. Click on schedule card
4. . See error

**Expected behavior**
After clicking on card data should be shown 
**Screenshots**

https://github.com/avniproject/avni-client/assets/104890488/7ebc8554-49ef-4410-b33f-961ba30c95bc

**Comment by mahalakshme** [comment]
@AchalaBelokar I am guessing this is for 7.0. correct me if I am wrong
@mahalakshme we need to prioritise this
