### ISSUE TITLE
Need params.entityContext available in old style rule

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#1234]
Currently, in one of the old rule implementation we need to access the Household's observations ie. Group information during the registration of a member registration, in order to achieve this we need to access entityContext in the rule.

### Background context:
entityContext was introduced an year ago to make groups of individual available in rules. Looks like it is not available/accessible for old rules.

**Comment by petmongrels** [comment]
@nupoorkhandelwal 
instead of entityContext have you tried using individual.groupSubjects[x].groupSubject.observations or individual.groupSubjects[x].memberSubject.observations?

@mahalakshme

**Comment by himeshr** [comment]
> @nupoorkhandelwal instead of entityContext have you tried using individual.groupSubjects[x].groupSubject.observations or individual.groupSubjects[x].memberSubject.observations?
> 
> @mahalakshme

@petmongrels 
This will only work after the individual is saved, so during updates. But for creates,  individual.groupSubjects[x]wont have the link as the individual hasn't been persisted to realm. I.e why, we need to use entityContext, which has the groupSubject available for Create as well as update scenarios.

**Comment by vinayvenu** [comment]
EntityContext not available when adding a member to a group. 

https://github.com/avniproject/ihmp/blob/master/registration/rules/registrationHandler.js#L29

Change method to
```
    @WithStatusBuilder
    maritalStatus([entity, ruleTypeValue, context, config, entityContext], statusBuilder){
        console.log('Checking status of entityContext')
        console.log('entityContext', _.keys(entityContext));
        console.log('Still waiting for the entity context to come in')
        statusBuilder.skipAnswers('Remarried', 'Other');
    }
```
```make deploy-staging-rules```

Use ihmp on staging, go to a group and try to add an member. Variable is empty

**Comment by petmongrels** [comment]
- added one commit
- but in rule to get the params, exec method of the class in the rule has to be changed

**Comment by mahalakshme** [comment]
@petmongrels we need not do this until implementation team gets back after trying with new rules. We can discuss in standup what to do with the code change

**Comment by mahalakshme** [comment]
@vinayvenu you mentioned you will check something on this. continuing to release since not a  blocker

**Comment by mahalakshme** [comment]
since this is complex to implement, we decided to write via new rules when such a usecase comes up
