### ISSUE TITLE
Unable lo login in jsscp showing sync failed 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1235]
**Describe the bug**
Unable lo login in jsscp showing sync failed 
I am trying to login with himeshr@jsscp
it is showing me sync failed "Cannot read property 'that' of undefined 

console.error: SyncService GroupSubject{uuid='429ead33-981f-46ef-b02d-5f3781b7ccff'} is unable to find Individual{uuid='db10befe-4375-478d-b5db-039777858d1f'}, {"errorCode":"Ignorable Association error 01","errorText":"GroupSubject{uuid='429ead33-981f-46ef-b02d-5f3781b7ccff'} is unable to find Individual{uuid='db10befe-4375-478d-b5db-039777858d1f'}"} Error: GroupSubject{uuid='429ead33-981f-46ef-b02d-5f3781b7ccff'} is unable to find Individual{uuid='db10befe-4375-478d-b5db-039777858d1f'}
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at SyncError (address at index.android.bundle:1:747827)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at construct (native)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at _createSuperInternal (address at index.android.bundle:1:751679)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at call (native)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at IgnorableSyncError (address at index.android.bundle:1:751960)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at throwSyncError (address at index.android.bundle:1:747335)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at getParentEntity (address at index.android.bundle:1:747144)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at fromResource (address at index.android.bundle:1:948634)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at anonymous (address at index.android.bundle:1:1496100)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at reduce (native)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at persistAll (address at index.android.bundle:1:1502771)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at processResponse (address at index.android.bundle:1:1506630)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at anonymous (address at index.android.bundle:1:1507086)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at apply (native)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at anonymous (address at index.android.bundle:1:246492)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at _callTimer (address at index.android.bundle:1:245486)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at _callReactNativeMicrotasksPass (address at index.android.bundle:1:245651)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at callReactNativeMicrotasks (address at index.android.bundle:1:247573)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at __callReactNativeMicrotasks (address at index.android.bundle:1:97625)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at anonymous (address at index.android.bundle:1:96764)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at __guard (address at index.android.bundle:1:97502)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at flushedQueue (address at index.android.bundle:1:96675)
12-19 17:06:00.331 10337 10397 E unknown:ReactNative:     at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:96618), js engine: hermes, stack:
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: SyncError@1:747827
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: _createSuperInternal@1:751679
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: IgnorableSyncError@1:751960
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: throwSyncError@1:747335
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: getParentEntity@1:747144
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: fromResource@1:948634
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: anonymous@1:1496100
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: persistAll@1:1502771
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: processResponse@1:1506630
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: anonymous@1:1507086
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: tryCallOne@53:15
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: anonymous@139:26
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: anonymous@1:246492
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: _callTimer@1:245486
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: _callReactNativeMicrotasksPass@1:245651
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: callReactNativeMicrotasks@1:247573
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: __callReactNativeMicrotasks@1:97625
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: anonymous@1:96764
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: __guard@1:97502
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: flushedQueue@1:96675
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: invokeCallbackAndReturnFlushedQueue@1:96618
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: _construct@1:104443
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: _construct@1:104366
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: Wrapper@1:104011
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: _createSuperInternal@1:100974
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: SyntheticError@1:102424
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: reactConsoleErrorHandler@1:102061
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: logError@1:660131
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: anonymous@1:1496174
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: persistAll@1:1502771
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: processResponse@1:1506630
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: anonymous@1:1507086
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: tryCallOne@53:15
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: anonymous@139:26
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: anonymous@1:246492
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: _callTimer@1:245486
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: _callReactNativeMicrotasksPass@1:245651
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: callReactNativeMicrotasks@1:247573
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: __callReactNativeMicrotasks@1:97625
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: anonymous@1:96764
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: __guard@1:97502
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: flushedQueue@1:96675
12-19 17:06:00.331 10337 10397 E unknown:ReactNative: invokeCallbackAndReturnFlushedQueue@1:96618
12-19 17:06:00.363 10337 10396 D ReactNativeJS: [5:06:00:362] [SyncService][Debug] Creating entity create functions for schema GroupSubject
12-19 17:06:01.079 10337 10396 E ReactNativeJS: 'SyncComponent-Sync', 'Cannot read property \'that\' of undefined, {}', 'TypeError: Cannot read property \'that\' of undefined\n    at _setChild (address at index.android.bundle:1:746784)\n    at addNewChild (address at index.android.bundle:1:746615)\n    at associateGroupSubject (address at index.android.bundle:1:936555)\n    at associateChildToMultipleParents (address at index.android.bundle:1:936805)\n    at anonymous (address at index.android.bundle:1:1502623)\n    at flatMap (native)\n    at associateMultipleParents (address at index.android.bundle:1:1502482)\n    at persistAll (address at index.android.bundle:1:1503024)\n    at processResponse (address at index.android.bundle:1:1506630)\n    at anonymous (address at index.android.bundle:1:1507086)\n    at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)\n    at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)\n    at apply (native)\n    at anonymous (address at index.android.bundle:1:246492)\n    at _callTimer (address at index.android.bundle:1:245486)\n    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:245651)\n    at callReactNativeMicrotasks (address at index.android.bundle:1:247573)\n    at __callReactNativeMicrotasks (address at index.android.bundle:1:97625)\n    at anonymous (address at index.android.bundle:1:96764)\n    at __guard (address at index.android.bundle:1:97502)\n    at flushedQueue (address at index.android.bundle:1:96675)\n    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:96618)'
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: console.error: SyncComponent-Sync Cannot read property 'that' of undefined, {} TypeError: Cannot read property 'that' of undefined
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at _setChild (address at index.android.bundle:1:746784)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at addNewChild (address at index.android.bundle:1:746615)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at associateGroupSubject (address at index.android.bundle:1:936555)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at associateChildToMultipleParents (address at index.android.bundle:1:936805)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at anonymous (address at index.android.bundle:1:1502623)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at flatMap (native)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at associateMultipleParents (address at index.android.bundle:1:1502482)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at persistAll (address at index.android.bundle:1:1503024)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at processResponse (address at index.android.bundle:1:1506630)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at anonymous (address at index.android.bundle:1:1507086)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at apply (native)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at anonymous (address at index.android.bundle:1:246492)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at _callTimer (address at index.android.bundle:1:245486)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at _callReactNativeMicrotasksPass (address at index.android.bundle:1:245651)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at callReactNativeMicrotasks (address at index.android.bundle:1:247573)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at __callReactNativeMicrotasks (address at index.android.bundle:1:97625)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at anonymous (address at index.android.bundle:1:96764)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at __guard (address at index.android.bundle:1:97502)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at flushedQueue (address at index.android.bundle:1:96675)
12-19 17:06:01.085 10337 10397 E unknown:ReactNative:     at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:96618), js engine: hermes, stack:
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: _setChild@1:746784
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: addNewChild@1:746615
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: associateGroupSubject@1:936555
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: associateChildToMultipleParents@1:936805
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: anonymous@1:1502623
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: associateMultipleParents@1:1502482
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: persistAll@1:1503024
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: processResponse@1:1506630
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: anonymous@1:1507086
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: tryCallOne@53:15
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: anonymous@139:26
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: anonymous@1:246492
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: _callTimer@1:245486
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: _callReactNativeMicrotasksPass@1:245651
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: callReactNativeMicrotasks@1:247573
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: __callReactNativeMicrotasks@1:97625
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: anonymous@1:96764
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: __guard@1:97502
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: flushedQueue@1:96675
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: invokeCallbackAndReturnFlushedQueue@1:96618
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: _construct@1:104443
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: _construct@1:104366
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: Wrapper@1:104011
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: _createSuperInternal@1:100974
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: SyntheticError@1:102424
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: reactConsoleErrorHandler@1:102061
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: logError@1:660131
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: _onError@1:1458459
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: tryCallOne@53:15
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: anonymous@139:26
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: anonymous@1:246492
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: _callTimer@1:245486
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: _callReactNativeMicrotasksPass@1:245651
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: callReactNativeMicrotasks@1:247573
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: __callReactNativeMicrotasks@1:97625
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: anonymous@1:96764
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: __guard@1:97502
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: flushedQueue@1:96675
12-19 17:06:01.085 10337 10397 E unknown:ReactNative: invokeCallbackAndReturnFlushedQueue@1:96618
12-19 17:06:01.148 10337 10396 D ReactNativeJS: [5:06:01:148] [SyncComponent::AC][Debug] Dispatching action: "SyncTelemetryActions.SYNC_FAILED"
12-19 17:06:01.226 10337 10396 D ReactNativeJS: [5:06:01:226] [SyncComponent::AC][Debug] Dispatched action completed: "SyncTelemetryActions.SYNC_FAILED" {"syncing":true,"isConnected":true,"progress":0.9099999999999965,"message":"downloadNewDataFromServer","syncMessage":"syncingData","startSync":false,"backgroundSyncInProgress":false,"startTime":1702984348257,"numberOfPagesProcessedForCurrentEntity":141,"totalNumberOfPagesForCurrentEntity":154}
12-19 17:06:01.227 10337 10396 D ReactNativeJS: [5:06:01:227] [SyncComponent::AC][Debug] Dispatching action: "SYNC.ON_ERROR"
12-19 17:06:01.283 10337 10396 D ReactNativeJS: [5:06:01:283] [SyncComponent::AC][Debug] Dispatched action completed: "SYNC.ON_ERROR" {"syncing":false,"isConnected":true,"progress":0.9099999999999965,"message":"downloadNewDataFromServer","syncMessage":"syncingData","startSync":false,"backgroundSyncInProgress":false,"startTime":1702984348257,"numberOfPagesProcessedForCurrentEntity":141,"totalNumberOfPagesForCurrentEntity":154}

**To Reproduce**
1. login with himeshr@jsscp user
2.  after login 
3. See error

**Expected behavior**
user should able to go the home page of app

**Screenshots**
<img width="325" alt="jsscp sync" src="https://github.com/avniproject/avni-client/assets/104890488/1799f3fc-7597-476d-b952-b1ac53f8cca6">

**Comment by mahalakshme** [comment]
@AchalaBelokar what does the logs say? will help to know if it is some implementation issue.

**Comment by mahalakshme** [comment]
@AchalaBelokar this is because the users catchment doesn't contain individual's location but has household's location. So not a valid bug. We have a card to prevent such scenario from happening. So closing this card.
