### ISSUE TITLE
Sync of audit information

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1238]
### Motivation:
- Sometimes users want to keep track of the individuals created by them alone(and not all individuals in the catchment) via report cards

### Acceptance criteria:
- Add a field called filledBy to encounter and program_encounter tables in client and server. Populate its value when encounterDateTime is populated. 
- Sync createdById and lastModifiedById info for all trannsactional entities
- In Registeration Details card instead of showing `Registeration Date: 27-Jul-2023` show as `Registered on 27-Jul-2023 by sample name` where sample@orgName will be taken from the created_by field - here name of the user
- In Enrolment Summary card, instead of showing `Enrolled on: 28-10-2023` show as `Enrolled on 28-Oct-2023 by sample name` - here name of user in createdBy field in enrolment table need to display
- In  encounter cards currently we show only the dates - instead of showing `16-Dec-2023` show as `16-Dec-2023 by sample name` - here name of the filledBy user need to display
- In the above when the logged in user has done the above changes, then instead of `by sample name` show as `by you`
- In other cases, the display name will be name column from users table not username column
- If the name field is unavailable because it is already synced data, then just the dates as before need to display

### Technical details:
- To achieve the above, sync the users UUID and name from server to mobile app
- From UserInfo table loggedin user can be identified.
- Feel free to change the technical details.

### Out of scope:
- Syncing of time audit fields - not needed since there are other datetime fields which can be used to meet the purpose
- We need not sync audit information for already synced data, In report cards based on definition of some model function we can differentiate the versions of the app, and accordingly decide to render the results of the report card.

**Comment by petmongrels** [comment]
Additional Commits:
- https://github.com/avniproject/avni-models/commit/e4c67b3f15ecbb2a309d6442a4998b778a2ff9fd
- https://github.com/avniproject/avni-models/commit/d6f5f2c77513fe3bc6159d94aad01babce1379a0
- https://github.com/avniproject/avni-client/commit/bdfb5c64ee734a2b1d03269b919792938b5bd287
- https://github.com/avniproject/avni-client/commit/a991b279ca643b394b8b1385cd7b687ba9b1795d

**Comment by petmongrels** [comment]
Tasks
- SQL to update last modified date time of all users

**Comment by mahalakshme** [comment]
@petmongrels adding a video/screenshots will help in showcases and for analyst to review.

**Comment by petmongrels** [comment]
Videos link - https://drive.google.com/drive/folders/1OmgewoglaGH5Xhw4CkGbCaaGawmnz7qN?usp=drive_link

Internal only. do not share outside, may contain beneficiary info.

**Comment by AchalaBelokar** [comment]
- [ ] I login with AchalaB@rwbniti on staging and reg machin with TT 09 GH 8979 and filled a encounter with Excavating Machine Endline .. registration  is showing by: you and encounter is not showing
- [ ] same for well
