### ISSUE TITLE
Autocalculated value not getting filled

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1239]
**Describe the _bug**_
Not able to calculate the Nutritional status on skhai app 
In child enrolment their is Nutrition  status which is auto calculated  currently  it is not showing 
need to login with Ach@sakhiapp

**To Reproduce**
1. Go to fill the child enrolment form
 

### Screenshots and logs:

<img width="439" alt="Screenshot 2023-12-20 at 11 15 19 AM" src="https://github.com/avniproject/avni-client/assets/10369963/88d2b69e-51ca-4e1b-aace-72cd830d49bd">

Though in logs we see the rule is getting executed, the autocalculated status not getting filled in the above. This issue doesn't exist in prod and Nutritional status gets updated. On a preliminary check, rules in both envs seemed to be the same.

<img width="1512" alt="Screenshot 2023-12-20 at 11 15 30 AM" src="https://github.com/avniproject/avni-client/assets/10369963/d94962f9-a9cf-4991-acb5-05590d9f44d2">

**Comment by AchalaBelokar** [comment]
- [ ]  Login with dinesh@adsr there is encounter Annual visit baseline Which contain medical details there is auto calculated  value BMI it is not generated .

![Image](https://github.com/avniproject/avni-client/assets/104890488/9c1ab444-7944-4b90-81c7-0a5b773673d5)

**Comment by 1t5j0y** [comment]
Introduced in #1037. 

Fix - Allowed nil observations to be updated by form element status rules as this is the common use case of using these rules.

This has the side effect that any editable form elements which have form element statuses cannot be edited to completely remove the value. Fixing this side effect might require significant refactoring of the original story.

Side effect behaviour:
https://github.com/avniproject/avni-client/assets/54208632/401c3f0a-e95c-4499-9913-6f66694087c6

**Comment by petmongrels** [comment]
@AchalaBelokar this needs thorough testing of the form wizard. pls take help from Dinesh also.
