### ISSUE TITLE
Error when syncing - looks like UUID issue

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1240]
https://avni.freshdesk.com/a/tickets/3334

Though on the day when the ticket was created user is on a version where the  UUID issue is fixed, possible that when the user faced the issue, could ve been on a older version. Or not sure if the UUID issue is still continuing.

How come all ASHAs are facing the issue? May be they share the same fast sync db?

Tasks
- reproduce sync behaviour
- drop uuid column on rule failure telemetry

**Comment by petmongrels** [comment]
### Observation
- If rule failure telemetry fails then sync telemetry stays in the entity queue on the client. hence we cannot infer sync behavior what is happening just based on server data.
