### ISSUE TITLE
Storing datetime for time concept

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1242]
https://avni.freshdesk.com/a/tickets/3342 - Preliminary analysis in the ticket

Looks like when users use 4.0.3 version, time concepts are stored with datetime causing ETL to fail
```
select * from encounter where created_by_id in (7146, 5389, 6703);
```

In the above result, looked like when the above users used 4.0.3 lfe version the above issue has occurred and when used 4.0.5 version the issue has not occurred. 

Confirm the same by checking in the app. If the above is not the case need to find root cause since recent encounters saved(for users using 4.0.3 version) also has this issue and reply accordingly in the ticket.

**Comment by petmongrels** [comment]
Cannot reproduce the issue on 4.0 branch

**Comment by mahalakshme** [comment]
@petmongrels can you check with lfe 4.0.3 version specifically, bcoz found couple of entries created with lfe 4.0.5 version had time concept saved as time.

And our 4.0 branch I think might not indicate lfe 4.0 version. Need to check that.

**Comment by petmongrels** [comment]
there is no tag for 4.0.3 and no apk to test with local

**Comment by petmongrels** [comment]
### Data extract and fix SQL
https://github.com/avniproject/data-fixes/blob/00df0fd7cb100f1be4340dc0ae23f062cd5cb6a0/lfe/dateTimeStoredInsteadOfTime.sql

### Data to be corrected
https://drive.google.com/drive/u/4/folders/1quW06xqIoCvy-rNMLE_ZvBqEEatUuts0

**Comment by mahalakshme** [comment]
@petmongrels  I am concerned that even if we run the data fix the issue will continue, since even 2 days back for encounter with id, 152375 this issue has occurred. Can you also please try to reproduce the issue with 4.0.3 prod apk and test with some UAT prod org? Let me know if you think otherwise.

**Comment by mahalakshme** [comment]
@petmongrels we can run the datafix for this. The client has come back and asked for update. I think since its on prod better to pair with someone when running the fix. @sachsk already has context for this.
