### ISSUE TITLE
Logic verification for computing weight for height

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1247]
### Background:
[anthro R package](https://github.com/WorldHealthOrganization/anthro/tree/96e8fe016f4e2ed79eb187f08278b336bafbb7b5) is mentioned as part of WHO [software tools](https://www.who.int/tools/child-growth-standards/software) used to determine child growth standards.

Unlike  computation for weight for age [here](https://github.com/WorldHealthOrganization/anthro/blob/96e8fe016f4e2ed79eb187f08278b336bafbb7b5/R/z-score-weight-for-age.R#L13), weight for length computation has some additional logic to determine L,M and S values  [here](https://github.com/WorldHealthOrganization/anthro/blob/96e8fe016f4e2ed79eb187f08278b336bafbb7b5/R/z-score-weight-for-lenhei.R#L17)

### Acceptance criteria:
- Determine if our logic to compute weight for height in avni-health-modules is inline with the code in anthro package.
- Determine the impact of missing out the additional logic from avni-health-modules codebase and if it needs to be added.

### Additional info:
Weight for height(WFH) and weight for length(WFL) both are same, WFL being used for children of lesser ages since they cant stand and WFH for children of greater ages.

**Comment by petmongrels** [comment]
`individual.dateOfBirth = moment(today).subtract(30, 'months').toDate();`
  `individual.gender = male;`
  `assert.equal(zScore(individual, today, 20, 100).wfh, 3.22); // 3.0`
`assert.equal(zScore(individual, today, 10.5, 68.5).wfh, 3.04); // 2.5`
  `assert.equal(zScore(individual, today, 12, 77.5).wfh, 2.13); // looks ok`
 `assert.equal(zScore(individual, today, 8, 75).wfh, -2.14); // looks ok`
  `assert.equal(zScore(individual, today, 12, 100).wfh, -2.98); // looks ok`

- the numbers are not ok on the higher end of zScore and age > 24 months.
- less than 24 months seems correct
- compared these on the WHO charts

perhaps using their table which is different by age, make fix this.

### the difference is meaningful in the output vs actual as per standard

## Tables
https://www.who.int/tools/child-growth-standards/standards/weight-for-length-height

## PDF with charts
https://iris.who.int/bitstream/handle/10665/43601/9789241595070_C_eng.pdf?isAllowed=y&sequence=3

**Comment by mahalakshme** [comment]
Found that we need not worry about the additional logic since it is applicable(diff_lenhei > 0) only when input height is with 2 decimal places. Since in our case it is always with single decimal place - diff_lenhei will be 0 and the additional logic will not be applicable.

@petmongrels
