### ISSUE TITLE
Issue with visit scheduling when reentering lost data

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1253]
https://avni.freshdesk.com/a/tickets/3348

#### Approach 1:
- Update old visit schedule rules to not create planned encounters if planned encounter already exists with the same name and encounter to be scheduled is backdated.
- handle for all programs - child, pregnancy, eligible couple, etc., and if general encounters if any.
- Example test cases: 
-- When editing a old delivery encounter, for which PNC1 already scheduled, PNC1 should not get again scheduled
-- At the same time, encounter forms like 'Monthly needs assessment' and 'ANC VHND Follow up' gets scheduled with the same name repeatedly. Future scheduling for these should not get affected.
- Need to test with CK and IHMP

#### Approach 2:
If in none of the visit schedule rules of CK and IHMP, we are modifying the scheduling of the visits based on data collected, then we can just disable scheduling of visits on edit flow(can be determined from encounter_date_time) for CK and IHMP. 
Old rules for CK and IHMP can be found in their respective repos.
Caution: There are some old rules in avni-health-modules also.

### Reference:
Data to be collected again can be found in this folder under the respective org folder:
https://drive.google.com/drive/u/0/folders/1gsrLmsvpZ6gbqxHEQb8zYRwUuQ0ALrWh

**Comment by mahalakshme** [comment]
@petmongrels [this](https://drive.google.com/drive/u/0/folders/1KxdKDGtnyyKpm6eKOIEUa5YtHeuMfbN3) was the data for which they need to recollect the data right?

**Comment by petmongrels** [comment]
yes.......for IHMP that is the folder

**Comment by petmongrels** [comment]
### Testing
- JSS, IHMP, Any other impl which has scheduled visits
- choose visit types that schedule visit types
- try with new visit and editing existing old visit

Wrong visits should be scheduled. Please verify after saving as well.

**Comment by mahalakshme** [comment]
@AchalaBelokar I think this should go as patch release since it for a urgent ticket where we have already delayed a lot and mistake on our side and I think we might not be able to release 6.1.0 by tomorrow. @petmongrels If you also think the same, can you cherry-pick the commit to 6.0 branch

@vinayvenu @petmongrels But IHMP's 170 users need to upgrade their app, to use this fix. Cant think of a way out.

**Comment by mahalakshme** [comment]
@petmongrels where are we calling this method: `everScheduledEncountersOfType` in IHMP and CK rules? cant find in client codebase

**Comment by petmongrels** [comment]
it is not called by rules but the RuleEvalService. the change is in the platform

**Comment by mahalakshme** [comment]
@petmongrels yeah I checked in 6.0 branch, didn't know it was pushed into a patch version branch. The commit was marked with a different card number.

1. was unable to find the function `everScheduledEncounters` used in models
2. to `everScheduledEncountersOfType` we are passing encounterType but we are consuming it considering it as name.
3. we didn't handle for general encounters - found 2 general encounters SES Survey and Census in the orgs of interest - not sure if they have visit schedule rules - I think we can handle it as well for consistency if you also think the same.

**Comment by mahalakshme** [comment]
making a different comment to notify:
@petmongrels have added a comment [here](https://github.com/avniproject/avni-client/issues/1257#issuecomment-1870803878) regarding release of this card.

**Comment by petmongrels** [comment]
i. fixed
ii. rules return encounter type as string
iii. these have been left out as the numbers are few

included for program enrolment and program encounter cancel

**Comment by mahalakshme** [comment]
@AchalaBelokar test in 6.0.1 branch

**Comment by AchalaBelokar** [comment]
Found 
- [ ] @petmongrels Login with taqi@ihmp Created a individual  with name Gjj Fh after that I enrolled Eligible  couple then visit is scheduled monthly  needs assessment  then I cancel the that visit then it is asking me next visit  but after filling that date visit  is not schedule.   

- [x] login with hr@calutta_kids  Their is individual  fgfg fgfg  fill the birth encounter their 3 questions are coming 2 times .. 

![Image](https://github.com/avniproject/avni-client/assets/104890488/980a9909-1fe9-4b22-8ae5-f436148fb14c)



![Image](https://github.com/avniproject/avni-client/assets/104890488/7bd74916-f20a-4e56-9415-76f23a84694f)



![Image](https://github.com/avniproject/avni-client/assets/104890488/38dff5cd-1906-4985-9216-3883ddf96c47)

last screen shot is on production

**Comment by himeshr** [comment]
@AchalaBelokar Fix for 
`Login with hr@calutta_kids Their is individual fgfg fgfg fill the birth encounter their 3 questions are coming 2 times .` issue mentioned above is done as part of card https://github.com/avniproject/avni-server/issues/675

**Comment by AchalaBelokar** [comment]
- [ ] If I edit the cancelled visit then back dated visit is schedule  Login with maha@calcutta_kids 
[az_recorder_20240405_091454.mp4.zip](https://github.com/avniproject/avni-client/files/14879629/az_recorder_20240405_091454.mp4.zip)
