### ISSUE TITLE
List style report cards

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1256]
### Motivation:
- Frequently there are cases where across report cards very similar logic is used and only a value used for comparison, changes. Eg: in one of our partner organisations, we load 'Total SAM children' and 'Total MAM children'. For rendering each takes around 20-30s. And hence the dashboard nos doesn't load until both the report card results are calculated and it makes the user to wait for a minute. If the logic is combined, we can render the results in 30s since it would need only retrieval from db and iterating once.
- The above kind of scenarios also lead to code duplication across report cards and when some requirement changes - say for the above SAM and MAM children less than 5 years then the change needs to be done in both.

### Acceptance criteria:
- Modify the return structure to be able to render multiple report cards on UI from single ReportCard rule definition as mentioned in the `Technical details`
- The card name and the colour (Text and card background) defined in report card rule will override whatever defined/selected via webapp UI
- Should be backward compatible - should work with old return object structure as well
- The colour we define in the UI is used as background color in Tile view and background colour of Text in List View(right side box). Let it remain/work the same.
- The value of colour should accept hexcode values and colors that can be defined in css styling.
- Documentation has to be updated related to custom dashboard Report-cards
- When the Number in the nested report card and the number of cards in the return structure dont match show the error `Configured number of cards don't match with the number of cards in the rule` on the cards rendered by the nested report card(independent of whether the configured number is greater than or less than the no of cards in the rule)
- Show an appropriate default rule

### Technical details:
Current structure:
```
{
        primaryValue: undernourishedCount,
        secondaryValue: `${percentValue}%`,
        lineListFunction: undernourishedIndividuals,
    };
```
Structure to be:
```
{
  reportCards: [
  {
        primaryValue: undernourishedCount,
        secondaryValue: `${percentValue}%`,
        lineListFunction: undernourishedIndividuals,
        cardName: 'name value',
        cardColor: '#hexone',
        textColor: '#hextwo',
    },
....
 ]
}
```

**Comment by himeshr** [comment]
## Related screenshots
-------

### Count Mismatch on client
<img width="589" alt="Count Mismatch on client" src="https://github.com/avniproject/avni-client/assets/72493481/f2913cfa-8211-4d28-b071-b6b79dcb4ff2">

-------

### Nested Report cards on client
<img width="589" alt="Nested Report cards on client" src="https://github.com/avniproject/avni-client/assets/72493481/175a6dfe-e6a4-4c1e-8d2f-454574239b2a">

-------

### Edit Report card on webapp
<img width="1334" alt="Edit Report card on webapp" src="https://github.com/avniproject/avni-client/assets/72493481/3f6f7b1a-b950-4d4c-96a8-dac0f7b2ad45">

-------

**Comment by himeshr** [comment]
Related documentation has also been added [here](https://avni.readme.io/docs/offline-reports#nested-report-cards)

**Comment by petmongrels** [comment]
- CustomDashboardActions.js L:123 - instead of _.map, we should use _.forEach as there is no return value (same for L:131)
- Translation will be required for secondaryValue in different places
- not able to understand the meaning of finding # in a UUID

**Comment by himeshr** [comment]
Added platform translations, sample of which is available below.
<img width="589" alt="Screenshot 2024-01-31 at 2 03 58 PM" src="https://github.com/avniproject/avni-client/assets/72493481/1a9c2e57-6ab0-4b44-95cf-c25d408b89d8">
