### ISSUE TITLE
getTime of undefined - error

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1257]
https://avni.freshdesk.com/a/tickets/3351 - context in the ticket. Check the rule failure telemetry of ihmp in prerelease. Looks like program Summary rule result is not getting displayed as a result of this issue.

**Comment by mahalakshme** [comment]
@petmongrels found the fix for this in 6.0.2 branch. from the fix looks like the corresponding actual card: https://github.com/avniproject/avni-health-modules/issues/2 was not tested during the 6.0 release. So I think its better to have the fix in 6.1.0 branch.

anyways for the visit scheduling patch release we can release 6.0.1 branch since that that has the fix

**Comment by mahalakshme** [comment]
@petmongrels looks like this fix needs to be cherrypicked to 6.1.0 branch

**Comment by petmongrels** [comment]
its done because it is only a version change only

**Comment by mahalakshme** [comment]
As part of this card this story need to be tested: https://github.com/avniproject/avni-health-modules/issues/2
