### ISSUE TITLE
Create new flavor for the new env org

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1267]
### WHY:
New flavor for the org in focus is needed since its server url is going to be different.

### Acceptance criteria:
Follow steps [here](https://avni.readme.io/docs/flavouring-avni#steps) to create new flavor for the org in focus with details mentioned [here](https://docs.google.com/spreadsheets/d/1yZwVWX-fbBNalwwSW_h9t53iAW09F73L-fhcIGGIVeQ/edit#gid=0)
-- the scope includes creating new flavor, and getting the app approved from playstore after uploading the apk

**Comment by vinayvenu** [comment]
@mahalakshme https://docs.google.com/spreadsheets/d/1yZwVWX-fbBNalwwSW_h9t53iAW09F73L-fhcIGGIVeQ/edit?usp=sharing

**Comment by 1t5j0y** [comment]
Added generation of staging apk into scope.

**Comment by AchalaBelokar** [comment]
- [ ] I upload the bundle  from prerelease  ... and try to reg the farmer but the the reg from having the 
firstname it should be First Name also for date of birth also see the sub summary 


![Image](https://github.com/avniproject/avni-client/assets/104890488/fe2f54c4-4c9a-48a2-a96b-49add53d25d0)



![Image](https://github.com/avniproject/avni-client/assets/104890488/a54611d8-19f3-4fa1-b357-2d5cdc97d80b)

**Comment by petmongrels** [comment]
@AchalaBelokar what is the user. also use the prod org only user

**Comment by mahalakshme** [comment]
live_dev of gramin not authenticating with the right cognito during login - downloaded the apk from here: https://app.circleci.com/pipelines/github/avniproject/avni-client/2289/workflows/bbe869df-6da4-49c2-8a06-9024c19ca923/jobs/14199/artifacts

Looks like store_artifacts in circle-ci config not handled for live_dev flavor
