### ISSUE TITLE
When user rejects reset sync, do not further continue

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#1269]
### Need:
- Making sure all necessary cases handled
- We have got cases where individual's address level has not synced. One rootcause could be this.

### Context:
- The [ability to ignore reset ](https://app.zenhub.com/workspaces/avni-product-deprecated-635b73bded85e50018871ae6/issues/gh/avniproject/avni-server/369)was added when users are in a place without good internet connection.
- Currently we are continuing to sync with the changed users catchment without syncing from beginning when user ignores reset sync. This will lead to association error issues and one mentioned below.

### Steps to reproduce:
- synced with maha@rwb24uat with test_maha catchment
- Changed the catchment to test_maha_new catchment
- Ignored to reset
- Got the error 'lowestAddressLevel Mandatory for Individual...' error. 

### Acceptance criteria:
- When the user presses 'No' dont proceed with further sync of pulling data.

### Clarifications:
- Data push should continue to happen before checking for reset sync like done currently.
- No need to change the user confirmation message since as of now no one has reported any confusion.

### Testing QA notes:
- Test for all cases mentioned [here](https://avni.readme.io/docs/internal-details-of-avni-sync#reset-of-sync)

**Comment by mahalakshme** [comment]
@petmongrels why do we need mechanism to turn off reset sync for any user - U ve mentioned this: 'we have no mechanism to turn of reset sync for any user'. There would be issues if turnedoff no? - moved the line to this card: https://github.com/avniproject/avni-client/issues/1339

**Comment by petmongrels** [comment]
The confusing part is - why is the option given to user to choose to ignore reset sync?

**Comment by mahalakshme** [comment]
@petmongrels yeah it should not have been given, so ve prioritised this - this card: https://app.zenhub.com/workspaces/avni-product-deprecated-635b73bded85e50018871ae6/issues/gh/avniproject/avni-server/369 - says its because some users could ve poor internet connection.

**Comment by 1t5j0y** [comment]
@AchalaBelokar the locations added / removed from a catchment need to have some subjects registered for reset sync record to get created for the user in that catchment.
