### ISSUE TITLE
Subject type filtered with not retained after sync

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1272]
Related ticket: https://avni.freshdesk.com/a/tickets/3369

### Issue:
- The subject type selected in dashboard filter is not retained after sync as shown in [this](https://avni.attachments2.freshdesk.com/data/helpdesk/attachments/production/36181304798/original/WhatsApp%20Video%202024-01-06%20at%205.21.19%20PM.mp4?response-content-type=video%2Fmp4&Expires=1704869836&Signature=HhbKuU0E8pxRoVsCJxlnYwlTGYuT3sh~3qD~Q6aQYJUnYDQQqc2B79xVxyO2slh4lA7I86BCRinMiVcX7J52p79b4fY4d5Ww~nY7nEaRoeKaz5t1mPtH5HERWLB4sMOj7sP7Ssr0kWGVF2Idh8zRfRhwVe7DBiu7oJYkPxKz7vOTKC6gDq6er5vspMbjcfXAuFpS5MB79zUwv3iNfGf28AW4S61Jtxr19C43BDYgFDR8iUbml2xjsGcD3RzlgpcUIggoyBWFvHHUDppR3TeTiVEv9t-50er-J19McsCDac-g8I7QsfuRKMTPQ1Sv6~CP2KKPX4-72MUibR0QJPlpzw__&Key-Pair-Id=APKAJ7JARUX3F6RQIXLA) video.
- So, fix made for [this](https://app.zenhub.com/workspaces/avni-product-deprecated-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/969) card, seems to be broken - may be when applying filters for standard report cards.
- The subject type retains after sync in apk with build version, 4.01.0-a212 apk. 
- You can use env: prod, login details: maha@jsscp to check the above issue.

### Acceptance criteria:
- Filtered subject type need to retain after sync
- Technically try to implement it such that we use the same approach for dashboard filters saving so that behaviour for both filters are the same and doesn't cause confusion. Looks like for subject type saving we have used `AsyncStorage` and for other filters we have used, `DashboardCache` realm table

**Comment by himeshr** [comment]
During testing for Embedded objects card, found an error with launching latest version (master branch) apk, in following scenario.

Env: Staging
User: vin@jsscp

1. Using 6.1 apk login and sync completely. Setup fast-sync.
2.   
     A. Either upgrade the apk directly without unistalling or clearing user data to master version
App then errors out after launch with below error stacktrace:
https://github.com/avniproject/avni-client/assets/72493481/8fc29106-7694-4e42-8e2c-7fbd261655d9


B. Or unistall 6.1 APK and install master apk and login as the same user, with fast-sync
App errors out with improper restore of userInfo, on relaunch app works but user info is lost. My Dashobard Register button is no longer shown and the Dashboard Search fields are also missing.

**Comment by himeshr** [comment]
> During testing for Embedded objects card, found an error with launching latest version (master branch) apk, in following scenario.
> 
> Env: Staging User: vin@jsscp
> 
> 1. Using 6.1 apk login and sync completely. Setup fast-sync.
> 2. A. Either upgrade the apk directly without unistalling or clearing user data to master version
>    App then errors out after launch with below error stacktrace:
>    https://github.com/avniproject/avni-client/assets/72493481/8fc29106-7694-4e42-8e2c-7fbd261655d9
> 
> B. Or unistall 6.1 APK and install master apk and login as the same user, with fast-sync App errors out with improper restore of userInfo, on relaunch app works but user info is lost

I'm currently unable to repoduce the issue with fresh package_manager running and same code base.
The errors encountered could be just due to build packager state issue and not actual bugs.
