### ISSUE TITLE
Entity sync status is not getting updated 

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1276]
When we sync the subject or encounter which hold the media file (image) the sync status show for media in queue eventhough we have synced the data.
Media data is getting updated in the DEA even the sync status shows in queue

env: pre-release
org : akrspuat
user: dinesh@akrspuat

Steps to reproduce
1.login to app
2.register the ward 
3.sync the data and check the entity sync status
4.complete the encounter Jal chaupal with the uploading the image
5.sync the data and check the entity sync status

Excepeted : sync should be completed and queue should be zero
Actual : Sync is completed but queue shows values.

https://github.com/avniproject/avni-client/assets/127730126/2527e2a3-12ca-4099-8330-7427c50e36fb

if the video is not clear check the below drive link

https://drive.google.com/drive/folders/1wRPwjR_hTDWtMDQB4JdsQe4FoFtLAR26

**Comment by mahalakshme** [comment]
@Dinesh2019 found issue is not happening in 6.0

**Comment by himeshr** [comment]
This was a minor regression caused due to code change done for avniproject/avni-server#678.

**Comment by himeshr** [comment]
Simple 1 line code reintroduced.. no code-review required.
The line was removed, assuming it was to pop the item that was being pushed during observations update after media items sync, but that wasn't the case. The pop was for the initial mediaQueueItem inserted when entity media was saved on device, before it being synced to the server.
As part of old saveOrUpdate / register methods, we weren't pushing any new item, therefore the removal of PopItem was wrong, and we ended up with stale mediaQueueItem in the queue.
