### ISSUE TITLE
Slow response when clicking on call task

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1280]
https://avni.freshdesk.com/a/tickets/3432

### Need:
- After clicking on call button, to complete the request for masked call(for the bottom toast to appear) it takes around 20-45 secs(try in actual phone). Since this needs to be done repeatedly in a day, the users are unable to complete their target number of call tasks. 

### Info:
- Issue exists in past few versions as well and users have been facing inconvenience in the past as well as the latest version(6.0.0).
- Though not same, there has been a [app breaking issue](https://github.com/avniproject/avni-client/issues/1070) in the same page that we have fixed before.

### AC:
- try to optimise(reduce the time taken) this(time between clicking of call task and showing the toast message after successfully placed request for masked call) as much as possible.

**Comment by AchalaBelokar** [comment]
https://github.com/avniproject/avni-client/assets/104890488/7ef13c92-668b-46fc-a937-de6a8190fb10

it is working fine

**Comment by mahalakshme** [comment]
@AchalaBelokar how much time on average it takes now?
