### ISSUE TITLE
User unable to sync - Sync Timeout issue

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1281]
https://avni.freshdesk.com/a/tickets/3431 - looks like issue with media upload getting timeout
Also check in bugsnag to understand the frequency of the issue.

### Context:
Already tried fixing [here](https://github.com/avniproject/avni-client/issues/1196)

**Comment by petmongrels** [comment]
waiting for mobile db backup and response to questions on the ticket

**Comment by mahalakshme** [comment]
closing the card since no response in the ticket and found the sync issue resolved for the user.
