### ISSUE TITLE
Autoselect bottom locations in location filter

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1283]
### Need:
As shown in the [video](https://github.com/avniproject/avni-client/assets/10369963/14550311-4bc3-48b9-8d52-c0061c82a7e6), as part of UX, the expectation would be that on selecting a location, say State, all districts below it will be selected. And on unselecting a state, all districts below it will get unselected. Unselection currently is working for one level, but not selection. This is an issue because of below 2 reasons:
- In one of the org, a user is assigned a district. District contains many blocks and each block contains around 25 villages. When needed to filter at block level, making user to select all 25 villages will be time consuming.
- UX reasons with respect to what user would probably expect.

### Acceptance criteria:
- Make the custom dashboard filters work similar to location filters in search. Refer the video below to understand the same:
https://github.com/avniproject/avni-client/assets/10369963/7e49086d-0d84-44dd-9774-ab16a1d68874
-- Things to be noted in the above video: 
Consider the below hierarchy:
![Image](https://github.com/avniproject/avni-client/assets/10369963/a5b3add2-89ea-4cf0-87ac-a8fc3e2bb6e0)

-- 1. when a higher level location is selected say, a, automatically assume all the bottom locations(b,c,d,e,f,g) in the filter are selected though no need to show the selection in UI
-- 2. But when a particular location is selected(a and b) at a hierarchy level in the bottom, then only that location in that level is considered to be selected (a, b, d, e)
-- 3. Also when b is unselected, then all of b,c,d,e,f, and g needs to be considered selected.

- Should work like above for filtering on standard report cards as well as custom report cards. For custom cards - pass all the locations considered to be selected as part of params.ruleInput. Apply this change for the org in focus for the custom report cards of Approval dashboard to verify the same.
- Also should work as above when locations are selected via search.
<img width="437" alt="Screenshot 2024-02-15 at 11 21 00 AM" src="https://github.com/avniproject/avni-client/assets/10369963/21991e84-6589-4162-bb4b-cd87c7bbd3ef">

- Note the release no. Make the change in the needed branch accordingly.
- Remove the message that says "Choose exact level at which subject is registered"

**Comment by mahalakshme** [comment]
will resume after getting feedback from client in focus to see if we can wait until UI/UX person joins.

**Comment by himeshr** [comment]
@mahalakshme the message is changed as follows, will this do.? 
```
    "addressFilterBehaviorHint": "(Choose exact level at which subject is registered)"
    "addressFilterBehaviorHint": "(Selection includes lower levels implicitly)"
```

**Comment by mahalakshme** [comment]
@himeshr 
- A better one could be - '(Selection includes lower address levels implicitly)' - and it needs to be in both Search filters and custom dashboard filters.
- The scope of the card was to fix for custom dashboard. Let me know if its handled for MyDashboard as well - so that I need not create card for it.

**Comment by himeshr** [comment]
> * A better one could be - '(Selection includes lower address levels implicitly)' - and it needs to be in both Search filters and custom dashboard filters.

1. The Helper text is only changed for Custom Dashboard filters, as understood from focus area in initial Acceptance criteria.
2. This is not done for MyDashboard, would need a separate card for that.

**Comment by mahalakshme** [comment]
@himeshr But my concern now is, it is inconsistent. The AC was to remove the message, since the working is same as in Search Filters and users are used to its working now. If we are adding message we need to add in both places.

**Comment by 1t5j0y** [comment]
@mahalakshme MyDashboard already behaves the expected way.

**Comment by mahalakshme** [comment]
@1t5j0y can you please make the messaging consistent in both places - we can add the message in Search filters as well or remove it here.

**Comment by mahalakshme** [comment]
@Dinesh2019 separated custom report cards testing to different story. You can pair with whoever tests it, to be able to test such cards in future.

**Comment by 1t5j0y** [comment]
Added message to search and older filters view.

**Comment by Dinesh2019** [comment]
@1t5j0y available for dev box
