### ISSUE TITLE
Fatal error during cloning state continues 

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1287]
### Context:
We already tried to address this issue in 6.0 release as part of [this](https://github.com/avniproject/avni-client/issues/1193) card.

### Analysis:
- ```setLocation``` in the stacktrace in [this](https://avni.freshdesk.com/a/tickets/3444) ticket has ```state.clone()``` which could be the probable issue
- Found the below stack traces from [bugsnag](https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/658bb2e9ae737b00074e280a?filters[error.status]=for_review&filters[event.since]=7d&filters[app.release_stage]=prod) in 6.1.0 version
```
TypeError Fatal error: undefined is not a function 
    /home/circleci/avni-client/packages/openchs-android/src/action/common/ObservationsHolderActions.js:113:36 toggleSingleSelectAnswer
    /home/circleci/avni-client/packages/openchs-android/src/reducer/Reducer.js:22:30 anonymous
    /home/circleci/avni-client/packages/openchs-android/node_modules/redux/lib/redux.js:566:33 combination
    /home/circleci/avni-client/packages/openchs-android/node_modules/redux/lib/redux.js:296:21 dispatch
    /home/circleci/avni-client/packages/openchs-android/src/framework/view/AbstractComponent.js:56:63 dispatchAction
    /home/circleci/avni-client/packages/openchs-android/src/views/form/formElement/SelectFormElement.js:27:51 toggleFormElementAnswerSelection
    /home/circleci/avni-client/packages/openchs-android/src/views/form/formElement/SelectFormElement.js:54:77 onPress
    /home/circleci/avni-client/packages/openchs-android/src/views/primitives/SelectableItemGroup.js:43:26 onItemPressed
    /home/circleci/avni-client/packages/openchs-android/src/views/primitives/SelectableItemGroup.js:66:101 onPressed
    /home/circleci/avni-client/packages/openchs-android/src/views/primitives/SelectableItem.js:78:40 onPress
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Components/Touchable/TouchableHighlight.js:208:28 onPress
```
- Found the below stack traces from [bugsnag](https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/6556f860808fb00008cfa142?filters[error.status]=for_review&filters[event.since]=7d&filters[app.release_stage]=prod) in 6.1.0 version
```
TypeError Fatal error: undefined is not a function 
    /home/circleci/avni-client/packages/openchs-android/src/action/program/ProgramEncounterActions.js:95:26 onNext
    /home/circleci/avni-client/packages/openchs-android/src/reducer/Reducer.js:22:30 anonymous
    /home/circleci/avni-client/packages/openchs-android/node_modules/redux/lib/redux.js:566:33 combination
    /home/circleci/avni-client/packages/openchs-android/node_modules/redux/lib/redux.js:296:21 dispatch
    /home/circleci/avni-client/packages/openchs-android/src/framework/view/AbstractComponent.js:56:63 dispatchAction
    /home/circleci/avni-client/packages/openchs-android/src/views/program/ProgramEncounterView.js:136:60 next
    /home/circleci/avni-client/packages/openchs-android/src/views/program/ProgramEncounterView.js:237:53 func
    /home/circleci/avni-client/packages/openchs-android/src/views/common/WizardButtons.js:66:58 onPress
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Pressability/Pressability.js:764:17 _performTransitionSideEffects
```
- Also found in ```SubjectRegisterActions.js``` in 6.0.4 version in bugsnag

**Comment by himeshr** [comment]
## Analysis
On analysis, found that, during init of Reducers, we invoke actionClass.getInitialState(beanStore) when initializing corresponding state for the ActionClass.

In the actionClasses where the above "TypeError Fatal error: undefined is not a function " exception is encountered while invoking ```state.clone()```, the getInitialState() method is initialized using an Empty Json object({}) which does not provide a clone() method, which is most likely the cause for this issue.

As a fix, modifying the  actionClass that have state.clone() function mentioned in them to have a  getInitialState() method that uses State object Constructor invocation to initialize the state.

Example:
```
export class SubjectRegisterActions {
    static getInitialState(context) {
        return new SubjectRegistrationState();
    }
...
}
```

### Additional info
The actionClasses where the above "TypeError Fatal error: undefined is not a function " exception have been encountered as per this card are as follows:
SubjectRegisterActions, PersonRegisterActions, ObservationsHolderActions , ProgramEncounterActions.

**Comment by himeshr** [comment]
## Avni client Test case scenarios:
Perform **sanity testing** for following functionalities
- Subject registration
- Encounter
- Program Encounter
- Program Enrolment
- Checklists
- Timed Encounter pages
- SubjectProgramEligibility

**Comment by AchalaBelokar** [comment]
- [ ] Login with mohot@power

 Error Code : Association error 06
Message : Encounter{uuid='c84c3758-ed0b-4625-a2b4-885c5462235f'} is unable to find Individual{uuid='7e1b1d87-29c6-45bc-b4b3-70ac4de5a9ad'}
at SyncError (address at index.android.bundle:1:750452)
at throwSyncError (address at index.android.bundle:1:749879)
at getParentEntity (address at index.android.bundle:1:749725)
at associateChild (address at index.android.bundle:1:943376)
at anonymous (address at index.android.bundle:1:1537056)
at map ((native)::)
at associateParent (address at index.android.bundle:1:1536915)
at persistAll (address at index.android.bundle:1:1537726)
at processResponse (address at index.android.bundle:1:1541469)
at anonymous (address at index.android.bundle:1:1541728)
at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
at apply ((native)::)
at anonymous (address at index.android.bundle:1:248507)
at _callTimer (address at index.android.bundle:1:247501)
at _callReactNativeMicrotasksPass (address at index.android.bundle:1:247666)
at callReactNativeMicrotasks (address at index.android.bundle:1:249588)
at __callReactNativeMicrotasks (address at index.android.bundle:1:99687)
at anonymous (address at index.android.bundle:1:98826)
at __guard (address at index.android.bundle:1:99564)
at flushedQueue (address at index.android.bundle:1:98737)
at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:98680)


- [ ] Login with maha@power and created on individual and after that  try sync it it is showing me sync time out error

**Comment by himeshr** [comment]
> * [ ]  Login with mohot@power
> 
> Error Code : Association error 06 Message : Encounter{uuid='c84c3758-ed0b-4625-a2b4-885c5462235f'} is unable to find Individual{uuid='7e1b1d87-29c6-45bc-b4b3-70ac4de5a9ad'} at SyncError (address at index.android.bundle:1:750452) at throwSyncError (address at index.android.bundle:1:749879) at getParentEntity (address at index.android.bundle:1:749725) at associateChild (address at index.android.bundle:1:943376) at anonymous (address at index.android.bundle:1:1537056) at map ((native)::) at associateParent (address at index.android.bundle:1:1536915) at persistAll (address at index.android.bundle:1:1537726) at processResponse (address at index.android.bundle:1:1541469) at anonymous (address at index.android.bundle:1:1541728) at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16) at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27) at apply ((native)::) at anonymous (address at index.android.bundle:1:248507) at _callTimer (address at index.android.bundle:1:247501) at _callReactNativeMicrotasksPass (address at index.android.bundle:1:247666) at callReactNativeMicrotasks (address at index.android.bundle:1:249588) at __callReactNativeMicrotasks (address at index.android.bundle:1:99687) at anonymous (address at index.android.bundle:1:98826) at __guard (address at index.android.bundle:1:99564) at flushedQueue (address at index.android.bundle:1:98737) at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:98680)
> 
> * [ ]  Login with maha@power and created on individual and after that  try sync it it is showing me sync time out error
> * [ ]

Hi Achala, i found that for user Mohit@power, fast-sync setup exists which was created a month ago.
Since we have recreated pre-release db a few times we might have lost entries that existed earlier or have extra entries.
Please delete the fast-sync and test again.
<img width="1840" alt="Screenshot 2024-04-08 at 10 47 59 AM" src="https://github.com/avniproject/avni-client/assets/72493481/e66e1a71-e442-4b82-afa8-92a5a9f6b27b">


Regarding the sync timeout error, would need more details to debug further. From the logs, it looks like you were able to complete sync and perform some activities.

**Comment by AchalaBelokar** [comment]
sync timeout error is occurring because of network issue on my side..

- [ ] tried with mohit@power I am facing the same issue..
- [x] Login with maha@power it is working fine ... check eligibility check, task assignment , calling registration , reschedule task all working fine
- [ ] Login with himeshr@jsscp  try to login with this  it is showing 
tried to delete the fast sync from s3 not able to delete 
update from schema version 185 is not allowed . please uninstall and install app .. tried with slow sync it is showing msg exception in the hostfunction: Cannot access realm that has closed.
- https://app.circleci.com/pipelines/github/avniproject/avni-server?branch=8.0 this is the server
- https://app.circleci.com/pipelines/github/avniproject/avni-client/2441/workflows/50aba8bd-3e22-4241-9447-18d63af805b1/jobs/15398 this is the apk

- [x] Login with taqim@sncu registration , edit registration ,child enrolment , edit enrolment

**Comment by himeshr** [comment]
Deleted the corrupt fast-sync files which were blocking testing for users mohit@power and himeshr@jsscp.
