### ISSUE TITLE
Additional subject types getting displayed

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1288]
https://avni.freshdesk.com/a/tickets/3457

### Issue:
- On logging in with the credentials mentioned in the ticket, and on clicking Register, unconfigured subject types show up.

### Analysis:
- Issue reproducible in 6.1.0 version.
![Image](https://github.com/avniproject/avni-client/assets/10369963/6857f069-5853-4002-a335-420492897afc)

- [This](https://github.com/avniproject/avni-server/issues/672) was the latest card played with respect to hierarchial orgs. But doesn't seem to do anything with this issue
- 'Eligible couple'(program in IHMP) and 'Child'(program in org with id 1) are program names not even subject types in parent orgs 
- On trying to register say pregnant woman, it takes to 'IHMP Registration form' associated with Individual subject type

### Acceptance criteria:
Show only the applicable subject types

**Comment by petmongrels** [comment]
not an issue. updated in ticket
