### ISSUE TITLE
Reset Sync flow broken after switch to Embedded dataType

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-client#1295]
**Describe the bug**
I do not have clear instructions to reproduce different issues encountered during reset-sync.
But as of now, i have captured errorLogs / stack-trace of 2 issues.

Issue 1: When resetSync is triggered, app throws error "Exception in HostFunction: You cannot query an embedded object."
Issue 2: When we change Catchment for user AchalaB@power, from "test" to "test new", then on sync, app throws error "lowestAddressLevel are mandatory for Individual, Keys being saved - ...."

User: AchalaB@power
Env: Prerelease
Apk: local run_app_pre-release dev on 7.0 branch

**Expected behavior**
Reset sync should work in various scenarios such as
1. Catchment change
2. SyncConcept value change for user
3. SyncConcept removal / addition for SubjectType

**Screenshots**
<img width="751" alt="Screenshot 2024-02-09 at 6 31 06 PM" src="https://github.com/avniproject/avni-client/assets/72493481/3a5b0a85-9b10-45fa-ab4e-afc2aa56c269">

**Logs**
[ResetSyncLogs2ndIssue.txt](https://github.com/avniproject/avni-client/files/14222233/ResetSyncLogs2ndIssue.txt)
[ResetSyncLogs.txt](https://github.com/avniproject/avni-client/files/14222234/ResetSyncLogs.txt)

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by himeshr** [comment]
Validated the test scenarios as part of dev-testing:
1. Catchment change
2. SyncConcept value change for user
3. SyncConcept removal / addition for SubjectType

Couldn't reproduce the 2nd issue mentioned here, fixed 1st one.

**Comment by Dinesh2019** [comment]
Still, we are facing this issue

Env: pre-release
org: rwb24uat
user: dinesh@rwb24uat
apk : https://app.circleci.com/pipelines/github/avniproject/avni-client/2316/workflows/4790a570-ab62-4209-9709-b8e01d61ccea/jobs/14418/artifacts

steps to reproduce:
1. Login to the org 
2. Wait still sync got completed
3. go to the web app
4. Under user update the catchment of the user
5. again come back to the app
6. click on the sync

Expected: sync should be completed
Actual: sync displays the error 

Reference video:

https://github.com/avniproject/avni-client/assets/127730126/6b0d6996-01d0-465b-b05d-be75cb131612

**Comment by himeshr** [comment]
@Dinesh2019 the apk used is from master branch, but it doesnot have the latest code changes done in 7.0 branch to fix Embedded entity related issues.

Use this apk for 7.0 release cards testing.
https://app.circleci.com/pipelines/github/avniproject/avni-client/2314/workflows/bf70df9e-92ae-4826-9215-9252a91a0214/jobs/14419/artifacts

**Comment by AchalaBelokar** [comment]
- [ ] I assigned a task to the achala but it is not reflected on task

![Image](https://github.com/avniproject/avni-client/assets/104890488/7bba386b-9a82-4ea8-bc7b-9020cbf257d0)
