### ISSUE TITLE
Not all crashes are getting notified in bugsnag

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1297]
### Issue:
Several times I reproduced [this](https://github.com/avniproject/avni-client/issues/1292) white screen issue, by clicking on 'Missed calls' when it is loading with mohit@power login id. But it didn't get notified even once. The [one bugsnag issue ](https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors?filters[event.since]=7d&filters[app.release_stage]=prod&filters[error.status]=for_review&filters[user.id]=mohit%40power)with mohit@power was already existing.

### Need:
There are certain issues raised from client, for which it is difficult to reproduce the issue. To fix such issues, we only know the userId who faced the issue. Hence need these crash logs to understand the issue.

### AC:
In testing one can only simulate network, server unreachable kind of situation which are already handled as regular scenario and they are not classified as error. Error is when there is a defect in the app. In QA one will not be able to introduce defects hence it cannot be tested directly as a story. The acceptance criteria here should be considered whenever error happens while testing something else.

- All crashes/error logs gets notified in bugsnag (may not be verifiable as QA)
- Never show white screen only on any error
- Provide option to copy errors in all error scenarios from the mobile app
- Provide appropriate actions like restart, close depending on the error

**Comment by 1t5j0y** [comment]
From the ticket description / comments and simulation
- we had a white screen (not caught by our error handler) which was reported to bugsnag (redux error #6). Simulated this.
- we had a fatal error (caught by our error handler) but not reported to bugsag. Was not able to simulate this.

Looking through the code, unsure why the above would occur. Additionally, tried introducing an error boundary (react-native-error-boundary) in Avni.js but that did not prevent the white screen issue.

Moving to hold till we decide next steps.

**Comment by 1t5j0y** [comment]
White error screen persists after putting try-catch around [`return GlobalContext.getInstance().routes` in App.js](https://github.com/avniproject/avni-client/blob/8ffcf870f194751367291a685abbab0bdccca91f/packages/openchs-android/src/App.js#L128)

**Comment by petmongrels** [comment]
### Broad scenarios
1. Server reporting error
2. Client code error during callback from server call
3. Client code error during render
4. Client code error during events, component mount etc
5. Client executing async code
6. Client executing setTimeout/setImmediate code

### Test above during
- Sync
- Startup
- Login
- Fast sync
- Rest of the app usage (doesn't involve server call)
- Native Code
- Scheduled Job

Tasks to remember
- translations for all the keys added
- native error handling
- bugsnag reporting in different scenario

**Comment by 1t5j0y** [comment]
1. importing Clipboard from react-native is deprecated. We are already using react-native-clipboard. Usages need to be updated.
2. Changes need to be in 7.1 branch.
3. ErrorDisplay.js only shows error if `!Config.allowServerURLConfig`. Can we not handle showing errors if this is the case also?
4. console.logs need to be replaced with General logDebug so prod apk (no logging) rules are respected.

**Comment by petmongrels** [comment]
1/2 - done
3. it has been introduced by TW and we don't use this config too much. it is meant for some dev env use case which I am not aware of.
4. the errors can take place before the app and logger is initialised, hence using console.log to ensure it is not missed in any case
