### ISSUE TITLE
Add ability to multiselect media in one go!

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1298]
### Need:
In usecases, where users are in need to add around 5 images, adding them each time by clicking 'Add More' is a pain. Hence they want to add them in one go.

### Acceptance criteria:
- Being able to multiselect image, video and file that supports multiselect options in one go without the need to click 'Add More' option each time. 
- Scope of this card is within mobile app since currently DEA doesn't support multiselect itself
- Clicking on 'Add more' should provide the ability to add more media in one go.
- For audio concept, currently multiselect not supported. if easy then support multiselect for audio concept. Note: package for supporting audio might be different.

### Technical details: updated as on 27th March:
- Found that this feature is supported only from android version 13 in the library we use, and that is enough to support.
- Refer the attached patch file in the comment for the work that has already been done.

### Out of scope:
- Not for DEA
- Not for Audio it it takes more than 3 hours.

### Suggestions:
no need UI/UX change.

**Comment by vinayvenu** [comment]
The newer version of [react-native-image-picker](https://www.npmjs.com/package/react-native-image-picker) has a selectionLimit. Setting this to 0 allows an infinite number of images to be selected.

**Comment by petmongrels** [comment]
[1298.patch](https://github.com/avniproject/avni-client/files/14506276/1298.patch)

**Comment by 1t5j0y** [comment]
## Notes:
- Audio selection of existing file was broken. Fixed that. Separate story will be needed to properly support Audio MultiSelect form elements.
- MultiSelect also worked for me on versions of android lower than 13. (Tested on android 11 with google photos as the gallery app).

## Testing Scope:
Image - Single and Multi Select
Video - Single and Multi Select
File - Single and Multi Select
Audio - Single Select
All of the above on android >=13 and android < 13

**Comment by Dinesh2019** [comment]
Test env : staging and pre-release

Test scenario :

1.Image video :
      -   Test uploading a single image
      - Verify that only one image can be selected at a time
      - Confirm that the uploaded image is displayed correctly
      - Test uploading multiple images.
      - Verify that multiple images can be selected simultaneously.
      - Confirm that all selected images are uploaded and displayed correctly.
      - Delete the image and validate the image in removed
 
2.Video Upload
      - Test uploading a single video file.
      - Verify that only one video file can be selected at a time.
      - Confirm that the uploaded video is displayed correctly.
      - Test uploading multiple video files
      - Verify that multiple video files can be selected simultaneously
      - Confirm that all selected videos are uploaded and displayed correctly
      - Delete the video and validate the image in removed

3.File upload
     -Test uploading a single file (e.g., PDF, DOC, etc.).
     -Verify that only one file can be selected at a time
     -Confirm that the uploaded file is displayed correctly
     -Test uploading multiple files(pdf,doc,xlsx)
    -Verify that multiple files can be selected simultaneously
    - Confirm that all selected files are uploaded and displayed correctly
    - Delete the file and validate the image in removed

4.Audio Upload:
      -   Test uploading a single audio file 
      - Verify that only one image can be selected at a time
      - Confirm that the uploaded image is displayed correctly
