### ISSUE TITLE
Location name getting cut on dashboard filters

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1300]
### Issue:
As shown in the below video, location name is getting cut in the dashboard filters. This is not happening in search filters.

https://github.com/avniproject/avni-client/assets/10369963/959d42a7-abe7-4529-9834-bba324aaff14

### Acceptance criteria:
Location names should not get cut

**Comment by himeshr** [comment]
Unable to reproduce with maha@rwb24uat in prod env (6.1 branch) using multiple emulators and diff form factors.
<img width="1495" alt="Screenshot 2024-02-15 at 6 58 55 PM" src="https://github.com/avniproject/avni-client/assets/72493481/6db9c8c9-fc7a-4afe-8b40-6721c8aae419">

**Comment by mahalakshme** [comment]
Because of the above, not worth the time.
