### ISSUE TITLE
Location hierarchy in search filter changes on selection and unselection

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1302]
### Issue:
Issue in both search filter and dashboard filters.
https://github.com/avniproject/avni-client/assets/10369963/eb362b39-b062-4ba6-a47c-8eb41140d4a8

### When not an issue:
When there is atleast one location that needs to be displayed as part of a location level.
https://github.com/avniproject/avni-client/assets/10369963/7ad1dbe1-beaa-4628-9a0a-320083264d7f

### Acceptance criteria:
- On unselection of a location filter at a higher level, all the the levels below it need to disappear when there is no location selected at lower levels. Currently only the levels immediately below it disappears. And hence when a higher level location is re-selected, the location hierarchy becomes incorrect as shown in the first video above.
- Note the release no, commit in a branch accordingly
- Make sure performance of selection/unselection doesn't get degraded.

### Need:
- Considering the org in focus is aiming to scale up around 10x times and that we now have filters in one more place, it is best to fix the issue now, though it is an existing issue.
- Their experience with us in the previous season was not great
- This issue also came up in the recent showcase.

**Comment by himeshr** [comment]
Sample recording after fixing the Location search filters used in CustomDashboards Filter and Individual Search screens.

https://github.com/avniproject/avni-client/assets/72493481/31aabd3f-b19d-48c5-9276-96158a98d2e5

**Comment by himeshr** [comment]
## Report card 
**Name: Daily recording farmer and machine
Description: Count of work orders that whose endline recording form has not been filled out.
Query: ** 
```
'use strict';
({params, imports}) => {
  const individuals = params.db.objects('Individual');
  const workOrders = individuals.filtered('subjectType.name == "Work Order" && voided == false');
  let addressFilteredWorkOrders = workOrders;
  if (params.ruleInput) {
    const orQuery = (array) => {
      return array.length > 0 ? '( ' + array.join(' OR ') + ' )' : ''
    }
    const filterBasedOnAddress= (entitiesResult, addressFilter) => {
      if (!_.isNil(addressFilter) && !_.isNil(addressFilter.filterValue) && addressFilter.filterValue.length > 0) {
        const joinedQuery = addressFilter.filterValue.map((x) => `lowestAddressLevel.uuid = "${x.uuid}"`);
        return entitiesResult.filtered(orQuery(joinedQuery));
      }
      return entitiesResult;
    }
    let addressFilter = params.ruleInput.find(rule => rule.type === "Address");
    if(addressFilter) {
      addressFilteredWorkOrders = filterBasedOnAddress(workOrders, addressFilter);
    }
  }
  return addressFilteredWorkOrders.filter(ind => !ind.encounters.some(enc => enc.encounterType.name == "Work order endline"));
};
```
