### ISSUE TITLE
After sync, MyDashboard stuck for sometime

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1303]
https://avni.freshdesk.com/a/tickets/3522

### Issue:
user: maha for adsr, env: prod
After sync for the org in focus, though numbers in MyDashboard show up, when clicking on Search, the app is stuck and it takes a minute to render the Search screen.

### Technical analysis:
After sync, looks like we are dispatching the action CustomDashboard.REFRESH_COUNT even when MyDashboard is the default dahsboard for the org. The same can be seen in the logs attached with the below video.
https://github.com/avniproject/avni-client/assets/10369963/8af6b243-78ef-45d7-9d8e-a523e9db91ac

## Test instructions
https://github.com/avniproject/avni-client/issues/1303#issuecomment-1970435028
https://github.com/avniproject/avni-client/issues/1303#issuecomment-1970436351

**Comment by himeshr** [comment]
### Test cases to validate
For ADSR, Goonj, Power, APF orgs, validate that
- On opening app, search and register button work immediately on click
- On completing manual sync, search and register button work immediately on click
- In "More-> Dashboards" section, the custom dashboard cards counts get refreshed when we switch across boards or open it first time
- In orgs, where CustomDashboard is primary(Goonj), card counts are refreshed on returning to Home page.

**Comment by himeshr** [comment]
@AchalaBelokar test using 6.1 pre-release apk, being built at 
https://app.circleci.com/pipelines/github/avniproject/avni-client/2368/workflows/1497d098-61bc-42cd-ad2c-e7a6002d4e8a/jobs/14835/resources

Users: hr at adsr, etc..

**Comment by AchalaBelokar** [comment]
- [ ] @himeshr  I am trying to open dashboard it is taking 10 min and after pressing the back button still it is not working ..back button is worked after 5 min .. is it fine

**Comment by himeshr** [comment]
Had to make additional fix to correct issue with no showing CustomDashboard in home screen for orgs which have a primaryDashboard configured, when we navigate to any other tab.

**Comment by himeshr** [comment]
Prerelease apk with all fixes for 6.1 is available here
https://app.circleci.com/pipelines/github/avniproject/avni-client/2369/workflows/2a9da98e-b67f-41eb-afd5-78f063474dae/jobs/14844/artifacts

**Comment by himeshr** [comment]
Cherry-picked commits onto avni-client 7.0 branch.
