### ISSUE TITLE
Fatal error : Cannot read property 'level' of undefined 

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1304]
Getting the above error when we click on the location in the search filter .Happens for all the location

env : pre-release 
org : rwb 
user : dinesh@rwb24uat
apk : https://app.circleci.com/pipelines/github/avniproject/avni-client/2328/workflows/e22a54e7-a471-48ac-9fa3-4b07ebdea5e6/jobs/14520/artifacts
[generic-prerelease-22911fb9e8e76fa3d44bc1cc5136586c62fbb0d8.apk](https://output.circle-artifacts.com/output/job/bb74222b-c6dc-4dab-88bb-4bea65948687/artifacts/0/generic-prerelease-22911fb9e8e76fa3d44bc1cc5136586c62fbb0d8.apk)

Steps to reproduce ;

1.login to app 
2.Click on the search option
3.Click on the location 

expected result : user should be able to select and display the error according to the user input
Actual result : user displayed with Fatal error 

https://github.com/avniproject/avni-client/assets/127730126/955312b3-d692-4c37-a031-33789391a8fb

**Comment by 1t5j0y** [comment]
Introduced via fix for #1294
Reopening that card based on discussion with @himeshr
