### ISSUE TITLE
Autoselected bottom locations available in custom report cards

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1307]
Make sure the necessary changes for [this](https://github.com/avniproject/avni-client/issues/1283) card are made as expected for custom report cards.

**Comment by himeshr** [comment]
## Report card 
**Name: Daily recording farmer and machine
Description: Count of work orders that whose endline recording form has not been filled out.
Query: ** 
```
'use strict';
({params, imports}) => {
  const individuals = params.db.objects('Individual');
  const workOrders = individuals.filtered('subjectType.name == "Work Order" && voided == false');
  let addressFilteredWorkOrders = workOrders;
  if (params.ruleInput) {
    const orQuery = (array) => {
      return array.length > 0 ? '( ' + array.join(' OR ') + ' )' : ''
    }
    const filterBasedOnAddress= (entitiesResult, addressFilter) => {
      if (!_.isNil(addressFilter) && !_.isNil(addressFilter.filterValue) && addressFilter.filterValue.length > 0) {
        const joinedQuery = addressFilter.filterValue.map((x) => `lowestAddressLevel.uuid = "${x.uuid}"`);
        return entitiesResult.filtered(orQuery(joinedQuery));
      }
      return entitiesResult;
    }
    let addressFilter = params.ruleInput.find(rule => rule.type === "Address");
    if(addressFilter) {
      addressFilteredWorkOrders = filterBasedOnAddress(workOrders, addressFilter);
    }
  }
  return addressFilteredWorkOrders.filter(ind => !ind.encounters.some(enc => enc.encounterType.name == "Work order endline"));
};
```

**Comment by himeshr** [comment]
AddressFilters work fine for 
- EntityApprovalStatus Report Card
https://github.com/avniproject/avni-client/assets/72493481/61dd75f1-2a49-4d60-89bc-2bf01834481d

- Custom Query Report Card
https://github.com/avniproject/avni-client/assets/72493481/35e16c80-eee2-49dd-9690-313e9228d147



The addressLevel filter is created such that, based on lowestSelectAddressLevel's type, all of the children of the selected addressLevels at the lowestSelectAddressLevelType are passed in the filterValue.

This is then used by standard report cards to perform the filter by addressLevel operation.
It has to be manually coded in customQueryFilter to use that, as shown in the code snippet.

```
if (params.ruleInput) {
    const orQuery = (array) => {
      return array.length > 0 ? '( ' + array.join(' OR ') + ' )' : ''
    }
    const filterBasedOnAddress= (entitiesResult, addressFilter) => {
      if (!_.isNil(addressFilter) && !_.isNil(addressFilter.filterValue) && addressFilter.filterValue.length > 0) {
        const joinedQuery = addressFilter.filterValue.map((x) => `lowestAddressLevel.uuid = "${x.uuid}"`);
        return entitiesResult.filtered(orQuery(joinedQuery));
      }
      return entitiesResult;
    }
    let addressFilter = params.ruleInput.find(rule => rule.type === "Address");
    if(addressFilter) {
      addressFilteredWorkOrders = filterBasedOnAddress(workOrders, addressFilter);
    }
  }
```

**Comment by himeshr** [comment]
@mahalakshme,
If we have applied filter at a higher level for an multiple addressLevels, but if we select only a few children from one of those higher addressLevel, then the filter now applies only for that selected children's all descendants.

Ex: Consider the below hierarchy:
![Image](https://github.com/avniproject/avni-client/assets/10369963/a5b3add2-89ea-4cf0-87ac-a8fc3e2bb6e0)

If we were to select => a,b,c,d,e, then the filter is effecively applied for all descendants of a->b->(d|e), but not for any descendant of a->c.

Is this behaviour acceptable.?

https://github.com/avniproject/avni-client/assets/72493481/5c1ee76c-e236-455a-874f-ce52a291decd

**Comment by mahalakshme** [comment]
@himeshr will check

**Comment by mahalakshme** [comment]
@AchalaBelokar can you verify the above scenario? descendants of a->c should get selected

**Comment by mahalakshme** [comment]
@AchalaBelokar since as discussed over the call the above functionality is inline with that of working of search filters, and also it seems to be intuitive with what the user would probably expect, we can move this to Done.
