### ISSUE TITLE
General Encounter Getting Scheduled Again on Edit 

### ISSUE THREAD

**Issue by vedfordev** [avniproject/avni-client#1315]
**Issue**
In cini, we are using general encounter for scheduling visit. some time some type of user is editing the encounter. so it schedule new visit which is already scheduled.

**Analysis**
We need to handle it like we have handled it for program encounter [here](https://github.com/avniproject/avni-client/blob/0b7ccf7bc7318f991be1fb7e9bbf0921b2ce0a4d/packages/openchs-android/src/state/AbstractDataEntryState.js#L354)

**To Reproduce**
Steps to reproduce the behaviour:
1. create general encounter.
2. write logic to schedule the encounter.
3. Go to app and schedule the encounter.
4. Edit the complete general encounter visit
5. It is scheduling again

**Reference documentation for Scheduling Visits**
https://avni.readme.io/docs/writing-rules#4-visit-schedule-rule 

**Acceptance criteria**

- General encounter should not get scheduled again on editing the completed visit.
- General encounter should not get scheduled again on editing a completed **Subject** registration (should have visit schedule rules that get triggered immediately on registration completion)
- General encounter should not get scheduled again on editing a completed **Person** registration (should have visit schedule rules that get triggered immediately on registration completion)

**Comment by AchalaBelokar** [comment]
- [x] I login with maha@cini_uat there is Dinesh Vidayala there are three completed encounter I am trying to edit monthly school monitoring I am not able to edit this encounter it is showing me visit can not done earlier .
- [x] I Login with dinesh@ihmp  I edited encounter of komal karan uaike ANC VNDC it is working fine there
- [x] Tried with sakhiapp there are
- [x] After completing the general encounter next visit is not getting schedule
- [x] After editing the general encounter next no duplicate visit is schedule.
- [x] After feeling the general encounter depend on that visit is schedule

**Comment by himeshr** [comment]
> * I login with maha@cini_uat there is Dinesh Vidayala there are three completed encounter I am trying to edit monthly school monitoring I am not able to edit this encounter it is showing me visit can not done earlier .

@AchalaBelokar, this error is because, in cini_uat org, implementation team has added additional validation as seen here, that is the reason its erroring out there.
https://prerelease.avniproject.org/#/appdesigner/forms/256d62ff-a7ed-4b7e-8ff6-10ba862efa72

<img width="1218" alt="Screenshot 2024-03-08 at 10 43 24 AM" src="https://github.com/avniproject/avni-client/assets/72493481/6ad1d047-ac07-4ac7-ad86-9a0cbd02a55e">
