### ISSUE TITLE
Avni gramin the add more option is not displayed 

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1318]
When we try to add more image or video the add more icon with displayed in the gramin the option is displayed but without any text 

env : prob(rwb)
org : gdgs
user : dinesh@gdgs24uat

Steps to reproduce : 
1.Login to the app
2.Click on the register
3.Click on the farmer 
4.Fill the first form
5.In the second page for the question land hold give value less than 2 
6.Will display two question they u can find the add more option displayed without name displayed in the icon

Expected : text should be displayed 
Actual : Text is not displayed 

References video :

https://github.com/avniproject/avni-client/assets/127730126/313d4433-c51d-4f99-a7d9-3cdacb64bc59

**Comment by mahalakshme** [comment]
duplicate, have asked this question in skype: this: https://github.com/avniproject/avni-client/issues/1318 is already fixed and the fix will be part of an upcoming Avni release. Is the fix needed for RWB app? @Anjali @Sachin @Pradipta
