### ISSUE TITLE
Sync audit information is coming wrongly after updating the 6.0 to 7.0.1 version 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1331]
**Describe the bug**
when new version came many user use avni app by updating it only 
In the 6.0 there is no audit information is present.
After updating 7.0.1 wrong information is came there.

**To Reproduce**
1. Install the 6.0.3 version production 
2. Login maha@power
3. update the app with newer version
4. see the registration details by 
5. it is showing there by: you.. but it is not created by maha 
6. Also Visit planed which is not completed encounter showing By: you this is bug
7. Look at the summary also it is showing wrong information
8. then I logout with maha@power 
9. And Login with maha@power
10. it is showing me this value
11. by right user
12. Summary will reflect diff user
13. uncompleted visit is showing by you

**Expected behavior**
For old data and planned encounters, audit information should not come.

**Screenshots**
<img width="330" alt="6 0 version" src="https://github.com/avniproject/avni-client/assets/104890488/1354b217-0a9c-4807-918f-1931d4746e3c">
<img width="324" alt="details power" src="https://github.com/avniproject/avni-client/assets/104890488/8d953bb3-fed9-4e99-9ecd-540d39260b95">
<img width="334" alt="version 7 0" src="https://github.com/avniproject/avni-client/assets/104890488/cdf64f81-893d-4f9c-a720-cb70a4202445">
<img width="319" alt="ver7" src="https://github.com/avniproject/avni-client/assets/104890488/1dc74212-6296-4679-be66-2869073066eb">

**Comment by mahalakshme** [comment]
issue fixed and tracked as part of [this](https://github.com/avniproject/avni-client/issues/1329) card
