### ISSUE TITLE
Update user audit fields immediately

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1332]
### Need:
- Currently the audit info of user doesn't get updated immediately. It gets updated after sync. This is because audit fields are created in server on syncing/saving and hence looks like it syncs back after that. This might cause confusion in places where audit fields are used. It is also difficult to handle this case, since old data will also be missing this audit info. 
Eg: When we want to show who observed a Teacher last in subject summary, eventhough say, it was me who created the last encounter, it will show the name of previous person. Even if we handle it not to show anything in such cases, it would cause confusion.

### Tech analysis:
- Approach 1: Looks like having a temporary user audit field, which will get filled with the name of the user who created subject/filled encounter  might fix the issue. This temp field can be used when the user audit fields are empty alone. And they need not be synced to server.
- Approach 2: Populate the name audit field when saving the entity. 
- Feel free to change the above tech implementation, based on what is best way forward 

### Acceptance criteria:
- User audit info to show without the need to sync.
- Note: the release is 7.1.0

### Out of scope:
- Dont update readme for the changes made as part of this card, since it can be updated around the time of releasing this

**Comment by petmongrels** [comment]
- we can use the same filledBy and createdBy fields. this will keep the code that uses it simple and same
- filledBy should be populated only on filling of encounter form and not on creation of encounter

When populating these fields we should use "you" or user name? If you then should it be translated?

**Comment by mahalakshme** [comment]
- we can use the same filledBy and createdBy fields. this will keep the code that uses it simple and same -> yeah agreed thats what I had meant in Approach 2.
- filledBy should be populated only on filling of encounter form and not on creation of encounter -> agreed
- When populating these fields we should use "you" or user name? -> I think username and uuid can be populated, so that the existing code will take care of rendering you. 
-  If you then should it be translated? Just remembered about platform translations, If we have not added, we might need to add platform language translations across languages for 'you' and 'By'.

**Comment by petmongrels** [comment]
1. Also implemented the same for lastModified fields.
2. In code review please verify the logic for filledBy population. It checks if it is not filled in db and the updating object is filled then it is getting filled and hence filled by fields should be updated in db.

**Comment by himeshr** [comment]
A minor renaming suggestion made [here](https://github.com/avniproject/avni-client/commit/b3556949fabbd89a81cb276878b5d282f43e4e64#r139616709).
The filledBy logic seems sound.

**Comment by Dinesh2019** [comment]
When we fill the unplanned visit audit is not updated as per the requirement

env : staging
org : offvd or cini_stag
user : dinesh@offvd  or dinesh@cini_stag


Steps to reproduce 
1.Login to the org
2.register the individual
3.Enroll into the program  
4.Complete the unplanned visit 

Expected result : audit should be updated when sync is not done
Actual result : audit is not updated when sync is not done

Please refer the screen-recording :

https://drive.google.com/file/d/1DhEGcr6F37C1DovtMKvoSDMhhUYvMPlH/view?usp=sharing

or 

https://drive.google.com/drive/folders/1KOXO_bIsZPaWta1Sbjb9y8hQ3yF-2LyI

**Comment by Dinesh2019** [comment]
Test  Case :

- [ ] Register and check for audit without sync
- [ ] Check the audit after sync 
- [ ] checked with another user that the audit name is populated correctly 
- [ ] Enroll in the program and check for audit without sync
- [ ] Check the audit after sync
- [ ]  checked with another user that the audit name is populated correctly user the enroll 
- [ ] Program encounter and check for audit without sync
- [ ] Check the audit after sync
- [ ] Checked with another user that the audit name is populated correctly user the program encounter
- [ ] General encounter and check for audit without sync
- [ ] Check the audit after sync
- [ ] Checked with another user that the audit name is populated correctly user the General encounter
- [ ] Unplanned encounter and check for audit without sync
- [ ] Check the audit after sync
- [ ] Checked with another user that the audit name is populated correctly user the General encounter
- [ ] And register with user a and check the audit status 
- [ ] login to user B check for the audit name and enroll in the program and check for the audit
- [ ] login to user C check for the audit name of enroll and complete the encounter
- [ ] Again back to user A and check for all the audit are updated correctly
