### ISSUE TITLE
Being able to access user and myGroups in all rules

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1334]
### Need:
- Currently user and, groups that loggedin user belongs to, are accessible only in some rules - like report card rule, edit rule. So when say in summary rule, I  want to show the user who did the last encounter for that subject, in that case, I will not be able to differentiate the loggedin user with other users, say when need to show as 'lastObservedby: you' instead of 'lastObservedBy: username'. 

### AC:
- Make user and, groups  that loggedin user belongs to, available across all rules in mobile app(for consistency purpose)

### Out of scope:
- Making the params available in DEA
- Making the params available for bundled rules.

**Comment by 1t5j0y** [comment]
@AchalaBelokar Wrongly asked you to move this to QA failed. The 'user' and 'myUserGroups' params are reflecting correctly.

**Comment by AchalaBelokar** [comment]
- [] Tested with summary rule showing the user is belonging to the two user group but it is showing only one

**Comment by vinayvenu** [comment]
@AchalaBelokar this was breaking custom dashboards. Just pushed a fix to it. Please take the latest.
