### ISSUE TITLE
Show the name of the custom report card in the listing page

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1335]
### Current status:
Currently when clicked on a custom report card, we list the subjects for that report card. The header in the top is constant and we show it as 'Subject List' for all report cards. 

![Image](https://github.com/avniproject/avni-client/assets/10369963/a4e5580d-a3f9-4174-988f-ac98e63942ef)

### AC:
- Show the name of the report card in the top instead of the constant 'Subject List'
- If the name of the report card exceeds 20 characters, cut it at 20 characters and show epsilon.

**Comment by vinayvenu** [comment]
@mahalakshme @petmongrels 

- "No change in behaviour" for search results screen
- I am not sure how we should handle cards that are coming from MyDashboard. There are cards such as "All", which show all subjects of a certain type.

**Comment by mahalakshme** [comment]
@vinayvenu for the All one - I think lets not handle it - since what it will display will be based on the filters and added complexity that I feel it not important for now.

**Comment by vinayvenu** [comment]
@mahalakshme agreed. So this is a testing note that it needs to work as is for search results and MyDashboard.

**Comment by AchalaBelokar** [comment]
- [x] Tested with custom report card suppose there is overdue visits are present it is showing that
- [x] Tested with normal dashboard

**Comment by mahalakshme** [comment]
@AchalaBelokar  what happens when a standard report card is part of custom dashboard?

**Comment by AchalaBelokar** [comment]
- [ ] Suppose there is long name on card it is showing only 1st word is coming.. 
- [ ] Login with AchalaB@power click on any card and see.

**Comment by AchalaBelokar** [comment]
- [ ] It is showing the only 14 character , character should be 20
<img width="330" alt="custom dasboard" src="https://github.com/avniproject/avni-client/assets/104890488/943a96e8-78a0-4151-982c-1721e6849368">
<img width="329" alt="individual not part of household " src="https://github.com/avniproject/avni-client/assets/104890488/210b755f-fc90-4029-ac1f-8dde29a7c6d2">

- [ ] suppose Their is one card Due which is part of standard report  card .. it is showing the Scheduled visits in the custom dashboard list

**Comment by Dinesh2019** [comment]
- [ ] Can we have like custom card which takes the name from name given by the user but for standard card it takes the name form the Standard report card type 

example : if the name of the standard card is given as due and standard report card type is selected as scheduled visit 

expected result : due should be displayed as header
Actual result : scheduled visit is displayed as header (which might cause confusion to the user)

References images: 



https://github.com/avniproject/avni-client/assets/127730126/8e45b648-d42c-40cf-a2eb-c34c7498333a

**Comment by AchalaBelokar** [comment]
- [x] still it is showing the schedule visit 
- [x] Also checked standard report card
