### ISSUE TITLE
Error message can be made clear

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-client#1337]
**To Reproduce**
1. Create a user without any sync attributes
2. Login on client and you must be able to see the error provided in the SS below

![Image](https://github.com/avniproject/avni-client/assets/94247708/0b1bfba6-51ac-4a56-8d14-05127883655c)

**Comment by mahalakshme** [comment]
@Gojo-Taqi I am unable to reproduce the issue. Tried multiple things. Please feel free to reopen the card if you are able to. Adding a video recording will help.
