### ISSUE TITLE
Dashboard setFilter - JSON.stringify - cyclical structure error

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-client#1340]
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/65ea8f3c4880080008b8db4c
Stacktrace:
```
TypeError Fatal error: cyclical structure in JSON object 
    native stringify
    /home/circleci/avni-client/packages/openchs-android/node_modules/openchs-models/dist/DashboardCache.js:62:36 setFilter
    /home/circleci/avni-client/packages/openchs-android/src/service/DashboardCacheService.js:55:36 anonymous
    native write
    /home/circleci/avni-client/packages/openchs-android/node_modules/openchs-models/dist/framework/RealmProxy.js:113:29 write
    /home/circleci/avni-client/packages/openchs-android/src/service/DashboardCacheService.js:53:21 updateFilter
    /home/circleci/avni-client/packages/openchs-android/src/action/mydashboard/MyDashboardActions.js:57:38 updateCachedFilter
    /home/circleci/avni-client/packages/openchs-android/src/action/mydashboard/MyDashboardActions.js:389:26 assignFilters
    /home/circleci/avni-client/packages/openchs-android/src/reducer/Reducer.js:22:43 anonymous
    /home/circleci/avni-client/packages/openchs-android/node_modules/redux/lib/redux.js:568:35 combination
    /home/circleci/avni-client/packages/openchs-android/node_modules/redux/lib/redux.js:296:35 dispatch
    /home/circleci/avni-client/packages/openchs-android/src/framework/view/AbstractComponent.js:56:63 dispatchAction
    /home/circleci/avni-client/packages/openchs-android/src/views/filter/FiltersView.js:116:34 applyFilters
    /home/circleci/avni-client/packages/openchs-android/src/views/filter/FiltersView.js:110:46 anonymous
    native apply
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:213:22 anonymous
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:111:14 _callTimer
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:359:16 callTimers
    native apply
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:428:31 __callFunction
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:113:25 anonymous
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:368:10 __guard
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:112:16 callFunctionReturnFlushedQueue
```

## Error scenario:
- Login to avni 7.0 Beta APK as any user where the organisation still uses MyDashboard and not a customDashboard as Primary
- Now apply address filter and attempt to apply the same for any subjectType
- App fails on clicking "Apply"
Note: Error seen for jsscp users in prod env, prod org

**Comment by himeshr** [comment]
## Test cases:
For myDashboardFilters test the following
 - Set of filters of different types (Address, gender, location, customFilters, name, etc..)
 - save and see that filters are applied
 - Open filters and ensure that applied filters are retained, change the filter and apply again
 - restart app and check that filter is retained for the subjectType
 - change subjectType and see that filters are cleared
 - apply new filters and save
 - filters should get applied
 - open filter and check that applied filters are retained
 - change subjectType and see that all filters are cleared

**Comment by AchalaBelokar** [comment]
Normal dashboard filter
- [x] Set filter with program it is working fine
- [x] After killing the app filters are retained.
- [x] After killing the app filter are retain also checked  
- [x]  Location with program filter 
- [x] Location with different address level
- [x] Select subject type and apply
- [x] After killing the app I reopen filter are retained

Custom dashboard

- [x] location filter
- [x] Killed app and open the app filters are retained
- [x] after updating the app still filter are retained
