### ISSUE TITLE
Rule is not applied until the page get refreshed 

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1354]
### Issue:
Details: When a rule C depends on B, and rule B depends on A, form element for C doesn't get updated, when A is updated. Only form element corresponding to B rule gets updated.

env : prod
org : apfodishauat
user : dineshg@apfodishauat

Steps to reproduce :

1.Login to the app
2.Register the individual
3.Try to enrol in the pregnancy program
4. we have the logic if the birth order count is 1 then we will not display the question birth spacing

Expected result : it should not display the question

Reference video :
https://github.com/avniproject/avni-client/assets/127730126/8049294d-6db4-4e6d-9af3-e3554b8d6617

### Analysis:
This is because we do only one refresh on going to a page. Here the form element rules are such that, the spacing value  needs to be set based on value set on `birth order` which is set by refresh on going to the page

### AC:
Add documentation (in writing rules doc) that transitive dependency of rules doesn't work and rules need to be written accordingly..

### AC:
Form element rules for lower form elements need to execute on values of form element at higher level set during the same rules execution

## Old: ignore
Add documentation to how rules need to be written. No fix needed.

**Comment by adamsanadi6** [comment]
When performing an action on the first page (default questions), the page (rules of other page elements) is not getting refreshed.

For reference:
Env: prod
Org: cini_uat
Form: School Teacher Registration

https://github.com/avniproject/avni-client/assets/64148954/1ad42723-6b23-4de8-8100-5910a7477392

**Comment by mahalakshme** [comment]
@adamsanadi6 found your comment to be a different issue, so moved it to separate card: https://github.com/avniproject/avni-client/issues/1398

**Comment by 1t5j0y** [comment]
Updated https://avni.readme.io/docs/writing-rules#2-form-element-rule
