### ISSUE TITLE
Duplicate identifiers on draft save

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1356]
https://avni.freshdesk.com/a/tickets/3646

### Issue:
To identify if an identifier is used, we introduce a `used` column in mobile app as part of [this](https://github.com/avniproject/avni-client/issues/1092) card. But looks like it is marked true only on save. Hence when a form with identifier is saved as draft, it is not marked as used, leading to duplicates. 

### Steps to reproduce:
Org: IPH CTRITH, env: prod
- Register a individual - dont click on Save button in the last page
- Register another individual - the same identifier assigned to the individual created in previous step will get assigned.

### AC:
- Identifiers used in drafts should not get reused. So looks like we need to mark 'used' as true on individual draft save
- Currently only applicable for individuals since enrolment doesnt have draft save
- Even when the user uses a different mobile say 'mobile 2', the identifier used in the draft in the previous mobile, say 'mobile 1' should not get used
- Exclude drafts while restoring fast sync db

### Technical point:
- Make sure identifier_assignment table is updated with individual_id/program_enrolment_id like currently on sync of individual/enrolment

### Analysis point:
- Apporach of generating identifiers only on save  - ruled out by sales team to retain current behaviour

**Comment by 1t5j0y** [comment]
avni-client commit: https://github.com/avniproject/avni-client/commit/a6be91567fc14400c8693d6fe785b2338c502406

**Comment by petmongrels** [comment]
Some amount of testing of non draft entities should also be done.

**Comment by AchalaBelokar** [comment]
- [ ] I created a individual  but not saved see the identifier and created next individual and see the individual identifier.
- [ ] created a individual other mobile try to create a another individual it is created .
