### ISSUE TITLE
Sanity testing of 7.2 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1360]
Sanity testing of 7.2 

https://github.com/avniproject/avni-product/releases

Need to test this card under this card

**Comment by AchalaBelokar** [comment]
1.  Calcutta kids
- [x] Login  with maha@calcutta_kids on 7.1 apk and create an individual dill the encounter and then update the app.
- [x] Created the user enrolled in the  program 
- [x] Exit the program
- [x] Cancel the visit 
- [x] Visit completed 

2. rwb 

- [x] Login with AchalaB@rwbnitiuat create farmer check the sync audit information of that also check the information  audit information previously created data. Fill the encounter and check the audit information  .
- [x] After updating the app 7.1 to 7.2 audit information is not coming for registration previously it is coming  TY 78 GJ 8978

3. jnpct
 - [x] Created  one individual enrol in the pregnancy program
- [x] Exit the pregnancy program
- [x] cancel the schedule visit
- [x] Complete the schedule visit 
- [x] Search the individual 
- [x] Filter the dashboard
- [x] Check filter is selected or not after killing the app
 
4. jsscp

- [x] News checked
- [x] Created individual enrolled the in program child
- [x] Check the vaccination checklist 
- [x] Due over due 
- [x] Done one vaccination
- [x] Check custom dashboard which is taking a time  

5. Adolescent - Sewa Rural
- [x] "Register Individual
- [x] Enrol into program
- [x] Standard dashboard
- [x] Search for subjects
- [x] Custom dashboard
- [x] Schedule and Perform Program encounters
- [x] Cancel program encounters
- [x] Exit Enrolment"

6.  @LAHI
- [x] Immutable encounter
- [x] User Subject Assignment

7. PoWER

- [ x] Reassigned task to another individual
- [ x] Program Eligibility Engine
- [x] Visit Scheduling
- [x] Task updates & rescheduling
- [x] Profile registration & calling
- [x] Profile calling 
- [x]  With older version of app perform fresh sync

**Comment by mahalakshme** [comment]
@AchalaBelokar considering we already did sanity testing for 7.0, I think it is good enough to focus on just cases related to cards of 7.0 - anyways you can decide.
