### ISSUE TITLE
UI improvements for profile page

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1361]
### Inputs vs Now:
<img width="1378" alt="Screenshot 2024-04-07 at 11 00 20 PM" src="https://github.com/avniproject/avni-client/assets/10369963/2f4f52ca-d736-4d6f-98b0-fcdbd93869ab">

<img width="441" alt="Screenshot 2024-04-08 at 12 14 42 AM" src="https://github.com/avniproject/avni-client/assets/10369963/d6009814-2652-494d-82fa-27cd78cc7618">

### Acceptance criteria:
- Change the format of audit like in the mockup: ```enrolled on date by maha``` / ```filled on date by maha```
- Move group of subject like in the image

### Points of issues:
- grey - our users might not be able to see only
- edit icon - our users dont understand icons
- cancel - red currently - for caution 
- cant expand when mentioned Completed tag on top right
- changing the position of enrol button and actions suddenly - might need retraining of users
- Call button inside elipsis - might make it less evident for PoWER users

### Questions:
- Removing black color on top - then we need to remove for form screens as well - will become inconsistent
- How should ```registeration details``` display when expand option is clicked. Currently this is how it is shown:
![Image](https://github.com/avniproject/avni-client/assets/10369963/7e4369f8-d6c8-4257-9d28-e35b5775546e)
- what should be color of scheduled vs due
![Image](https://github.com/avniproject/avni-client/assets/10369963/ccc71c0e-cd02-427a-8099-b720705572cf)
- How should Summary display - like in table format currently?

**Comment by vinayvenu** [comment]
To think about
1. Text styling of the section headers (capitalisation, font size etc)
2. Having a consistent label on the top right for all cards
3. Flat UI for cards instead of the 3D style we have now
4. Remove the black from the top and bottom (and from all headers) - look at impact of this change first. Ensure all buttons work well
5. Change font sizes etc everywhere

**Comment by mahalakshme** [comment]
@vinayvenu I have concerns on 3 and 4. read about skeuomorphic design which I think is what we have currently to some extent. If we change to flat design, it might not be very intuitive that the encounters are clickable. Also currently the black top - feels like a letter pad header which is I think is easier for users that it is not clickable. Considering we are catering to different set of users, its understandable that TeachAP wants it to be more modern. But I am afraid it would be at the cost of usability for primitive users for whom skeuomorphic design might better suit.

**Comment by vinayvenu** [comment]
@mahalakshme the design style we had initially was inspired by material design 1, and has nothing to do with skeuomorphic design. Material has moved on from that time through versions 2 and 3 based on their learnings. 

The ideas we are using are now 10 years old, and can use a refresh of the styles based on these learnings.

**Comment by mahalakshme** [comment]
@vinayvenu I am not convinced because of the following reasons:
      - Material design has incorporated a mix of skeuomorphic and flat design. So i can understand that both have similarities. Material design 3 also has elevated cards: https://m3.material.io/components/cards/guidelines . Flat design emerged because people became familiar with usage of mobiles and we no longer needed to mimic the real world objects. But this is not applicable to considerable quantum of our users. Eg: APF users some of them I have seen are not aware how to move to next page. Also even material design 1 was introduced in 2014 came after flat design(introduced much earlier - before 2010).
      - Now people who train users on the ground might have for eg: told that they need to click on cards, If we make subject profile page design alone flat, it would not be consistent with other pages - Menu, Search button, login button, dialog boxes, . So how will they train the users now
      <img width="448" alt="Screenshot 2024-04-09 at 10 58 26 AM" src="https://github.com/avniproject/avni-client/assets/10369963/49ff1cef-4da9-4652-9379-14858c103681">
      <img width="442" alt="Screenshot 2024-04-09 at 10 08 16 AM" src="https://github.com/avniproject/avni-client/assets/10369963/31860389-58cf-495f-a361-62e5dbb8724e">
      - I even thought if we can change screen by screen across releases. But from UX perspective what will be better is to introduce a single change across screens in the same release, and introduce consecutive changes in consecutive releases.
      - We are currently not in need of right arrow on report cards, because of the elevated cards design
      - If we change cards to grey color what will be the color to differentiate the page names(FEG names) and form elements
<img width="425" alt="Screenshot 2024-04-09 at 11 12 03 AM" src="https://github.com/avniproject/avni-client/assets/10369963/125ab1dd-fccb-44b7-8301-9c0ec76c833f"> I can suggest something, but I am not sure if that will be any better.
- Regarding point 2, though the entire card is clickable, when seeing the down arrow, users can predict which side the card will open(and this kind of predictability is a good UX is what I read in 'Design of Everyday things' book) compared to individuals where it will open in new page. And arrows are indicative not only expansion also collapsing. I am not able to find good UI for moving the arrow to bottom.
<img width="419" alt="Screenshot 2024-04-09 at 11 04 27 AM" src="https://github.com/avniproject/avni-client/assets/10369963/ca3edd30-a6ab-436f-8a6c-0fbe9eb98906">
- Regarding 1 and 5, I dont know what to do regarding font sizing, caps in other pages:
<img width="441" alt="Screenshot 2024-04-09 at 11 34 44 AM" src="https://github.com/avniproject/avni-client/assets/10369963/5e94fad9-1e36-419e-a753-1b90064d74ed">
<img width="430" alt="Screenshot 2024-04-09 at 11 24 07 AM" src="https://github.com/avniproject/avni-client/assets/10369963/54aba183-5c2f-4523-9512-fcd29b79eb5d">
Everything is already inconsistent and it will continue to be so. So I am not sure if we are improving anything
-  I am not telling current UX is better. Currently we have used flat design inside missed calls card but different design  in other cards. 4 different font sizes in one page :( 
<img width="430" alt="Screenshot 2024-04-09 at 11 24 07 AM" src="https://github.com/avniproject/avni-client/assets/10369963/9d24445b-c3a5-4b31-867c
<img width="435" alt="Screenshot 2024-04-09 at 11 25 04 AM" src="https://github.com/avniproject/avni-client/assets/10369963/a365743e-ea14-410c-9f87-b636ca092c5c">
-59a9f7050ae8">
      - I mean I dont know how to go about the above without above questions resolved. I think we need suggestions for holistic revamp of mobile UI with someone who understands our users(who can also do some user testing) and all the screens/cases so that we can make sure it helps all kinds of users we have: not just look and feel, also helps improves/retains the usability.
