### ISSUE TITLE
UI improvements for report cards

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1362]
### Inputs vs Now:

![Image](https://github.com/avniproject/avni-client/assets/10369963/9709a4d9-6a84-4092-8ba5-4aa19d6cbcbf)

<img width="902" alt="Screenshot 2024-04-07 at 11 17 11 PM" src="https://github.com/avniproject/avni-client/assets/10369963/4b9f32c2-d65f-4adf-ae4f-2ee8da38738b">

![WhatsApp Image 2024-04-08 at 12 16 56 AM](https://github.com/avniproject/avni-client/assets/10369963/341490a4-a5ac-4851-a45e-86c2b43ce20d)

### AC:
Nil - We can just change the report card and text color

### Inputs:
- colors pallete
- indication to press right arrow

### Issue points:
- Currently all the configured card colors are bright colors to match the white text, hence if we make the text to black color visibility of numbers on existing configured colors will be an issue. Migration difficult since 301 distinct colors.
- having collapsible in the first page - can create confusions - if by default its gonna be open - I doubt if anyone will even use it.
- Numbers in the left are considered serial number in registers - not sure our primitive users will understand
- Color for entire card in list style - it is used by other orgs as well - considering we have used dark colors everywhere report card name might become difficult to read.

### Questions:
- I feel when compared to table format, card format for list style is better right?
- How to display multiple dashboards?

**Comment by vinayvenu** [comment]
To verify
1. Keep list numbers to the right
2. Move card colours to black
3. Keep note of border square vs roundings, font sizes etc
4. Make screen flat
