### ISSUE TITLE
User able to see their own forms

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1365]
As a user, I should be able to fill required details related to me, to communicate my grievances to my supervisor.
As a user, I should be able to see the forms that I filled with details related to me.

### Acceptance criteria:
- [x] Validate that **only** his own User specific Subject(UserType SubjectType) is synced to the User's device for each User.
- [x] UserType Subject types, without any address details should still sync correctly only to its corresponding user.
- [x] Sync should success with both old and new versions of env apks. The only difference, being that old apk, will not show any UserType Subject types, whereas the new apk should show them all that info.
- [x] As a user of any  user group level I should be able to sync my forms (Unless Privileges restrict syncing the UserType Subject or its children entities)
- [x] On clicking on Register only show subject types with registeration Form Mapping. So for now User subject type will not display. Administrator User in UserGroup Privileges section, always sees the Privilege.ViewSubject for all User type SubjectTypes, even if they do not have a FormMapping associated with them. This would need the Adminstrator to Void the FormMapping to the User type SubjectType and enabling the Privilege.ViewSubject for that SubjectType for sync to work on client for related entities.
- [x] Do not show User subject type in Search.
- [x] Mockups for when there are due encounters that User need to fill for themselves - Standard report card(Overdue) and custom report card(right) like below - user identified as '${username}(You)'
<img width="732" alt="Screenshot 2024-04-01 at 7 39 05 PM" src="https://github.com/avniproject/avni-product/assets/10369963/028322d9-f6ae-474e-a8a5-24667c6857f5">

- [x] On clicking on '${username}(You)', take to the profile(below) of the User. On clicking on red arrow take to encounter form like done currently.

<img width="293" alt="Screenshot 2024-04-10 at 1 59 23 PM" src="https://github.com/avniproject/avni-client/assets/10369963/eaa14124-36fd-4272-8cae-4d4642f7968d">

- [x] no need to display Location, just '${username}(You)' in the header
- [x] Do not show 'Registration Details' section in the profile page when the registration form has no form elements
- [x] The UI of profile page is currently determined based on the entities associated with subject type: Eg: when the subject type has general encounters, encounters get displayed on the subject profile page itself - so similar kind of behaviour need to continue for User subject type
- [x] Rules in the form if any added should continue to work.

## Old: Ignore:
- On clicking on My forms -> direct to profile page. Like in Teach AP, since it has general encounters and no programs make it to display like below: 
![Image](https://github.com/avniproject/avni-product/assets/10369963/5c510d11-3767-49d8-a566-5d3143032978)

- When registeration form not associated, do not show `Registeration details` section. 
- Standard report card(Overdue) and custom report card(right)
<img width="732" alt="Screenshot 2024-04-01 at 7 39 05 PM" src="https://github.com/avniproject/avni-product/assets/10369963/028322d9-f6ae-474e-a8a5-24667c6857f5">

- User subject type, should not appear in Search and Register.

### Technical details:
- Entity sync status same as current	
- Make it extensible to be able to sync when ordering of levels comes in

### Inputs
- one subject type - 
- might not work in real life - this hierarchy
- Menu item - separate card - not needed to deliver now
- ETL, register, resgiteration details - no form elemtns, immutable, 

- system stable - 4x
- readme - salesforce - videos
- 

### Points of discussion:
- standard report card needed?
- in profile need to display the menu item? remove
- sync and locations

**Comment by petmongrels** [comment]
- There are existing assumptions in the code that the user has catchment at the time of sync. This means the `User` cannot be the only subject type in an implementation and for that reason, user doesn't have any catchment. It won't work. Unlikely but pointing out. Will document.
- Individual in realm requires address level as a mandatory field. Don't like relaxing this constraint. Also the avni client code may have made assumptions. Null object pattern?

**Comment by himeshr** [comment]
- In-order to ensure we do not break sync for older versions of Avni-client, the AddressLevel should return a dummy value as part of the Server Individuals sync response
 - We cannot handle requirement to hide User Subject Types in Search box, in old client
 - We cannot meet UI requirements mentioned in this card for old versions of client, which could cause issues like broken Touchable entities and irregular Formatting

**Comment by mahalakshme** [comment]
@himeshr 
1. what would happen if the user selects User subject type in older versions of client
2. are we storing the dummy value somewhere as well? If so, to avoid it, is it possible to create another api version for new version of clients and modifying the server api of old version to not return User subject types?

**Comment by himeshr** [comment]
@mahalakshme and @vinayvenu If we do not have Registration Forms for UserType subject, then scheduling the First Encounter on User Create capability will be lost.

**Comment by mahalakshme** [comment]
based on the above discussion we have decided to not support 'User' subject type for older versions of client.

@himeshr good point. but currently we can do the same of displaying registeration form only if there is atleast one form element - for completing the story - you can insert some dummy encounter data. 

I will analyse the gap and create a separate story for dealing with it.

**Comment by himeshr** [comment]
> * In-order to ensure we do not break sync for older versions of Avni-client, the AddressLevel should return a dummy value as part of the Server Individuals sync response
> * We cannot handle requirement to hide User Subject Types in Search box, in old client
> * We cannot meet UI requirements mentioned in this card for old versions of client, which could cause issues like broken Touchable entities and irregular Formatting

Changes to approach based on Tech discussions
- We are not sending Dummy AddressLevel from Server, rather we are only populating DummyAddressLevel in Client during Sync
- We are not going to sync UserType Subjects to old versions of Avni-client, as we have a flag based sync for this, which only new clients will send

**Comment by himeshr** [comment]
Sample client screen recording for UserType subject handling on client

https://github.com/avniproject/avni-client/assets/72493481/2ae92747-659e-4feb-9010-7e0b02baecc7

**Comment by himeshr** [comment]
@mahalakshme and @vinayvenu , currently we do not sync UserSubject entity that links User to Subject(of subjectType.type User) to client. Therefore, if there are more than 1 UserType subjects belong to different Users, then, we'll not be able to reliably figure out which Subject corresponds to logged-in user, as name comparison is not sufficient.

**Comment by himeshr** [comment]
Sample screen recording for English

https://github.com/avniproject/avni-client/assets/72493481/f5f8a89d-d263-4679-ad2f-805c85e7940c

**Comment by himeshr** [comment]
@mahalakshme and @vinayvenu 
To satisfy this requirement
`As a user of any user group level I should be able to sync my forms (Unless Privileges restrict syncing the UserType Subject or its children entities)`
I haven't made any changes in code, this should be achievable by enabling/disabling Permissions in UserGroups.

**Comment by himeshr** [comment]
In-order to get User Type SubjectTypes data to be synced to the Client, Its Privilege.ViewSubject should be enabled.

**Comment by mahalakshme** [comment]
Currently User subject type will not show if form mapping for that User registration is deleted - and sync is made to work with this.

**Comment by himeshr** [comment]
Have improperly handled below Acceptance Criteria: 
 - On clicking on Register only show subject types with registeration form, that atleast have one form element. So for now User subject type will not display.
 
 - Have made changes such that Admin User in UserGroup Privileges, sees the Privilege.ViewSubject for all UserType subjects, even if they do not have a FormMapping associated with them. This needs Admin user to remove the FormMapping to the UserType Subject and enabling the Privilege.ViewSubject for the things to work on client.
 
 @petmongrels and @vinayvenu should this be reversed and we do a simple change in Client.?

**Comment by himeshr** [comment]
> Have improperly handled below Acceptance Criteria:
> 
> * On clicking on Register only show subject types with registeration form, that atleast have one form element. So for now User subject type will not display.
> * Have made changes such that Admin User in UserGroup Privileges, sees the Privilege.ViewSubject for all UserType subjects, even if they do not have a FormMapping associated with them. This needs Admin user to remove the FormMapping to the UserType Subject and enabling the Privilege.ViewSubject for the things to work on client.
> 
> @petmongrels and @vinayvenu should this be reversed and we do a simple change in Client.?

After discussion with Vivek, we concluded that this approach is fine.

**Comment by AchalaBelokar** [comment]
- [x] I created one org which contain the user subject type . user name is AchalaB@usersub
- [x] After creating the usersubtype login on client and try to register individual but it as mentioned in the card without location individual  should be registered but I am not able to register the individual .
- [x] After removing form mapping it is not showing on client
- [ ] created a program encounter, program enrolment , general  encounter

**Comment by himeshr** [comment]
@Achala, this case is not valid as of now _After creating the usersubtype login on client and try to register individual but it as mentioned in the card without location individual should be registered but I am not able to register the individual_  Sorry for the confusion.
