### ISSUE TITLE
Landing screen UI revamp

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1370]
See here for [Design](https://www.figma.com/proto/HPzr68jbroQxLDjDfY4SLk/Mobile-App?type=design&node-id=584-2540&t=g0BftVfisLxQ2eGB-0&scaling=scale-down&page-id=584%3A2539) and the design [system guidelines](https://www.figma.com/proto/HPzr68jbroQxLDjDfY4SLk/Mobile-App?type=design&node-id=346-6162&t=g0BftVfisLxQ2eGB-0&scaling=min-zoom&page-id=346%3A4600)

### Sections in scope
- Header including sync button (see if this will be a problem since the header is across all screens)
- Filter
- Bottom bar
- Custom Dashboard cards (all three types - list style, card and list)
- Custom Dashboard (that is not in Home)
- MyDashboard cards

### Different from scope/removed from scope
- Keep numbers on the list style report card to the right instead of the left as provided
- Ignore the expand/collapse mechanism
- Search button

**Comment by vinayvenu** [comment]
@petmongrels lets keep the numbers on the right hand side (see AC) on the list style report cards.

**Comment by mahalakshme** [comment]
@petmongrels when incorporating client showcase feedback found that text size of the report card names are smaller than the numbers and the section name. And looks like section name is little bigger than the current size used.
