### ISSUE TITLE
Subject Dashboard UI revamp

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1371]
See here for [Design](https://www.figma.com/proto/HPzr68jbroQxLDjDfY4SLk/Mobile-App?type=design&node-id=584-2540&t=g0BftVfisLxQ2eGB-0&scaling=scale-down&page-id=584%3A2539) and the design [system guidelines](https://www.figma.com/proto/HPzr68jbroQxLDjDfY4SLk/Mobile-App?type=design&node-id=346-6162&t=g0BftVfisLxQ2eGB-0&scaling=min-zoom&page-id=346%3A4600)

The UX will remain the same. All sections will remain the same. Changes involved here are purely at the UI level. The primary changes we are doing here include
- Header (if not already done)
- Change in background colors (of the top card and the overall background)
- Change in structure of all cards. Remember to make the changes in all cards, including
  - Summary
  - Planned and completed visits
  - Registration Details
  - Empty Program
  - Eligibility Report
  - Relatives
  - Group members section for group cards
- Bottom bar (make it similar to home screen)

**Comment by mahalakshme** [comment]
@AchalaBelokar u checked the below cases:
- checking of eligibility
- exiting program
- enrolling into multiple programs

**Comment by mahalakshme** [comment]
@AchalaBelokar just documenting the issues we discussed to avoid it getting missed:
- Secondary buttons are of different colors - grey and red - make it same color (Void, Exit buttons)
- Eligibility report card is not changed to gray color
- Call button is towards extreme right - needs more padding.

**Comment by AchalaBelokar** [comment]
- [x] Login with maha@power and check that eligibility check should be in gray currently it is showing in white background
- [x] In power organisation calling button is present but it is little but side
- [x] Login with maha@jsscp  click on more button there is news field which is also in white it should be in gray colour 
- [x] In household there is member we can remove and edit the individual remove and edit buttons 

![Image](https://github.com/avniproject/avni-client/assets/104890488/9bc64ef2-bd76-4269-837d-837cb9096095)

**Comment by himeshr** [comment]
@AchalaBelokar have mode fixes for above reported issues. Except for _"In household there is member we can remove and edit the individual, remove and edit buttons"_. After discussion with Maha, we decided to retain the current colour for it, as its supposed to be using Complimentary colors there.
<img width="751" alt="Screenshot 2024-06-03 at 5 36 24 PM" src="https://github.com/avniproject/avni-client/assets/72493481/81c00b0c-49d4-4820-a4c4-d6340fa1384a">
<img width="751" alt="Screenshot 2024-06-03 at 4 39 18 PM" src="https://github.com/avniproject/avni-client/assets/72493481/80d976f8-b6ff-40c9-90a7-e69463b461ed">
<img width="751" alt="Screenshot 2024-06-03 at 3 22 47 PM" src="https://github.com/avniproject/avni-client/assets/72493481/e1af7fc9-974c-45b3-a4cd-b828ca5bd8a2">
<img width="751" alt="Screenshot 2024-06-03 at 5 34 47 PM" src="https://github.com/avniproject/avni-client/assets/72493481/9d2a9e41-9ef3-48d1-8c9c-4f0817e8a17d">
