### ISSUE TITLE
Search Results UI revamp

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1372]
See here for [Design](https://www.figma.com/proto/HPzr68jbroQxLDjDfY4SLk/Mobile-App?type=design&node-id=584-2540&t=g0BftVfisLxQ2eGB-0&scaling=scale-down&page-id=584%3A2539) and the design [system guidelines](https://www.figma.com/proto/HPzr68jbroQxLDjDfY4SLk/Mobile-App?type=design&node-id=346-6162&t=g0BftVfisLxQ2eGB-0&scaling=min-zoom&page-id=346%3A4600)

### Summary
- We are moving away from having details on the right to everything on the left only. 
- Order of content will be 
  - Name
  - Age, Gender
  - Location
  - Search result attributes, one after another. Overflow to multiple lines and separated by commas
  - Enrolled programs

We can choose to keep the left icon as-is since we might not be able to have good icons for everything.

**Comment by AchalaBelokar** [comment]
- [x] Login with AchalaB@hello tested there with search
- [x] Login with AchalaB@jsscp search with individual ,with Name , location
- [ ] age search is not working in AchalaB@jsscp

**Comment by AchalaBelokar** [comment]
- [ ] I Login on AchalaB@rwbnitiuat there is custom dashboard which contain filter  it is not showing the filter word as we mention in the card it should be on the top 



![Image](https://github.com/avniproject/avni-client/assets/104890488/61a3ba78-9f59-4117-91ae-d1a46cc7867b)
