### ISSUE TITLE
Filter not applied at all address levels

### ISSUE THREAD

**Issue by vedfordev** [avniproject/avni-client#1375]
**Describe the bug**
When implementing a filter at the block level in Goonj, the dashboard card does not filter data that is at a higher level, such as District.

**To Reproduce**
Steps to reproduce the behaviour:
1. Login with gvamp_uat user (maha@gvamp_uat)
2. Apply filter like (Kerala -> Alappuzha -> Other)
3. Check Demand to be dispatched (data is not filtered, as the Demand is registered at higher address level type => "District")

### AC:
- In the params pass all the selected locations as well(along with lower level locations implicitly selected) since subject might be registered at any address level
- The standard report cards added to custom dashboard as well need to work inline with this (filter needs to be applied based on all locations(any level) selected and lower address levels implicitly) 
- Note the release number to make sure the commit is made in the needed branch

**Analysis**
Working in 7.1 but not in 7.2 which has fix for selection of lower address levels implicitly(https://github.com/avniproject/avni-client/issues/1283)

**Comment by mahalakshme** [comment]
@vedfordev It doesn't work with 7.1.x - latest release as well?

**Comment by vedfordev** [comment]
@mahalakshme not working

**Comment by mahalakshme** [comment]
@vinayvenu are you aware of the priority for this?

**Comment by vinayvenu** [comment]
Breaking an implementation

**Comment by mahalakshme** [comment]
@vinayvenu @vedfordev  already working in 7.2 and 7.1 as well


https://github.com/avniproject/avni-client/assets/10369963/7b6b2e2d-1fbd-4de1-b27b-6c1943c93567


Am I missing something?

**Comment by vinayvenu** [comment]
We did a common debugging session. This is a product bug. Specifically, when choosing a lower level location, the higher locations do not show up in the address array of ruleInput. This is a problem when there are multiple cards, and some of them rely on subjects that are registered at a higher level.

**Comment by petmongrels** [comment]
- shape of address filter added here https://avni.readme.io/docs/writing-rules#filter-value-shapes (for rules type name should be sufficient and typeUuid shouldn't be required)
