### ISSUE TITLE
WIP: Add client database side validations to report issues through bugsnag 

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-client#1377]
### Motivation
In certain scenarios, we make complex changes to the Avni-client Realm DB Datamodel, which might end up causing data loss issue on the client. These when synced to server, end-up wiping out the old data. This issue though takes a lot of time to surface and reach the Product team. We should rather have validations in place that ensures that there is no rampant errosion of data and notify when that changes using bugsnag.

Ex: A background test that runs every midnight, which maintains count of say ProgramEnrolment entities amongst other entity types, that have non empty observations and notifies when there is a change of more than 10 entries or decrease by 10%, from previous recorded count for that entityType.

### Acceptance Criteria
Run data-validation checks once every day, for all the major entities that store transactional data on the client, to ensure that Observations data count is not changed drastically over the last 24 hours.

**Comment by mahalakshme** [comment]
Suggestions given:
- Issue might not happen again
- Have some tables immutable - done in other systems?
- Check added in server side for individual and enrolment

**Comment by himeshr** [comment]
Closing this card, as during a discussion on this topic, we concluded that we should direct most of our energy in ensuring that the changes we make in our application should ensure sanctity of data.
Spending effort on introducing the validations will have a very low ROI.
