### ISSUE TITLE
Getting error on make run_app

### ISSUE THREAD

**Issue by shahinraza1** [avniproject/avni-client#138]
Hello developer,
I have cloned this project and tried to setup locally. I have installed the openchs-servers and its working properly and server is running. And my emulator is working properly on adb. I have checked for adb devices. But while I am running openchs-client app as make run_app , I am getting the below issues in terminal . Can you please give me hints to resolve this issue..

make run_app
Makefile:197: warning: overriding recipe for target 'open_app_bundle'
Makefile:190: warning: ignoring old recipe for target 'open_app_bundle'
adb root
adbd is already running as root
adb remount
remount of /system failed: Read-only file system
remount failed
adb pull /system/etc/hosts /tmp/hosts-adb
0 KB/s (73 bytes in 0.078s)
sed -i.bak '/dev.openchs.org/d' /tmp/hosts-adb
echo '	dev.openchs.org' >> /tmp/hosts-adb
adb push /tmp/hosts-adb /system/etc/hosts
failed to copy '/tmp/hosts-adb' to '/system/etc/hosts': couldn't create file: Read-only file system
Makefile:43: recipe for target 'setup_hosts' failed
make: *** [setup_hosts] Error 1

**Comment by mihirk** [comment]
Hello Shahin,
Which operating system are you running it on and also what android emulator
are you using?
Make sure you have the android emulator running when you run make run_app

**Comment by shahinraza1** [comment]
Hello, 
I am using Ubuntu 16.04 LTS and I have two android emulator ie, Pixel API 27 and Nexus S both working on android oreo. The android emulator is running properly, I have checked it through $adb devices command,  and the command is showing my devices.
