### ISSUE TITLE
 Incorrect media URL

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1380]
### Need:
Many of the profile pics uploaded in 2024 have only image name and not the URL.
From the below found 48% of individuals registered in 2024 with profile picture have URLs incorrect
```
select count(*) from individual where profile_picture is not null and profile_picture not like '%http%'
and registration_date > '2024-01-01'::timestamptz;
;
-- 139

select count(*) from individual where profile_picture is not null
                                  and registration_date > '2024-01-01'::timestamptz;
--285
```

### Analysis:
- Many of the profile pics uploaded in 2024 have only image name and not the URL. 
- Was unable to find any media observations with this issue - checked in Goonj which had prominent number(1331/1593) of individual registered in 2024. With JSSCP with just 285 registerations the issue occurred. In both orgs 90% of syncs have happened in versions greater than 6.0 in 2024. So looks like media observations doesn't have this issue.
- But the image(profile pic) is present in S3.
- And the issue is not reproducible with the below:
----  slow network, - timeouts and sync doesn't proceed, media item from queue not popped, so resumes when network better
----- app closing, - stops and since the media item not popped resumes from beginning on reopening
----- app moved to background,  - sync continues
---- bigger size images, - if timeouts since the media item not popped out
---- CSV upload, - places where issue present - entries not uplaoded via CSV
---- DEA upload - works as expected
- Its not related to data loss issue - since the individuals registered itself has happened in versions that doesn't have data loss
- Issue across different orgs.
- Found in couple of cases that sync has stopped(no end time) or sync failed before doing data sync and after trying to sync media

![Image](https://github.com/avniproject/avni-client/assets/10369963/7f1aec91-f4c5-4ba9-ad06-523ae7d25dc7)

Unable to find issues in bugsnag for the above.

### AC:
Find the rootcause and fix it. Create cards if you think thats better.

**Comment by petmongrels** [comment]
Profile picture issue is reproducible on 6.1 branch which was also 7.1 release. This issue has been fixed now.

### Code on 6.1

https://github.com/avniproject/avni-client/blob/83361342f68255033fc9e32cec54873c07cd511f/packages/openchs-android/src/service/IndividualService.js#L113

### Code on 7.3
https://github.com/avniproject/avni-client/blob/b3556949fabbd89a81cb276878b5d282f43e4e64/packages/openchs-android/src/service/IndividualService.js#L115

**Comment by mahalakshme** [comment]
@petmongrels can you also add how to reproduce the issue? I am eager to know. Will also help for testing.

**Comment by petmongrels** [comment]
### Test scenario
- Use 7.1 app or 6.1 branch app
- Take an individual and edit it
- add profile picture
- sync
- check the db
