### ISSUE TITLE
Being able to apply subject type filter on Due and overdue visits cards when part of custom dashboard

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1381]
### Need:

1. Frequently we are unable to use SRC as such because users want to customise it based on program or encounter.
Eg: 
- Overdue visits for child followup in APF Odisha - which is based on program, encounter type
- No of Follow-up visits due for Epilepsy followup in JSSCP - Infividual ST, followup encounter type, Epilepsy program
- Due WIMC meeting in AKRSP - WIMC meeting encounter type and Individual subject type
- Eye checkup due in Chashma - 'Eye checkup' encounter type and Patients subject type

2. To be able to achieve MyDashboard functionalities via Custom Dashboard code ie. to have the code at one place eventually.

### Example configurations: 
--- 1. I add a 'Scheduled Visits' report card to a custom dashboard, with subject type as Child(configured on report card). This is needed when a user wants to see due visits for all subject types in primary dashboard, without having to filter each time.
--- 2. I have 'Scheduled Visits' report card added to custom dashboard without any filters configured on report card, but 'Subject type' configured on custom dashboard filters. This is useful for cases where user would like to decide on the filters when using the app.

### Acceptance criteria:
- When the 2nd configuration mentioned [here](https://github.com/avniproject/avni-webapp/issues/1203) is done, then, in mobile app, subject type filter need to work similar to the default subject type filter in MyDashboard:
      - Based on the subject type selected - general encounter types and program need to show
      - Based on the program selected, program encounter types need to show up
- When the 1st configuration, mentioned [here](https://github.com/avniproject/avni-webapp/issues/1203) is done, the above is not applicable since the program and encounter type filters are already configured in 'App Designer'.
      - The card color needs to be of the configured color. Currently for standard report cards we have hardcoded the colors. 
- For both configurations, applied filters need to work on Due and Overdue cards in SRC added to CD. 
- The expectation is both configurations will not be used at the same time.

### Additionally impacted Areas
- Custom Dashboard Filters cache across Landing Page and Dashboards page
- In-general the CustomDashboard functionality and Filter capabilities
- CustomReportCards standard and non-standard with Filters removed and applied both

### Technical details:
Have added the ACs for both configurations in the same card, since its good to have the same code for applying filters for both configurations.

**Comment by petmongrels** [comment]
### Notes
- marked as high risk due to refactoring being done. DashboardFilterCache was storing extra variables that could be computed.
- all custom dashboard caches will be invalidated

**Comment by mahalakshme** [comment]
@petmongrels 
Subject type filters are working very differently between the default custom dashboard and MyDashboard
- In the new default custom dashboard, general encounter types continue to display even after program is selected - which leads to confusion regarding say the no on Overdue visits card
- In the bar on top that displays the applied filters, Program and Encounter type filters displays with | separation instead of showing labels Program, Encounter Type

https://drive.google.com/file/d/1HMH25q-2WQQsPgX_S9iB4jy9jxvK1MWQ/view?usp=drive_link - screenshot link

**Comment by himeshr** [comment]
### Test cases
- Sanity of Custom Dashboards { create / edit dashboard, create / edit sections,  create/edit filters, create/edit reportCards}
- Creation of SubjectType filter on dashboard
- Creation of AsOnDate filter on dashboard
- Creation of Standard report card with SubjectType, Program and EncType filters config
- Creation of Custom Query report card to use Dashboard SubjectType filter
- Primary / Secondary dashboards
- Caching dahboard filters
- Ensure that Config clash of dashboard filter and reportCard config is handled correctly and zero results are returned there
