### ISSUE TITLE
Custom Filter is not working power organisation  

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1384]
**Describe the bug**
Custom Filter is not working power organisation  
login with maha@power
try to filter with location

**To Reproduce**
1. Login with maha@power
3. Apply filter
4. Showing the same result
5. See error

**Expected behavior**
filter value should be shown.

https://github.com/avniproject/avni-client/assets/104890488/9ee266b1-b041-4633-b744-2e57ca57e088

**Comment by mahalakshme** [comment]
@AchalaBelokar what do you mean by not working? are no on standard report cards not refreshing or custom report cards? please add a screen recording to understand the issue better.

**Comment by mahalakshme** [comment]
@AchalaBelokar for custom cards it is not working since the location filter is not used in the report cards query.
