### ISSUE TITLE
Dashboard is not showing the value in jsscp after some time it is showing the value. 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1388]
**Describe the bug**
Dashboard is not showing the value in jsscp after some time it is showing the value. 
it is showing the blank value but after some time it is showing the actual value.

**To Reproduce**
1. Login with maha@jsscp
2. after click on completed 
3. See error

**Expected behavior**
it should be shown actual value.

**Screenshots**

https://github.com/avniproject/avni-client/assets/104890488/5a9a082e-3a0e-4a7d-8f7a-b1a9e54926b4

**Comment by mahalakshme** [comment]
looks like could be related to some of the recent issue fixes made in recent releases on dashboard or some dashboard features we worked on. So moving to Ready

**Comment by 1t5j0y** [comment]
unable to simulate this - with 'dashboard auto refresh' setting  enabled / disabled.
