### ISSUE TITLE
Support BMI for age zscore calculation

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1395]
### Need:
- To calculate the nutritional status of adoloscents, 
- WFA cant be used because of the following reason mentioned by WHO

> Weight-for-age reference data are not available beyond age 10 because this indicator does not distinguish between height and body mass in an age period where many children are experiencing the pubertal growth spurt and may appear as having excess weight (by weight-for-age) when in fact they are just tall.

### AC:
- Use the LMS values provided [here](https://www.who.int/tools/growth-reference-data-for-5to19-years/indicators/bmi-for-age) to calculate the zscore
- Need to use appropriate LMS values for both genders
- Use appropriate formula mentioned [here](https://cdn.who.int/media/docs/default-source/child-growth/growth-reference-5-19-years/computation.pdf?sfvrsn=c2ff6a95_4) - based on whether |z| <= 3 or not
- z-score should have 2 decimal places precision
- BMI value can be calculated by using the existing `calculateBMI` method in `common.js`
- Add appropriate tests

### Some of the test cases:
- check whether able to get nutritional status
- Need to test in webapp and android app
- age < 10, between 10 and 20, more than 20

**Comment by mahalakshme** [comment]
Commits to review is available as part of this card: https://github.com/avniproject/avni-health-modules/issues/3

**Comment by mahalakshme** [comment]
@sachsk I dont see where we are calculating bmi - I see we have made the comparisons based on weight: 
https://github.com/avniproject/avni-health-modules/blob/5328e941fa9c2d23d0a96f9e3d27d78b595fa80d/src/health_modules/adolescent/growthStatusCalculator.js#L31

**Comment by sachsk** [comment]
@mahalakshme  please check this https://github.com/avniproject/avni-health-modules/blob/master/src/health_modules/adolescent/growthStatusCalculator.js

**Comment by mahalakshme** [comment]
@sachsk also default value cant be 3, it needs to be undefined, since we dont know, this is something found on first look, when someone does proper code review they might add more, you can choose to do the fixes accordingly.

**Comment by petmongrels** [comment]
- @sachsk please check with Maha cherry-pick into the right branch, depending on when this should be released
- @mahalakshme @AchalaBelokar the QA for this has to be the implementation team, we have to only release / deploy it. this code is for lack of other options present in the health-modules, but it should be treated as implementation code

**Comment by mahalakshme** [comment]
@sachsk so the below can be done:
- code needs to be in 8.1.0 branch of avni client
- return undefined for those for which we dont ve values
- also make it accessible from avni-client/any other repo as needed

**Comment by mahalakshme** [comment]
@Dinesh2019 move it to in QA once u ve picked up
