### ISSUE TITLE
Remove empty space at bottom of subject types listing page

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1397]
org: cini_uat, env: prod

### Issue:
As you can see in this video, it looks like, School is the last subject type. But there are more subject types. 

https://github.com/avniproject/avni-client/assets/10369963/a4dd0055-86b0-4138-a42c-227890110cbd

### AC:
To avoid this issue, remove the space between School and bottom bar so that more subject types can be shown on the screen.

**Comment by kusumdesai** [comment]
Hey !!!!
Can you please assign this issue to me under GSSoC'24?

**Comment by adamsanadi6** [comment]
![Image](https://github.com/user-attachments/assets/2211ccd9-e897-48a3-8f3b-acb12f4ed003)

**Comment by dinesh2096** [comment]
QA Reference : 

https://github.com/user-attachments/assets/9a8446d2-60d9-4940-8a84-ef65ff2009b0
