### ISSUE TITLE
Clicking on General Encounter FEG Edit button crashes the app

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-client#1400]
**Describe the bug**
Clicking on General Encounter FEG Edit button crashes the app

**To Reproduce**
1. Navigate to any Individual which has a General Encounter
2. Click on any of the Completed General Encounter's  Collapsed pane to view its Observations
3. Click on the "Edit" button specific to a FEG of the encounter
4. App crashes with error "Cannot read property 'editFormRule' of undefined"

**Expected behavior**
We should be able to edit General Encounter from a specific FEG position 

**Screenshots**

https://github.com/avniproject/avni-client/assets/72493481/23c780dc-58e3-4b62-9747-330ad490ebea

**Smartphone:**
 - Device: Genymotion Emulator
 - OS: Android 11
 - Version: 8.0 Prod DEV APK

**Additional context**
This seems to have occurred as regression due to EditFormRule changes done recently.

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing? No
- [ ] Are you mentioning the required scenarios that could be affected? Yes
- Generic testing for following scenarios
  - Create an Encounter, Individual, Enrolment or ProgramEncounter
  - Edit an Encounter, Individual, Enrolment or ProgramEncounter using edit button
  - Edit an Encounter, Individual, Enrolment or ProgramEncounter from a specific FEG position

**Comment by AchalaBelokar** [comment]
- [ ] Login with AchalaB@rwbnitiuat search on work order  and try to edit the general encounter getting the error earlier it is working
- [x] Then I login with beulah@rwbngos2023 serch with work order and try to edit it is working fine
- [ ] tested wit maha@power with creating and editing encounter

**Comment by himeshr** [comment]
@AchalaBelokar The issue reported here 
"Login with AchalaB@rwbnitiuat search on work order and try to edit the general encounter getting the error earlier it is working" is a different issue, but a regression nonetheless.
Will work on fixing it, please continue regression testing across Individual, Program, ProgEnc and Enc Create/Edit/Observation_View/FEG Edit

https://github.com/avniproject/avni-client/assets/72493481/e6a7c5fa-980d-42ea-8a76-3a678a9ca8cb

**Comment by himeshr** [comment]
@AchalaBelokar 
The issue reported in previous comment is caused due to Data issue, for that Individual's encounter.. and is not a regression caused due to editFormRule.
A required Field "Farmer" of type SubjectSelect has a value that doesnot belong to this catchment, resulting in error displaying the details.

**Comment by himeshr** [comment]
We'll show an abnormal color UUID, when SubjectFormElement has Subject which doesnot exist on device.
<img width="751" alt="Screenshot 2024-05-15 at 1 15 00 PM" src="https://github.com/avniproject/avni-client/assets/72493481/e428878b-b062-4156-8a97-517ac5548284">
