### ISSUE TITLE
Dashboards not syncing

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1407]
https://avni.freshdesk.com/a/tickets/4057

### Steps to reproduce:
- Login to mahanew2@apfodisha, 8.0.2 apk
- Go to 'More' and click on 'Dashboards'
- Dashboards are not visible
- All dashboards assigned to the user group 'Poshan Sathi' should have been visible. This was the old behaviour, independent of selection of primary and secondary dashboards.

https://github.com/avniproject/avni-client/assets/10369963/cfc49043-f112-4f4d-9091-d0737f314fd5

- It works as expected with 7.2 version apk [here](https://ap-south-1.console.aws.amazon.com/s3/object/samanvay?region=ap-south-1&bucketType=general&prefix=openchs/2440-c24936c7e24ef5949b81198ba212d0516b721f9e/prod_dev/app-generic-release.apk)

**Comment by AchalaBelokar** [comment]
- [ ] tested with mahanew2@apfodisha it is working fine there.
- [ ] I chose selected only secondary dashboard it is showing me as expected.

**Comment by himeshr** [comment]
Draft release notes: https://github.com/avniproject/avni-product/releases/tag/untagged-3fd80c2442a8fdff4750
