### ISSUE TITLE
Enrolment in the program is failing on apfodishauat on 8.1.0 beta version 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1409]
**Describe the bug**
Enrolment in the program is failing on apfodishauat on 8.1.0 beta version 
8.0 it is working fine there

**To Reproduce**
1. Login with dineshg@apfodishauat
2. register the individual 
3. try to enrol 
4. fill the form
5. See error

**Screenshots**

https://github.com/avniproject/avni-client/assets/104890488/70559992-d89b-4d43-b4df-6af0a3e28f16

### Analysis:
Was unable to find any form level rule or form element group or last form element rule, where this could be an issue. So looks like issue could be with the code.

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by mahalakshme** [comment]
@AchalaBelokar this seems to be because of some rule, so check the logs

**Comment by mahalakshme** [comment]
@1t5j0y ve updated the release of the card to 8.1.1

**Comment by 1t5j0y** [comment]
Unable to simulate this and verified with Achala that it is not happening for her either.
