### ISSUE TITLE
 Filter Taking Time to Load

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1410]
The filter feature in the application is taking an excessive amount of time to load, causing delays in user interactions and reducing overall user experience.

env: prod
org : gvamp_uat
user : dineshg@gvamp_uat

Steps to reproduce 
1.login to the org
2.Click on the filter in the dashboard 

Expected result : The filter should apply immediately or within a reasonable timeframe.
Actual Result : The filter takes a significantly long time to apply.

https://github.com/avniproject/avni-client/assets/127730126/94aa99cd-bb78-4436-9706-7ae6af32ffdb

**Comment by Dinesh2019** [comment]
@maha Compared to the previous version it is fast.

**Comment by mahalakshme** [comment]
@Dinesh2019 because of the below reasons discussed, closing this card:
- issue specific to Goonj since it has more number of locations
- new version faster than old
- Goonj users also might not face this issue since their catchment is at state level and not all states, or just group of districts
