### ISSUE TITLE
Individual registration is not working on staging

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1411]
**Describe the bug**
Individual registration is not working on staging
I login withAchalaB@jsscp and try to register Individual 
it is giving me error  cannot read property level of undefined

**To Reproduce**
1.Login with AchalaB@jsscp
2. Click on register
3. try to regiser

**Expected behavior**
user is able to login the data

**Screenshots**

https://github.com/avniproject/avni-client/assets/104890488/644a1d9e-385e-4403-85f6-8a639cd8752d

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by himeshr** [comment]
Issue was caused due to use of individual with a dummyAddressLevel.
