### ISSUE TITLE
Check if encounter type exists before checking for privilege

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1414]
The application crashes when an individual attempts to enroll in the program

Note : uploaded the database

Env : prod 
org : adsruat
user : dinesh@adsruat
version 8.1.1-7d17a
issue not happening in 8.0, happening in 8.1.1 and 8.1.0

Steps to reproduce : 
1.Login to the org
2.Register the individual
3.Try to enroll the individual to adolescent program

Expected result : The individual should be successfully enrolled in the program without any issues.
Actual result : The app crashes immediately after submitting the enrollment form.

Video References : 

https://github.com/avniproject/avni-client/assets/127730126/f98f7b17-635f-454b-a8d3-b9676fca75eb

**Comment by petmongrels** [comment]
@AchalaBelokar @Dinesh2019 we need to do worklist testing by changing rules and that provides data that is incorrect.
