### ISSUE TITLE
Change the listing text color to black from grey

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1415]
### Need:
In the [mockups](https://drive.google.com/file/d/1V4u4tlpR0o-9Ni567vapnx2sSyVD4233/view) it seems to be black. Having grey color, with the existing dark color bg, makes the text less visible and more card colors need to be changed.

### AC:
Change the card list view text color to black, similar to that of card tile view.
![Image](https://github.com/avniproject/avni-client/assets/10369963/d5855827-267c-4e3c-8af0-0646697d9d9b)

**Comment by himeshr** [comment]
@mahalakshme have kept the description color same for tile and list. Its now set to same value as that was there previously for Tile View. But its not black, its hexcode is #333333.
<img width="412" alt="Screenshot 2024-06-07 at 1 35 56 PM" src="https://github.com/avniproject/avni-client/assets/72493481/a84f815d-05ba-42d3-836e-66dd496fc656">

**Comment by himeshr** [comment]
Minor code change, no code-review required.

**Comment by mahalakshme** [comment]
@himeshr please make it black, with #333333 more card colors(like #3e50b4, #0f6560) need to be changed. I did the checking using [here](https://drive.google.com/file/d/1TtPrAbJ6uOHKlQP28Bb9pbyyndRLxCcs/view?usp=drive_link) and hence suggested black

**Comment by himeshr** [comment]
Set both to be black by default.
<img width="392" alt="Screenshot 2024-06-07 at 2 09 04 PM" src="https://github.com/avniproject/avni-client/assets/72493481/b5b16d8c-baef-4fc5-9a1d-91e408a6de9e">
