### ISSUE TITLE
Filter in MyDashboard not working

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1416]
https://avni.freshdesk.com/a/tickets/4156
https://avni.freshdesk.com/a/tickets/4154

### Steps to reproduce:
- Login with maha@ctrith_iph with latest apk
- Apply address filters in MyDashboard (select one block and village)
- It shows the same results(same as when filters not applied at any address level)
- Address filters in search works for this scenario

### Video of the issue:
https://drive.google.com/file/d/1vSALNFVj59IWYgXzRCacSBqspNsHor9y/view?usp=drive_link

### Analysis:
Could 've broke after [this](https://github.com/avniproject/avni-client/issues/1375) fix. This fix was done for subjects registered at higher levels.

### Expected:
- Subjects to be shown: Only subjects registered at addresses selected in the address filters + subjects registered at levels lower to the lowest address levels selected 
- Similarly for encounters.

**Comment by petmongrels** [comment]
Search/Filter by all selected items and descendants of lowest level items was done this card. #1393

**Comment by mahalakshme** [comment]
@petmongrels that card was only about passing in selected addresses at all address levels in params so that in the custom report card we can filter subjects registered at any level right?

**Comment by petmongrels** [comment]
changed the mydashboard address matching to follow the same method used elsewhere - registered at - all selected and descendants of lowest level selected.

**Comment by himeshr** [comment]
Triggered prerelease and prod apk build for this fix here
https://app.circleci.com/pipelines/github/avniproject/avni-client/2528

**Comment by AchalaBelokar** [comment]
- [ ] Custom dashboard is not working with location I Login with maha@apfodisha try to filter with block Harichandanpur , Gp Badapaspal , village hamlet- Nolla
