### ISSUE TITLE
Dashboard List View issues

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1418]
**Describe the bug**
Arrow is not displayed if the dasboard view list is created as listed and while clicking it is popping up 

**To Reproduce**
1. Login to dinesh@mc
3. change the dashboard which is having the list
4. click on listed item
6. See error

**Expected behavior**
arrow should be clearly visible
Text should not get cut

**Screenshots**

https://github.com/avniproject/avni-client/assets/104890488/bd585d77-95a0-4c7b-aab7-ef463b4a9f25

<img width="516" alt="Screenshot 2024-06-07 at 3 52 46 PM" src="https://github.com/avniproject/avni-client/assets/10369963/29194996-628a-45a3-a02e-fdbf6760e8fb">

### AC:
- Also we have retained the nos to the right, so I think the arrow should be on the extreme right on the numbers. In the mockups since description is towards the right, I think arrow is on it.  But during development if you think arrows on name of the card looks better, we can retain the same. But colour of the arrow needs to be fixed anyways.
- Text(card name) should not get cut (taqim@sncu)
- Place percentage inside brackets like in the mockup [here](https://drive.google.com/file/d/1V4u4tlpR0o-9Ni567vapnx2sSyVD4233/view?usp=sharing)

**Comment by himeshr** [comment]
Done with styling changes as specified in the AC.

https://github.com/avniproject/avni-client/assets/72493481/c11dbdfb-7f4e-4b57-8815-a18d16ed67c6

Secondary values:
<img width="589" alt="Screenshot 2024-06-11 at 12 35 49 PM" src="https://github.com/avniproject/avni-client/assets/72493481/b8b386b5-95fa-4988-a48b-3655ca569370">
<img width="589" alt="Screenshot 2024-06-11 at 12 35 30 PM" src="https://github.com/avniproject/avni-client/assets/72493481/66ab415b-b6bb-49dd-8490-24f9a3adb216">

Error Message:
<img width="590" alt="Screenshot 2024-06-11 at 12 36 22 PM" src="https://github.com/avniproject/avni-client/assets/72493481/b0b76d71-7c5b-46e1-b345-5bf45371721d">
<img width="585" alt="Screenshot 2024-06-11 at 12 36 32 PM" src="https://github.com/avniproject/avni-client/assets/72493481/9aa759b8-1f20-493b-853e-e658321738cb">

**Comment by mahalakshme** [comment]
@AchalaBelokar for text getting cut u can test with Nexus 6 in this card.
