### ISSUE TITLE
Task assignment is not working as per expectation 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1419]
**Describe the bug**
Task assignment is not working as per expectation 
After assigning a task to specific user it is not showing on client
I Login with nupoork@power assign task to nupoork@power but it is not showing 
**To Reproduce**
1. Login with nupoork@power 
2. assign task one new task to nupoork@power
3. see in the client 
4. see the error

**Expected behavior**
the task should be shown to the client 
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by petmongrels** [comment]
This is working for me. One may not have waited for 10 second before syncing.
