### ISSUE TITLE
Selected filters in app, gets vanished after applying after clicking on sync.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/avni-client#1424]
1. Login to Adolescent Sewa Rural production.
2. Apply a few filters and click on apply.
3. Once the filtered results are displayed, click on sync, let the sync complete.
4. Post sync, click on filter again and check the selected filters are removed.

**Comment by mahalakshme** [comment]
not applicable after 10.0 since MyDashboard will be removed
