### ISSUE TITLE
Report card colors to be updated

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1431]
### Need:
- With 9.0 release, the colours of the text in report card are going to become black from white. Hence with some of the existing report card colours, the text will not be visible. So some of the report card colours need to be changed such that it is visible with both black and white text colours since we do graded release and at a point multiple versions of the app will be used by users.

### AC:
- Update the colours for the cards mentioned here:
https://docs.google.com/spreadsheets/d/1299mpA8al5B7nKlh9RjIcMK5Ku2JLuF-JOtKepo20zE/edit#gid=155574426
- Need to be fixed also for the corresponding UAT orgs
- Active live orgs I assumed and hence checked for these: 'JSCS', 'Shelter', 'Goonj', 'Adolescent Sewa Rural', 'Swadhar swayam', 'CTRITH IPH', 'Sakhi App', 'Calcutta Kids', 'Ward Implementation and Management Committee - AKRSP','Periodshala', 'APF Odisha','PoWER', 'Mobile Creches', 'JSS', 'Chashma', 'Yenepoya', 'JSS Singrauli', 'Lend a Hand India', 'JSSCP'. So kindly check for any missed orgs in this list as well.

### Details to identify the card with issues and colour compatibility:

Query used:
```
select dscm.id as dashboard_section_card_mapping_id, o.name as org_name, ds.name as dashboard_section_name, rc.name as report_card_name, rc.colour as report_card_color
from dashboard_section ds
         inner join dashboard_section_card_mapping dscm on ds.id = dscm.dashboard_section_id
         inner join report_card rc on dscm.card_id = rc.id
         inner join organisation o on ds.organisation_id = o.id where
    o.name in ('JSCS', 'Shelter', 'Goonj', 'Adolescent Sewa Rural', 'Swadhar swayam', 'CTRITH IPH', 'Sakhi App', 'Calcutta Kids', 'Ward Implementation and Management Committee - AKRSP','Periodshala', 'APF Odisha','PoWER', 'Mobile Creches', 'JSS', 'Chashma', 'Yenepoya', 'JSS Singrauli', 'Lend a Hand India', 'JSSCP')
                                     and rc.is_voided=false and dscm.is_voided= false and ds.is_voided=false;
```

and used the results in a [HTML](https://drive.google.com/file/d/1uljOCGFSkNbtwmvY1ik56DNG2Cgcq7bk/view?usp=drive_link) to identify colour compatibility

**Comment by petmongrels** [comment]
@1t5j0y we should add this to the Release card for deployment activity?

**Comment by 1t5j0y** [comment]
Added to 9.0 deployment tasks

**Comment by AchalaBelokar** [comment]
- [x] I login with beulah@jsscp check the offline dashboard there are multiple dashboard check with colours .
- [x] I login with maha@goonj check the offline dashboard colours are reflected fine.
- [x] I login with beulah@lahi check the offline dashboard colours are reflected fine.
- [x] I login with maha@chashma working fine there.
