### ISSUE TITLE
Media selection issue with Android APIs for version 13

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1435]
https://avni.freshdesk.com/a/tickets/4160

### Need:
Since some of our users organise their photos in albums to be able to segregate based on work, we need to support selection from albums.

### Issue:
< 13 - we are not supporting multiple selection, >= 13 - we are not supporting selection of media from all albums. 

### AC:
- Media select should support selection of media(image, video, file and audio) from non-default albums (custom)
- Media select should support selection of multiple items at the same time
- The above functionality should work for all versions of Android
- Media select should support selecting content in a consistent manner across media-types and selection(single/multi) criteria

### Technical details
- Android doesn't seem to consider custom folders as albums and hence this issue.
- Try patch fix on react-native-image-picker current library to use Android old APIs like mentioned [here](https://github.com/react-native-image-picker/react-native-image-picker/issues/2073#issuecomment-1371465684). 
- The above fix should be fine since the new API, ACTION_PICK_IMAGES is recommended only to provide better user experience when images/videos alone needs to be selected. So ACTION_GET_CONTENT will be continued to be supported since it can be used to select any kind of content unlike ACTION_PICK_IMAGES.
- Also seems like [EXTRA_PICK_IMAGES_MAX](https://developer.android.com/reference/android/provider/MediaStore.html#EXTRA_PICK_IMAGES_MAX) works with ACTION_PICK_IMAGES. Hence for android > 13 as well if we do the above changes, might need to patch to use EXTRA_ALLOW_MULTIPLE for multi-selection. 
- Additionally use, Intent.ACTION_GET_CONTENT always for selecting media of all types and selection criteria

### Known issues with Emulator
- Capturing Video using Android 13 version of emulator fails with an error, ignore as specified [here](https://github.com/react-native-image-picker/react-native-image-picker/issues/2026#issuecomment-1361511595) 

### Context:
To make the image picker work for android 13 we updated the react-native-image-picker library as part of this commit(648b525c). So the [updated](https://github.com/react-native-image-picker/react-native-image-picker/commit/28aa402da120170caafa2b357ba03b3239e86c9b) library uses [updated Android APIs in versions 13](https://developer.android.com/reference/android/provider/MediaStore.html#ACTION_PICK_IMAGES) and above to access images. And this API seems to have the [issue](https://support.google.com/voice/thread/245164146/not-able-to-access-all-my-photos?hl=en) where it doesn't allow to access images out of default albums for versions >= 13 since may be they are not considered to hold images/video.

### Possible solutions:
1. Use react-native-image-crop-picker where it is still using the old Android APIs - though it is old able to access all albums in android 13 and multiple selection also works for >13 and <= 13.
2. Do a patch fix on react-native-image-picker current library to use Android old APIs like mentioned [here](https://github.com/react-native-image-picker/react-native-image-picker/issues/2073#issuecomment-1371465684)

### Additional:
With respect to accessing photos, Android APIs seems to be in a [transition](https://developer.android.com/about/versions/14/changes/partial-photo-video-access) state

**Comment by himeshr** [comment]
Sample screen recording after fix for future reference..
https://drive.google.com/file/d/1vVwu0oM5WgIhiEUiBZsK59W2OeXUwosP/view?usp=sharing

**Comment by AchalaBelokar** [comment]
- [x] I am using the 11 version of andriod it is not working there.


![Image](https://github.com/avniproject/avni-client/assets/104890488/68edd76d-09e0-4085-beef-e276703ba3f6)


1. Login with maha@goonj fill the activity form
2. After that I started the upload the image multiple images

[Screen Recording 2024-07-04 at 3.17.06 PM.zip](https://github.com/user-attachments/files/16096841/Screen.Recording.2024-07-04.at.3.17.06.PM.zip)

- [x] tested with single selection image on 13 version
1. Login with AchalaBrwbnitiuat
2. serach for workorder edit there are multiselect image and videos 
3. it is not working there.


https://github.com/avniproject/avni-client/assets/104890488/65d39680-40d8-47c9-90fd-23d2b4c4ad73

**Comment by himeshr** [comment]
@AchalaBelokar , the reason why Multi-select test failed for you when editing existing Work-order was that, you had changed the FormElement from single-select to multi-select for Image and Video.

I was able to reproduce this scenario only after performing the aforementioned change in WorkOrder registration form.

This is not a valid test-case, therefore moving the card back to QA Ready.
Please create new FormElements for Multi-select image and Multi-select videos to test the edit and create scenarios.

**Comment by himeshr** [comment]
@AchalaBelokar please use the 9.1 branch pre-release apk for testing this..
https://app.circleci.com/pipelines/github/avniproject/avni-client/2571/workflows/6236914c-44f9-41f1-8669-8d70c5f67f26/jobs/16385/artifacts

**Comment by himeshr** [comment]
### Note regarding multi-select of media content
Android's chooser has Photos and/or Gallery available on some devices. 
Photos allows multiple images to be selected. Gallery allows just one at a time.
But outside these apps, Users are allowed to select multiple items at a shot.
Also, they are able to access all folders on the device.

Above behaviour is consistent across all android version > 5.

**Comment by mahalakshme** [comment]
@himeshr I tested in actual phones - redmi and samsung. I was able to multi-select from gallery. In redmi I was unable to multiselect outside from file manager. Anyways based on this I will reply in a generic way to the client.

**Comment by himeshr** [comment]
Okay, so in-general multi-select is a problem on certain devices in certain views, but we have always been able to select multiple images one at a time, so should be fine.
