### ISSUE TITLE
Being able to apply subject type filter on 'Recent' type cards when part of custom dashboard

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1436]
### AC:
- Similar to https://github.com/avniproject/avni-client/issues/1381
- Should work for standard report cards 'Recent registrations', 'Recent enrolments', 'Recent visits'
- For both configurations, applied subject type based(subject type, program, encounter type, program encounter type) 
filters need to work on the above cards. Additionally in configuration 1, if recent duration filter applied that needs to work with or without configuration 2.
- The filters currently have slightly broken from the expected functionality. When program p and program encounter e filters applied,  
        1. recent registrations card need to show individuals enrolled in p and having encounter e(completed or scheduled) and registered within the selected recent duration - found program filter not working sometimes - unable to reproduce now
        2. recent enrolment card need to show individuals enrolled in p and when their enrolments have encounter e(completed or scheduled) and enrolled in p within the selected recent duration
        3. recent visit card need to show individuals enrolled in p and completed e within the selected recent duration
- The above is just an example. Eg: Multiple program selections, general encounter type filter and other combinations as well need to work
- For configuration 1, the selected colour from the colour picker need to be applied in the mobile app.
- The expectation is both configurations will not be used at the same time. But duration range filter in configuration 1 and custom date filters can be applied simultaneously. Eg: Want to see recent registrations in 6 months but with enrolment date range in last 2 days. This is the existing functionality(since date range filters work with recent 24 hours) and we are just retaining it.

### Reason for keeping this as separate card inspite of what discussed:
- Because of existing above issues
- To ease testing for developers and QA
- as per INVEST principle

**Comment by petmongrels** [comment]
Please see - #1437 for commits

**Comment by AchalaBelokar** [comment]
- [ ] due visit is not showing in while creating standard report card.
Login with jsscp and then try to create a card with due visits
![Image](https://github.com/user-attachments/assets/123f2755-a59c-4fc0-a1a9-ae941435d966)

**Comment by mahalakshme** [comment]
@AchalaBelokar scheduledVisits is the due Visits - if this is confusing we can deal with it later(create a separate card) - not within the scope for 10.0

**Comment by AchalaBelokar** [comment]
- [ ] I created a standard dashboard with due and overdue visit and apply filter o that that both filter and card is not working for phulwari.

**Comment by AchalaBelokar** [comment]
- [x] Recent Registration is working fine.
- [ ] Recent Enrolment is not working
Login with maha@jsscp then create individual Tina Min  which is enrol in child I created a recent enrolment card but it is not refelecte there![Image](https://github.com/user-attachments/assets/57416a47-936e-452a-a81a-8ed2149d0727)
![Image](https://github.com/user-attachments/assets/a5691283-4e62-4dc8-af04-b0f93d290133)

**Comment by petmongrels** [comment]
Please test once after setting the right date and time in your device.

**Comment by AchalaBelokar** [comment]
- [ ] I created a user with name ACH TestAch which is not reflecting any card on custom dashboard I sync 2,3 time ..on my dashboard card it is reflecting. Login with maha@jsscp card is RecentIndiviual
- [ ] I tested on my personal mobile
