### ISSUE TITLE
Abnormal flag when set via rule, doesn't show up in red

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#1438]
**Describe the bug**
- There is an existing feature to display a value in red colour if required in the Program Summary. Currently its broken.
- When set abnormal via rule it is not working.
- Not working in 7.2 itself.

**To Reproduce**
1. Go to a program summary rule
2. Add an observation from the program to display it this way (set - isAbnormal -true)
3. `summaries.push({name: "HB values", value: value, abnormal: isAbnormal})`
4. Save and sync the app, check the program summary
5. The value isn't displayed in red as expected

**Screenshots**

![Image](https://github.com/avniproject/avni-client/assets/37863085/acd645c4-e019-42f3-998b-bedc62ebb5a8)

**Need to fix the issue**
Though we have new ways to set abnormal value via UI, from a product perspective, flexibility to set abnormal via rules is helpful for many cases.

**Technical details**
- https://github.com/avniproject/avni-models/blob/86f72cfc54af542c3d1012d96f9519a88a708931/src/Observation.js#L155 - From the code, it is clear we have supported it before

**Additional AC**
Add about this way of being able to mark from rule in readme

**Comment by pkundu** [comment]
@mahalakshme we can go live without this. But a good one to fix
