### ISSUE TITLE
Unable to go to Summary page

### ISSUE THREAD

**Issue by BEULAHEVANJALIN** [avniproject/avni-client#1439]
https://avni.freshdesk.com/a/tickets/4212

**Describe the bug**
When clicking the summary button in an encounter form (dispatch receipt encounter in Goonj), the RuleService continuously tries to load rules (such as ViewFilter, Validation, Decision) for the dispatch receipt form `57bb2d3a-f8a5-4405-8d2c-514456e91533`, leading to an infinite loop.

![Screen Recording 2024-06-25 at 5 45 39 PM](https://github.com/avniproject/avni-client/assets/44082588/5c9d8925-d950-4137-86ee-d927602f6e66)
https://drive.google.com/file/d/1kRN9QYB9dpfIMSNo8rwYiYdKKRJ0OiJb/view?usp=drive_link

**Expected behavior**
The rules associated with the dispatch receipt form should load once and then allow the user to proceed to the summary page. 

**Additional context**
Have tried in 8.1 and 7.0
I also tried it in dummy org where it worked fine. 
Also tested it with different concept types like question group with repeatable fields. It's working fine there.

**Error message**
```
DEBUG  [10:47:09:823] [IndividualEncounterView::AC][Debug] Dispatching action: "EA.SUMMARY_PAGE"
DEBUG  [10:47:09:834] [RuleService][Debug] Getting Rules of Type ViewFilter for Form - Dispatch receipt form 57bb2d3a-f8a5-4405-8d2c-514456e91533
DEBUG  [10:47:09:931] [RuleService][Debug] Getting Rules of Type ViewFilter for Form - Dispatch receipt form 57bb2d3a-f8a5-4405-8d2c-514456e91533
DEBUG  [10:47:10:000] [RuleService][Debug] Getting Rules of Type ViewFilter for Form - Dispatch receipt form 57bb2d3a-f8a5-4405-8d2c-514456e91533
DEBUG  [10:47:10:002] [No form elements here. Moving to next screen][Debug] undefined
DEBUG  [10:47:10:004] [RuleService][Debug] Getting Rules of Type ViewFilter for Form - Dispatch receipt form 57bb2d3a-f8a5-4405-8d2c-514456e91533
DEBUG  [10:47:10:093] [RuleService][Debug] Getting Rules of Type Validation for Form - Dispatch receipt form 57bb2d3a-f8a5-4405-8d2c-514456e91533
DEBUG  [10:47:10:095] [RuleService][Debug] Getting Rules of Type Decision for Form - Dispatch receipt form 57bb2d3a-f8a5-4405-8d2c-514456e91533
DEBUG  [10:47:10:095] [RuleEvaluationService][Debug] {"enrolmentDecisions":[],"encounterDecisions":[],"registrationDecisions":[]}
DEBUG  [10:47:10:099] [RuleService][Debug] Getting Rules of Type VisitSchedule for Form - Dispatch receipt form 57bb2d3a-f8a5-4405-8d2c-514456e91533
DEBUG  [10:47:10:099] [RuleEvaluationService - Next Visits][Debug] []
DEBUG  [10:47:10:101] [TypedTransition][Debug] Route size: 4. To: /SystemRecommendationView Param Keys: {"form":{"that":BELOW_DEPTH},"decisions":{"enrolmentDecisions":BELOW_DEPTH,"encounterDecisions":BELOW_DEPTH,"registrationDecisions":BELOW_DEPTH},"individual":{"that":BELOW_DEPTH},"saveActionName":"EA.SAVE","onSaveCallback":function onSaveCallback(a0) { [bytecode] },"observations":[BELOW_DEPTH,BELOW_DEPTH,BELOW_DEPTH],"validationErrors":[],"headerMessage":"Dispatch receipt - Summary & Recommendations","checklists":[],"nextScheduledVisits":[],"message":"Dispatch receipt Encounter Saved","workListState":{"workLists":BELOW_DEPTH,"getParametersFn":BELOW_DEPTH},"isSaveDraftOn":false,"isRejectedEntity":undefined,"entityApprovalStatus":undefined,"onPreviousCallback":undefined,"affiliatedGroups":{}}
```

**Comment by petmongrels** [comment]
not reproducible on 9.x

**Comment by mahalakshme** [comment]
@petmongrels I am able to reproduce the issue - tried with the same encounter as in the ticket 

### Steps to reproduce: 
- 9.0.2 apk, prod env, maha@goonj,
- Open the dispatch with name "2024/KER/ACC-30007/KER/494"
- Click on edit of the completed encounter
- Click on Summary button on top right

### Screenshot:
![Image](https://github.com/avniproject/avni-client/assets/10369963/0ded1649-de19-4b89-85f2-b0b591e7cc3c)

### Screen recording:
https://drive.google.com/file/d/13K-jrguVVBqCruWPH9vfwCOAUOvyQUcM/view?usp=drive_link
