### ISSUE TITLE
After completing the encounter on web app it is not reflected on client 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1442]
**Describe the bug**

In lahi orgnisation I login with dinesh@lahi then I  register the karigar batch on client with the name Test Ach and then assign it to dinesh user after assignment I fill the attendance encounter on client and then check it on web app it is reflected and then I fill the next attendance encounter on web app and then check on client it is not showing the 2 encounter completed

**To Reproduce**
1. Login with dinesh@lahi 
2. create a karigar batch group on client
3. then login with dinesh@lahi on web app and assign this batch to the dinesh user
4. fill the attendance encounter on client 
5. checked weather it is appear on web app
6. fill the encounter on web app and checked it is appear or not
7. Currently it is not appearing on client

**Expected behavior**
all encounter with same batch name will appear on web app as well as on client.

**Screenshots**
![Screenshot 2024-06-26 at 11 45 10 PM](https://github.com/avniproject/avni-client/assets/104890488/dabc0949-802b-482a-b3b0-7ae5b2900454)
<img width="322" alt="Screenshot 2024-06-26 at 11 48 46 PM" src="https://github.com/avniproject/avni-client/assets/104890488/a285fa0e-7886-4471-aeb0-cb81ecb2fd47">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by mahalakshme** [comment]
@AchalaBelokar can u try now and check - is the time in mobile app current - it has 10 secs delay

**Comment by mahalakshme** [comment]
not an issue

**Comment by mahalakshme** [comment]
not an issue
