### ISSUE TITLE
MyDashboard queries are done even when the primary dashboard is a custom dashboard.

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#1443]
These queries are done when the users goes to Home and on startup. Also check opening custom dashboard filter and then apply.

### Analysis:
check if relevant after 10.0

**Comment by mahalakshme** [comment]
@petmongrels this: https://github.com/avniproject/avni-client/issues/1443 is one of the rootcauses for this: https://avni.freshdesk.com/a/tickets/4247 is it?

**Comment by mahalakshme** [comment]
will not be relevant after 10.0
