### ISSUE TITLE
[Documentation] Translation for keys with dynamic values

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1444]
We have uploaded the translation in the lokalise for some sentence we have translation but not displayed in the cilent app.

Env : prod 
org : apfodisha
user : dinesh@apfodisha

Steps to reproduce : 

1.Upload the bundle in the lokalise 
2.Login to the cilent app 
3.Change the language to odisa
4.enroll the pregancy program 
5.Under the weight give the value as 100

Expected  : error should be displayed in the odisha language 
Actual : still displays in english

Refer screenshot : 

<img width="468" alt="Screenshot 2024-06-28 at 12 12 49 PM" src="https://github.com/avniproject/avni-client/assets/127730126/363fb4e3-d1ab-4f5d-9692-de5258ece297">

file uploaded in lokalise : 

[no_filename.json](https://github.com/user-attachments/files/16025410/no_filename.json)

form details : 
[Pending for translation.xlsx](https://github.com/user-attachments/files/16025498/Pending.for.translation.xlsx)

### Root cause:
Its because the above kind of messages which can have dynamic values, doesn't need translation for each msg. Instead the generic keys needs translations: ```numberAboveHiAbsolute``` and ```numberBelowLowAbsolute```

### AC:
- Move the readme [here](https://docs.google.com/document/d/1jA2dcfQhENge3qN-QEMT9fNYrPz14qHRSgBVGG9mkmg/edit#heading=h.2ovuxygeq3qi) to under 'End User Guide'
- Add steps on how to translate keys with dynamic values, Eg keys: numberAboveHiAbsolute and enrolmentSavedMsg
- Delete the contents [here](https://avni.readme.io/docs/translation-management) and add a redirection link to the new above page since the users might have the link of the old page still. 

### Analysis note:
I understand the difficulty of moving documentation from docs to readme. It was so because of a different process agreed with other teams. Going forward we can update directly in readme.

**Comment by mahalakshme** [comment]
@Dinesh2019 also mention the form name, steps to reproduce the issue. 

I dont see trnaslation for 'should be 90, or less than 90' in the json file. Is the error message dynamically generated? from some rule?

**Comment by AnjaliBhagabati** [comment]
@mahalakshme this issue is happening will all the translations mentioned as not yet in this sheet in column "
[Uploading Pending for translation.xlsx…]()
F"

**Comment by AnjaliBhagabati** [comment]
@mahalakshme here is the json file
[Uploading or1.json…]()

**Comment by mahalakshme** [comment]
It will work when translations added for keys: numberBelowLowAbsolute and numberAboveHiAbsolute

**Comment by himeshr** [comment]
- configured the path old "/translation-management" to point to new page under Section "End User Guide"
- Have hidden the old translations path, which is now available at "/translation-management-old"
- Added a section on translating keys with placeholders
