### ISSUE TITLE
getAll() does not allow multiple scheduled visits of same encounter type at a time

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#1446]
**Describe the bug**
It is not possible to schedule multiple visits of the same encounter type simultaneously. If one visit is already scheduled, any subsequent scheduled visits will override it.

**To Reproduce**
1. Go to an Encounter A
2. Add a visit scheduling logic under Encounter A to schedule visit of encounter type AB, complete encounter A in the app and see that visit AB is scheduled 
3. Go to an Encounter B
4. Add a visit scheduling logic under Encounter B to schedule visit of encounter type AB (u can assign a different visit name, say-  AB 2) , complete this encounter B 
5. As soon as encounter B is completed, the visit AB already scheduled is overridden by the AB 2

**Expected behavior**
return scheduleBuilder.getAll(); should allow to schedule same encounter type visits simultaneously irrespective of their name or dates.

**Screenshots**

https://github.com/avniproject/avni-client/assets/37863085/d535c282-5395-434a-b45f-93db4a75c499

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by mahalakshme** [comment]
@nupoorkhandelwal try https://avni.readme.io/docs/writing-rules#using-the-createnew-visit-strategy and reopen the card if the issue still persist
