### ISSUE TITLE
App must target Android 14 (API level 34) or higher, required for Avni and Gramin apps

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-client#1455]
### Motivation
Motivation: Won't be able to release app updates after aug 31, for Avni and Gramin
Deadline: Aug 31, 2024
Violation: App must target Android 14 (API level 34) or higher
Details: To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements.
From Aug 31, 2024, if your target API level is not within 1 year of the latest Android release, you won't be able to update your app.

https://play.google.com/console/developers/7316254808379559958/app/4974885142174090692/policy-center/issues/4989128963434203636/details

Android 14 Behavior Changes - https://developer.android.com/about/versions/14/behavior-changes-14

### Acceptance Criteria
Avni and Gramin APKs should target Android 14 (API level 34) or higher

**Comment by 1t5j0y** [comment]
- Changing only targetSdk to 34 caused app to not launch on Android 14 while it worked on lower versions.
- Also changed compileSdk 34 which required an upgrade to gradle 8. https://developer.android.com/build/releases/gradle-plugin#api-level-support
- Gradle 8 uses Java 17
- Tried Android Studio AGP Upgrade Assistant which gave up half way
- Specific changes in the commit message

**Comment by AchalaBelokar** [comment]
- [x] tested with calutta kids maha@calcutta_kids vaccination, general encounter,  program encounter, enrolment .
- [ ] tested with rwbnituat which contain approval scenario tested with that general encounter , video uploading and image uploading and check on media viewer 
- [ ] Login with dinesh@apfodisha-custom dashboard is working fine
