### ISSUE TITLE
[Clearer error message] Catchment not found

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1460]
https://avni.freshdesk.com/a/tickets/3443

### Issue
version 9.0, prerelease
do not assign a catchment to a user. and sync in mobile app, and see the unreadable error message(exception stacktrace)

https://github.com/user-attachments/assets/4795af07-f5ee-436e-a11a-4e3754e0df1a

### AC:
- Display error message stating, 'Contact administrator to configure a catchment for your login to proceed further.'
- The heading in the error message box 'Sync Failed' can be retained
- The error messages should be supported in languages: English, Gujarati, Hindi, Kannada, Marathi, Tamil without the need for configuring the translations at the implementation level.

#### Reasons to do the above:
- Though we might soon also add validation on User page to add catchment and sync attributes, for existing users without catchment it can still fail 
- anyways above restriction on User page needs more thought(though restriction is there via CSV upload) since for users like API users, sync configuration might not be relevant and might lead to confusion.

**Comment by dinesh2096** [comment]
When we change the language of the users the error still display in English language 

env : staging 
org : Test dashseven
user : dinesh@dashseven


QA Reference : 


[Click here to watch video](https://drive.google.com/file/d/1hSr4LJ1GDgS1frYopxTSLjS0RqIM5Xzx/view?usp=drive_link)

**Comment by 1t5j0y** [comment]
We can't show error message in other language in this scenario since the translations have not synced either due to this failure. Can test if error message is shown in other languages after at least one successful sync happens and then removing the catchment from the user.

**Comment by dinesh2096** [comment]
QA Reference : 

[Click here to watch the video](https://drive.google.com/file/d/1s-7C7bm2erm6Fes8pwIaRICi8LmVndov/view?usp=drive_link)
