### ISSUE TITLE
Display of filters on custom dashboard

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1463]
### Issue:
There have been many changes in caching of results, filters, addition of custom filters - the display of filters on custom dashboard is working currently.

### Technical details
The filters are available from the cache directly and its modifications are reflected in cache on apply. The flters values are in model objects. The display of filters should display it from this.

**Comment by petmongrels** [comment]
### Tasks
- Filter update, not showing the updated value in display (done)
- Wrapping of long text (done)
