### ISSUE TITLE
Encounter Eligibility Check Rule is not working

### ISSUE THREAD

**Issue by vedfordev** [avniproject/avni-client#1464]
**Describe the bug**
When returned false from an encounter eligibility check rule, it still shows up the encounter.

**rule :**
```js
//SAMPLE RULE EXAMPLE
'use strict';
({params, imports}) => {
  const individual = params.entity;
  return false;
};
``` 

**To Reproduce**
prod env, 9.0
1. Add the above rule in child followup encounter of org 'JNPCT Adoloscent UAT' 
2. use user **dinesh@adjnpctuat**
3. search for individual **test01 july17**
4. see that it shows child followup

**Expected behaviour**
encounter eligibility rule should work properly

**Screenshots**
<img width="549" alt="Screenshot 2024-07-17 at 11 56 12 AM" src="https://github.com/user-attachments/assets/c4405a5d-c62f-4f61-96d4-2edf4caad6fb">

**Analysis notes:**
Related card in implementation: avniproject/jnpct-adolescent#54 

### AC:
should see what to do to avoid confusion, since the visit button is generally used for unplanned visit.

### Analysis:
Its evident that the scheduled encounter is what will get filled, since on clicking 'New Program Visit' as well, we show both planned and unplanned encounters. So no need any improvements.

**Comment by mahalakshme** [comment]
not a bug since looks like on clicking the button it fills the planned encounter
