### ISSUE TITLE
Vaccination details is not update as expected in the new version 9.0 

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1466]
when we applied the dates for vaccination so vaccination are not getting updated as expected 

env : prod
org : ck
user : dinesh@ck_uat

steps to reproduce : 

1.Login to the app
2.Register the individual
3.Pentavalent- 2 vaccinations shows as 75 days added at the age of the child)

expected  : vaccination needs to be displayed 
Actaul : vaccination is not displayed 

Refer video : 

https://github.com/user-attachments/assets/bf8a425e-209b-42f6-ae4b-40512a72cdc0

### Analysis:
Checklist rule, db values everything seems to be correct. May be we are not displaying all the Due items because of styling or something.

**Comment by 1t5j0y** [comment]
Unable to simulate in 9.0.2 (downloaded from play store) or 9.1 with the same credentials.

**Comment by mahalakshme** [comment]
@Dinesh2019 check the above comment and do the needful.

**Comment by Dinesh2019** [comment]
@mahalakshme unable to reproduce it.. so closing the card
