### ISSUE TITLE
Unable to build apk due to missing dependency

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-client#1469]
**Describe the bug**
Unable to build avni-client apk due to missing dependency.
Failing circleCI [job](https://app.circleci.com/pipelines/github/avniproject/avni-client/2588/workflows/04c8797d-29d3-44bc-8c2d-6cf5fde2d9bc/jobs/16519)
```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.yqritc:android-scalablevideoview:1.0.4.
Searched in the following locations:
  - file:/home/circleci/.m2/repository/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
  - https://dl.google.com/dl/android/maven2/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
  - https://repo.maven.apache.org/maven2/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
  - file:/home/circleci/avni-client/packages/openchs-android/node_modules/react-native/android/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
  - file:/home/circleci/avni-client/packages/openchs-android/node_modules/jsc-android/dist/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
  - https://jitpack.io/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
  - https://maven.google.com/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
  - https://dl.google.com/dl/android/maven2/index.html/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
  - https://repo1.maven.org/maven2/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
  - https://plugins.gradle.org/m2/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
  - https://oss.sonatype.org/content/repositories/snapshots/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
  - https://www.jitpack.io/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
Required by:
    project :app > project :react-native-video

```

**Additional context**
Fix has been made in a later version >=6.0.0, so upgrading to it seems the best way forward.

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [x] Does the fix require extensive regression testing? No
- [x] Are you mentioning the required scenarios that could be affected? Yes
- - Play video on avni-client in Observations summary screen 
- - Play Videos in "Menu" -> "Videos" section

**Comment by himeshr** [comment]
Completed dev testing using staging apk.
https://output.circle-artifacts.com/output/job/5a386b5d-7f82-4544-b00e-be647c9341cb/artifacts/0/generic-staging_dev-50f8a107a71f9b5dba9f6ded4c05bb6783229f94.apk

On emulator playback of video within avni doesnot work well, but the same was fine on device.

**Comment by AchalaBelokar** [comment]
- [x] Login with AchalaB@rwbnitiuat created a workorder AA 00 VJ which is having video recording .. in summary page it is working fine
- [ ] Then I am search for workorder which is already present and see the summary page and try to play the video which is not working.


https://github.com/user-attachments/assets/4ded3fb0-09d2-463b-9502-d7e2719767f1
