### ISSUE TITLE
After clicking on vaccination app is showing the message app will restart now..

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1471]
**Describe the bug**
Login with maha@calcutta_kids on prerelease
then I search the individual  with name chfirst chlast
click on vaccination see the error
App will restart niw 
cannot read property ' completed' of undefined
apk for this is here 

**To Reproduce**
1. Login maha@calcutta_kids 
2. search the individual with name chfirst chlast
3.  Click on 'vaccinations'

**Expected behavior**
Vaccination list should be visible 
**Screenshots**
https://github.com/user-attachments/assets/fc8e37ca-9570-4b8a-8093-0d8cf4affe8c

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by petmongrels** [comment]
Vaccination should be tested on prerelease for calcutta kids. The schedule has been changed but the checklist item has not be migrated yet as per the new schedule.
lets test for another organisation
