### ISSUE TITLE
Calcutta kids vaccination issue

### ISSUE THREAD

**Issue by vedfordev** [avniproject/avni-client#1472]
**Describe the bug**
Dependent condition on vaccine, where it was applicable is not working currently in production. 
This issue was reported today. The client has shared two reports 
Immunization Due List as on July 1st in which dependency condition is working fine
Immunization Due List as on July 30th dependency logic not working, link shared below

July 1st report,

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'CK Reports on Metabase'
2. Click on 'Immunization Due List'
4. See error, dependency on applicable vaccine is removed

**Expected behaviour**
Dependent vaccine should work as it was working before. 

**Screenshots**
[Immunization Due List as on July 1st ](https://docs.google.com/spreadsheets/d/1K8ANqiojXa9LnT2GHqhVtsiVeAhwwU16/edit?gid=605068405#gid=605068405)in which dependency condition is working fine
[Immunization Due List as on July 30th ](https://docs.google.com/spreadsheets/d/1nVL6HBtVwF6B-HRusQQ5SIasVE2rYhJ2/edit?gid=1446854652#gid=1446854652)dependency logic not working

**Comment by mahalakshme** [comment]
duplicate
