### ISSUE TITLE
[Clearer error message] Bad gateway

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1475]
### Issue:
When we deploy server or when server goes down, the user sees the below error message in mobile app:

![Image](https://github.com/user-attachments/assets/02b7ab54-a8bc-4e81-b0e4-edbdf5c2783d)

### AC:
- Display error message stating, 'Server under maintenance. Please try again after sometime'
- The heading in the error message box 'Sync Failed' can be retained
- The error messages should be supported in languages: English, Gujarati, Hindi, Kannada, Marathi, Tamil without the need for configuring the translations at the implementation level.

**Comment by 1t5j0y** [comment]
Testing notes: Server will need to be stopped to test this.

**Comment by dinesh2096** [comment]
- [ ] when the server is down and user did the fresh sync or logging for the first time then the app stuck in the app logo itself 

QA Reference : 

[Click here to watch the video](https://drive.google.com/file/d/1kT4RuFR-IEvfA9gNyhD1S3GEpoUTz7Hh/view?usp=drive_link)

**Comment by dinesh2096** [comment]
@joy can we change the error message as Server under maintenance. Please try again after sometime when user download the app while the server is down currently we are showing as server unavailable 

QA References : 

<img width="473" alt="Screenshot 2024-11-01 at 4 05 28 PM" src="https://github.com/user-attachments/assets/18128650-5d5d-4ace-aaf9-3890f0e87dc3">

**Comment by dinesh2096** [comment]
QA Reference : 

[Click here to watch the video](https://drive.google.com/file/d/19n9VkNoUlJSPugbgpYPOYjDL1M7bWSlp/view?usp=drive_link)
