### ISSUE TITLE
Sync is not completed for media audio 

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1477]
we add the media file and if we done sync media file is not synced 

env : prod 
org : Testdin
User : dinesh@Testdin

Steps to reproduce : 

1.Login to the app
2.Add the media file 
3.click on the sync 

Expected Result : Sync should be completed 
Actual Result : Sync is not completed.

[Click here to watch video](https://drive.google.com/file/d/1sX4hBjXsbLnZ-u8choF1fxg4naxHvqVp/view?usp=drive_link)

**Comment by mahalakshme** [comment]
@Dinesh2019 is this issue happening now in prod as well?

**Comment by 1t5j0y** [comment]
Issue specific to >= Android 13.
https://github.com/hyochan/react-native-audio-recorder-player/issues/497

Upgraded library to fix the issue.

Testing note: Additional regression test in Android 12 or lower.

**Comment by Dinesh2019** [comment]
- [ ] When we try to validate the data in the media viewer of the web app the page is loading in the staging environment.

Refer video : 

[Click here to watch video](https://drive.google.com/file/d/1Gbvsb-CXuDaYJqOvxN9kLz6Ogl4sd23b/view?usp=drive_link)

**Comment by dinesh2096** [comment]
QA Reference video : 

[Click here to watch video](https://drive.google.com/file/d/1TNUwog0ku6MT1VtElK64x5X9nREHWYAp/view?usp=drive_link)
