### ISSUE TITLE
myUserGroups param shows all user groups

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1483]
### Issue:
The logged in user belongs to only 2 user groups. But params.myUserGroups displays all the user groups

![Image](https://github.com/user-attachments/assets/7ab2aff8-f541-48be-9bf9-f17970f1bd0c)

### Steps to reproduce:
You can try to access the user groups from a rule like below:

<img width="1319" alt="Screenshot 2024-09-05 at 10 30 51 AM" src="https://github.com/user-attachments/assets/da217c2e-97f7-4b51-ad04-bc73dd3b038b">

### Technical reason:
Looks like we are accessing `Groups` table in realmdb instead of `MyGroups` from realmdb

**Comment by mahalakshme** [comment]
@himeshr applies to all rules that executes in mobile app. Forgot to add this.

**Comment by himeshr** [comment]
After discussion, concluded that we'll not provide any additional info regarding privileges that are granted to the user as part of UserGroups that the user is associated with.
The entity type for params.myUserGroups is now https://github.com/avniproject/avni-models/blob/master/src/MyGroups.js

**Comment by himeshr** [comment]
Dev testing screen recording: https://drive.google.com/file/d/1lL1Hq_D8mpCfaiwq3yvgq8GGqSOGvbuG/view?usp=sharing

**Comment by Dinesh2019** [comment]
- [ ] Getting the below error for all org in the pre-release 

org : akrsp
user : dinesh@akrspuat

org : teststatus
user : dinesh@teststatus



![Image](https://github.com/user-attachments/assets/dd64a9b2-f7df-434b-b295-5c34422eaa78)

**Comment by 1t5j0y** [comment]
Moved back to QA ready as login is working fine on prerelease apk
