### ISSUE TITLE
Release 9.4.0 client

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1484]
### As is:
- Webapp and server already released for an another issue

### AC:
- This is to release mobile app for the urgent issue related to userGroups access
- Merge branches, add tags as necessary to 10.0 and master branches
- Update release notes in avni-product repo for 9.4.0 release

**Comment by vedfordev** [comment]
1. As per 9.x release add versionCode=94000 and merged 9.4 into 10.0 and master.
2. There is no update in release notes

**Comment by vedfordev** [comment]
@mahalakshme  still, apk is in review. So, unable to rollout for 5%

**Comment by vedfordev** [comment]
rolled out to 5% of user

**Comment by vedfordev** [comment]
20% rolled out done

**Comment by mahalakshme** [comment]
@vedfordev can we promote this to 100% now? any reason why it was not done?

**Comment by vedfordev** [comment]
100% rolled out done

**Comment by vedfordev** [comment]
@mahalakshme closing this card.
