### ISSUE TITLE
On old client 9.4 filter is not working 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1488]
**Describe the bug**
Login with AchalaB@shelteruat and apply filter on the client
it is showing the error Cannot read property 'concept' of undefined

"09-09 16:26:07.117  3860  4154 I ReactNativeJS: 'AvniErrorBoundary', 'render'
09-09 16:26:07.117  3860  4154 I ReactNativeJS: 'UnhandledErrorView', '{""userMessage"":""Cannot read property \'concept\' of undefined"",""reportingText"":""Cannot read property \'concept\' of undefined\nat render (address at index.android.bundle:1:4211468)\nat finishClassComponent (address at index.android.bundle:1:367154)\nat updateClassComponent (address at index.android.bundle:1:367015)\nat beginWork$1 (address at index.android.bundle:1:399333)\nat performUnitOfWork (address at index.android.bundle:1:386384)\nat workLoopSync (address at index.android.bundle:1:386286)\nat renderRootSync (address at index.android.bundle:1:386170)\nat performSyncWorkOnRoot (address at index.android.bundle:1:383653)\nat flushSyncCallbacks (address at index.android.bundle:1:348683)\nat batchedUpdatesImpl (address at index.android.bundle:1:400107)\nat batchedUpdates (address at index.android.bundle:1:341540)\nat _receiveRootNodeIDEvent (address at index.android.bundle:1:341813)\nat receiveTouches (address at index.android.bundle:1:394963)\nat apply ((native)::)\nat __callFunction (address at index.android.bundle:1:97655)\nat anonymous (address at index.android.bundle:1:96148)\nat __guard (address at index.android.bundle:1:97088)\nat callFunctionReturnFlushedQueue (address at index.android.bundle:1:96106)""}'
09-09 16:26:07.117  3860  4154 I ReactNativeJS: 'ErrorDisplay', 'render', undefined
09-09 16:26:07.119  3860  4154 D ReactNativeJS: [4:26:07:118] [ErrorHandler][Debug] TypeError: Cannot read property 'concept' of undefined
09-09 16:26:07.119  3860  4154 D ReactNativeJS:
09-09 16:26:07.119  3860  4154 D ReactNativeJS: This error is located at:
09-09 16:26:07.119  3860  4154 D ReactNativeJS:     in ObservationBasedFilterView"

**To Reproduce**
1. Login with  AchalaB@shelteruat
2. home page there is filter
3. Click on that filter 
4. you can see the error message 

**Expected behavior**
filter should work properly ..

**Screenshots**

https://github.com/user-attachments/assets/59a6f1de-0f6a-4215-ab51-6c90245bb230

**Comment by mahalakshme** [comment]
this is duplicate
