### ISSUE TITLE
On 9.4 version of apk applied filter name is not showing on custom dashboard

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1489]
**Describe the bug**
On 9.4 version of apk applied filter is not working.
on setting Household filter on household Count Custom Dashboard, AppliedFilter veiw does not show selected household name.
Works on new client.

**To Reproduce**
1. Login AchalaB@shelteruat
2. click on more
3. select household dashboard
4. apply the filter 
5. applied filter is not showing on dashboard
**Expected behavior**
which filter is applied should be shown on dashboard.

**Screenshots**
![household count](https://github.com/user-attachments/assets/b31b930d-ce55-4173-898a-b0ad490af78d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by mahalakshme** [comment]
will check this after filter sync issue is fixed - blocker

**Comment by mahalakshme** [comment]
No need to fix since it works from 10.0 and in 9.4 even before it was not working
