### ISSUE TITLE
Due and overdue visit is not showing on dashboard card.

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1490]
**Describe the bug**
mahanew2@apfodisha, I configure a overdue visits report card with filters - Child Program and Growth Monitoring Visit encounter type - But in mobile app on clicking the report card it shows children with 'Child followup' overdue as well - also the child doesn't ve a single Growth Monitoring visit  - this is how it shows in MyDashboard as well 

**To Reproduce**
1. Login with mahanew2apfodisha 
2. configure overdue and due visit on report card of child program and growth monitoring visit 
3. but on clicking on app it is showing child follow up visit 

**Expected behavior**
Dashboard should show only configure data.

**Screenshots**
https://drive.google.com/file/d/1yFQ7JkYc2zgWgKVUqKp0bb02Ii--7A3A/view?usp=drive_link

**Comment by mahalakshme** [comment]
@AchalaBelokar not a bug, 'Child followup' viist is still of 'Growth monitoring' encounter type
