### ISSUE TITLE
The total count is not shown at the top of the newly created card on the dashboard 

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1496]
The total count is not displayed for the new card created in the dashboard

env: pre-release
org : apfodisha

steps to reproduce :

1.Login to cilent app
2.click on the more
3.Click on the dashboard
4.go the din dashboard which created recently

Excpeted result : count should be displayed - Before it used to show 40 matching results ie., with count
Actual result : count is not displayed

Screenshot: https://drive.google.com/file/d/1WyO43AQ-hpnoF1UBerqBWLD0Orcw739k/view?usp=drive_link

**Comment by himeshr** [comment]
Sample screenshots:

<img width="589" alt="Screenshot 2024-09-16 at 10 17 16 AM" src="https://github.com/user-attachments/assets/85a7f0c3-ee7a-4c05-a982-69622f0b6acb">

<img width="589" alt="Screenshot 2024-09-16 at 10 18 42 AM" src="https://github.com/user-attachments/assets/b98302a3-4ab6-4180-bf95-4001a16b29f6">
