### ISSUE TITLE
New filters not getting synced

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1497]
### Issue:
- Login to maha@shelteruat
- I added filter 'something' on 'Sanitation Program' custom dashboard 
- On 9.4 apk it is not showing on going to More -> Dashboards -> Sanitation Program -> clicking filter icon

### Analysis:
- Not time issue - emulator time inline with server time
- Looks like server sync issue
- Not working on apfodisha_dev org also

### Video link:
https://github.com/user-attachments/assets/68d9c68a-48f5-4ba2-a30b-69766e492c24

**Comment by 1t5j0y** [comment]
By design as per https://github.com/avniproject/avni-server/issues/782
