### ISSUE TITLE
Mandatory coded concept is not working for APFodisha form

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1510]
**Describe the bug**
Mandatory coded concept is not working for APFodisha form
Login with maha@apfodisha 
I am try to register the individual
there is question Marital status which is mandatory question which is having 5,6 option which is not showing on client .
 this is happening on prerelease 
with build version 1-8213

**To Reproduce**
1. Login with maha@apfodisha
2. try to register individual 
3. See error

**Expected behavior**
User should be able to register the individual

https://github.com/user-attachments/assets/15e90c29-9443-4924-8724-7d716e7db780

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by mahalakshme** [comment]
@AchalaBelokar can you test now. There was a configuration wrongly done in the org., Forgot to update u

**Comment by AchalaBelokar** [comment]
@mahalakshme it is working fine
