### ISSUE TITLE
Register overview card disappears 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1517]
**Describe the bug**
when we are in home page the register overview count show as zero but it display the individual data and also if we change the subject type and come again to the subject type the overview card is disappeared.
org : Mobile creches
env: pre-release 
test apk : https://app.circleci.com/pipelines/github/avniproject/avni-client/2665/workflows/1ec84804-e67f-4fb1-a094-6e580d54724f/jobs/17163
2.https://app.circleci.com/pipelines/github/avniproject/avni-client/2667/workflows/4496378e-c34b-4cab-bf48-1c5f0c8462c9/jobs/17164

steps to reproduce : 

1.Login to the app
2.click on the register overview 
3.click on the filter and change the subject type 
4.again come to the old subject type 

Expected result : register overview should be displayed
Actual result : the card get disappeared.

Refer video : 

https://drive.google.com/file/d/1GMH_Z0uH2MblUx64_aLxZzh-lrfJ8fnj/view?usp=sharing

**Comment by mahalakshme** [comment]
@AchalaBelokar I think for this org hideTotal flag is set to true in org config. Can you check that once?

**Comment by mahalakshme** [comment]
@AchalaBelokar @dinesh2096 As per this card: https://app.zenhub.com/workspaces/avni-product-deprecated-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/880 Only for orgs where hideTotalForProgram is set to false, total will show on selecting program or encounters as well. Else it will not show. For this you can check the skype comment. It should show even on program selection. Please feel free to reopen this card, if that happens.
