### ISSUE TITLE
cancel button is not appearing on my dashbaord ..

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1519]
**Describe the bug**
cancel button is not appearing on my dashbaord after applying the filter
On my dash board earlier cancel button is appearing ut now I am not able to see the data.
this is happening when I updated the app 9.4 version to 10.0. also not apearing on 9.4 version.

**To Reproduce**
1. Login with maha@calcutta_kids. on 9.4 version of app
2. register a individual
3. update the app with 10.0
4. sync the app
5. Apply the any filter
6. try to cancel it but there is on cancel button is present

**Expected behavior**
cross button should be present on filter section after applying on that

**Screenshots**

https://github.com/user-attachments/assets/f9facc29-7041-4dfe-a1f4-c6891d8d29da

ormation):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by AchalaBelokar** [comment]
@petmongrels this feature is not present earlier so no need to fix this. if we want to fix next release we can do this

**Comment by mahalakshme** [comment]
@AchalaBelokar we need not support any new features on MyDashboard since our aim is to deprecate it soon
