### ISSUE TITLE
Dashboard issues of previous release - part 1

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1523]
1. Refresh button to be in green color.
2. Change the text to 'Last refreshed on {datetime}' so that that UI will look better. Also this was the text in MyDashboard. And datetime need to be of the format, DD-MM-Year HH:MM. Don't include seconds and don't display in year-month-date format. These are not formats that users know. Eg: 'Last refreshed on 07-09-2024 17:23' (24 hour format is fine, since that was what was used already) 
For translations, refer [this](https://docs.google.com/spreadsheets/d/1yLGub4DM-QdvvLXpvnuTdZWcgIkyeDLAPpG98Ee8K3U/edit?gid=0#gid=0)

Current screenshots:
![Image](https://github.com/user-attachments/assets/55e31679-8ad3-48b3-9fd4-4caa998f0226)

![Image](https://github.com/user-attachments/assets/467a2e5d-3435-4579-aa64-655d2a44f24a)

3. For subject type, name of the filter is not reflecting. It is working as expected for Gender.

<img width="700" alt="Screenshot 2024-09-25 at 10 35 20 PM" src="https://github.com/user-attachments/assets/376ecf08-f2be-4756-8705-7384677bcc54">

### Analysis notes:
Making hideTotalForProgram work in new MyDashboard might not be needed. Because from [this](https://app.zenhub.com/workspaces/avni-product-deprecated-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/808) and [this](https://app.zenhub.com/workspaces/avni-product-deprecated-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/880) looks like were done for 2 orgs - JSSCP and CK. But in JSSCP this setting is set to false and in CK, program and encounter type myDashboard filters itselves looks like are removed. Looks like so this setting is not relevant anymore.

**Comment by 1t5j0y** [comment]
### AC2
Used existing standard datetime formatting method `to12HourDateTimeFormat` to aid readability and have conformity with other date formatting on the dashboard screen.
<img src="https://github.com/user-attachments/assets/1a6fdcae-a547-44d8-970b-e2b34513f783" width="300" />

### AC3
'Subject type' filter actually displays corresponding programs and encounters in addition to subject types if configured. Fixed to show the filter name above the subject type selection so user configured filter name is visible. Also, retained 'subjectTypes' sub header and added platform translations so it is correctly rendered for other languages.
<img src="https://github.com/user-attachments/assets/c6c93fb8-6147-4f63-bd64-e41c588db15c" width="300" />

**Comment by mahalakshme** [comment]
@1t5j0y I had suggested the DD-MM-YYYY format because we dont have translations for the months - and there would be users who will not know that as well(I have interacted with users who dont know English at all). didnt notice the as on date - as on date as well was before in DD-MM-YYYY format

**Comment by himeshr** [comment]
Pending the DD-MM-Year HH:MM formating, rest of the changes look fine as per code review stanadards.

**Comment by 1t5j0y** [comment]
Changed format for last refreshed message and as on date display. This also changes display format wherever DatePicker is used.
![image](https://github.com/user-attachments/assets/cc029d61-e3f9-4886-94b4-e04a04b58298)

**Comment by dinesh2096** [comment]
- [ ] Can we have same format everywhere 


References :

![Image](https://github.com/user-attachments/assets/82e2e0ae-8c73-4fe1-8e6a-7c460174a571)

**Comment by dinesh2096** [comment]
QA Reference video : 

[Click here to watch the video](https://drive.google.com/file/d/1IfnxLg1FJP-lgCHef59_EGGbUT7FeFUM/view?usp=drive_link)
