### ISSUE TITLE
 Program is not display in the my dashboard filters 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1525]
**Describe the bug**
When we click on the filter in my dashboard the program related to the subject type is not displayed 
screen overlapping is also happen after click on more then dashboard

org : adjnpct,uninhibteduat
env : prod
version : 10.0

Steps to reproduce : 
1.Login to the app 
1.Login to the app 
2.Click on the filter 

Expected result : Program should be listed for that subject type

Actual : it is not displayed 
**Expected behavior**

**Screenshots**

https://github.com/user-attachments/assets/c9e6a837-1403-419f-b0b0-48b75a05506b

**Comment by dinesh2096** [comment]
- [ ] when we change the subject type the program is automatically selected.


[Click here to watch video](https://drive.google.com/file/d/1julJGDe21uWDo37hgnC-YUYbork1L5Iy/view?usp=drive_link)

**Comment by mahalakshme** [comment]
comment that got deleted:
----------
 when we change the subject type the program is automatically selected.
https://drive.google.com/file/d/1julJGDe21uWDo37hgnC-YUYbork1L5Iy/view

**Comment by petmongrels** [comment]
We have the logic to auto select the program if there is only one program.
