### ISSUE TITLE
[Custom Default Dashboard] Filters should display only for the configured subject type

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1530]
### Issue:

When any filter is configured for a specific subject type, it needs to show only when that subject type is selected.

#### Video demonstrating the issue:
https://drive.google.com/file/d/1xr8hk_UFVDNMeYotc-X4f_SZ4gKrMrVm/view?usp=drive_link

#### Screenshot:
<img width="750" alt="Screenshot 2024-09-25 at 10 16 49 PM" src="https://github.com/user-attachments/assets/5892b5c0-836b-4b17-9789-b30926ed3460">

### Need:
- For organisations like Shelter that have many custom my dashboard concept filters applicable to different subject types, it will not be UX friendly to show all filters for all subject types - users will need to scroll more and relevant filters might appear in the bottom with irrelevant on the top, considering we don't have a way to order filters as well.
- And concepts like WFA Grade, cannot be applicable to subject types like Household and might lead to confusion

### AC:
- In webapp: When any filter, say Gender is configured for a particular subject type, and if 'Subject Type' filter doesn't already exist, save the 'Subject Type' filter as well. This should not lead to saving of duplicate 'Subject Type' filters
- In Webapp: When any filter, say Gender is configured for a particular subject type, and user tries to remove the existing 'Subject Type' filter, then show an error and disallow the user operation
- In mobile app: When one of the selected subject types is configured in the filter, then show the filter. Else don't.
- In mobile app: Whenever there is change in CustomDashboardFilterConfig, clear the CustomDashboardCache after sync of the changes

### Analysis notes:
1. Like subject type we have not made it specific to program and encounter type, because of the below reason:
Lets say, I want see view all Overdue visits of type 'NRC' of an individual enrolled in program Child, whose WFA grade is 1. And WFA grade is calculated in 'Growth Monitoring visit'. Then I can select Individual subject type, enter WFA grade and select encounter type 'NRC'. ie., it gives me the flexibility to view any visit type for individuals of a particular WFA Grade and especially this works because we are applying concept filters on individuals and not on the encounter that has its value.

2. Had mentioned the AC [here](https://github.com/avniproject/avni-client/issues/1382) but looks like not clear.

**Comment by himeshr** [comment]
## Known Issues
- Changing the Filter type doesnot reset sub-configurations previously set for the filter
- Multiple Filters can have the same name in the same Custom Dashboard
