### ISSUE TITLE
Applying concept filters crashing the app

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1531]
### Issue:
All type of concept filters so far tried(in JSSCP and Adolescent Sewa Rural) when applied on MyDashboard is crashing the app.

prod, 10.0.1 latest apk, maha@adsr,
In the below video it is working in 9.4 but crashing in 10.0.1
https://drive.google.com/file/d/1aM25AKQx1gWjJstr8IHcBRCJ6JFoFRJc/view?usp=drive_link

### AC:
Concept filters should get applied and return the right results.

### Test cases:
All types of filters on MyDashboard

**Comment by mahalakshme** [comment]
JSS Singrauli, Shelter are the other orgs that have concept filters.

**Comment by AchalaBelokar** [comment]
- [ ] I am login with  maha@adsr concept filter is not working
- [ ] then I login with dinesh@shelter with family member add filter with date and program and then app is crashing
- [ ] https://github.com/user-attachments/assets/b195e0ac-b64f-4ac7-af91-80969e77814d
- [ ] all filter which is concept is not working.

**Comment by AchalaBelokar** [comment]
I login with maha@jsscp and try to filter with the program and phulwari location after sync then and then only my dashboard is reflecting value otherwise it is not showing I added another phulwari it is showing the zero value.

**Comment by AchalaBelokar** [comment]
- [ ]Login with maha@jsscp and try to filter with phulwari sumitrabai apply the filter and app is crashing[az_recorder_20241008_112153.mp4.zip](https://github.com/user-attachments/files/17289112/az_recorder_20241008_112153.mp4.zip)
- same happen with adsr
