### ISSUE TITLE
Enrolment save does not trigger creation of checklist items if checklist detail already exists

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-client#1532]
https://avni.freshdesk.com/a/tickets/4597

For a scenario where the checklist configuration is modified to add some checklist items, the expectation is that saving the enrolment for already enrolled subjects (with or without making any edits) should trigger creation of checklist items not already created.

This is currently [not happening](https://github.com/avniproject/avni-client/blob/b22b62817d210a0f4734aa21035bfb1fd43e4261/packages/openchs-android/src/service/ChecklistService.js#L38) if the checklist detail already exists.

**Comment by mahalakshme** [comment]
It is fine to retain the old behaviour. Changing it will result in some old enrolments having new checklist details items and others not having.
