### ISSUE TITLE
Address related rule is not evaluting

### ISSUE THREAD

**Issue by vedfordev** [avniproject/avni-client#1533]
**Describe the bug**
In goonj activity registration, when we select other block in address other block related form element is not evaluating immediately.

**To Reproduce**
Steps to reproduce the behaviour:
1. In client go to Activity registration.
2. Select other block.
3. See that you are unable to see other block form element.
4. now change the focus form element other block will be shown

**Expected behaviour**

**Additional Context**
put simple log in form element rule. try to check in console it is not evaluating immediately.

**Smartphone (please complete the following information):**
- Version: 10.0.*

**Comment by himeshr** [comment]
@vedfordev this is a known limitation of Avni client, we do not evaluate rules for any change in AddressLevel fields until we get to a change in a Custom FormElementGroup's FormElement..

**Comment by mahalakshme** [comment]
duplicate
