### ISSUE TITLE
Media selection should work as before without asking access for storage permissions

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-client#1534]
### Need:
Need to comply with Google Play store policies related to "READ_MEDIA_IMAGES/READ_MEDIA_VIDEO" permissions.
Currently the deadline for app October 31st 2024 (or Jan 22nd 2025, if we get an extension), failing to meet the acceptable use case criteria will be disallowed from publishing on Google Play.

### Acceptance Criteria
- App should not ask for accessing photos and videos on the device or for accessing storage like available currently. It can ask for taking pictures and recording video

https://github.com/user-attachments/assets/0c584d9f-7aff-441f-ae96-28b96e74af29

- Without the above should be able to select photos from gallery app or other apps(from all custom albums)
- Should be able to multi-select photos/videos/audio
- Above should work in Android version >= 13 across different Android models
- it should work like [this](https://drive.google.com/file/d/1WxFcordvzFqkyti7hZJLe_4OsJU2pTfx/view?usp=drive_link) across all models and versions.

### Tech Approach
According to [this](https://android-developers.googleblog.com/2023/04/photo-picker-everywhere.html) link, looks like GET_CONTENT is supported with the new photo-picker as well. Hence we can import selected images into app without having complete access to Android media storage.

## Old: Ignore:
- Do away with READ_MEDIA_IMAGES and READ_MEDIA_VIDEO privileges
- Use a system picker, such as the [Android photo picker](https://android-developers.googleblog.com/2023/04/photo-picker-everywhere.html) or alternative photoPicker whichever works best for us.

**Comment by mahalakshme** [comment]
@dinesh2096 have updated the AC to work in greater than or equal to 13 since for versions < 13, READ_MEDIA_IMAGES/READ_MEDIA_VIDEO permissions are not required. It is different permissions namely 'READ_EXTERNAL_STORAGE' and we need not remove this permission.

**Comment by dinesh2096** [comment]
QA Reference video : 

[Click here to watch the video](https://drive.google.com/file/d/1sRbhHbXvYE-snLRzQ0mtnwHUNyn0t1Co/view?usp=drive_link)
