### ISSUE TITLE
Display all the groups a member belongs to

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1537]
https://avni.freshdesk.com/a/tickets/4457

### Issue:
In mobile app, when there is more than one group/household assigned to a member,  we dont display any of the household/group names.

https://github.com/user-attachments/assets/346fd46a-9aac-4946-a15d-7b716e3f714e

### AC:
- Display all the groups and household, a member belongs to.
- Show the household/group names side by side, and not one below the other

### Out of scope:
In DEA the above already works.

**Comment by adamsanadi6** [comment]
![Image](https://github.com/user-attachments/assets/8a41f3d8-2ff1-4a27-8713-7ce73e1ba9f9)
![Image](https://github.com/user-attachments/assets/4af26d24-3193-4704-8144-9fcc8dd13f06)
![Image](https://github.com/user-attachments/assets/daa2e2df-dfeb-4110-ae04-60c7118db79a)

**Comment by dinesh2096** [comment]
QA Reference Image : 

![Uploading Screenshot 2024-12-03 at 6.07.51 PM.png…]()
