### ISSUE TITLE
Voided dashboard also displaying

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1543]
### Issue:
1)env: prod
app version: 10.0.3
Screen recording : https://drive.google.com/file/d/1w6Opx3HU_RwqNruhv_Q2tibepOX4Ow4B/view?usp=sharing"
username: mahanew4@apfodisha, org: APF Odisha

On syncing you will find that, the dashboards voided - like Pregnancy, Child, and Overview also displays

2) env: prod, app version: 10.0.3
username: maha@maha, org: maha

On syncing you will find that, the dashboards voided - like something3 and something4 doesn't display which is the expected behavior.

![Image](https://github.com/user-attachments/assets/2ff3067b-fb3e-482b-a07a-311653f76016)

### AC:
- Voided dashboards should not display in mobile app
- It should not display in webapp under UserGroups as well

![Image](https://github.com/user-attachments/assets/a0cd446b-9707-4151-9a67-f1a22f52da69)

- Also find the reason how in `maha` org it works as expected.
- Suggest a workaround to fix the first case - will voiding of group_dashboard entries help?

### Technical analysis:
- On deleting of dashboard we are not voiding the corresponding entry in the group_dashboard table.
- But no idea how it is working in `maha` org
- Both orgs also seem to have similar entries in the db

**Comment by 1t5j0y** [comment]
Cause: `CustomDashboardService.getGroupDashboards` did not ignore voided dashboards
Did not impact `maha` org because a different method (which handled voided dashboards) is called if user group has all privileges.
Not handling hiding of voided dashboards in user groups screen on webapp as that would require voiding of dependent entities when a dashboard is voided and is a much larger change.

**Comment by mahalakshme** [comment]
@1t5j0y : it is not just group_dashboards right.. we have other entities that need to be voided as well (dashboard_card, dashboard_filter, dashboard_section_card_mapping...) so we need a holistic story that deals with all these entities
I'm not sure if we should void the dependent entities in the first place (makes unvoiding difficult). If we are doing it, we should do it across the board for all dependent entities and not selectively

@mahalakshme :
the concerns above seems to be more of technical complexities, but just from the card, the AC that I see needs to be achieved is that voided groups should not display. I think @petmongrels  or @Himesh can better answer the above questions. Also functionally there is no need to unvoid a dashboard from UI currently or in the near future. I am just trying to separate the functional complexity from that of technical so that it might help us to be more productive.

Entries of these: dashboard_card, dashboard_filter, dashboard_section_card_mapping - dont display anywhere, so functionally I dont see any issues whether it is voided or not. What is good technically you can decide. I can understand you are worried about the consistency though.

**Comment by mahalakshme** [comment]
it was decided not to do this: It should not display in webapp under UserGroups as well since the cost to benefit is hight
