### ISSUE TITLE
Loading of a form takes more time

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1544]
https://avni.freshdesk.com/a/tickets/4908

### Issue:
env: prod, apk: 10.0.3, user: maha@shelter -> login -> search household 0155 -> Click on Edit of  'Household Level daily reporting' - it takes 30 secs to render the form

in 9.4.0, it only takes less than a second to get rules of type ViewFilter. It takes less than 5 secs to render the form.
![Image](https://github.com/user-attachments/assets/cf96a362-4b0a-4ba9-9cc6-881883bedca6)

But in 10.0.3, it takes more than 10 secs to get rules of type ViewFilter.
![Image](https://github.com/user-attachments/assets/396a42e5-7559-4675-a1c1-bf89ba365d4e)
Issue video recording: [Link](https://avni.attachments2.freshdesk.com/data/helpdesk/attachments/production/36210603616/original/WhatsApp%20Video%202024-11-07%20at%2012.54.23.mp4?response-content-type=video%2Fmp4&Expires=1731049024&Signature=j852hfxdm0fpV~erM8s9UY6l42fncwtf5SWazi9NLV7bDQZ4ZNzmN~VNb8TwX5Uk~8zgkvMEFZwTLC-hluBAW8w8HzQBp7AkyN0oOq7gsWTRcb1VUpW~-ctb~NHGDBsqtRMS~ytyoMITJw~R2HGeFmAShct3Xr~7ZtcxCwsr-s4Ip3kdpHS-fbAhJl8Cwb0JbujYIG20tf8IPRAdzUJOzozb4GhrW3Ro6b~Ks4QtwLDy9xKHZ32Q9Ihwn6rwo3~TxJIPMBK0TTzNfI04jrg2cN9nyek7q7PGLqlVJCuE8gU4BfyXsnJUld26DJP~BrqiPowQKuxSeXjqC0Ggza6iZQ__&Key-Pair-Id=APKAJ7JARUX3F6RQIXLA)

### AC:
- Loading of the Edit page should not take more than 5 secs

### Technical analysis:
Why is rules of Type ViewFilter fetched twice (both in 9.1 and 10.0)? Fix it if possible

**Comment by himeshr** [comment]
On debug, found that the additional logic introduced to filter out formElements whose parent formElement entities are voided, had caused severe degradation of performance.
Using a hashmap restored the performance to previous levels seen in apk of version 9.4.
Added a functional and performance criteria test for the same, the test before fix took ~4.5 seconds, but after fix took less than 100 milliseconds.

**Comment by dinesh2096** [comment]
QA Reference : 


[Click here to watch video](https://drive.google.com/file/d/1_2z5xwES8IGh3dH8tak8aUMG24R01VZ9/view?usp=drive_link)
