### ISSUE TITLE
Group subject filter type not working

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1554]
https://avni.freshdesk.com/a/tickets/5006

### Steps to reproduce:
- ctrith_iph, 10.1.1, prod
- Click Filter -> Select 'Individual' as subject type -> Select a household name(one of the filters) which has a due visit
- In 9.4.0 it will display the due visits, but not in 10.1.1

![Image](https://github.com/user-attachments/assets/470c6118-b6b1-4188-befe-1c15e70a3f2f)

[Left] 9.4.0 [Right] 10.1.1

### AC:
Should work in 10.1.1 as in 9.4.0 - should have probably broken in 10.0 release

**Comment by 1t5j0y** [comment]
@AchalaBelokar moving this back to in progress as there is an issue.
