### ISSUE TITLE
Blank Checkbox Appearing in Address Filter

### ISSUE THREAD

**Issue by dinesh2096** [avniproject/avni-client#1556]
A blank checkbox is displayed in the address filter dropdown, which is unexpected and may confuse users.

Env : prod
APK : 10.1.1
User : dinesh@apfodisha_uat

Steps to reproduce : 

1.Login to the app
2.Click on the dashbaord
3.Click on the filter
4.Under GP Filter we are getting the Blank checkbox

Expected Result : GP filter should display only the address for a location
Actual Result : Its also displaying the blank address

Reference video : 

[Click here to watch the video](https://drive.google.com/file/d/1ilwJG0iouUXhAmXD2qdYEcDsd7sV8lQR/view?usp=drive_link)

**Comment by adamsanadi6** [comment]
@dinesh2096 Unable to reproduce the issue. Please have a look and let me know if the issue still exists.

**Comment by dinesh2096** [comment]
@adamsanadi6 As we discussed, seems like an implementation user mistakenly deleted the address from the database might have caused the blank space issue.Hence closing this issue.

cc: @mahalakshme
