### ISSUE TITLE
Sync on App not working properly

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/avni-client#1557]
All the cards are not syncing even after the app is synced. Users have to click the refresh button in each section of the dashboard. 
This issue is currently happening for most of the users.

1) The app was synced at 12:01 PM.
2) The "Last refreshed" timestamp on the "Homepage," "Pregnancy scheduled and backlog visit," and "Child scheduled and backlog visit" sections is showing 11:59 AM.
3) The "Last refreshed" timestamp on the "Pregnancy" and "Child" sections is showing 12:00 PM

User ID : 7008140327@apfodisha, 9937911923apfodisha

Screen recording: https://drive.google.com/file/d/13XZKeQLrOStaQlGrX15r_wXmX1pGIo1p/view?usp=sharing

Please click here for more details : https://docs.google.com/spreadsheets/d/1IlQJZDRw4rnuEHvO9HGJvvIQ6wPrXuGH8PdksUHYbm0/edit?gid=0#gid=0&range=A146:A157

**Comment by mahalakshme** [comment]
not an issue
