### ISSUE TITLE
Location issue

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1558]
https://avni.freshdesk.com/a/tickets/5008

### Context:
As part of this ticket, some location table updates via script was run

### Steps to reproduce:
env: prod, login to dinesh@jscs, you will find the below issues, that doesn't exist in prerelease

1. After fast sync the original username is not reset. Potential issue of all sync happening with this name
2. During edit of registration, location selected is not getting displayed
3. In the filter, even before selecting district and block, all villages are getting displayed

https://drive.google.com/file/d/1CBlKLOdaozTQEvv0ik6geOdeHRb25bmx/view?usp=drive_link

### Need to fix this:
- We periodically do client migrations, run db scripts on server and users do fast sync. Presence of such inconsistent data might lead to unexpected behaviour.
- There might be more hidden issues.
- Soon new HWC location type will get introduced in the prod JSCS, and this inconsistent data, might aggravate the issue

### AC:
Currently the prerelease or staging JSCS doesn't have the issue that prod JSCS has. Hence finally in prod need to work like the below:

1. On clicking Edit of registration, selected locations should get displayed
2. On clicking Filter, only after selecting the highest location filter - District -> the rest of the location types should get displayed
3. On completion of fast sync, with login as dinesh@jscs -> it should show dinesh@jscs and not some other username

**Comment by himeshr** [comment]
The root cause of issue _"After fast sync the original username is not reset. Potential issue of all sync happening with this name"_ is as per [card](https://github.com/avniproject/avni-client/issues/1552)

Confirmed that the issue doesn't happen if we clear emulator storage and do sync.

**Comment by himeshr** [comment]
## Resolution for AC:
1. During create / edit of registration issue ==> Resync of "Location Mapping" resolves the issue
2. In Filter screen or Subject Search screen issue ==> Resync of "Location Mapping" resolves the issue
3. Old user name present ==> Resolved as part of #1552 

## Data-fix
Resync of "Location Mapping" shall be achieved by updating lastModifiedDateTime for all LocationLocationMapping table entries for JSCS org done as part of commit https://github.com/avniproject/data-fixes/commit/98a2edb3a9203baa24cfac3b3a2c62352708c9a4

**Comment by himeshr** [comment]
Patch to force sync all LocationMappings on client dev apk without modifying Server or Client DBs..
[#1558___Force_fetch_LocationMapping.patch](https://github.com/user-attachments/files/18228198/1558___Force_fetch_LocationMapping.patch)

**Comment by mahalakshme** [comment]
@AchalaBelokar this is Tech QA card

**Comment by mahalakshme** [comment]
@himeshr you can itself pickup this card and get it to done, since we are not much people now.

**Comment by himeshr** [comment]
Ran the [script](https://github.com/avniproject/data-fixes/blob/main/JSCS/update_location_mapping_last_modified_date_time.sql) and later on verified that **following** issues were **resolved**:
- During create of registration, child locations are displayed before a parent is selected
- During edit of registration, location selected is not getting displayed
- In Individual Filter screen or Subject Search screen, child locations are displayed before a parent is selected

[JSCS location mapping update transaction logs](https://github.com/user-attachments/files/18244009/jscs_prod_location_mapping_db.txt)
