### ISSUE TITLE
Privilege issue

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1559]
https://avni.freshdesk.com/a/tickets/5016

### Steps to reproduce:
env: prod
- Login to swathi@iphscd, password in the ticket
- Go to profile of any individual of 'Participant' subject type, enrolled in 'Sickle Cell Disease (Affected)' program
- None of the completed encounters will show 'Edit' option
- But when you go to profile of any individual of 'Participant' subject type, enrolled in 'Sickle Cell Trait (Carrier)' program, Edit option is visible on completed encounters.

### Technical analysis:
- The privilege to Edit is available in mobile db with allow set to true
- No edit form rule defined
- Code as well seems to be correct
- So need to debug to figure out the issue.

### AC:
Edit option should have been visible.

**Comment by 1t5j0y** [comment]
@mahalakshme this is because 'Follow up SCD' (Registry SCD) which is the only encounter type linked to the 'Sickle cell disease (Affected)' program is configured as immutable.
