### ISSUE TITLE
Regression testing Bug : "Not Enough Identifiers" Despite Valid User Setup

### ISSUE THREAD

**Issue by dinesh2096** [avniproject/avni-client#1560]
The client app displays the error message "Not Enough Identifiers" when attempting to access functionality for a specific user. However, the corresponding user has a valid ID and has been properly assigned in the web app.

Env : pre-release
org : testorg
user : dinesh@testorg

Steps to reproduce :

1.Login to the webapp
2.Click on the admin
3.Click on the user added the prefix
4.Click on the user assignment added to the user
5.Sync on the cilent app 

Expected Result : User should be synced and added the individual as expected
Actual Result : User is displayed with the error 

Reference video : 

[Click here to watch the video](https://drive.google.com/file/d/1Y6WjZFKfmATl2BsHy9mtXI0elBJN_Qnd/view?usp=drive_link)

**Comment by 1t5j0y** [comment]
@dinesh2096 the id form elements in the registration forms are not linked to an identifier source. Please link them and sync and retry.
![image](https://github.com/user-attachments/assets/7b2e2e42-8687-4289-87ad-93b1f0fea7c6)
