### ISSUE TITLE
Beneficiary mode

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#182]
As an OpenCHS user, I should be able to enter into a Beneficiary mode, which will help me give the app to beneficiaries so that they can fill in their own information. 

Tasks
- If I have the showBeneficiaryButton on my settings = true, I will be shown a button under the "More" tab of the home page. 
- Once I click this button, I will be prompted for a PIN. 
- After entering the PIN, I will be taken to a Beneficiary Login screen. 
- The screen will have an "Exit Beneficiary Mode" button. 
- Clicking on the Exit Beneficiary Mode button will prompt for the PIN once again. 
- On correct entry, it will take you to the app. 
- On wrong entry, it will stay there, with an Incorrect PIN message
- There will be an option to exit this PIN popup which will keep user in beneficiary mode. 
- After 3 unsuccessful entries, take user to Cognito Login (which will require internet)
- On successful Cognito Login, remove beneficiary mode by default
- On restart of app that is in beneficiary mode, stay in beneficiary mode.

**Comment by garimadosar5** [comment]
@vinayvenu @sidsamanvay 
##### QA Comments -
- The message "Incorrect PIN (1 out of 3)" is not very clear. May be we can say "Incorrect PIN (1 out of 3 failed attempt)" or anything more specific.
- Even if there is no PIN entered it says, "Incorrect PIN".
- On PIN page after pressing EXIT button from beneficiary page there is no previous button. Device button takes to the beneficiary search page.

**Comment by garimadosar5** [comment]
@sidsamanvay 
##### QA Notes 2- 
- If I enter password wrong 2nd time, It still says `1 out of 3 failed attempt`.
