### ISSUE TITLE
Include Individual Encounter in my dashboard

### ISSUE THREAD

**Issue by ghost** [avniproject/avni-client#188]
Indclude Individual Encounters in the summary numbers and also update the filters.

testing apk: staging-5cd6b-2019-09-10-11-59-14.apk

**Comment by garimadosar5** [comment]
@sidsamanvay 

QA Comments - 
- The filter is not working for the individual encounter.
- The encounter is not showing in Scheduled.
- In Overdue it is showing before time. For eg: It will be overdue on 16-09-19 but showing in overdue list on 14-09-19.
