### ISSUE TITLE
[Platform] beneficiary mode Bugs

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-client#202]
- Current Behaviour : Exit from beneficiary mode and again go back to beneficiary mode. The last value is still filled. in IHMP, the Household number is filled when again enter in the beneficiary mode. Expected Behaviour : The last value should not show up
- Current Behaviour : In case of every error, it shows the same error "Unable to fetch Unique record for the given information". If record does not exist then also it shows this message. Expected Behaviour : Relevant error message should be shown in a user friendly language. 1. Unable to find a record with the given identification details. 2. More than one record found with the given identification details

**Comment by vindeolal** [comment]
Staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-3e7a-2019-11-05-14-20-27.apk

**Comment by garimadosar5** [comment]
@vindeolal 
QA Comments - 
- If there are `two` record of the same identification information. And one of the record is voided then it should not include voided individual in the search.
But this is not happening, it gives the error that "MORE THAN ONE RECORD FOUND WITH THE GIVEN IDENTIFICATION DETAILS."
