### ISSUE TITLE
[Platform] DOB goes one day prior after two time sync.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-client#203]
In registration form for eg: 
- Individual Reg form
- DOB as "01-11-2017"
- save the form. 
- Sync the form
- Again sync the app.
- DOB changes to "31-10-2017".

- It happens with the LMP and Registration date also.

##### Comment:
It happens because of time zone difference. We store all the time in UTC (i.e GMT +0), so if the client is in any timezone which is behind UTC (i.e. GMT -1), then date shows as the previous day's date.

**Comment by arjunk** [comment]
@garimadosar5 @vindeolal is there anything that we plan to do in this defect. othwerise, we can close this.
