### ISSUE TITLE
[Platform] When a subject type is registered from backend, edit button should not show in the profile.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-client#204]
![Screen Shot 2019-09-26 at 6.32.11 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/9502924d-61ae-417e-b9c6-bddfced9b238)

The edit button should be hidden as there is no registration form for these subject type.

**Comment by vindeolal** [comment]
APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-a9372-2019-11-08-16-29-25.apk
