### ISSUE TITLE
Ability for impl to specify visit creation strategy

### ISSUE THREAD

**Issue by ghost** [avniproject/avni-client#205]
Based on different usecases an implementation may not work with the default strategy of the platform, that is to overwrite the scheduled date if the visit of the same type already exists which effectively means change of schedule.
In most cases the default strategy of overwrite may just be fine.

[We also have a requirement of a completed encounter being rescheduled. Can we accomplish the same using this strategy.]

The returned object could look like below. The platform can read the value of strategy and decide what to do when an encounter of specified encounterType is found. 
{
encounterType:
earliestVisitDate :
maxVisitDate :
encounterCreationStrategy: overwrite (default) | createNew
}

See for more info: https://openchs.freshdesk.com/a/tickets/446

**Comment by vinayvenu** [comment]
## Changes made

### Product
When retrieving visits, we can pass in a flag "visitCreationStrategy" that can be either "default" or "createNew". 
All logic for "default" stays as is. 
If it is "createNew", a new visit is created always. 

### CK implementation. 
#### Affected forms 
- Doctor Visit Form (Mother and Child) related followups (Both Doctor Visit followup and Home followup). 
- ANC Doctor Checkup (Pregnancy) related followups (both doctor visit as well as home followup). 

#### Change logic
- New forms are scheduled if there is no scheduled visit of the specified type for the specified date. 
- If there is a change in encounter date time or follow up date when editing a form, duplicate visits are created.

**Comment by garimadosar5** [comment]
@vinayvenu 
QA Notes - 
- If Multiple doctor visits are done then all the followup visit at home are showing as scheduled on the same date. Eg - Test 2 date (staging)
![Screen Shot 2019-10-10 at 5.28.05 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/8690f815-5017-4b20-ab06-e490750345bc)
