### ISSUE TITLE
JSON Parse error: Property name must be a string literal

### ISSUE THREAD

**Issue by ghost** [avniproject/avni-client#214]
We get this following error in bugsnag:
```
JSON Parse error: Property name must be a string literal
```
*Speculation: the jsonb fields in postgres db might be having an array where an object is required.*
**Right now not enough Information available to debug this error.** So we will add some code to get more info later on when the error occurs. So, wrap all `JSON.parse(...)` with `try ... catch ... ` block and throw a custom error with more info. So, we know what is happening in detail from bugsnag. Remember to wrap all the `JSON.parse(...)` calls, including openchs-models and `impl.`'s rules.

**Comment by hithacker** [comment]
No longer getting this closing it
