### ISSUE TITLE
Ability of filter by gender

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#241]
Display gender filter in search and my-dashboard page.
Gender filter should only show for individual subject types.

**Comment by vindeolal** [comment]
Staging APK :  https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-ae5c3-2019-11-07-14-53-32.apk

**Comment by garimadosar5** [comment]
QA Notes - 
@vindeolal 

- The app is crashing when Gender is selected.
![Screen Shot 2019-11-07 at 6.05.58 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/07824cb2-4ec1-4877-bb15-abc699d434e2)
