### ISSUE TITLE
Folder does not exist | Attempt to get length of null array

### ISSUE THREAD

**Issue by ghost** [avniproject/avni-client#244]
*Speculation: When storage permission not provided but background PruneMedia  task calls RNFS.readDir and fails because there are no permissions to read directory.*

See: [RNFS code for "Folder does not exist"](https://github.com/itinance/react-native-fs/blob/master/android/src/main/java/com/rnfs/RNFSManager.java)

### Fix
We can use FileSystem.init() call to make sure permissions are there before doing readDir. We are doing similar thing in App.js.

**Comment by arjunk** [comment]
@hithacker @vinayvenu this defect is not clear in term of feature, scenario and impact. can you add that.

**Comment by vinayvenu** [comment]
Too old. Closing.
