### ISSUE TITLE
Support text-based search option on dashboard

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#257]
As an implementer, I should be able to configure any text concept datatype on the registration form or the enrolment form to be searchable from either the search screen or My Dashboard. 

### Acceptance criteria
- When a text concept datatype is configured, then an includes search is performed for that concept
- When two terms are provided in the search query, the search will split into tokens and do an AND search among them
- When two concept datatypes are configured, then search will be an AND across the two. 
- All other search terms are also ANDED to the final search result. 
- Text field label must be internationalized
- Text field should look like other text fields on forms
- Fields on the search will be shown only if it matches the subject type option that is provided on the screen. 
- Text field should be placed above all other search options

**Comment by garimadosar5** [comment]
#### Test Cases -

1. Implementation - IHMP **_DONE_**
- Registration - Name, Household Number
2. Implementation - CHETNA **_DONE_**
- Registration - Household Number
3. Implementation - Preconception - **_DONE_**
- Registration - Name of Husband
4. Implementation - CK - **_DONE_**
- Registration - mychi ID
5. Implementation - Sewa Rural - **_DONE_**
- Registration - Mother's Name
6. Define search scope wrong. MyChi Id is in Registration, configure this in enrolment.

**Comment by garimadosar5** [comment]
QA NOTES - 

- If we do not define search scope right. It does not give any error but no search result is found on the client. On the client, we do not know what is wrong. 
(Do we know this issue?)

**Comment by vindeolal** [comment]
@garimadosar5 
We need to set scope properly while configuring filters from web. Or else it won't work.
