### ISSUE TITLE
Support numeric field search option on Dashboard and Search

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#258]
As an implementer, I should be able to configure any numeric concept datatype on the registration form or the enrolment form to be searchable from either the search screen or My Dashboard. 

### Acceptance criteria
- When a numeric concept datatype is configured, then a widget is present on the top of all other search options. 
- The widget provides an option to provide a minimum and a maximum value
- Search should be inclusive on both ends
- All other search terms are also ANDED to the final search result. 
- Field label must be internationalized
- If no value provided, then criteria should be removed from the search
- Fields on the search will be shown only if it matches the subject type option that is provided on the screen.

**Comment by garimadosar5** [comment]
#### Test Cases - 

1. Implementation - IHMP
 - Reg -Total number of individuals in the household , Contact Number
- Pregnancy Enrolment - Height
- Child Enrolment - Weight of child.
- Eligible Couple Enrolment - Gravida, Number of children alive

2. Implementation - CHETNA
- Reg - Total Family Member, Age at Marriage.
- Lactating Mother with Child Enrolment - Age of Mother, weight of the child at birth.

3. Implementation - Preconception
- Registration - Family Income, Age of Husband
- Enrolment/Baseline - BMI, Calorie Intake, Protein Intake.

4. Implementation - CK
- Pregnancy Enrolment - Gravida
- Child Enrolment - Weight of child

5. Implementation - Sewa Rural
- Registration - Age

6. Implementation - Phulwari
- Registration - Birth order
- Child Enrolment - Day of the month to visit Phulwari

7. Implementation - Sickle Cell
- Registration - Aadhar

**Comment by garimadosar5** [comment]
QA Notes- 
- Decimal values are not accepted.
- In the search page, the filter gets reset if the user goes back and again apply the filter.

**Comment by vindeolal** [comment]
@garimadosar5 
fixed both.
