### ISSUE TITLE
Replace default search screen with options available in organisation config

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#259]
As part of this story, we will deprecate the feature of showing any filter on dashboard or search page by default and make it configuration only. 

### Acceptance criteria (Applicable to dashboard and search screen unless otherwise specified)
- When no search options are configured, dashboard filters and search screen show only a subject type filter. 
- When no search options are configured, "Search All" filter (that searches for all text fields in registration and enrolment) will be provided in the beneficiary search screen alone (not on the dashboard). 
- This search all filter will be called "Search (Registration and Enrolment fields). 
- When search options are provided, the screen will show these options in the order specified (after the subject type selection option)
- Search options will be ANDED to produce the search result
- Search and dashboard filter still work with the subject type filter alone. 
- Options that can be configured include Name, Gender, Age and Location
- Option configuration is available in the [epic](https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/openchs/openchs-product/1076)

Note: There will be a different story played that will add default values when creating an organisation.

**Comment by garimadosar5** [comment]
QA Notes- 
- Age filter and Other data are not showing on client-side. (On MyDashboard) - **DONE**
- Other Data search filter is not showing on search page also. Do we need to show other data now as we are giving all the options for filter/search?  - **DONE**
- How age search works. If I am saying 22 years, it gives me 20 years result also and 25 years also.
(It was + and - 4 years before but now what we should do as we are giving each specific filter) - **DONE** - for now we are keeping age filter same as previous.
- For default filter, Filter name does not change according to the name given by admin. It keeps the name given by the system for Age, Name, Full search etc.

**Comment by vindeolal** [comment]
@garimadosar5 
1. We don't show them on client-side. Fixed web-app, now it won't show up for dashboard filters.
2. Other data is Search All. Fixed name. It'll only show up when either no filter is configured or searchAll is configured.
3. Right now age is +4 and -4 of the entered age.
