### ISSUE TITLE
Use access control on avni-client

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#263]
As part of this story, we will modify avni-client to show or hide buttons based on the privilege of a user. 

Register subject on home screen
Edit profile on Individual dashboard
Void subject button on Individual dashboard
Enrol into program on Individual dashboard
Edit enrolment on Individual dashboard
Exit from program on Individual dashboard
New program Visit on Individual dashboard
Checklist button on Individual dashboard
New program Visit from Program dashboard
Edit program visit on Individual dashboard
Cancel scheduled program visit from Individual dashboard
New visit from Individual dashboard
New visit from Program dashboard
Edit visit on Individual dashboard
Cancel scheduled visit from Individual dashboard

On Dashboard and search, we do not show options that user does not have view access to. This includes program, encounter type, checklist and subject type.

**Comment by garimadosar5** [comment]
@1t5j0y I guess I will need new apk to QA this story. Please attach a new apk here.

**Comment by 1t5j0y** [comment]
@garimadosar5 sorry about that.
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-4dfd4-2020-04-06-10-09-07.apk

**Comment by garimadosar5** [comment]
QA Note- 
- Cannot sync the app.
![Screen Shot 2020-04-11 at 10.18.45 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/8242b44b-ecf5-4437-baf7-8dc089fc8bc9)

**Comment by 1t5j0y** [comment]
Generated a fresh APK to include the updates to this feature as mentioned in #312.

APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-614d-2020-04-13-17-50-49.apk
