### ISSUE TITLE
Support for registration, enrolment, programEncounter and encounter date search option on dashboard

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#264]
As an implementer, I should be able to configure registration, enrolment, programEncounter and encounter date to be searchable from either the search screen or My Dashboard. 

### Acceptance criteria
- When a Date is configured, then an includes search is performed for that date.
- When two datatypes are configured (registration, enrolment), then search will be an AND across the two. 
- All other search terms are also ANDED to the final search result.

**Comment by garimadosar5** [comment]
#### Test Cases -

1. Implementation - IHMP
2. Implementation - CHETNA
3. Implementation - Preconception
4. Implementation - CK
5. Implementation - Sewa Rural
6. Implementation - Phulwari
7. Implementation - Sickle Cell
