### ISSUE TITLE
Support Date search option on dashboard

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#265]
As an implementer, I should be able to configure any Date or DateTime concept datatype on the registration form or the enrolment form to be searchable from either the search screen or My Dashboard. 

### Acceptance criteria
- When a Date or DateTime concept datatype is configured, then an includes search is performed for that concept.
- When two concept datatypes are configured, then search will be an AND across the two. 
- All other search terms are also ANDED to the final search result. 
- Date or DateTime field label must be internationalized
- Date or DateTime field should look like other text fields on forms

**Comment by garimadosar5** [comment]
##### Test Cases - 
1. **Implementation - IHMP** - **_DONE_**
_Subject Type - Individual_
Registration - Date of Marriage
EC Enrolment - Date of last Outcome
_Subject Type - Asha Input_
Registration - Reg date

2. **Implementation - Chetna**  - **_DONE_**
Registration - DOB
Pregnancy Enrolment - LMP (Date Range)

3. **Implementation - Preconception** - **_DONE_**
Registration - Reg date
Enrolment - Date of last pregnancy outcome

4. **Implementation - CK** - **_DONE_**
Pregnancy Enrolment - EDD

5. Select the future date for Registration date filter.
6. Select the future date for the LMP date filter.
7. Select the future date for Last outcome date filter
8. Select the future date for Marriage date filter.
9. In case of Date range if I put only one date. -

**Comment by garimadosar5** [comment]
QA NOTES - 

1. Preconception <- Dashboard filter <- Registration date range <- if I select only start date or end date and then apply filter <- app crashes.
 2. We can select bigger date as start date and smaller date as end date. for eg: start date - 01-02-2020 and end date - 12-12-2019.
3. How to apply the filter on DOB of an individual. (Age filter is there but DOB filter is not there)

**Comment by vindeolal** [comment]
@garimadosar5 
Fixed 1 and 2
For 3, right now we don't have DOB filter. We'll use Age filter from the search page. (which is +4 and -4 of the entered age).
