### ISSUE TITLE
[JNPCT] Child Module UAT feedback/ Changes

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#274]
** Birth form ** :- Change range of temperature from 36.11-37.2 instead of 35.5-37.5. - **DONE**

**Child PNC ** 
First examination question's-- Check skip logic - **DONE**
Grade as per weight is not shown .  - **DONE**
Weight at time of stop KMC --make it non mandatory 
Form is getting stuck when question comes that child needs to refer. - **DONE**

**Child Followup ** 
Grade as per height and weight is not shown - **DONE**
While we complete the form summary does not shown the risk condition like fever , fast breathing , chest indrwaning  in red colour. - **DONE**

**Comment by garimadosar5** [comment]
QA Notes - 
- Child PNC - KMC related questions are showing up. for weight <= 2.5
