### ISSUE TITLE
[Feature] When answer of mandatory question is missing and click on next, it should scroll the page to missed question

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-client#279]
If any mandatory question is unanswered, clicking on 'Next' should scroll the screen to that particular question(s) marked in red automatically.

**Comment by vindeolal** [comment]
Staging APK :  https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-fa4e-2020-02-06-18-00-18.apk
