### ISSUE TITLE
[Client] From webapp Voided/deleted subject type and program encounter shows in the aplication. 

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-client#280]
- App
![Screen Shot 2020-02-10 at 11.11.58 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/21f73247-a8ef-4dfc-a029-e94618fe423f)

- Webapp
![Screen Shot 2020-02-10 at 11.14.15 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/7d61e3b9-250f-4b9b-b464-4f1f8beed8ad)

Program Encounter - 
- App
![Screen Shot 2020-02-19 at 4.46.16 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/4a7c9115-a61d-4ad4-bb11-d5b5ffbf35db)

- Webapp 
![Screen Shot 2020-02-19 at 4.47.00 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/988520df-d708-4b2d-aee0-549b753e3dab)

- Voided Subject type - 
![Screen Shot 2020-04-27 at 1.41.53 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/519aab1c-e9c9-4a80-8990-cbfad7242610)

![Screen Shot 2020-04-27 at 1.42.11 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/c19567f3-34f7-4de6-8595-d2d52541997c)

**Comment by vinayvenu** [comment]
@arjunk if this is caused by form mappings not being voided, then it is taken care by https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/298

**Comment by arjunk** [comment]
This will get handled by:
https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-product/1145
