### ISSUE TITLE
[MobileApp] If we do not give unit to numeric field, it shows an empty bracket for unit in the app.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-client#288]
for eg: 
![Screen Shot 2020-02-19 at 12.46.33 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/61170300-5f39-4580-9316-1718444032ba)

**Comment by vindeolal** [comment]
Staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-e1777-2020-09-01-16-53-46.apk
