### ISSUE TITLE
Date picker mode fix on android

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-client#294]
Use date picker mode setting when the concept type is Date and keyValues has durationOptions specified. 

Tech: File FormElementGroup.js in avni-client. Line ```else if (formElement.concept.datatype === Concept.dataType.Date && !_.isNil(formElement.durationOptions)) {```

**Comment by swapnil106111** [comment]
@hithacker Created pull request branch name is removeDatePickerQuestion.

**Comment by garimadosar5** [comment]
QA Notes - 
- If the form element is date type and duration is selected then it shows calendar type on the client by default even if the "spinner" is selected.

Implementation - Ayu
Form - Registration (Individual)
Form Element - date (Basic Details) and Date of house tax paid (Other Details)

**Comment by swapnil106111** [comment]
@garimadosar5 Can you take pull and test?

**Comment by hithacker** [comment]
@garimadosar5 I think you need latest staging apk https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-61fd-2020-04-08-04-44-38.apk
