### ISSUE TITLE
Show autoRefresh button on myDashboard only when autoRefresh is disabled

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#299]
1. Show Refresh button on myDashboard only when autoRefresh is disabled by user.
2. User should be able to enable/disable autoRefresh by going to settings page.

**Comment by vindeolal** [comment]
Staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-a31fb-2020-03-09-10-53-53.apk

**Comment by garimadosar5** [comment]
QA Notes-
- Option "Disable Dashboard auto-refresh" is not showing here - 
![Screen Shot 2020-03-09 at 12.57.50 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/a4a1b414-6374-421d-860b-d862488bbfe6)
