### ISSUE TITLE
Show group information in dashboard

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#302]
Group subject types have member information that will need to be displayed in the dashboard. 
We also need to identify them easily, some UX changes should take care of it. 

### Acceptance criteria
- Header of subject dashboard will have a distinct colour to identify that it is a group subject
- The profile tab will have a members section that shows all members of the group
- Touching on the profile of a person will take them to their individual profile

**Comment by vindeolal** [comment]
Staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-4dfd4-2020-04-11-23-08-50.apk
