### ISSUE TITLE
Add/remove group members from group dashboard

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#303]
As part of this story, we add the ability to add group members from the subject dashboard. 

### UX
https://drive.google.com/drive/u/0/folders/1Zuxvl7y-UXvhG0hVhRZPflQrwkINwG1x

### Acceptance criteria
- On the Subject profile of a group, there is an "Add new member" button
- Pressing on the button takes you to a search screen where you can search and choose a person
- The search screen also has a Register New Member, which will take you to the first screen that takes two details - membership start date and role. It will then take you to the normal registration screen. 
- On the members section of the subject dashboard, there will be an option on the side of every member to remove them from the group. 
- Removal will take you first to a screen where end date is asked
- On the members section of the subject dashboard, there will be an option on the side of every member to edit details. 
- Editing will first take them to a screen where they can edit the role and start date, then to the regular registration of the person.

**Comment by garimadosar5** [comment]
Test Cases - 
1. Void Form and not void form mapping
2. Void Form Mapping and do not void form
3. Check in the client app
4. Void form and check the client for behaviour.

**Comment by hithacker** [comment]
@garimadosar5 I guess your comment is for void form story and not this story?

**Comment by garimadosar5** [comment]
QA Notes - 
- In action "three dots" are not sowing any options.
  ![Screen Shot 2020-04-14 at 9.57.08 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/615f03fc-e27a-4827-8316-31517856aee4)

**Comment by garimadosar5** [comment]
QA Notes - 

- One person can be added more than once as relative - 
![Screen Shot 2020-04-15 at 1.22.18 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/4a2b358f-0c47-492d-b1ff-ce6611fe9c1f)

![Screen Shot 2020-04-15 at 1.09.22 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/84bc1836-a9c6-473c-bcd2-3c10cb3ce030)

**Comment by vindeolal** [comment]
Not able to reproduce these scenarios.
