### ISSUE TITLE
Voided programs and addresses show up in android app

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-client#305]
Bug: Programs that have been voided from the admin app show up in the android app.
It shows up in the registration menu and also in "enrol to program" popup on the subject dashboard.
Also the same thing with addresses.

Screenshots
![image](https://user-images.githubusercontent.com/100277/77050949-843ed800-69f0-11ea-954c-b4e72d029cf5.png)
![image](https://user-images.githubusercontent.com/100277/77050994-9ae52f00-69f0-11ea-9d74-a165cbf42fda.png)

**Comment by vinayvenu** [comment]
Duplicate.
