### ISSUE TITLE
Addition of household members

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#310]
When household members are added, avni-client needs to automatically create relationships between an individual and the head of the family. This story will achieve this objective. 

### Acceptance criteria

- [ ] Places in the app where we ask for the role of a group member should be replaced with asking the relationship with the head of household. 
- [ ] Places where role of a group member is shown should be replaced by the relationship with the head of the household. If head of household, then it should be "Head of household"

- [ ] If there is no relationship available between a person and head of household, then that value is shown as "Unavailable" so that user edits the relationship and adds a relationship.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-614d-2020-04-13-13-08-47.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- I cannot add new member in the family from the household dashboard.
![Screen Shot 2020-04-14 at 8.59.34 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/69f627d1-c0a1-4384-9807-043e209c7927)

- After I register the head of the family, It should give the option of adding next family member.
 ![Screen Shot 2020-04-14 at 9.11.23 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/cefcda9f-3b46-425e-acae-ce046040f7d3)

- This is the registration of Household Head but it says Household registration.
![Screen Shot 2020-04-14 at 9.10.15 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/56e548a7-3b5a-4b17-9f00-44234e6a571f)

**Comment by garimadosar5** [comment]
QA Notes - 
- I cannot add new member in the family.
![Screen Shot 2020-04-14 at 8.59.34 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/69f627d1-c0a1-4384-9807-043e209c7927)

**Comment by vindeolal** [comment]
First was because individual_relations were not deployed. Fixed 2&3
