### ISSUE TITLE
Creation of a household

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#311]
As part of this story, we will provide an easy mechanism to register a household. 

### Acceptance criteria

- [ ] When registering a household, the first screen will have an additional question - "Total number of members". This will be a mandatory numeric field. 

- [ ] Once household is registered, a new task is added to "Save and Add Head of household"

- [ ] Once the head of household is registered, there will be tasks to add members, with the message 'Save and add member x" (where x = 1, 2, 3 etc). 

### Technical solutioning

- We will implement this using the worklists feature. 
- There will be the need of adding household member, which is not currently available in worklists.

**Comment by garimadosar5** [comment]
QA Notes - 
- In case of Household type group subject, In individual dashboard can we say "<household name> household" or "<Household name> family" or something. "<Household name> Group" does not sound appropriate in case of family. (Just a suggestion, we can ignore this for now).
![Screen Shot 2020-04-14 at 8.52.57 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/dc4933dc-98ad-481a-91e3-c912cf6c7874)

**Comment by vindeolal** [comment]
Fixed.
