### ISSUE TITLE
Use "All Privileges" privilege on avni-client

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#312]
### Context
When we add new subject types after creating organisation, the Everyone group is not updated. This makes the main purpose of creating an Everyone group redundant. The purpose of the Everyone group was to allow organisations who don't care about groups/privileges to not worry about them.

To fix this issue, we will create a new privilege - "Everything". This will be used everywhere, and will be part of the sync API, usage of API on the client.
We will also prevent users from adding/removing users from the Everyone group or changing its name. However, we will be able to edit privileges associated with this group.

There is a [story](https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/292) to create this privilege in the system. In this story, we will consume this privilege on avni-client. 

### Acceptance criteria

- [ ] Refer to the [story](https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-client/263) where we introduced privileges on avni-client. All these should be allowed if there is a privilege called "All Privileges" marked for the user. 

- [ ] Sync should work as usual.

**Comment by 1t5j0y** [comment]
Approach to handle "All Privileges" was changed. Instead of having a new privilege to represent this, a new property to each group to indicate if the group applies all privileges or selected.

**Comment by 1t5j0y** [comment]
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-614d-2020-04-13-17-50-49.apk
