### ISSUE TITLE
Not able to register/enrol when the form is empty

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#324]
Users are not able to enroll in a program when the enrolment form is empty. The app crashes if the user tries to enroll in the program. Also, non-individual subject registration has the same issue. Same issue with encounter and program encounter also.

https://app.bugsnag.com/samanvay-research-and-development-foundation/openchs-client/errors/5eabbd9548076e001765b5d3?event_id=5eabbd95005b2fee3d310000&i=gi&m=nw

**Comment by hithacker** [comment]
Estimate: 8 hours

**Comment by hithacker** [comment]
APK https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-a18c7-2020-05-08-10-35-57.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- First Page for Enrolment form is looking like this - 
![Screen Shot 2020-05-08 at 6.46.12 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/316f5edc-9173-4278-ba75-a21ab4fc6f82)

**Comment by arjunk** [comment]
@garimadosar5 i think that is fine for now. We have two separate parts in wizard. If the form is empty this part will show up this one page and then System Recommendations page will show up where save button should be present. If that is how it is working, please go ahead with clearing this card. 
cc : @hithacker

**Comment by hithacker** [comment]
@garimadosar5 Test it with non-individual subject registration also. And test with program encounter and encounter as well.

**Comment by garimadosar5** [comment]
**Test Scenarios -** 
Individual Registration - **DONE**
Non-individual Registration - **DONE**
Group Registration - **DONE**
Household Registration - **DONE**
Program Enrolment - **DONE**
Program Encounter - **DONE**
General Encounter - **DONE**
Encounter Cancel - **DONE**
Program Exit -  **DONE**
