### ISSUE TITLE
Missing scroll on Register page

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-client#327]
There is a scroll missing on the Register page. 
When there are lot of registration options, they start getting hidden behind the bottom tab and difficult to click. Easily reproducible in phones with smaller screen.  
Probably introducing a scroll pane would fix this. 

![Many registration options issue.jpeg](https://images.zenhubusercontent.com/5ce7c98fd8501ed6b9d2d1f8/38303198-987a-4bb0-9097-b034018dce31)

**Comment by vindeolal** [comment]
APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-0fc4d-2020-05-08-09-28-06.apk

**Comment by arjunk** [comment]
@vindeolal when i try to install this app, it fails. could something be wrong with APK?
