### ISSUE TITLE
Minor issues on Login page

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-client#328]
1. Since our usernames require @, its better to show a email type keyboard. So that user doesn't have to switch to choose @. 
2. Forgot password is wrongly place. It can be shown in between Show password and Login button. 
![Forgot password wrongly placed.jpeg](https://images.zenhubusercontent.com/5ce7c98fd8501ed6b9d2d1f8/d00ef75e-66ee-4230-b411-61274f7b8d2c)

3. 'Cannot click 'Show Password' on first password change'

4. Date 31-12-1899 in Entity Sync Status is confusing. Show 'Never' instead.

Release 3.7 patch.

**Comment by vindeolal** [comment]
APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-25fff-2020-05-08-13-22-41.apk
