### ISSUE TITLE
Introduce 'Register+Enrol' user setting

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-client#329]
Users, especially newbies, are finding it confusing when they see the Register + Enrol option on the Registration page of mobile client. Some clients are at the moment using this. 
We can introduce a user setting and show these buttons only if the setting is turned on.

Acceptance Critera
1. Setting 'Register + Enrol' available on User page
2. In mobile client show the Register + Enrol buttons only when the setting is turned on. 
3. We don't need to show this setting on the mobile client to allow user to change it. Only admin can change it from web interface.

**Comment by vindeolal** [comment]
Staging APK :https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-25fff-2020-05-08-13-22-41.apk
