### ISSUE TITLE
Cannot delete first form element group from the UI

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#332]
Steps to reproduce
 - Go to an individual profile form on App designer
 - Delete the first form element group
 - Sync to client
 - Client should still work
Actual - Form rendering fails. 

Similar problems exist for all forms except program enrolment.

**Comment by vinayvenu** [comment]
@garimadosar5 Please verify all possible flows - registration, enrolment, encounter, program encounter, encounter cancellation, program encounter cancellation, exit etc. Also try going forward and backward, checking with empty groups, single page forms etc.

**Comment by garimadosar5** [comment]
**Test Scenarios -** 
- Individual Registration - **DONE**
- Non-Individual Registration  - **DONE**
- Household Registration - **DONE**
- Program Enrolment - **DONE**
- Program Encounter - **DONE**
- General Encounter - **DONE**
- Encounter cancellation - **DONE**
- Program encounter cancellation - **DONE**
- Program Exit - **DONE**
