### ISSUE TITLE
Use active flag in avni-client

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#333]
Voided entries must be considered deleted by the system, and should not be shown anywhere. Retired entries can be shown in search options and MyDashboard search options, but nowhere else. 
If there is data related to a retired subject type or program, then it will be shown no matter what. 

### Acceptance criteria

- [x] Voided entries will not be shown in MyDashboard search options
- [x] Voided entries will not be shown in Search options
- [x] Voided or inactive entries will not be shown in the Register page
- [x] Voided or inactive entries will not be shown when enrolling to a program
- [x] Voided or inactive entries will not be shown when performing an encounter
- [x] Voided or inactive entries will not be shown when performing a program encounter

**Comment by vindeolal** [comment]
Staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-d06c1-2020-05-15-17-26-34.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- If a program is inactive, I can access the schedule form but I cannot fill the entries and it does not give any error also. It is a bit confusing.
- If a concept is inactive I can use that see that concept in the form and I can fill that form element or concept answer.

**Comment by vindeolal** [comment]
@garimadosar5 
1. We'll allow to perform already scheduled program encounters. Only new enrollment to inactive program will not be allowed.
2. This we'll change in the webApp #372. Now you can only inactive any concept if it is not used in any form.
