### ISSUE TITLE
Minor Usability Issues in Mobile app

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-client#336]
- [x] Mobile app - first time login - change password screen - show password option does not work
- [ ] Buttons - Group expand/collapse icon and add new member are close. Wanted to expand but ended up clicking add member. Maybe expand/collapse icon can go towards extreme right before "Members (1)"
- [x] For login and forgot password, turn off capitalization
- [x] Mail keyboard on forgot password
- [x] forgot password screen doesn't scroll up so entering email id is a nightmare
- [x] Form name still appears as REG_DISPLAY_subjecttype in the field app

**Comment by 1t5j0y** [comment]
- Mobile app - first time login - change password screen - show password option does not work was already fixed previously as part of #328
- Buttons - Group expand/collapse icon and add new member are close. - Not fixed as this is overall app design related.

Other items have been fixed.

**Comment by 1t5j0y** [comment]
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-94195-2020-05-20-15-44-40.apk
