### ISSUE TITLE
Individual.encounters not available in rules in ProgramEnrolment form element rules

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#337]
Try accessing individual encounters from an enrolment form's rules. Sample rule below. 

```
'use strict';
({params, imports}) => {
  const programEnrolment = params.entity;
  const formElement = params.formElement;
  console.log('encounters are', programEnrolment.individual.encounters);
  };
```

Expected: Should be available
Actual: Not available.

**Comment by nupoorkhandelwal** [comment]
I**ts working. Tested on staging**>>

05-26 09:06:19.586  4946  4983 I ReactNativeJS: 'encounters are', { '0': 
05-26 09:06:19.586  4946  4983 I ReactNativeJS:    { uuid: '5c46086e-d212-4116-9cb6-b5bcdf391899',
05-26 09:06:19.586  4946  4983 I ReactNativeJS:      encounterType: 
05-26 09:06:19.586  4946  4983 I ReactNativeJS:       { uuid: '6949580d-c4a8-40fd-ada5-5846377bfef2',
05-26 09:06:19.586  4946  4983 I ReactNativeJS:         name: 'Diagnosis',
05-26 09:06:19.586  4946  4983 I ReactNativeJS:         operationalEncounterTypeName: 'Diagnosis',
05-26 09:06:19.586  4946  4983 I ReactNativeJS:         displayName: 'Diagnosis',
05-26 09:06:19.586  4946  4983 I ReactNativeJS:         voided: false,
05-26 09:06:19.586  4946  4983 I ReactNativeJS:         encounterEligibilityCheckRule: null,
05-26 09:06:19.586  4946  4983 I ReactNativeJS:         active: true },
05-26 09:06:19.586  4946  4983 I ReactNativeJS:      encounterDateTime: Tue May 26 2020 09:05:47 GMT
