### ISSUE TITLE
MyDashboard Cache

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#342]
Background: https://avni.freshdesk.com/a/tickets/651?note=36119748199

Right now all the numbers shown in my dashboard are calculated on the fly and are stored in state. This state gets deleted when a user reopens the app or when the sync is complete. We can store these numbers on a realm table when these are calculated for the first time and keep showing those numbers unless the user refreshes the dashboard which will update these numbers.

Last updated dateTime will also get saved into the DB and current queries will use this dateTime to filter the results so that when the user clicks on the card he doesn't see more/less individuals than the count displayed on the dashboard.

We should use this DB state only when the auto-refresh of the dashboard is disabled.

DB schema :

```
static schema = {
    name: "DashboardState",
    properties: {
        updatedAt: "date",
        countJSON: "string",
    },
};
//countJSON will be a json string like : {total: 20, scheduled:1, overdue:2, recentRegistration: 1, recentEnrolment: 0, recentVisits: 0}

```

Acceptance Criteria:

1. User presses refresh button -  Numbers get updated, sync time will be proportional to volume of data
2. User updates the filter - Numbers get updated, sync time will be proportional to the volume of data.
3. User submits the form - Numbers don't get updated. Same set of filter and numbers would show up as earlier.
4. User syncs - Numbers don't get updated. Same set of filter and numbers would show up as earlier.
5. User restarts the app - Numbers don't get updated. Same set of filter and numbers would show up as earlier.
6. If the actual numbers are different from cached numbers, a message to be shown to the user indicating the same. (This can be identified if any of following is greater than the cache db update time : created datetime, last modified date time, sync time)

QA
- The experience should also be tested out with high volume orgs. 
No regression should happen for when auto-refresh is on. That should keep working as is.

**Comment by petmongrels** [comment]
@vindeolal I cannot remember, so help me, is the dashboard not updated when the user performs actions leading to creation of new visits and then the user visits the dashboard?

**Comment by vindeolal** [comment]
@petmongrels Yes. We also have a user setting (disable auto-refresh) which does not refresh the count automatically until the user presses the refresh button. This was done for the implementations/users which does not have catchments and their dashboard takes time to load when they come back to the dashboard after doing the visit.

**Comment by arjunk** [comment]
@vindeolal i have added a few Acceptance criteria and QA notes. Please review and update if required.

**Comment by vindeolal** [comment]
Staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-fdba5-2020-07-24-18-54-34.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- When I apply any filter or click on sync it takes around one to two minutes to sync based on the numbers (jscs-staging)
(This is not related to this card. will create a new card if needed.)
