### ISSUE TITLE
Form wizard skips some form element groups from the middle.

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#346]
Test cases
- Skip the first form element group. - **DONE**
- Skip the last form element group. - **DONE**
- Skip any form element group from the middle. - **DONE**
- Skip all form element groups. - **DONE**
- Void first form element group. - **DONE**
- Void last form element group. - **DONE**
- Void any middle form element group. - **DONE**
- Skip few form elements of a group. - **DONE**

**Comment by vindeolal** [comment]
Staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-581da-2020-06-09-17-49-30.apk

**Comment by garimadosar5** [comment]
QA Notes -
- After filling one registration form, the sync button shows '2' number.
- Go to Registration, fill one form till the last page but do not save but sync button shows '1' number.
In sync entity status table, it shows "Rule telemetry failure".
- If the first form element group is hidden/skipped, the first page is empty, the next element group start showing from second page onwards.
User - admin@testbundle2
