### ISSUE TITLE
Ability to void visits

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#349]
We should provide an option to void the visits directly from the client. One should be able to control the permissions using privileges.
- [ ] Add new privilege 'Void visit' in the privilege table.
- [ ] Use the user privilege to hide/show void option on the client.
- [ ] User should be able to void a visit by clicking on the void button.
- [ ] Org-admin should be able to control this privilege from the web app.

**Comment by vinayvenu** [comment]
@vindeolal Are there existing users who are looking for this functionality?
