### ISSUE TITLE
object must be of type 'object', got (undefined)

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-client#352]
**Describe the bug**
object must be of type 'object', got (undefined) error being logged in bugsnag. 

**Analysis**
Looks like it's happening when user is syncing data and app trying to clear the item from queue but the item having been cleared already from the queue. We can put a null check in the following code to call db.delete only if itemToDelete is not null. Though this does indicate some kind of bug and we should fix it but we can prevent the app crash till the time we find the bug.
```
const itemToDelete = this.findByKey("entityUUID", uuid, EntityQueue.schema.name);
this.db.write(() => this.db.delete(itemToDelete))
```

**To Reproduce**
N/A

**Bugsnag link**
https://app.bugsnag.com/samanvay-research-and-development-foundation/openchs-client/errors/5dfb6379b214f40019bb0798?filters[event.since][0]=7d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[device.manufacturer][0][type]=ne&filters[device.manufacturer][0][value]=Genymotion&pivot_tab=event

**Number of times it has occurred in last 7 days**
16 times

**Number of Users it has impacted in last 7 days**
2 users

**Expected behavior**
The exception should not be happening. 

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by hithacker** [comment]
This issue has been linked to an error in Bugsnag
[**Error** in **MainActivity**](https://app.bugsnag.com/samanvay-research-and-development-foundation/openchs-client/errors/5dfb6379b214f40019bb0798?event_id=5efc3937005b7ecad6160000&i=gh&m=li)

**Comment by vinayvenu** [comment]
Stack trace cannot be found anymore. Closing.
