### ISSUE TITLE
Search filter modifications are not synced if the user already has the app

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#358]
**Describe the bug**
Search filter modifications are not synced if the user already has the app

**To Reproduce**
1. Install avni field app.
2. Log in to an implementation (this will trigger sync)
3. Check the search filters
4. Add another search filter from the admin app.
5. Sync from the field app.
6. Check the search filters, they do not reflect the changes.
7. Reinstall and log in. Check search filters they are reflecting.

**Smartphone (please complete the following information):**
 - Genymotion emulator (Google Pixel 2)

**Additional context**
I tried it for Calcutta Kids Training org. Here my dashboard filters worked fine but for search filters, I had to reinstall. Note that CK Training is an inherited org - not sure whether it is related to that.

**Comment by arjunk** [comment]
@petmongrels 
This is not reproducible for me. I tried the same org and search filter. 
Please note that it takes 10 seconds to reflect any changes. I think you may have experienced this. 
We plan to pick this up soon.  https://github.com/avniproject/avni-server/issues/211

**Comment by petmongrels** [comment]
I can see it now. So likely that is the case.
