### ISSUE TITLE
In case we hide primary subject type from a user group then we cannot search that subject type in client.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-client#362]
**Steps -** 
- Create two subject types. (first Household and then Individual)
- create a user group and hide the primary(fist created subject type or the subject type that shows by default on client home page) from that user group.
- Go to client and sync.
- Now you can register only Individual all the accesses for household are revoked.
- but on Home page, you have only Household information.
- User cannot find the registered individual.
- Register an individual and check.

On Staging check on IHMP staging.
Groups EVERYONE and GROUP 2.

**Comment by vindeolal** [comment]
Staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-72ed5-2020-07-21-13-54-13.apk
