### ISSUE TITLE
Dashboard doesn't get updated for device having 24 hour time format

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#366]
**Describe the bug**
In case we register or enroll an individual on a device having 24 hour time format , the count doesn't get updated on the dashboard. ie. the dashboard is not getting updated. 

**To Reproduce**
1. Go to device and set the time format to 24 hour time format
2. Go and register an individual
3. Come to home screen
4. The counts for "last 24 hours registartion" and "Total" won't get updated

Same is for enrollments and other tabs

**Expected behavior**
Ideally dashboard should be auto updated for device having any of the two time formats (and with correct date) without doing sync.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by vinayvenu** [comment]
Closing issue based on inputs from @nupoorkhandelwal
