### ISSUE TITLE
App crashes when the cancel form is empty for an encounter or a program encounter

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-client#367]
**Describe the bug**
App crashes when the cancel form is empty for an encounter or a program encounter. We had fixed this behavior for registration, enrolment, encounter, and program encounter forms but it seems we missed it for cancel forms. We should also check whether the app is crashing for program exit forms as well and fix it if it does.

**To Reproduce**
1. Go to app designer and create a new general encounter or a program encounter with default options. Make sure "Select Encounter Cancellation Form" is set to "New Form".
2. Set a rule to schedule the encounter.
3. Sync the app and try to cancel the scheduled encounter.
4. App crashes.

**Expected behavior**
The app should not crash. It should show an empty form with just encounter date and let the user save.

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [x] Are you mentioning the required scenarios that could be affected?

**Test scenarios**
- [x] Encounter and Program Encounter empty cancel form should not crash.
- [x] Encounter and Program Encounter cancel form with form elements should work as it used to earlier.
- [x] Encounter and Program Encounter cancel form with all hidden FEG should not crash the app.
- [x] Encounter and Program Encounter cancel from with some hidden FEG should work as expected.
- [x] All cancel form should display cancel date which users can't edit.

**Comment by vindeolal** [comment]
Staging APK https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-b1e9b-2020-08-05-11-31-55.apk
