### ISSUE TITLE
Individual summary in Profile.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-client#372]
Server : add new column ```subject_summary_rule``` on ```subject_type``` table.
AppDesigner : implementers should be able to write rule for a subjectType while creating/editig it.
Client : User should be abe to see the subject summary from the individual profile page.

**Comment by vindeolal** [comment]
Moving it back. Will pick it later

**Comment by vindeolal** [comment]
Staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-e1777-2020-09-01-16-53-46.apk

Have created one sample rule for Yenepoya in staging.
