### ISSUE TITLE
Remove user identifiers before creating DB backup

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#375]
We should delete all the identifiers before we create the DB backup so that the user who is restoring this backup doesn't end up using the identifiers of the user who created the backup.

**Comment by vindeolal** [comment]
Staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-57187-2020-09-10-15-53-32.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- if I try login using any userid with another catchment then it gives the error "Authentication failure".  and  when try to change the password after authentication failure, it gives an error "invalid verification code provided. please try again".
Shouldn't we give more clear message.

**Comment by vindeolal** [comment]
Any user can restore data and right now we don't do any catchment validation and it is the responsiblity of user to restore the correct catchment data.
