### ISSUE TITLE
Upgrade React Native

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#380]
Moving from 0.59 to 0.63 has quite a few advantages

- Autolinking of modules
- Better support for androidx, and run of jetifier by default
- "Fast Refresh" to allow faster debugging (minor code changes to view does not require a full refresh of app)
- Move to Hermes (performance boosts, multiple bundles etc)

Hopefully we can also include moving to more recent node versions as node v8 has already moved to EOL, which means we won't get security patches etc. 

### Acceptance criteria
- Move react native to 0.63
- Move node to v12 (current LTS)

**Comment by pratyaksh123** [comment]
Hey I would like to work on this
