### ISSUE TITLE
Save location in form

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#381]
As a user, I want to associate locations in forms.

The choice of location should be similar to how we select address levels when creating subjects. 

Such observations should be displayed always as the observation value of the identifying concept (section 3.3 in the design document). Note that this information is present on the form element. 

Design document
https://docs.google.com/document/d/1WLhNl05Mj05Cps9SReRt8cp6rF-mx09N_xfD1rbg-_4/edit#

**Comment by vindeolal** [comment]
Create a location type concept and use it in the form to test.
Test scenarios,
- Within catchment and outside catchment locations.
- Concept having the highest level or lowest levels and both.

Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-eb387-2020-10-07-16-28-45.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- registration and enrolment encounter are not getting updated on sync button at home page.
Implementation - user1@prebb/password
(On MDSR, sync it is okay.)
![Screen Shot 2020-10-09 at 4.38.25 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/7305045d-03bf-4947-bce6-c721e3efd0e2)

![Screen Shot 2020-10-09 at 4.38.33 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/04c6fa9d-a4e6-4066-ab89-130cd82ce68c)
