### ISSUE TITLE
Save subject in form

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#382]
As a user, I want to associate subjects in forms.

The choice of subject should be using the same way we search for relatives. 

Such observations should be displayed always as the observation value of the identifying concept (section 3.3 in the design document). Note that this information is present on the form element. When clicked/tapped the dashboard of the subject should be opened.

Multiple subject selection should be possible.

Out of scope

Associating to an enrolment
Design document
https://docs.google.com/document/d/1WLhNl05Mj05Cps9SReRt8cp6rF-mx09N_xfD1rbg-_4/edit#

**Comment by vindeolal** [comment]
Create SingleSelect and Multiselect Subject type concept for this to test both senarios.

Staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-e1ec-2020-10-12-11-07-40.apk
