### ISSUE TITLE
Collect More device info / Sync Telemetry

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-client#385]
### Context
We are currently collecting some device info through sync telemetry. These are device_name, android_version, app_version
Certain parameters are not working like device info is not helping us know the brand. Many times clients want a recommendation for mobile phone models we should procure. Also we would need some other insights like RAM to help correlate the device status with issues

We are already using a library. We can collect more params using the same library
1. We should have following info to be able to provide recos : Mobile model, Max memory
2. To help supervisors with HR :  Power state, App version, Pin set

### Tech
Methods to use
https://github.com/react-native-community/react-native-device-info#getbrand
https://github.com/react-native-community/react-native-device-info#getfreediskstoragenew
https://github.com/react-native-community/react-native-device-info#getmaxmemory
https://github.com/react-native-community/react-native-device-info#getdeviceid
https://github.com/react-native-community/react-native-device-info#getpowerstate
https://github.com/react-native-community/react-native-device-info#getsystemversion
https://github.com/react-native-community/react-native-device-info#ispinorfingerprintset
https://github.com/react-native-community/react-native-device-info#getdevicetype

We will have to change the model to support all these params and more if we have in future. A Json type would be better suited.

**Comment by hithacker** [comment]
Notes:
This package has moved to a new version which has converted the methods to async so if we move to new version of this package then we will have change our implementation to use these async methods. First, we should try to not upgrade the version and try using the same version to get all this information. If we can not get this information using the same version we are using then we can think of upgrading.

**Comment by vindeolal** [comment]
New column `device_info` of type `jsonb` is added to `sync_telemetry` table. Below is the device information we are capturing right now.
```
{
  "brand": "Android",
  "carrier": "Android",
  "maxMemory": 100663296,
  "deviceType": "Handset",
  "isEmulator": true,
  "powerState": {
    "batteryLevel": 1,
    "batteryState": "full",
    "lowPowerMode": false
  },
  "totalMemory": 2050650112,
  "manufacturer": "Genymotion",
  "lastUpdateTime": "19 Jan 2021 06:08 pm",
  "freeDiskStorage": 11336990720,
  "firstInstallTime": "19 Jan 2021 06:08 pm",
  "isLocationEnabled": true,
  "isPinOrFingerprintSet": false
}
```

Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-49c44-2021-01-19-18-58-26.apk

**Comment by arjunk** [comment]
@vindeolal as discussed see if two more params can be added : 1. wifi or data network 2. If data network, what generation it is (2g, 3g, etc)

**Comment by vindeolal** [comment]
@arjunk added `connectionType`(none, wifi, cellular, unknown) and `effectiveConnectionType`(2g, 3g, 4g, unknown) information.

```
{
  "brand": "Android",
  "carrier": "Android",
  "maxMemory": 100663296,
  "deviceType": "Handset",
  "isEmulator": true,
  "powerState": {
    "batteryLevel": 1,
    "batteryState": "full",
    "lowPowerMode": false
  },
  "totalMemory": 2050650112,
  "manufacturer": "Genymotion",
  "connectionType": "wifi",
  "lastUpdateTime": "22 Jan 2021 06:05 pm",
  "freeDiskStorage": 11343851520,
  "firstInstallTime": "22 Jan 2021 06:05 pm",
  "isLocationEnabled": true,
  "isPinOrFingerprintSet": false,
  "effectiveConnectionType": "unknown"
}
```
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-209d-2021-01-22-21-18-49.apk

**Comment by arjunk** [comment]
@vindeolal  For me, if the selected connection is 4g it keeps showing that even if the actual connection is different. But clearing this for now.
