### ISSUE TITLE
Media link gets updated on db but media file is not present in s3

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#387]
https://avni.freshdesk.com/a/tickets/777
In Shelter for some cases, they are getting an error when clicking on the media URL link. This is happening because the file with that name is not present in their s3 bucket.
One such case is https://prod-user-media.s3.ap-south-1.amazonaws.com/shelter/9fd9f1f3-a952-4ada-b9c2-a7bfb6e6e270.jpg

**Comment by garimadosar5** [comment]
Issue is resolved so marking it closed.
