### ISSUE TITLE
[Household] app is crashing when user adds a family member.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-client#389]
**Describe the bug**
Steps are given below and this is happening only for IHMP staging. On Yenepoya UAT, it is working fine.

**To Reproduce**
ihmp-staging/password
1. Go to a registered Household or register a new HH
2. Click on 'Add member'
3. select a relation and register new member
4. Fill information.
5. Select Gender and app crashes.

**Expected behavior**
User should be allowed to add a member in a household.

**Screenshots**
![Screenshot_20201003-124944.jpg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/27019f38-9e7c-4b94-bc67-85661b73dfd3)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [x] Does the fix require extensive regression testing?
- [x] Are you mentioning the required scenarios that could be affected?

Test scenarios
- Test with the implementation which has single gender  for selected relationship (IHMP).
- Test for the implementations having multiple genders(male/other) for a given relationship (yenepoya and jsscp).

**Comment by vindeolal** [comment]
Staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-f05b7-2020-10-05-12-45-02.apk

**Comment by arjunk** [comment]
@vindeolal @garimadosar5 anything pending to close this?
