### ISSUE TITLE
Respect dynamically generated answer options

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-client#399]
### Context
Implementers will start specifying which answers to show. The client should consider the data coming from showAnswers method in FormElement Rule and show them accordingly. 

### Acceptance Criteria
1. As a field app user, i should see only the subjects/concepts that are specified by the implementer using the showAnswers function
2. If the answers to be selected are from less than 20, I should see the same widget like for coded answers (single-select / multi-select). Subjects should be sorted alphabetically. 
3. If the answers to be selected are more than 20, then it should continue to the existing behaviour that is search. 
4. As a field app user i should see the name of the subject. Clicking on names should select the answers (like coded answers) and not take me to subject page. 

### Tech
1. Ensure that this number 20 in not deep hardcoded. It should be present in some constants file or some global place with a clear name. If possible we should do the small refactoring of bringing other such constants all at one place. One example of such constant we recently introduced is when to show the search option.
2. If the answers to be selected are more than 20, i should see search option for subject which what is there already. For concepts we are not doing anything in this story. We will handle the case of concepts more than 20 in another story. 
3. We will receive uuids from the rule, which we will have to convert to uuid+name object. The name will be used to show on the UI and the uuid will be persisted in observation.

**Comment by 1t5j0y** [comment]
- [x] Use updated rules config
- [x] Update avni-client FormElementStatus definition to include answersToShow
- [x] Update avni-models -> FormElementGroup `filterElements` to set answersToShow in the formElement
- [x] Add componentWillMount to MultiSelectSubjectFormElement and SingleSelectSubjectFormElement to fetch subjects based on answersToShow value.
- [x] Update MultiSelectSubjectFormElement and SingleSelectSubjectFormElement to render similar to coded answers when answersToShow is present and count is less than 20. Render search UI otherwise.
- [x] Sort subjects by name alphabetically.
- [x] If answersToShow is provided and search UI is used, restrict search to values within answersToShow
- [x] Update avni-models -> FormElement `getAnswers` to consider answersToShow for coded form elements

**Comment by 1t5j0y** [comment]
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-208c-2020-11-04-16-34-44.apk

**Comment by garimadosar5** [comment]
'use strict';
({params, imports}) => {
  const individual = params.entity;
  const formElement = params.formElement;
  const statusBuilder = new imports.rulesConfig.FormElementStatusBuilder({individual, formElement});

  statusBuilder.showAnswers("1c6eca55-9eb0-4b0e-b3d3-b72ef6fef43e",
"30c5d22a-19c9-465d-90e6-be36d711469e",
"f7b439f1-347a-40ea-8f2a-ed13398e2ea5",
"6b83cc43-ca1f-4c5d-9258-5e914d8ee958",
"c0d39b24-5f3b-4ec3-926a-b0845e4691a3",
"c111f183-7e97-4595-b9ef-746944147156",
"891e11dd-ba83-4744-8526-0c2bba0af78e",
"790fabd9-16e3-40b6-81b0-75951868a43e",
"12788fa2-b75f-4719-80dc-35cc2138c12c",
"454b3323-7ca0-49eb-b15a-8e8f385246d8",
"48319786-c284-4fc7-8129-b3393df989bd",
"4741ba69-5c62-4aae-9e7f-50b992ae7990",
"a2f58612-90be-47f4-bb94-4de4e17da6c4",
"555c4c1a-c902-47f5-b14f-c39956853e1c",
"6d07b25f-80c5-4a7d-925d-5b2a70cb5733",
"e067d2ca-d71b-46fd-8e16-aff3ebcd134c",
"5fb93846-5748-4e15-8d45-c4609698b726"
);

//statusBuilder.showAnswers("103c1c04-57cf-45a5-9a2d-cc51e97dfb1f", "ef5f1c30-0063-4250-a1b9-fd7308001e21","2b35da3a-af90-4005-a3c7-c3350317c373","cb03a8a0-0a5c-4b21-a981-e677ec45441a");

  return statusBuilder.build();
};

**Comment by 1t5j0y** [comment]
Fix included to not display voided subjects even if showAnswers returns such uuid(s).

APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-d36a7-2020-11-09-11-43-15.apk
