### ISSUE TITLE
Auto select RadioButton if only one mandatory option is there in formElement

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-client#402]
Make autoselect form element if only one mandatory option is there in formElement

**Comment by garimadosar5** [comment]
@sachsk Share the latest staging apk.

**Comment by sachsk** [comment]
APK for testing:- https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-41bb5-2020-11-05-10-51-27.apk
