### ISSUE TITLE
Should be able to use Spinner control in Time concept

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-client#405]
### Motivation
Give users a choice of using clock or spinner mode for choosing the value of a time concept.

### Acceptance Criteria
- In user settings, there should be an option to choose time picker mode from options 'clock', 'spinner', 'default'.
- On the form element in the app designer, there should be an option to choose time picker mode from options 'clock', 'spinner', 'default'.
- In the android app, based on the app designer option:
  - 'clock': Show a time picker in clock mode.
  - 'spinner': Show a time picker in spinner mode.
  - 'default': Show a default time picker based on Android versions.
- Form element setting should override the user setting.

### Tech Approach
Use the same approach as used in the Date concept.

**Comment by 1t5j0y** [comment]
- [x] Webapp: New user level setting to capture time picker mode
- [x] Webapp: Update app designer to show time picker mode setting for form elements using concepts of type Time
- [x] Models: Add method to fetch timePickerMode to FormElement
- [x] Field app: Apply form element and user level settings while displaying Time based form elements

**Comment by 1t5j0y** [comment]
1. for date time fields, if date picker mode is explicitly set (via form element or user setting), time picker mode will follow the date picker mode regardless of user setting (for consistency in display). Is this ok? For eg: The only scenario where date will be shown as calendar and time shown as spinner is:
1.1 Form element does not specify date picker mode
1.2 User does not have date picker mode setting set
1.3 User has time picker mode set to spinner
2. date and time controls used outside of form elements. (Filters etc) - user setting needs to be considered there?
3. currently used [date](https://reactnative.dev/docs/datepickerandroid) and [time](https://reactnative.dev/docs/timepickerandroid) react components are deprecated. move to [datetimepicker](https://github.com/react-native-datetimepicker/datetimepicker)?

**Comment by 1t5j0y** [comment]
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-5ebe-2020-12-04-19-04-58.apk
