### ISSUE TITLE
View filter not working for Vaccination checklist form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#407]
**Describe the bug**
 The view filters are not working and the following error is getting logged in Rule failure telemetry--
**_t.cloneForEdit is not a function. (In 't.cloneForEdit()', 't.cloneForEdit' is undefined)_**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- Does the fix require extensive regression testing?
  - No
- Are you mentioning the required scenarios that could be affected?
  - Not required

**Comment by hithacker** [comment]
@nupoorkhandelwal Can you put the rule code also here?

**Comment by hithacker** [comment]
Staging apk https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-da95dd-2020-12-22-16-45-00.apk
