### ISSUE TITLE
Custom filter search crashes in case there are lot of program encounters 

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#410]
**Describe the bug**
We are loading all the program encounters into the memory before we filter based on the selected option. In case there are lot of program encounters, app crashes because it can't load all the object into memory.

**To Reproduce**
- watch the video at https://avni.freshdesk.com/a/tickets/1011
- Restore JSCS dump in the emulator.
- There is already Hemoglobin genotype filter created. Select any value from the options and click on search. 
- App will crash

**Expected behavior**
- App should return the filtered result

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by vindeolal** [comment]
Staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-0a4c8-2021-01-06-13-12-59.apk

**Comment by garimadosar5** [comment]
It takes too much time to apply search filter in case of too much data.
created a separate card for that: https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-client/412
