### ISSUE TITLE
Scheduling general encounter for same / other subject from program enrolment/encounter does not work

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-client#414]
**Describe the bug**
Any general visits scheduled via the visit schedule rule for a program enrolment or encounter schedules it as a program encounter. 

**Expected behavior**
General encounter should be scheduled.

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [x] Are you mentioning the required scenarios that could be affected?

 

Scenarios

- [x] From program encounter, schedule general encounter for same subject - Pass name of general encounter in the rule

- [x]  From program encounter, schedule general encounter for other subject - Pass subjectUUID parameter for other subject

- [x]  From program encounter, schedule program encounter for same subject - Pass name of program encounter in the rule

- [x] From program encounter, schedule program encounter for other subject - Pass programEnrolment parameter for the other subject and name of program encounter applicable to that subject.

- [x]  From general encounter, schedule program encounter for same subject - Pass programEnrolment parameter for the same subject

- [x] From general encounter, schedule program encounter for other subject - Pass programEnrolment parameter for the other subject.

- [x]  From general encounter, schedule general encounter for same subject - Pass name of general encounter

- [x]  From general encounter, schedule general encounter for other subject - Pass subjectUUID parameter and name of general encounter.

**Comment by 1t5j0y** [comment]
- [x] Scheduling general/program encounter for other subjects from program enrolment/encounter
- [x] Scheduling general encounter for same subject from program enrolment/encounter

**Comment by 1t5j0y** [comment]
~APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-49c44-2021-01-15-14-48-34.apk~

APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-8dba-2021-01-18-17-53-40.apk

Scenarios:
1. From program encounter, schedule general encounter for same subject - Pass name of general encounter in the rule 
2. From program encounter, schedule general encounter for other subject - Pass subjectUUID parameter for other subject
3. From program encounter, schedule program encounter for same subject - Pass name of program encounter in the rule
4. From program encounter, schedule program encounter for other subject - Pass programEnrolment parameter for the other subject and name of program encounter applicable to that subject.
5. From general encounter, schedule program encounter for same subject - Pass programEnrolment parameter for the same subject
6. From general encounter, schedule program encounter for other subject - Pass programEnrolment parameter for the other subject.
7. From general encounter, schedule general encounter for same subject - Pass name of general encounter
8. From general encounter, schedule general encounter for other subject  - Pass subjectUUID parameter and name of general encounter.

**Comment by nupoorkhandelwal** [comment]
For scenario 5 From general encounter, schedule program encounter for same subject - Pass programEnrolment parameter for the same subject 
Getting this error after We click on "Save" the general ecounter.

![screenshot-2021-01-22_15.59.27.129.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/77267f5a-7d48-402a-bf2e-f962e5790baf)

**Comment by nupoorkhandelwal** [comment]
Its working fine.
