### ISSUE TITLE
Remove older drafts automatically

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#416]
## Story
Drafts older than 30 days should be auto-removed from the system so that the list of drafts does not increase endlessly. 

Please see epic for context. 

## Acceptance criteria
- There is a job that runs every night and removes drafts that are older than 30 days
- There is a message on the drafts list that mentions that "Drafts will stay here for 30 days, after which they are deleted."

**Comment by vindeolal** [comment]
- Drafts are removed after 6 hours of closing the app. 
- To test it first create some drafts. Next, change the device date to some future date that is greater than 30 days from the day when drafts were created. Now close the app. Now open it after 6 hrs, those drafts should get deleted.

Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-5fc6-2021-02-03-18-06-51.apk

**Comment by garimadosar5** [comment]
QA Notes - 
Draft are not getting deleted after 30 days. - (Org - Yenepoya Staging)
![Screen Shot 2021-02-08 at 7.58.01 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/63ca6d4a-f692-4595-b7c1-84c9b5c30f64)

**Comment by vindeolal** [comment]
It works for me when background job time is set to every 15 mins. Can you try with this APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-d5b57-2021-02-11-17-10-32.apk. In this timeout is 15 mins and I checked, it deletes the older drafts after 15-20 mins of closing the app.
