### ISSUE TITLE
Remove out of sync drafts

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#417]
## Story
During sync, when there is a change in the registration form, we should be removing all drafts from the system for that subject type so that new registrations do not use the old form

Please see epic for context. 

## Acceptance criteria
- When there is a change in the registration form for a subject type, all draft subjects created for that subject type are deleted. 
- Draft subjects of other subject types are not removed

**Comment by vindeolal** [comment]
APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-5fc6-2021-02-03-18-06-51.apk
