### ISSUE TITLE
Phone number form element

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#418]
## Story

As a data entry user, when a form has the phone number form element, then a corresponding field is shown on the screen. 

## Design
https://preview.uxpin.com/dd0056db40a31fbc518076fd5ab9cc1b8437b144#/pages/135816808/simulate/sitemap?mode=i
https://preview.uxpin.com/dd0056db40a31fbc518076fd5ab9cc1b8437b144#/pages/135816816/simulate/sitemap?mode=i

## Acceptance criteria

A detailed workflow of the flow and data storage is provided in https://docs.google.com/document/d/1LW9qrdXMspB_6GUD-yEfOOOk_jOpTxwr9DKiTfrZmC0/edit#

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-666d8-2021-02-12-15-06-41.apk

**Comment by garimadosar5** [comment]
QA Notes - 
No place to put OTP.
![Screen Shot 2021-02-14 at 1.32.27 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/67a8d37b-4334-43f2-9ccd-66deb3352b29)

**Comment by vindeolal** [comment]
@garimadosar5  You'll need to edit the older msg91 configuration, so that otp length gets saved in the org config. Right now I'm guessing you are using the older msg91 config for that org.
