### ISSUE TITLE
[AndroidApp] Approve a form

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#422]
As part of this story, we will complete the flow to approve a form. 

### Acceptance criteria
- For standard report cards of type Approve, Reject or Pending, take user to default listing page
- From listing page, take user to the detail page (https://preview.uxpin.com/dd0056db40a31fbc518076fd5ab9cc1b8437b144#/pages/135496271/simulate/sitemap?mode=i)
- For rejected forms, the rejection reason will be shown on this screen (Not on visualisation)
- There are 4 buttons on this page - Approve, Reject, Edit and Details. Approve and Reject show up for pending cards when user has permission. Edit is available for Rejected cards. Details is available for all cards
- When Edit is pressed, take user to edit the item
- There is a confirmation dialog before save (https://preview.uxpin.com/dd0056db40a31fbc518076fd5ab9cc1b8437b144#/pages/135700472/simulate/sitemap?mode=i)
- There is a rejection dialog before save (https://preview.uxpin.com/dd0056db40a31fbc518076fd5ab9cc1b8437b144#/pages/135700476/simulate/sitemap?mode=i)
- Approval status is stored in client and synced to server. 
- When a user creates or edits a subject/enrolment etc, approval status is set to "pending" by default if it is not Rejected. 
- If form is currently rejected, there is a popup that confirms from user if the form should be sent for approval. Status is changed to 'pending' only when user says yes. 
- Approvals work for registration, program enrolment, program exit, encounter, program encounter and checklist requests. 

### Out of scope
- Approval screen as provided in design
- Header in rejected requests

**Comment by vindeolal** [comment]
To enable approval workflow we need to enable it in the org config. Right now that is not possible from the admin interface. Use SQL to add that.
```
with audits as (
    update organisation_config set settings = settings || '{
      "enableApprovalWorkflow": true
    }'::jsonb
        where organisation_id = (select id from organisation where name = 'Demo test')
        returning audit_id
)
update audit
set last_modified_date_time = current_timestamp
where id in (select audit_id from audits);
```

Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-81423-2021-02-23-14-14-16.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- Form name is going out of the box. Apart from this everything is working.
![Screen Shot 2021-02-26 at 9.16.58 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/ac7c7779-2908-4b27-b69d-1f4005b6f7e0)

**Comment by vindeolal** [comment]
APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-00059-2021-03-01-13-07-06.apk
