### ISSUE TITLE
Display based on privileges for approval workflow

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#424]
As part of this story, we will provide the ability to limit custom dashboards and approval/rejection of forms using privileges. It is assumed here that the required privileges and groups have already been added. 

### Acceptance criteria
- Custom dashboards will be shown only to those who have permissions
- Approval/rejection button will be enabled only to those who have permissions
- Edit button will be available only when there is permission to edit the enrolment/encounter/subject.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-4540c-2021-02-24-18-18-00.apk
