### ISSUE TITLE
[AndroidApp] Make a custom dashboard as the primary dashboard

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#425]
Now that we have custom dashboards, it will be useful to have a custom dashboard as the primary dashboard for an organisation. 

### Acceptance criteria
- When a custom dashboard is made as primary dashboard, it shows up in the beginning when opening the app
- When there are no primary dashboards, default behaviour works fine
- User should be able to add sections and define the viewType for each section from webapp, which will be handled in the client side.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-4540c-2021-02-24-18-18-00.apk

**Comment by vindeolal** [comment]
APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-00059-2021-03-01-13-07-06.apk
