### ISSUE TITLE
[avni-client] Voided relationships showing up in app

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#429]
**Describe the bug**
Check on yenepoya org, we have voided duplicate relationships and there are still appearing the app, even after fresh sync.

**Expected behavior**
Ideally, voided relationships shouldn't show up in the app while adding relatives in the household.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-86dd6-2021-02-11-17-56-28.apk

**Comment by nupoorkhandelwal** [comment]
@Yenepoya Prod. 

- [ ] **Whenever a relative is added, voided relationships start showing up.** 

- [ ] **Also, not all relations are available in the app. There are almost 16 non-voided relations created on webapp**

**Comment by vindeolal** [comment]
@nupoorkhandelwal 

This is a Metadata issue, and not related to the platform. I have fixed the data for Yenepoya prod, please test it out.
