### ISSUE TITLE
Sync and display of icon on avni-client

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#430]
As a field-app user, when there is an icon for a subject type, it is shown in the results. 

### Acceptance criteria
- Icons are synced and stored in local storage
- Icons are shown on the search results and the subject dashboard
- Default icons are shown when no icon is already configured

### Additional tasks
- New default icons for individual, person, group, and household subject types.
- Display the icon on the register screen.
- All the subject listing screens should also display respective icons.

**Comment by vindeolal** [comment]
staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-0363d-2021-09-10-11-57-30.apk
