### ISSUE TITLE
[FieldApp] Show broadcasts

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#433]
As a user, when I click on an item on the news broadcasts, I will be shown the broadcast (see https://preview.uxpin.com/dd0056db40a31fbc518076fd5ab9cc1b8437b144#/pages/135862252/simulate/sitemap?mode=i)

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-7eeb-2021-03-17-11-08-04.apk

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Translations are missing.
