### ISSUE TITLE
[AndroidApp] Subject should have ability to comment and view comments

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#434]
As an Android app user, I should be able to view and comment on subjects. 

### Notes
- We do not support threaded comments, or comment status (resolved etc) in this iteration of comments. 

### Acceptance criteria
- When I go to the subject dashboard, I should be able to see comments by pressing on the comments icon on the top right (see https://preview.uxpin.com/dd0056db40a31fbc518076fd5ab9cc1b8437b144#/pages/136010047/simulate/sitemap?mode=i)
- When I press on the comments icon, I should be able to see the list of comments for the subject (see https://preview.uxpin.com/dd0056db40a31fbc518076fd5ab9cc1b8437b144#/pages/136010285/simulate/sitemap?mode=i)
- I should be able to post a comment on this screen

**Comment by vindeolal** [comment]
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-26aab-2021-03-25-11-11-43.apk
