### ISSUE TITLE
[Androidapp] View comments on home screen

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#436]
As an AndroidApp user, when I have comments present, there should be a tab to show them on the home screen (similar to offline dashboards)

### Acceptance criteria
- When there are no comments, then no screen is shown.
- When there are comments, the option is shown, which takes you to the list of comments (ordered by last-updated). See https://preview.uxpin.com/dd0056db40a31fbc518076fd5ab9cc1b8437b144#/pages/135852729/simulate/sitemap?mode=i. Rename heading to comments, and use only the comments. Date should be shown (not just time as displayed in the design). 
- On pressing on a list item, user is taken to the subject dashboard of the subject on whom the comment is made

**Comment by vindeolal** [comment]
This is done using a standard report card of type "Comment" which can be added to the dashboard and will display the list of open comment threads.

https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-2fce88-2021-04-01-18-16-56.apk
