### ISSUE TITLE
Audio form element in client

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#439]
Implement the audio form element in avni-client. 

## Acceptance criteria
- When there is an audio form element, it provides the ability to record
- Once audio is recorded, it is saved like other media elements
- Audio is uploaded to S3 during sync and downloaded on-demand
- Icons on the subject dashboard for audio elements. 

### Tech
Several libraries such as https://www.npmjs.com/package/react-native-sound-recorder allow sound recording.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-39a5-2021-04-26-10-49-38.apk

**NOTE: Audio recording might not work properly on the simulator, it is good to test this on a real device.**
