### ISSUE TITLE
Add button near to the phone number when verification is required

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#440]
It will be useful to have the verification of phone numbers to be done as a button right next to the phone number for verification. 

### Acceptance criteria
- Once we verify through the button, we should go back to the same form element group, because the page might not have been filled
- If verification was not done, we go to the verification page as usual

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-ef291-2021-03-05-16-24-35.apk
