### ISSUE TITLE
Group affiliation form element type

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#445]
### Acceptance criteria

- New group affiliation form element type to be created
- It should provide options of group subject type that should be selected
- Add new subject selection option when GA form element type is chosen
- Save subject as part of the group when registration is complete
- Do not save values of the GA form element type as obs in the subject
- When subject is already part of the group, show association on edit
~- Do not show option for GA form element type when form is not of type registration~
- Form stitching to support member removal from the group

**Comment by vindeolal** [comment]
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-12b9-2021-03-29-17-18-56.apk

**Comment by vindeolal** [comment]
- Group affiliation form element can be used in registration/enrolment.
- Form stitching to remove the member from the group can be done using worklist updation rule, below is an example to stitch it at the program exit of the program "Car program".

```
({params, imports}) => {
    const workLists = params.workLists;
    const context = params.context;
    const WorkItem = imports.models.WorkItem;

    const main = () => {
        const currentWorkItem = workLists.getCurrentWorkItem();
        if (currentWorkItem.type === WorkItem.type.PROGRAM_EXIT) {
            const programEnrolment = context.entity;
            const groupSubject = _.find(programEnrolment.individual.groups, ({groupSubject}) => groupSubject.subjectType.uuid === 'fbe58240-b10a-4d7f-b6ba-57cd6c3a5524')
            const currentWorkItem = workLists.getCurrentWorkItem();
            switch (currentWorkItem.parameters.programName) {
                case 'Car program': {
                    if (groupSubject) {
                        workLists.addItemsToCurrentWorkList(
                            new WorkItem("495e255c-335c-4ee5-ae53-6d3487ae3409",
                                WorkItem.type.REMOVE_MEMBER,
                                {
                                    groupSubjectUUID: groupSubject.uuid,
                                    subjectUUID: _.get(context, "entity.individual.uuid"),
				    groupName: groupSubject.groupSubject.nameString
                                }));
                    }
                }
                default: {
                    return workLists;
                }
            }
        }
        return workLists;
    };
    return main();
};
```

APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-913f-2021-03-30-15-41-14.apk

**Comment by garimadosar5** [comment]
**QA Notes -** 
- One group is already selected, it should be blank and the user needs to select the relevant group.
![Screen Shot 2021-04-02 at 11.28.18 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/9971f25a-97b0-4db9-98bb-1d2460dac886)

**Comment by vindeolal** [comment]
@garimadosar5 it will be selected by default if the subject is a part of any group. If subject is not added to any group then you can select it from the options.
