### ISSUE TITLE
Automated Background Sync

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#447]
With the new jobs, automated sync will work. However, we need to be efficient with this mechanism so that we do not overload our servers. 

### Points
- The primary purpose of automated sync is to ensure data does not stay in people's devices. To achieve this, running POST is usually sufficient.
- A full sync can take place a couple of times a day. This will ensure that changes in metadata are synced correctly

### Acceptance criteria
- [x]  Run POST only sync every hour. Ensure job runs only when there is power and network
- [x]  As part backgroundSync, run complete sync, if 12 hours have passed since last complete sync (This ensures metadata changes are pushed to client even when they have not yet synced). 
- [x]  When user triggers sync, disable sync if it is already running in the background (use WorkManager.info), perform user sync and then enable it back. 
- [x]  Do not run if sync is running in foreground: As we replace with dummy-sync job, we should not have issues with background-sync getting triggered during manual-sync
- [x]  Update Dev docs about the Avni-client : Sync workflow as a diagram with summary (Refer to [this](https://docs.google.com/drawings/d/12-EW4lYNCv9VS3SmJz71ik-5TExWGTXk7Mbq-BafHWo/edit?usp=sharing) link)

Additional info:
===========
With regards to requirement _"When user triggers sync, disable sync if it is already running in the background (use WorkManager.info), perform user sync and then enable it back."_ the code changes done is as follows:
As part of manual sync, we'll first replace the "background-sync" job with a "dummy sync" job, perform manual-sync and then, replace the "dummy sync" job again with "background-sync" job.

In react-native-background-worker, when we schedule a job with same jobKey(Name) as an existing job, it replaces the old one with new one. Therefore, above specified steps are supposed to fulfill our need to NOT run background-sync in parallel with manual-sync.

This is done, as we do not have a way to cancel jobs by name directly in react-native-background-worker. We could only cancel by id, but we do not want to store job id in db.

**Comment by garimadosar5** [comment]
@petmongrels @vindeolal Please provide apk to test this.

**Comment by vindeolal** [comment]
@garimadosar5 Stating APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-e8b96-2021-04-06-10-53-27.apk

**Comment by petmongrels** [comment]
The background jobs are likely causing crashes. This is because for some reason android thinks that our jobs can be run in the foreground although we have not allowed for it. This specific line in https://github.com/facebook/react-native/blob/0.59-stable/ReactAndroid/src/main/java/com/facebook/react/jstasks/HeadlessJsTaskContext.java#L92

We cannot allow the sync job to run in the foreground (to get around the issue above) because it is a long-running job.

**Comment by vinayvenu** [comment]
Needs analysis and spike (after the upgrade)?

**Comment by vinayvenu** [comment]
Referring - https://app.zenhub.com/workspaces/product-635b73bded85e50018871ae6/issues/avniproject/avni-client/447
