### ISSUE TITLE
Show indicators when there are unread news broadcasts

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#449]
When there are unread news broadcasts, show an indicator (pink dot) on the "More" icon. 
On the news line item, show number of unread news broadcasts (as a badge). 
When a news item has been read, mark it as read. 
Only non-voided items should be checked for unread.

**Comment by vindeolal** [comment]
We'll not sync back the read status back to the server and will save it on the local DB. This means it'll get reset when a user has read all the articles and does fresh sync.
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-74068-2021-04-06-11-58-24.apk

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Every time I login into the application, it shows me all the broadcasts. even if I already read them.

**Comment by vindeolal** [comment]
@garimadosar5 That's what is mentioned in the comment. We don't sync the read status back to server so when you login after deleting the data it'll show all the news as unread. Right now this is by design.
