### ISSUE TITLE
newly added members in a group subject don't get populate through rules until they are synced

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#452]
**Example**

For JSS UAT, the new children who get added in the group subject through group affiliation concept dont get populated in the daily attendance form.

Rule used to fetch them is --

const groupSubject = params.entity.individual.groupSubjects;
const children = [];
 
groupSubject.forEach((groupSubject) => {
             children.push(groupSubject.memberSubject.uuid);
            statusBuilder.showAnswers(groupSubject.memberSubject.uuid);
        });

**Comment by vindeolal** [comment]
@nupoorkhandelwal Please take the latest of 3.13 to test this on prod.

**Comment by garimadosar5** [comment]
@vindeolal @nupoorkhandelwal please provide apk.

**Comment by vindeolal** [comment]
@garimadosar5 Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-39a5-2021-04-26-10-49-38.apk
