### ISSUE TITLE
Cannot sync the catchment data for new user.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-client#458]
**Describe the bug**
If fast sync is set up for a catchment, it does not work after change password screen for new users.

**To Reproduce**
1. setup fast sync for a catchment.
2. create a new user from the admin app for the same catchment.
3. now logout from the app and login with this new user, he'll go to the change password screen and dbdump sync will fail and regular sync will start.

**Expected behavior**
Ideally, after changing the password fast sync should start followed by the regular sync.

**Screenshots**
![1620368069398.JPEG](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/56608198-78f0-4e39-b907-bbe6a4acdaf0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by garimadosar5** [comment]
@vindeolal Please share the staging apk.

**Comment by vindeolal** [comment]
@garimadosar5 https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-7b4c-2021-05-18-16-18-31.apk
