### ISSUE TITLE
When a new user without catchment sync, it gives error

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-client#467]
Steps - 
1. Create a new user.
2. Do not assign any catchment to the user.
3. Login into app using this user.
4. After change password page, shows the following error
![1622017210081.JPEG](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/af3b5129-74d3-4f94-a39c-33ca6511d6a7)

**Comment by vindeolal** [comment]
Staging APK :https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-35ae-2021-05-28-17-48-44.apk

**Comment by garimadosar5** [comment]
**QA Notes -** 
- when new user without catchment, tries to login, it stays on change password screen and gives error 
[object object]

- It should not be there on change password screen as the password is already changed on first change password click.

**Comment by vindeolal** [comment]
Fixed. We'll close the app once user presses ok button.
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-239b7-2021-06-02-18-00-36.apk
