### ISSUE TITLE
Numeric element does not accept zero after the decimal

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#476]
**Describe the bug**
Try filling in any numeric field with the value 1.01. Once you press the 0 after the decimal, the decimal point disappears

**To Reproduce**
1. Go to fill any form with a numeric field
2. Type 1.01
3. See value filled in

**Expected behavior**
Numeric value should accept right values

**Comment by garimadosar5** [comment]
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-ed37-2021-07-07-12-32-41.apk
