### ISSUE TITLE
Group subject enhancements

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#479]
1. Right now when the user starts registering members to the group from the group dashboard, they can only add two members in a flow. After registering 2 members they again need to press Add member and start the flow. We should not limit this to just two members and provide Add another member option every time in the add member flow.

2. For a Household group, ideally all its members will have the same address as the group. Right now users have to manually select the address for each member of a household. We should instead auto-select the household address for its members and user should be able to change it if they want.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-0169-2021-07-15-16-03-04.apk

**Comment by garimadosar5** [comment]
QA Notes - 
1. Case HH Test.
hh members = 5. When added 5th member it added multipletimes
![Screen Shot 2021-07-15 at 6.02.59 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/95345729-a345-4dcb-8ad9-c5d763dd8d0f)

- Address was not auto-selected for HH members. Case - HH test 2

**Comment by vindeolal** [comment]
@garimadosar5 
1. Relationship setup was wrong. We have fixed it now.
2. This is also fixed.
Satging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-5d81-2021-07-16-12-16-49.apk
