### ISSUE TITLE
Seach filter does not reset the filter values when subject type is changed.

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#481]
In the search filter when subject type is changed, filter values do not reset. This ends up sending the same filter values for the newly selected subject type, even though that filter is not configured for that type.
For example. There is a name filter for subtype1, and the user tries to search by name. Now when users switch to subjecttype2 same name value is passed for search. It is confusing as it does not show in the screen but still uses previous subject type filters to search by.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-a0a7-2021-07-19-14-31-56.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- Org - Garima QA
Setup search filter.
Name for Household and Name for Individual.
Go to DEA and look for filters,No filter available.
Come back to filter setup page. There is no filter available,
![Screen Shot 2021-07-20 at 9.54.20 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/c1c07938-5239-41dc-bb16-2ef79b783a96)
