### ISSUE TITLE
Show home screen on avni-client

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#482]
As an avni-client user, I should be able to see the home screen configured through the avni-webapp when I open the app. 

### Acceptance criteria
- Home screen is shown after logging in
- It will be shown for 2 seconds every time the app is opened
- After 2 seconds, app will transition to regular flow. 
- Default Home screen will be shown if a custom home screen is not available

### Tech tasks
- Sync of home page to android app
- Probable additional changes required for organisation config sync
- Show Home screen if available
- Show default Home screen if none available
- Default Home screen must contain Name of organisation and Avni logo

**Comment by garimadosar5** [comment]
@vinayvenu Please share apk for this card.
