### ISSUE TITLE
Encounter type/program select does not scale well

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#488]
When we start a new program encounter or a program, if there are too many options, modal should be scrollable. Since it is not scrollable, it is not able for us to reach some encounter types or programs.

**Comment by vindeolal** [comment]
Staging APK
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-e5350-2021-08-10-10-41-23.apk
