### ISSUE TITLE
Group subject filter 

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#490]
There are use cases where the user wants to get the dashboard for all the members of a particular group. Users should be able to choose a group and the dashboard will show the scheduled/overdue/all as per the members of that group. 
Right now this is required by JSS, where we have the Phulwari group. From the dashboard user will choose a Phulwari and the dashboard will update the count as per the members of that Phulwari group.

**Tasks**
- Add a new Group Subject filter in the form designer.
- Respect this filter on the client.

**Comment by vinayvenu** [comment]
@vindeolal You meant "Add a new Group Subject ~~type~~ filter in the form designer", right?

**Comment by vindeolal** [comment]
@vinayvenu Yes.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-8a40-2021-08-10-11-34-58.apk

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Filter is taking too much time. ~30 secs for small amount of data.
User - garimad@qa/password

**Comment by vindeolal** [comment]
@garimadosar5 
- There are about 38K individuals on which this filter is applied, so it is taking time.
- Whenever a custom filter is applied we need to compute some result in memory. This is because Realm does not support direct joins. If a custom filter is used with any other filter like location/program then this time will come down.
