### ISSUE TITLE
ID concept value should be modifiable using view filter rule

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#491]
Right now id is not marked used if any rule modifies its value. This happens because before saving the entity we try to find the id by its a value that is already changed by the rule, so the same ID is returned every time.
We should also keep ID's UUID and should use UUID to search the used ID in the observations.

**Comment by vinayvenu** [comment]
Check out the rule for individual registration in "vinay" organisation on staging.

**Comment by sachsk** [comment]
Rule
'use strict';
({params, imports}) => {
  const individual = params.entity;
  const formElement = params.formElement;
  const statusBuilder = new imports.rulesConfig.FormElementStatusBuilder({individual, formElement});
  const idValue = individual.getObservationReadableValue('my new id');
  const _ = imports.lodash;
  if(_.includes(idValue, 'NEW-VALUE')){
    return statusBuilder.build();
  }
  statusBuilder.value(`NEW-VALUE-${idValue}`);
  const response = statusBuilder.build();
  console.log('response', response);
  return response;
};
Test cases

- [x] ID part is changing and it is not appending to same ID.
- [x] On editing the record, it is not changing to back to original ID and it keeps same.
- [x] After saving sync to server -> delete the data -> do a fresh sync -> older records should be fine on edit.
- [x] After fresh sync try to register new records and it should be taking the next ID.
