### ISSUE TITLE
Quite a lot of parallel syncs happening on the android app

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#492]
![image_2021_08_05T05_26_51_201Z.png](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/4ce746ec-1ffb-49b2-96d1-f74741827deb)

Off late, the number of parallel syncs (syncs with the same user and the same start time) have increased quite a lot. 

In many cases, only one of them successfully complete. However, there are situations where more than one sync completes successfully. 

At any point in time, only one sync should be active on avni-client. 

Note: One of the reasons we see this is because if there is a failure, the next sync starts with the same time as the previous one. This also needs to be fixed.

**Comment by vindeolal** [comment]
There are two reasons why parallel sync was happening.
1. As mentioned in the card as well, when the sync fails start_date does not get updated and the next sync uses the earlier set start_date. (This is not really a parallel sync)
2. Actual parallel sync can happen if the user tabs the sync button two times. It calls the sync method two times, both syncs start with the same start_time.

Both these issues are fixed.

Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-e7b4-2021-08-19-17-33-26.apk
