### ISSUE TITLE
Miscellaneous issues on mobile app

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#496]
- The program enrolment modal doesn't show correctly if there is only one program.
- In the search result screen if there are a lot of enrolments for a subjects program name overflows
- In the home dashboard use newer style cards.

**Comment by vindeolal** [comment]
- Check the Dashboard UI on real device as well.
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-f1a4-2021-08-19-11-13-12.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- Home page is not scrollable.
![Screenshot from 2021-08-19 14-40-56.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/7f54b7fd-4050-412f-966f-799214e504fa)
- Suggestion - Check with pthers.
All the blocks should be of same size.
- ![Screenshot from 2021-08-19 14-48-57.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/0267165d-08c1-4d1c-bb47-9e6c24ed7ebc)
Middle row, Right side there is more space left.
Only three blocks can fit in one row so please keep equal space.
- The heading of Home page (Individual/Household/Vehicle etc), this is not in the middle.

**Comment by vindeolal** [comment]
Fixed all issues except card width one. Please sync the translations and it won't appear like that.
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-e7b4-2021-08-19-17-33-26.apk
