### ISSUE TITLE
Reset the user groups before restoring the realm db backup

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#497]
There can be cases where the user who uploaded the db dump might not belong to the same user group as who is restoring the dump. In such cases we want the user groups to sync from start and delete/sync data according to the user who is restoring the DB.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-0ce22-2021-08-23-13-14-23.apk

**Comment by garimadosar5** [comment]
**Test Cases -** 
- Create and restore backup from the same level or same user group.
- Create and restore the backup from same user.
- Create the backup from the user with more permissions and restore from the user with lesser permissions.
- Create the backup from the user with lesser permissions and restore from the user with more permissions.
