### ISSUE TITLE
Upgrade native-base to 2.15.2

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-client#498]
Issue: Some devices (emulators) are displaying incorrect icons (checkboxes and radio buttons)

Solution:
Upgrade native base to 2.15.2
The current native base version is 2.12.1
Right now the latest version of the native base is 3.1.0 but our react-native version does not support this version so we are upgrading it to 2.15.2.

**Task**

- [x] Upgrade native-base
- [x] test all icons

**Comment by garimadosar5** [comment]
**QA Notes -**
- In multi select the tick is showing without clicking on the option.
![Screenshot from 2021-08-27 14-20-47.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/7b626e28-544a-4f31-971e-b3250fe2214a)
