### ISSUE TITLE
Awareness initiatives report

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-client#499]
https://docs.google.com/document/d/1vZffUdoqgApNqNyl-Qqk5fOfYo_jwKYBV5vVXJeaphI/edit#

**Comment by sachsk** [comment]
Report link https://reporting-mahapeconet.avniproject.org/

**Comment by garimadosar5** [comment]
QA Notes - 
- First drill down opens in the same tab but second opens in a separate tab.**Done**
- We fill "plan" encounter in organisation subject type. but there is no information of Organisation is there in the report.**There is no such req.**
- Nashik district data is not there in the report.
