### ISSUE TITLE
Ability to upload and downoad the file

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#501]
If the file concept is used in any form as a user I should be able to upload the file. File MIME type and file max size as configured for a form element should be respected while uploading the file to s3. Display the file name once the user selects a file in the form. The user should also be able to download the file from s3.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-1cc7-2021-08-30-11-21-10.apk

**Comment by garimadosar5** [comment]
**QA Notes-** 
- ![Screenshot from 2021-08-30 22-22-59.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/f36e4323-17c0-4296-a253-04a0600e5e79)
No proper error message.
- Jpeg is also allowed.

**Comment by vindeolal** [comment]
- Deployed translations.
- You can upload any file if file type is not set in the form element.
