### ISSUE TITLE
Check box tick does not appear at the center.

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#504]
Check box tick does not appear at the center. it's slightly on the bottom.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-74d1-2021-09-03-12-35-40.apk

**Comment by garimadosar5** [comment]
It is still not in the middle.
![Screenshot from 2021-09-03 14-59-19.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/8b5cfe61-07ef-4bff-87f7-33c15f658b13)

**Comment by vindeolal** [comment]
@garimadosar5 we can't exactly place it in the middle with this size of the checkbox. Either we'll need to increase the size of the checkbox a little bit. @arjunk is it fine to increase the size of the checkbox a little bit?
