### ISSUE TITLE
Dashboard with standard report cards isn't loading until we perform any action/click

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#505]
**Describe the bug**
After adding standard dashboard in Save the Children Assam Tea Plantation, the dashboard is not getting loaded until we click on any other menu/buttons.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-847d-2021-09-07-17-13-03.apk
