### ISSUE TITLE
Offline dashboard bug

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-client#506]
**Describe the bug**
Back button does not work in offline dashboard.

**To Reproduce**
1. click on Dashboard on the client.
2. Click on any number and go to line list.
3. Now click on back button and come out of line list.
4. Now again press the back button or try to go to other dashboard. It takes too much time to execute the command and it feels like it is stuck.

**Expected behavior**

**Screenshots**
![Screenshot_2021-09-07-19-30-24-54_e67de974eab1ae435bf1faa372eb4549.jpg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/98988467-2f1e-49c8-9bcc-f22553fc21a3)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by vindeolal** [comment]
staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-0363d-2021-09-10-11-57-30.apk
