### ISSUE TITLE
Deselect the auto-selected answer on edit.

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-client#507]
**Describe the bug**
if there is only one answer remains for multi-select ques. it will select automatic but when we edit that question and changed the answer then the old selection is remains selected.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-e998-2021-09-10-17-28-18.apk

@sachsk the fix is pushed to master. Please check it out.
