### ISSUE TITLE
In the dashbord filter restrict user from selecting both program and general encounters

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#515]
- Right now even user selects a program we still query the encounter table to get the scheduled/overdue visits. This creates confusion. So we should fix this and only show the result as per the filters applied.
- There is another situation where users can select a program visit and one general visit to filter with. Taking common subjects might slow down the query so we should not allow users to select both at the same time.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-59f7-2021-09-16-17-38-24.apk

**Comment by arjunk** [comment]
Close this ticket when deployed to production : https://avni.freshdesk.com/a/tickets/1433
