### ISSUE TITLE
Call only the required sync APIs

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#517]
Use `/entitiesToSync?now=currentTime` API to get the list of entities that have changed and are required to sync. Use the now time param sent by the same API.

**Comment by garimadosar5** [comment]
**Test Scenarios -** 
-

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-01893-2021-10-04-11-12-37.apk

**Comment by garimadosar5** [comment]
**QA Notes -** 
- sync message is incomplete.
![Screenshot from 2021-10-04 15-13-29.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/2beda364-596b-4bbc-b36a-1447864635d7)

**Comment by vindeolal** [comment]
New APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-b2e6f-2021-10-04-16-23-01.apk
