### ISSUE TITLE
Handle changes for subjectMigration

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#520]
This is how we will handle subjectMigration entities

- SubjectMigrations are synced into device
- After sync is complete, we look at all new subjectMigrations (There will be a flag that says if a migration has been processed or not within the subjectMigration table)
- For each subjectMigration, 
    - If old and new addresslevels are part of my catchment, do nothing
    - If old address is in my catchment but new one is not, then delete all details of the subject from device. 
    - If old address is not in my catchment, but new one is, then pull all details of subject to device using the new API
    - For individualRelationships and groupSubjects, save only if both subjects are in the client

### Testing scenarios
- Regular sync testing for regression (first time, subsequent syncs, sync telemetry, test with an organisation with media, sync when media is present vs absent)
- Migration scenarios based on permissions
- Migration scenarios for individualRelationships and Groups
- First-time sync with subjectMigrations present
- Testing with old apk to ensure it works with the new server
- Performance of the new APIs

**Comment by garimadosar5** [comment]
- Vaccination checklist
- Access and privileges.
- Group and Household related
