### ISSUE TITLE
Number does not refresh on back button. [Home page]

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-client#523]
**Describe the bug**
On home page, numbers do not get refreshed on back button.

**To Reproduce**
1. Go to pending box
2. Approve/reject a form
3. Now press back and check the number does not change.
4. click on the box and go to the list snd you will get the form there.
5. Now come back and got to some other page. Eg: search page and come back to home page.
6. On page refresh, now the number gets updated.

**Expected behavior**

**Screenshots**
![1633517422898.JPEG](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/9c8a4c19-1857-4e94-badc-4357d1a73e54)
![1633517446955.JPEG](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/754dd966-23b4-43ea-aa8f-b808e6214e84)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by vindeolal** [comment]
@garimadosar5 I was not able to reproduce this on the latest app, seems like it was fixed. Can you pls try it out on the latest app https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-8362-2021-10-28-11-39-05.apk
