### ISSUE TITLE
Hide Keypad when not needed

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-client#529]
Refer the attached video
https://images.zenhubusercontent.com/64590403/2895815b-4240-47f5-9592-acf0c60442ed/whatsapp_video_2021_10_20_at_3_19_38_pm.mp4

The keypad opens up when a text / numeric type question is answered. The keypad should get hidden as soon as we get to know that the user has moved on, say the user selects a coded answer in next question. Alternate way of putting this would be the focus should shift from the text question to the coded question.

**Comment by vindeolal** [comment]
staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-bd6d7-2021-10-28-17-24-35.apk
