### ISSUE TITLE
App crashes when editing the existing member deatils and when save and add new member is pressed

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#530]
Check the last video attached to the ticket: https://avni.freshdesk.com/a/tickets/1479

Try to edit the member and then press save and add a new member, the app crashes.

**Comment by vindeolal** [comment]
staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-cd9df-2021-10-27-17-08-34.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- Edit not working.
User - user@test/password

https://images.zenhubusercontent.com/64590403/af8f9e3b-913e-4fab-8244-e3432c562485/save_not_working.mov

**Comment by vindeolal** [comment]
@garimadosar5 This is happening because the Relationship type is not defined for the relation "Sister in law". I have added the user feedback, so the user will see the message in case such relation is chosen. You can add the relationship type from the app designer.
APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-8362-2021-10-28-11-39-05.apk
