### ISSUE TITLE
Fixing Avni filesystem to use app's workspace for saving any files.

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#539]
**Context**
Recently android has done some [privacy changes](https://developer.android.com/about/versions/11/privacy/storage) on how apps can use external storage. Right now Avni writes everything to external storage and it used to work fine because we had opted out of new scoped storage using `requestLegacyExternalStorage` flag. But during the last release, we had to set the `targetSdkVersion` to at least 30 due to some policy changes. After this change our all filesystem related features broke on Android 11 because requestLegacyExternalStorage is not respected from target SDK version 30.

**Current problem**
Right now if you are on Android 11 and using the latest app, these features will not work, fast sync, DB upload, any media form element(Image, video, audio, file).

**Fix**
As the app can't access external storage, so we'll use the app's workspace to save any file that is required. So from now, all the data will be saved at /Android/data/com.openchsclient/files/Avni/....

**Migration**
For anyone who is below android 11 all the files present in OpenCHS folder will be moved under Android/data/com.openchsclient/files/Avni/. If user is on andoid 11 or above this migration will fail silently and app should continue to work as it is.

**What will change**
Files will get deleted from the above folder in case someone uninstalls the app.

**Test cases**
- App works fine on Android 11.
- Test on some lower Android versions like 9 and 10.
- Above mentioned features should work fine on all versions.
- Migration works fine on devices below android 11. (after installing data under OpenCHS should move to /../Avni/..)
- New app which includes migration should work fine on android 11 as well.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-12d14-2021-11-15-15-30-31.apk

**Comment by garimadosar5** [comment]
QA DONE - 
- Android 6
1. Image (camera and file  system)
2. Video (camera and file  system)
3. Audio (camera and file  system)
4. Document (file  system)
5. DB Upload
6. Fast sync
7. Check media folder on device.
- Android 10
1. Image (camera and file  system)
2. Video (camera and file  system)
3. Audio (camera and file  system)
4. Document (file  system)
5. DB Upload
6. Fast sync
7. Check media folder on device.
- Android 11
1. Image (camera and file  system)
2. Video (camera and file  system)
3. Audio (camera and file  system)
4. Document (file  system)
5. DB Upload
6. Fast sync
7. Check media folder on device.
- Data filled from one device is shown another device.

**Comment by garimadosar5** [comment]
Notes - 
![Screenshot_2021-11-15-19-22-55-47_e67de974eab1ae435bf1faa372eb4549.jpeg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/238e131c-f548-4e9f-8917-d933b1863e60)
For media date column is blank.

**Comment by vindeolal** [comment]
@garimadosar5 we don't store dates in the Media queue and it's fine.

**Comment by vindeolal** [comment]
New app: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-4532e-2021-11-16-12-33-19.apk
