### ISSUE TITLE
Support Attendance UI for existing subject form element

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-client#540]
New attendance UI for the subject from element.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-48dc-2021-11-17-18-34-03.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- Facilitator and students both are showing in attendance list. Facilitator should not be there I guess.
- ![Screen Shot 2021-11-19 at 12.16.49 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/917e3378-a50b-4afd-8d96-291c237a24c2)
Attendance and Task completed both the questions are not separated properly. In one glance user cannot make out that there are two questions.
