### ISSUE TITLE
Fix rule failures from rule failure telemetry 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#542]

**Comment by nupoorkhandelwal** [comment]
For rule --
7182bd8f-006a-49e4-ba2b-0996f4da1df4
22b02753-45b0-4e00-96e2-5f24931680c1
undefined is not an object (evaluating 'medTaken.getReadableValue')


We need to test the diabetes program followups on JSSCP UAT. Once its QAed, will move the changes to JSSCP prod.




For rule failure -
undefined is not an object (evaluating 'programEncounter.programEnrolment .findObservation("Day of month for growth monitoring visit").getValue')

Made changes in Program Encounter Cancellation Form for encounter type Growth Monitoring. Need to test this and will move the fix to prod


And rule failure--
undefined is not an object (evaluating 't.getTime')


This error is coming for those pregnancy enrolments (13 such cases on jsscp prod) who dont have observations (lmp & edd are blank) and their 'ANC Clinic visit' is cancelled. we need to share details to client and ask them to fix such enrolments.And its not reproducible yet.

**Comment by garimadosar5** [comment]
@nupoorkhandelwal there are some old rule failures. Please close them. **Closed**

**Comment by nupoorkhandelwal** [comment]
We need to fix the **undefined is not an object (evaluating 't.getTime')** rule failure.
