### ISSUE TITLE
getAllUnique('name') is not working

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-client#544]
**Describe the bug**
While scheduling the same encounter type visit with a different name using getAllUnique('name')
visits are not scheduled. it shows in summary but in the general tab showing only one visit.

**To Reproduce**
1. Schedule visits for the same encounter type with a different name in registration/encounter.
2. fill the form registration/encounter form
3. Go to general tab
4. See the scheduled visits

**Expected behavior**
It should scheduled all visit

**Test Data**
impl: ywnxtkef
Uname: sachink@ywnxtkef
Password :saman@123

**Additional context**
the rule is present in batch registration of  ywnxtkef implementation 

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by vindeolal** [comment]
Bug description: visitCreationStrategy flag is not respected for the general encounters and hence multiple encounters of the same type can't be scheduled.
This is fixed and pushed to master.
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-9a36-2021-12-20-12-57-05.apk
