### ISSUE TITLE
[Keys] Keys missing for Translation.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/avni-client#545]
**All the places Visit needs to be replaced by Entry**

- [ ] This is filter on completed visits page- 
![Screen Shot 2021-12-21 at 10.41.38 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/960e00af-2fd2-4255-8576-375f4c808f99)

- [ ] This table is on completed visits page - 
![Screen Shot 2021-12-21 at 10.39.56 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/3549a5bf-20eb-4d59-aa71-39d77316df6b)

- [ ] Subject profile page (Completed visits) - 
![Screen Shot 2021-12-21 at 10.37.10 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/3ed2fe4a-48f5-431b-b427-6e72fb165e44)

- [ ] Encounter first page - 
![Screen Shot 2021-12-21 at 10.43.54 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/ffeecc8e-b686-46c9-94ed-26575e4db5bb)

**Comment by vindeolal** [comment]
Keys are generated if you download the web platform translations. There was i18n missing on the client filter screen which is not fixed.
staging apk: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-dca0-2021-12-21-12-27-51.apk
