### ISSUE TITLE
[avni-client] Lowest address level specified in subject type should be respected by client when there are multiple levels in same catchemnt

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#561]
![1644577076205.JPEG](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/4b4e72d6-b35d-4250-b836-dc05932fd363)

**Comment by vindeolal** [comment]
staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-5e778-2022-02-15-10-25-35.apk
