### ISSUE TITLE
Groups on Android app

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#565]
### Acceptance criteria
- Groups are shown with a heading within the app
- If all items in a group are numeric or text, then show them in a grid
- If atleast one of the items is neither numeric nor text, then show them one after another like we normally show form elements
- On the summary and recommendations screen, items that are in a group have a slight indentation towards the right.
- Similar changes will be done on the observations display in PreviousEncounters, SubjectDashboard, Approval screen and all screens related to the Subject/Enrolment/Encounter
- Observations are stored in the form {groupUuid: {itemUuid: value, itemUuid: value}} for non-repeatable values, and as {groupUuid: [{itemUuid: value, itemUuid: value}]} for repeatable values

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-ae65-2022-03-14-09-57-21.apk

**Comment by nupoorkhandelwal** [comment]
Comments -
1. Order of the group elements is changing on different screens >> Approval screens, previous encounter observations. It should remain same .
Right now its changing its order by the latest element which got updated.

**Comment by vindeolal** [comment]
Fixed in this APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-6ccae-2022-03-14-19-00-45.apk
