### ISSUE TITLE
Training Subject Type Registration

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/avni-client#570]
Training
Subject Type: Individual

Training can happen at PHC, Block, District and at State level. Access to be given based on the catchment specific user.

1. Training Form:
https://docs.google.com/spreadsheets/d/1irX8216_JSvLAvpVc5mnQSA1ONlam4FV/edit#gid=975714895

**Comment by nupoorkhandelwal** [comment]
QA comments -

Form is not complete. Fields are not added as per req. doc.
