### ISSUE TITLE
Sequencing for Question group concepts is not displayed correctly in Observations summary screen.

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/avni-client#576]
For STC-CV different age group observations are recorded with total displayed at the end of each category. (Check screenshot).

The Total is sometimes displayed above the entries while sometimes it is also shown in between the entries in Observation summary. Within the form, the Total is after entries only.

![Daily PHC Reporting.jpg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/f6c52aac-3bcb-4173-baa9-6af6b4eb1949)

![Daily PHC Reporting.jpg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/499f4b4f-8526-4f1b-9f4c-0deeaa6af1f5)

**Comment by vindeolal** [comment]
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-7c05-2022-04-06-22-26-08.apk
