### ISSUE TITLE
Profile pic in client

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#581]
### Acceptance criteria
- If subject type allows profile picture, then there is an option to click a pic by touching the profile pic area
- If subject type allows profile picture, then first page of registration has option to add profile picture. 
- Profile pics are synced to server (modifications required to MediaQueue)
- Profile pics are downloaded when someone touches the profile pic area (if it is not already downloaded)
- Image pruning (see PruneMedia.js) does not delete profile pics
- Image pruning deletes pics if not in either observations or profile pics
- Search results and other listing pages - icons will be replaced with images where possible.

**Comment by vindeolal** [comment]
Staging APK link: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-cd0f428-2022-05-23-17-19-59.apk
