### ISSUE TITLE
Info details for the subject name.

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#586]
### Motivation
In RWB, there are rules to create workorders. Since there are multiple people creating the workorder, it is hard to train people to create the right name. With this story, we will be creating a mechanism to add a help text next to the name. 

### Tech notes
- New column name_help_text to be added to subject_type table
- This will be synced to avni-client
- It will be shown below the name until 10 words (assuming 2 lines of text)
- If more than 10 words, there will be an ellipsis, and when clicking on help text, it shows up as a popup with more details

### Acceptance criteria
- When name_help_text is added to subject_type table, it is shown on avni-client
- When name_help_text is long, then it is shortened using ellipsis and shown as a popup on pressing anywhere within the text
- name_help_text can be internationalised
- When help text is not present, there is no unnecessary space in its place

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-58ab-2022-05-12-11-51-05.apk

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-58ab-2022-05-12-11-51-05.apk

**Comment by AchalaBelokar** [comment]
Verified on web and mobile application. The changes are reflecting as per requirement.
