### ISSUE TITLE
Multiple images form element

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#591]
### Acceptance criteria
- Media form elements (Image, Video and File) will have the ability to specify single or multiselect
- Default is single select
- Observation will be stored in the form of {"uuid-of-element": ["url", "url"]} for multiselect options
- App will work even if a multiselect has a string value
- Form elements will be able to add multiple values if multiselect is enabled
- Form elements can delete one of the multiple values added
- If in string form, and observation is edited, then observation is converted to an array
- When enlarging, images are shown in a carousel
- Multiple images are shown when on the subject dashboard/form
- When enlarging, images are shown in a carousel, all files are downloaded when clicking download button. 
- If some files have been downloaded when others are not, then we download all the remaining files as well
- Sync should upload images that are in an array format as well
- Images/files/video are chosen one after another, with an add button that will add another image/file/video
- It should be possible to remove just one item from the list of media elements

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-dfdb-2022-05-26-12-02-55.apk
