### ISSUE TITLE
Encounter form element

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#592]
### Acceptance criteria
- Only encounters within the subject are allowed
- When there is an encounter form element, then a list of options are provided in the form of a coded form element. Names will be provided by options defined in the form element
- Selected encounters will be shown on the subject dashboard as well. The name will be dynamically generated from the encounters
- Observations will be of the form {"conceptUuid": "valueUuid"}
- Multiple encounters will be supported with the form {"conceptUuid": "valueUuid"}

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-574f-2022-05-31-12-39-02.apk

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-574f-2022-05-31-12-39-02.apk
