### ISSUE TITLE
Offline dashboard changes don't reflect, users are required to do a fresh sync 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#594]
**Describe the bug**
Whenever a new card is added or removed from the offline dashboard, these changes don't reflect in the app until unless a fresh sync is done.

**Expected behavior**
Ideally, users should be able to view changes to dashboard after just a sync.

**Comment by nupoorkhandelwal** [comment]
@vinayvenu @vindeolal **Even Users without fast sync setup are not able to view offline dashboard changes when a new card is added or removed from it.**

**Comment by vinayvenu** [comment]
Test Cases
- Plain sync
- Add dashboard sync - Items should show on Dashboard
- Make dashboard primary and sync - Items should shown on Home screen
- Add item to dashboard and sync - Item should be added
- Remove item from dashboard and sync - Item should be removed
