### ISSUE TITLE
Form group should respect display order

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#596]
Group form elements currently do not respect display order. All numeric and text elements are bunched together first, and the other elements are shown next. 

If an implementer wanted this behaviour, she/he can order the elements as is. However, the app currently does not have a mechanism to show it however the implementer chose. 

### Testing scenarios
- Ensure display order is respected irrespective of moving form elements to different places.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-01003-2022-06-09-14-50-27.apk
