### ISSUE TITLE
Image Thumbnail not showing after image upload in repatable group form element

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/avni-client#599]
Repeatable group form element:

For Image upload option, when we click on the upload icon and select the image and upload - nothing shows up and no thumbnail is shown. 

User can not identify if the image has been uploaded or not.

**Comment by vindeolal** [comment]
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-12b52-2022-06-13-18-44-17.apk
