### ISSUE TITLE
Sync and Show tasks as a standard report card

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#604]
### Acceptance criteria
- When a standard report card of type tasks is set on the dashboard of an organisation, the count of incomplete tasks is shown on the dashboard of avni-client
- When a task report card is selected, it shows a listing of cards on the screen
- The listing looks like [this](https://www.figma.com/file/AJY0FkP6SseAEgmMmOBI3C/PoWER) for a task of type "Call"
- Unassigned tasks are not shown for a user
- Only required tasks and task_migrations are synced to a user's device
- All assigned, and only assigned tasks are shown to the user

### Tech tasks
- Definition of a new standard report card for tasks
- Sync of tasks based on assignment
- Migration of task assignments from one user to another
- Sync of task_migration should only migrate tasks that have current user either in the old or new subject
- GET of task assignment in case there is a task that was migrated in 
- Removal of task assignments that were moved out from a user to another
- Show Report card based on tasks on the dashboard
- List of tasks on a standard report card

### Out of scope
- Actions on the report card

**Comment by AchalaBelokar** [comment]
when I am assigned a task to one user to another user it is still reflected in 1st user.

**Comment by vindeolal** [comment]
new APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-d75a-2022-08-31-12-01-01.apk
