### ISSUE TITLE
Task type "Call"

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#605]
### Acceptance criteria
- When there is a "Call" task type that is shown on a listing screen, then it has the following options
  - A Call button that calls the person
  - A mechanism to reschedule the call to a different time
  - A mechanism to change the task status
- When the "Call" button is pressed, the app shows a dialer with the contact_number on the metadata of task. App is still usable during the call. App moves to the next screen - Task Details
- In the Task Details screen, a potential list of subjects is shown based on the contact_number of subjects. 
- If there is a subject_type_id, encounter_type_id or program_id provided in the task, then corresponding options are provided in avni-client
- When the reschedule button is pressed, the user is presented with a date/time option to set the time
- When the "Change task status" button is pressed, there are options to set up a "Task Status". If any of the terminal statuses are selected, then the task is set a completion date. 
- There can be a form associated with a task where we set up some questions. If there is a form, then it takes the regular form flow and gets saved. 

### Visual design
https://www.figma.com/file/AJY0FkP6SseAEgmMmOBI3C/PoWER

### Testing notes
- Tasks can be created by adding them to the database

**Comment by AchalaBelokar** [comment]
1) When the reschedule button is pressed, the user is not  presented with a time option to set the time
2) 9404375389 this no is associated  with subject type beneficiary but not showing while calling the number

**Comment by vindeolal** [comment]
1 is not required.
2 is fixed.
New APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-03ab7-2022-08-24-16-09-16.apk
