### ISSUE TITLE
Timed questions

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#606]
### Motivation
Some questionnaires are time sensitive. One of the usecases here is the LFE Teach questionnaire. 

**Requirements**
- At the end of a particular time, a question will be asked. This will be visible for a particular amount of time after which nothing will be shown. 
- The app should stay active and in foreground during the entire period of the questionnaire so that any time checks are shown correctly
- Timer times should stay steady for the entire time a form is being filled. 

### Design
- New fields form.is_timed and form_element_group.start_time (seconds) and form_element_group.stay_time (seconds)
- Some mechanisms that we have in our current workflow do not work for timed forms. They are
  - Mandatory checks
  - Skipping empty form element groups
- It is assumed that empty form element groups (based on visibility) are not present, and if they are, then the Next Button might not work as expected. 

### Acceptance criteria

1. When a form is timed, a "Start" button will be shown  on the first page. 
2. If the first FEG starts after "0", then app stays on same page
3. At the feg.start_time of each FEG, the form moves to that page
4. The count-up and count-down timers are shown always on each page at the same place. 
5. If there are no form element groups for a particular timeframe (based on start_time and stay_time, then an empty page with just the countup and countdown timers are shown
6. Mandatory checks are not performed in this flow (out of scope for this story)
7. If 2 FEGs have the same start time, then show the Next and Previous buttons to go across the two. 
8. Summary page will be shown automatically
9. Timing stuff will not be shown on edit of form
10. App will be awake during the entire time period
11. Whenever there is a screen change, app vibrates
12. App timer should work even if user goes to a different application during this time

### Tech tasks
- New fields in form and form_element_group
- Changes in App Designer
- Sync
- Change in form rendering

**Comment by vindeolal** [comment]
New changes after discussion with the client,
1. Remove the timed flag from form and add it to FEG.
2. If FEG is timed then the modal with the start button will show and the timer will start.
3. Timer will continue if case next FEG is also timed.
4. For the timed FEGs next and previous will not show up and next will get pressed automatically after stay time is over.
5. Timer will not start again if the user comes back using the previous button and during edit flows.

**Comment by vinayvenu** [comment]
Vibration for 5 seconds is too much. Maybe reduce it to 3 seconds
Home and Back buttons don't work when start button is on the page. 
The count up and count down timers may be best kept away from each other. Count up on the left and count down on the right? 
Timer background color can be a bit lighter?
