### ISSUE TITLE
Task type "Open Subject"

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#609]
### Motivation
This kind of a task takes you to a subject that is defined in the task. The task name gives an idea of what the task is about while the subject that you can do after opening the subject. 

This can be used to open the subject and run eligibility checks etc. 

### Acceptance criteria
- When a task of type "Open Subject" is shown on the listing screen, pressing on it takes you to the subject dashboard of the subject that is associated with the task
- Visualisation will be similar to the "Call" task type except for the call button. All other functionality (change status, reschedule etc) will be available on this task type as well. 

### Testing notes
- Tasks can be created by inserting rows into the task table
- Navigating to the task can be achieved by adding a corresponding dashboard widget

**Comment by vindeolal** [comment]
@AchalaBelokar, The issue was with the task that you created, It was a completed task and we don't show the completed tasks on the dashboard. I have completed on as null now, Please sync and try it now.
