### ISSUE TITLE
Readonly Repeatable Group section should not show add remove buttons

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-client#613]
### Acceptance criteria
- There is an option on the App Designer to "Disable manual addition and removal"
- If present, plus and minus buttons don't show up on avni-client

**Comment by vindeolal** [comment]
Use new key: allowUserToAddRemove

**Comment by vindeolal** [comment]
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-c11a1a-2022-07-19-11-37-19.apk

**Comment by AchalaBelokar** [comment]
<img width="376" alt="Screenshot 2022-07-22 at 4 32 40 PM" src="https://user-images.githubusercontent.com/104890488/180426269-17985b22-d666-44c1-92ad-c3618085cec1.png">
remove button is appearing
