### ISSUE TITLE
Ticket - Growth chart crashing app

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#647]
https://avni.freshdesk.com/a/tickets/2101

### Issues
1. Growth chart crashes when values are in string format. 
2. Growth chart button does not show up when opening the app for the first time

### Test scenarios
- Verify that button shows up on first open of subject dashboard after first open of app
- Verify app does not crash when values for weight/height are strings and not numeric
- Verify the dashboard button does not show up when opening for a non-child program, or switching to it

**Comment by AchalaBelokar** [comment]
When I clicked on beneficiary  screen gets blank out
