### ISSUE TITLE
BackgroundTask run in when in foreground (causing 25% of crashes)

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#648]
**Describe the bug**
One of the major crashes (about 25%) reported in the play store is happening due to this. You will have to navigate to one of the crashes in this to find the stack trace with the message (not all of them have it).

https://play.google.com/console/u/0/developers/7316254808379559958/app/4974885142174090692/vitals/crashes/d6c34dcb4b0ed8c8f92481bf5de9be48/details?installedFrom=PLAY_STORE&days=30&clustering=NEW

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This issue is discussed here and a standard solution has been provided to use AppState and check whether the app is in the foreground or background. See a couple of links below.

https://github.com/jamesisaac/react-native-background-task/issues/65
https://reactnative.dev/docs/appstate

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by vinayvenu** [comment]
Will take care as part of https://app.zenhub.com/workspaces/product-635b73bded85e50018871ae6/issues/avniproject/avni-client/447
