### ISSUE TITLE
Save button not consistently displaying across forms.

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#654]
Steps to reproduce:

On form settings page:
![Screenshot 2022-08-22 at 6.55.29 PM.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/1f00c319-a877-424d-9edb-4c2a5699243d)

Form edit page:
![Screenshot 2022-08-22 at 6.55.39 PM.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/81a8a42a-df02-48a2-8b8c-4f83ce869042)

**Comment by vinayvenu** [comment]
Will take care when we do the UI revamp.
