### ISSUE TITLE
Text getting cut in coded concept answers

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#662]
To reproduce

- Login to staging Goonj organisation
- Fill in activity form
- Second page. Select Agriculture plantation. Look at options. Some have their last word cut off

![image.png](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/6794b9a5-1dcd-45b2-9b9e-dbfef21854c5)

![image.png](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/181407f1-177b-4f3b-9ee5-f7fa3fc2da63)

**Comment by vinayvenu** [comment]
Need to verify what happens when enrolling into program.

**Comment by AchalaBelokar** [comment]
Text is cut at the end coded concept.

**Comment by AchalaBelokar** [comment]
![Screenshot 2022-09-01 at 3.16.44 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/9c534cd9-998d-4e49-8783-06594838adfa)
2nd option is not shown in the objective type
the option needs to show  There was shortage of vegetables in the village/to improve availability of vegetables in the village, hence kitchen garden

**Comment by vinayvenu** [comment]
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-35010-2022-09-26-12-29-55.apk
