### ISSUE TITLE
[APF] Household Registration

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-client#663]
Location Hierarchy - Block >> GP >> Village/Hamlet
Subject Type - Group
Subject Name - Household

Add fields under "Household information" as mentioned in the following requirement document-
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=1229007889

**Comment by Gojo-Taqi** [comment]
Estimated time of completion:- 30 min

**Comment by AchalaBelokar** [comment]
when I click on household this error is coming
