### ISSUE TITLE
[APF] AWC Information

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#669]
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=1321389229

- [x] Create an individual subject type - "AWC area inputs"
Subject registration location will be - "AWC" and registration form will be blank

- [x] Create general encounter under this subject - "AWC inputs"
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=1321389229

- [x] Encounter eligibility check - To be shown only once.

**Comment by utkarshavni** [comment]
updated google sheet link, it was refering to Village input sheet.

**Comment by AchalaBelokar** [comment]
Plz check mandatory fields in the form
