### ISSUE TITLE
idToken should be available in customizable links

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#671]
Patch release (3.28 branch)

As an implementer, I should be able to retrieve an idToken when constructing a url on a customizable menu, so that I can use it to call any Avni API within my extension.

**Comment by vindeolal** [comment]
New param is passed `getAuthToken` which is an async function. Calling this will return the token which can be used in the function

**Comment by himeshr** [comment]
https://images.zenhubusercontent.com/64590403/f98ab526-7d8b-426a-9e2a-4bd4a69cdab6/screen_recording_2022_09_28_at_3_22_14_pm.mov
Please refer to above attached video for demo on opening up DawaPrapatra for a user and downloading pdf for the same.
