### ISSUE TITLE
Start immutable encounters from the first non-filled page

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#674]
### Acceptance criteria
When an encounter type is marked immutable, then when opening the form, it moves to the first non-filled form element group

**Comment by AchalaBelokar** [comment]
Go to the Adolescent organization.
After that enroll in an adolescent program.
There is Addiction Follow-up Encounter or any encounter you need to fill out the form.
On last but one page there is counseling page.

**Comment by mahalakshme** [comment]
the above bug need not be fixed. a story for a new concept type will be created.

**Comment by AchalaBelokar** [comment]
Login Lahi orgniazation
login details AchalaB@lahi, password: password
Fill the student registration form
Fill the program Program Eligibility form encounter
HCL tech bee encounter form

**Comment by AchalaBelokar** [comment]
[Uploading... Screenshot 2022-09-22 at 6.33.36 PM.png]
