### ISSUE TITLE
"Values are not equal" error message displays in concepts.

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#677]
Images to help reproduce the issue:

Check in the same project and form to be able to reproduce the issue. Since it doesn't occur in all cases.

![Screenshot from 2022-09-13 23-56-02.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/13dbdea4-48ec-425b-9fc1-94dd5234b1ef)

![Screenshot from 2022-09-14 00-00-21.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/2ac17168-b17a-4c07-82c6-a98f8b0c38e7)

The error message displays for different types of concepts like multiselect, text, etc.,

**Comment by vinayvenu** [comment]
Different project. Closing this card. 

Added https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/804
