### ISSUE TITLE
Offline cards doesnt get updated until the new data entered in the app is synced

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#687]
Whenever changes or new data is added, it doesn't reflect on the offline dashboard until unless the data is synced.

To reproduce--

In APF Odisha UAT, update the Weight for Height status for any child, the count on the offline cards wont get updated.

It will reflect only after the user syncs the data.

Developer Analysis details:
=====================
This is an issue specifically for CustomDashboards and not for GenericDashboardReportCards(Works for this)
- The issue specified occurs, when user click on Home button and navigates back to the Home screen after updating as specified above.
- The issue does not occur, if the user were to navigate back to dashboard using the "Back button" in upper left corner of our app
- The "refreshCounts" functionality is currently triggerd on following actions, apart from after sync:
    1. Clicking on "Back button" in upper left corner
    2. Clicking on a "Dashboard" to open it
    3. Whenever Dashboard screen gets reloaded (After a sync or otherwise) 

Fix details:
=========
Staging APK with fix for refreshCounts of CustomDashboard on clicking back, home or physicalBack buttons in LandingView and Dashboard view is Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-74daa-2022-10-18-13-48-06.apk

**Comment by petmongrels** [comment]
setTimeout is not needed as redux calls are sync.

if two action
moving it to dev complete as the coding guidelines are not there at the moment and there is legacy of this.

**Comment by himeshr** [comment]
Made the code change to remove setTimeout (), used in refreshCount of customDashboard, as the dispatchAction operation is synchronous.
Dev testing done to verify functionality.

**Comment by himeshr** [comment]
Reverted the commit to make it sync, as the operation might have hidden reprecusions

**Comment by AchalaBelokar** [comment]
https://images.zenhubusercontent.com/64590403/2c0505eb-9766-48aa-85ab-9411da006ed8/20221013_165512.mp4
it is going into next card but still it is reflecting in current one

**Comment by AchalaBelokar** [comment]
1. when we go from the mobile back button it does not reduce the count.

**Comment by himeshr** [comment]
Staging APK with fix for refreshCounts of CustomDashboard on clicking back, home or physicalBack buttons in LandingView and Dashboard view is Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-485d-2022-10-18-14-26-11.apk
