### ISSUE TITLE
Vaccination checklists getting generated on Phulwari program enrolment

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-client#688]
**Describe the bug**
Vaccination checklists getting generated on the 'Phulwari' program enrolment. 

**To Reproduce**
1. Use an implementation like JSSCP which has a program named 'Phulwari'
2. Have a user which has permission for creating checklists
3. With this user enrol an individual in 'Phulwari' program
4. Vaccination checklist is getting generated. Button is not visible. But it is there in realm db and database
5. This is causing Association error for the user with no permission for Phulwari program and blocking the user. 

**Expected behavior**
Vaccination checklist should get generated for only 'Child' program.

**Analysis Notes**
Avni health modules hardcodes childProgramConfig for 'Child' and 'Phulwari' program. This was done because we wanted to show Growth chart for both of these programs. The vaccination button is shown based on checklist rule written on enrolment form but vaccination checklist generation is not dependent on this so it is generating just by the name. We need to stop it as an immediate fix. Ideally, both these features should be dependent on configuration and not on the Program name. 

its still not clear how checklists have started getting created from 3rd Dec only. Also it seems that permission is missing for 'create checklist' as users from Phulwari group are able to create checklist. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by petmongrels** [comment]
Fix - https://github.com/avniproject/JSSCP/blob/master/data%20fixes/checklist-rule-na-for-phulwari.sql

to delete any ongoing checklists created for phulwari - 
https://github.com/avniproject/JSSCP/blob/master/data%20fixes/void-checklists-for-phulwari.sql
