### ISSUE TITLE
Unable to add member to a household in staging

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#689]
This is happening in staging in all projects. From the error in android app, it looks like its because its unable to fetch group roles. In webapp -> app designer -> household subject type, unable to add roles. Nor the existing roles seem to display.

Was occurring because - member role not defined. Hence not a bug. But need to handle the case on app side instead of showing error screen.

**Comment by petmongrels** [comment]
service call is being done from the view, but due to legacy code moving the card to dev complete
