### ISSUE TITLE
UI styling fixes across the app

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#701]
After all the screens are functionally working. Make sure that all the screens in avni-client are UI styling the same as before or acceptable. Note that we are going through UI styling improvement very soon - so this will be changed. We can optimise our efforts accordingly.

- [x] Date/TimePicker clear/backspace button not working (using Touchable or fix button) [HR]

- [x] Subject: list, details, create / edit, summary before save [HR]

- [x] Encounter (subject and Program): list of encounters for subject, details, create / edit, summary before save

- [x] Program: list for subject, details

- [x] Tasks: list, details, schedule, modify status [VS]

- [x] Login screen [VS]

- [x] Check performance of custom dashboard individual listing

**Comment by himeshr** [comment]
Staging APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-15ac-2022-12-08-10-24-24.apk
