### ISSUE TITLE
Quick register subject

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#716]
From the task list, when there are Call Type tasks, the user is sent to a list of subjects. This screen does not have the ability to quickly register a user, which makes the user go back to the home screen to register. 

As a user, I would like to have a "Register" button on the Search Results page that I go to when I click on the "Call" button so that I can quickly register someone if they do not match the list of people in the list. 

### Acceptance criteria
- The list of subjects will also have a "Register" button on the screen
- The Register button will provide the options to choose from all the subject types that user can register (based on privileges)
- Once registration is done, the user is taken to the Subject Dashboard so that they can perform more actions on the user

**Comment by vinayvenu** [comment]
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-ea23-2022-11-03-11-53-23.apk

**Comment by petmongrels** [comment]
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-c9f1-2022-11-14-15-57-00.apk

**Comment by AchalaBelokar** [comment]
https://images.zenhubusercontent.com/64590403/41f84f17-28ba-495f-acb6-3522ee2efc2d/az_recorder_20221115_164410.mp4
unable to find reg button

**Comment by petmongrels** [comment]
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-c01f4-2022-11-16-11-09-54.apk
