### ISSUE TITLE
Redesign tasks screen

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#718]
When tasks are created, we add in metadata to these fields. These are currently not used on the Android app. 
Task search fields are useful to be used as filters as well as within the cards themselves. So are task statuses. As part of this story, we will redesign the tasks screen to include these fields

### Acceptance criteria
- There is a filter button on the tasks list
- The filter button takes you to a page where you can configure - Task metadata search fields and their criteria, task type, task status, created and completed dates. 
- On done, you get back to the page with the filtered list (and the filter criteria on the header)
- The task filter stays unless it is reset
- Task status and search criteria metadata is shown on each card below the phone number.

**Comment by petmongrels** [comment]
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-f8af6-2022-11-11-14-24-24.apk

**Comment by vinayvenu** [comment]
TaskListActions.js - All actions here are creating a new state and not doing a state.clone() of the previous state. This can cause errors in the future if we add a new key.

**Comment by vinayvenu** [comment]
There are no headings for the new buttons added. We should either add them, or drop the column names altogether.

**Comment by vinayvenu** [comment]
TouchableOpacity UI feedback is not that great. We should use TouchableNativeFeedback instead. For icons, preferably to use SelectableBackgroundBorderless() so that the ripple goes above the touch radius.

**Comment by petmongrels** [comment]
1. Created separate issue for touchable opacity - https://app.zenhub.com/workspaces/product-635b73bded85e50018871ae6/issues/avniproject/avni-client/727
2. Removed the heading for phone number/taskName only.....other headers indicate the meaning of icons which is not very obvious.

**Comment by petmongrels** [comment]
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-c9f1-2022-11-14-15-57-00.apk
