### ISSUE TITLE
Odia text is getting cut in UI (matra on top and buttom of alphabets)

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#721]
**For an implementation, APF, Odia text is getting trimmed (matra from both top and bottom)**

![1667215002941.JPEG](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/9044b14a-c76e-4793-b72f-b60d78e5f6b4)

**Comment by vinayvenu** [comment]
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-ea23-2022-11-03-11-53-23.apk
