### ISSUE TITLE
All data has been filled even if it's not an immutable encounter

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-client#726]
Staging app
Org - IHMP
Register a individual and get enrolled into a program.
Complete a visit so a new visit can be scheduled.
Now when you click on the scheduled visit to complete it, it lands you on the final page, i.e, the page where you get to click on save, with all the data to be pre filled exactly like the previous visit.

**Comment by vinayvenu** [comment]
@Gojo-Taqi can you confirm if the encounter type you used was not defined as immutable?

**Comment by vinayvenu** [comment]
There are immutable encounter types defined for ihmp. I tried with other encounter types, and they do not have this problem.

**Comment by AchalaBelokar** [comment]
Unable to reproduce this.
