### ISSUE TITLE
Show scheduled date on the tasks screen

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#734]
We have a filter for scheduled date, but do not show it on the screen itself. With this story, we will add this to the screen.

**Comment by vinayvenu** [comment]
![Screenshot 2022-11-18 at 10.13.02 AM.png](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/6ba88b4b-a1db-409d-8121-59725fca4189)

**Comment by AchalaBelokar** [comment]
when I am trying to click on the schedule it showing fatal error.
