### ISSUE TITLE
App is not showing the correct location hierarchy during registration.

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-client#739]
**Describe the bug**
App is not showing the correct location hierarchy during registration.
Currently, App shows all locations it should show locations which are part of the parent location.

I have tried to see the location mapping so it's present in the DB but not in the realm DB.

**To Reproduce**
Steps to reproduce the behaviour:
login to STCCVUAT organisation.
Go to Volunteer Vaccination Reporting registration.
Check the address field.

**Comment by vinayvenu** [comment]
This needs thorough testing on multiple scenarios to ensure it works.

**Comment by AchalaBelokar** [comment]
@tested on sakhi, stccv,rwb
