### ISSUE TITLE
Ability to filter tasks by scheduled Phone Number

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#741]
Ability to filter tasks by scheduled Phone Number
- [ ] Currently I am trying to filter with mobile no  8218224012 it is not showing any result.
       but I am trying to filter with prefix with 0 like 08218224012 it is working fine.![Screenshot 2022-11-22 at 1.44.26 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/efc84871-4209-42ab-8478-dbd13f99e3a9)

![Screenshot 2022-11-22 at 1.44.57 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/3ed60d5d-b6f0-448c-a8cb-672b2fc3d3f3)

![Screenshot 2022-11-22 at 1.47.14 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/c2f8b5b0-458c-4269-b135-e72ce117d40c)

**Comment by petmongrels** [comment]
The phone numbers used are different. They are differing in more than 0. moving back to ready for qa.
