### ISSUE TITLE
Allow generic extensions

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-client#742]
When we added extensions to be used for menu links, we did not have a mechanism to specify a type for them. With this story, we will allow a new type of extension (Generic extension) that will allow the user to add extensions where the exact extension point may not be defined in Avni. 

### Acceptance criteria
- When adding a new extension, there is an option called "Generic Extension", which will create an extension of that type in the system
- Generic extensions are synced to avni-client (testing only)

**Comment by himeshr** [comment]
![Screenshot 2022-12-05 at 3.34.10 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/1df4bd7e-640d-4894-ab84-670d45520b05)
Introduced a new extension option called "Generic", and updated Staging Sakhi implementation, myDawaPrapatra to use that extention type. After that change was made, post sucessful sync in avni-client, the homeScreen does not show dawaprapatra and instead we are directly shown the dashboard.

Post update, sakhi orgConfig has following json content:
{
  "languages": [
    "en"
  ],
  "otpLength": null,
  "extensions": [
    {
      "label": "myDawaPrapatra",
      "fileName": "final_dawa_prapatra.html",
      "extensionScope": {
        "name": "Generic",
        "uuid": "",
        "scopeType": "Generic"
      }
    }
  ],
  "searchFilters": [
    {
      "type": "Name",
      "titleKey": "Name",
      "subjectTypeUUID": "8ce8db7f-419e-485f-99ba-df7a0372f3de"
    }
  ],
  "myDashboardFilters": [],
  "showHierarchicalLocation": false,
  "customRegistrationLocations": [
    {
      "subjectTypeUUID": "a577a36e-f87a-44e9-b721-1015e889bea4",
      "locationTypeUUIDs": []
    }
  ]
}
