### ISSUE TITLE
Save button should always be visible

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-client#743]
### Motivation
Currently in form wizard on the Summary and Recommendations page, the Save button shows up at the bottom. If the form is too big the Summary and Recommenation page is too long with a scroll. When rolling out at scale with untrained users, the user get confused where the save button is. This is leading to users coming out of the form without saving leading to draft encounters. 
It's better to make the Save and Previous buttons visible at all times irrespective the scroll. In other words the user should have to scroll to the bottom. 
Or if we want to continue to nudge the user to still scroll and review all that is there on S&R then we give another button 'Scroll to the bottom to Save'

**Comment by himeshr** [comment]
Chosen option: Nudge the user to still scroll and review all that is there on S&R then we give another button 'Scroll to the bottom to Save'

**Comment by petmongrels** [comment]
The scroll button will be shown only if the save & previous buttons are not visible.

**Comment by petmongrels** [comment]
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-26721-2022-12-06-12-35-26.apk
