### ISSUE TITLE
Slow feedback on Single/multiselect

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#746]
Feedback can be improved by providing a faster feedback on the screen and allowing processing to happen in the background (use uncontrolled components).

**Comment by AchalaBelokar** [comment]
- [ ] still radio button  is taking time to click .[Himesh have context it]

- [ ] it is happen with lfe and avni

**Comment by himeshr** [comment]
To debug the issue further, installed the latest LFE prod app on both on a physical device and an  emulator.
Slow feedback on single/multiselect was only observed on my phone and not on the emulator.
It is same situation as what we had observed during our joint debug with Vinay and Vivek.

**Comment by himeshr** [comment]
Issue has been reported by clients:
https://avni.freshdesk.com/a/tickets/2344

**Comment by petmongrels** [comment]
Previous APK from (Dec 30) - https://s3.console.aws.amazon.com/s3/object/samanvay?region=ap-south-1&prefix=openchs/staging-apks/staging-14c41-2022-12-30-09-41-15.apk
New APK with improvements - https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-fc69-2023-01-16-13-37-28.apk
note: this app has improvements done only in encounter flow (not program enc)

**Comment by AchalaBelokar** [comment]
tested on lahi, power lfe organisation. the performance is better than previous.
