### ISSUE TITLE
Limit addition of members to relevant subject types

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#748]
### To reproduce
1.  Take an implementation that has household as one of the subject type
2. Choose a household
3. Click on Add Member
4. Next screen is the search screen which shows Household also as one of the subject types
5. When the user by mistake chooses a household, app crashes

Expected :
The app should show only show relevant subject type.

**Comment by petmongrels** [comment]
@vinayvenu I do not see this happening in JSSCP on staging. will need an implementation name.

**Comment by vinayvenu** [comment]
Duplicate of avniproject/avni-client#1013. Closing
