### ISSUE TITLE
Not able to select / enter values in a question group.

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-client#749]
For organisation rahiuat,
Encounter name :- Livelihood information encounter.
Page name :- Crop details.

The page **Crop details** has a bunch of question groups which have a simple show form element rule written in each of them.
Each question group has a coded concept and two numeric concepts that the user has to answer.
Clicking on the answers doesn't do / select anything. And while entering numbers in the numeric fields, after entering, the values are deleted.

**Test cases I tried**
I added a coded concept and a numeric field without a question group, and there we are able to select values and enter numbers.
I added a text field inside a question group and there I was able to add text, and the values were not getting deleted.

**Root cause**
There is a rule written for the form element group to show only when the answer to the question "Whether engaged in agricultural activities" is "Yes" in the same encounter.
If I remove this rule, everything works fine.
![Screenshot from 2022-11-29 11-27-31.png](https://images.zenhubusercontent.com/627c9e38b2b7107ec1888b53/be67411e-b896-46fd-bf4f-c6217bd3234f) ![Screenshot from 2022-11-29 11-27-42.png](https://images.zenhubusercontent.com/627c9e38b2b7107ec1888b53/1687d2a4-1031-47f1-84f9-fe45d87e2812)
https://images.zenhubusercontent.com/64590403/6e9a7fb9-9775-4aa4-a319-931dd07fd57e/screencast_from_29_11_22_11_48_10_am_ist.mp4

**Comment by himeshr** [comment]
The Numeric values getting over-written issue was resolved by following rule chage:

'use strict';
({params, imports}) => {
    const encounter = params.entity;
    const moment = imports.moment;
    const formElementGroup = params.formElementGroup;
    const _ = imports.lodash;
    let visibility = true;
    return formElementGroup.formElements.map((formElement) => {
        
  const condition11 = new imports.rulesConfig.RuleCondition({encounter, formElement}).when.valueInEncounter("689b0d91-fb7d-45e0-b7de-8e707b356020").containsAnswerConceptName("25e40da2-f849-4e7b-8e99-7c838f42146c").matches();
  
        visibility = condition11 ;
        let value =  encounter.getObservationReadableValue(formElement.concept.name);
        console.log('visibility', visibility, _.isNil(value) ? "null" : JSON.stringify(value[0]), JSON.stringify(formElement));
        return new imports.rulesConfig.FormElementStatus(formElement.uuid, visibility, _.isNil(value) ? null : value[0] );
    });
};
