### ISSUE TITLE
Validation errors doesn't go away after the validation has been fixed.

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-client#750]
Org :- sakhiapp
Encounter type :- Delivery encounter
Name of fields :- "Number of live birth" , "Number of still birth", "Outcome of delivery". (All numeric)

What's happening ?
  - There are two rules written for outcome of delivery :
    1) Adding "Number of live birth" and "Outcome of delivery" and showing the value.
    2) Have a validation when both "Number of live birth" and "Outcome of delivery" are equal to zero, a validation error pops saying **Number of live birth and number of still birth cannot be equal to zero**.

On adding values to both the fields, the validation error doesn't go away.

Below is the SS for the rule written :-
![Screenshot from 2022-11-29 18-38-45.png](https://images.zenhubusercontent.com/627c9e38b2b7107ec1888b53/a56aebe4-b8b5-465d-81db-7cd80513f716)

Below is the SS of the error :- 
![Screenshot from 2022-11-29 18-41-22.png](https://images.zenhubusercontent.com/627c9e38b2b7107ec1888b53/4e7c0c34-357d-49ab-a93a-d18cb530ab56)

**Comment by AchalaBelokar** [comment]
https://app.zenhub.com/workspaces/product-635b73bded85e50018871ae6/issues/avniproject/avni-client/750 because of this it is blocked

**Comment by vinayvenu** [comment]
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-9e9a-2022-12-01-11-39-55.apk

**Comment by AchalaBelokar** [comment]
still showing a validation error
.![Screenshot 2022-12-02 at 8.48.54 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/8467d82b-61d4-4f85-a901-9a7325bcfae7)

Organization  detail :StatusBulider 
form: Individual Registration
user id: AchalaB@statusBuilder

**Comment by vinayvenu** [comment]
It seems to be working fine. Please check.
