### ISSUE TITLE
LFE app issues

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#752]
### LFE app issues:
- [x] - Icons on More page are broken
- [x] - Splash screen does not work - Maha
- [x] - Getting an error on last screen of the Observation - Vinay
- [x] - N/A is not getting auto selected when its the only option (Himesh)
- [x] - Autopopulate is not working for coded answers
- [x] - Documentation icons not showing (Vinay)
- [x] - Encountered NaN error at the end of observation in LFETeach UAT (Most likely is not an issue- Vinay and Himesh)
- [x] - Rules take 5 secs to trigger update on Himesh's phone (Himesh/Vivek/Vinay)
- [x] - LFE App crash (ignoring this crash for now)
- [x] - Revert commented "Subject" and "Class" fields auto-populate in LFE Observation rule, post support for that (Do it next week) (Himesh)

**Comment by himeshr** [comment]
We have pushed the fix for issues mentioned in the task description as an internal testing release build to Playstore.. 4227909 (3.36.5)
You may opt-in/opt-out of internal testing using https://avni.readme.io/docs/play-store-tracks.

**Comment by AchalaBelokar** [comment]
- [ ] ![Screenshot 2022-12-05 at 7.09.44 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/cba0b2bb-36b6-4016-b43c-b25f42991260) why Hindi  is coming in Hindi  language rest are in English

**Comment by himeshr** [comment]
We have added platform translations for the word "Hindi", hence, its translated value is shown.

**Comment by AchalaBelokar** [comment]
![Screenshot 2022-12-06 at 3.33.03 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/52185697-9008-4583-a170-ee902a13fb1c)-

- [x]  text getting  cut  for medium  of instruction.

 
[ ] Autopopulate is not working for coded answers single select 

- [x]  - N/A is not getting auto selected when its the only option (Himesh)

![Screenshot 2022-12-06 at 5.16.16 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/9b99ad32-3531-4e21-8590-2271e91d5baa)

**Comment by himeshr** [comment]
Fixed the text overflow in RadioButtons paired options.
Also, the N/A auto-populate issue was not due to code, but rather due to missing rule config. Made the required rule config change.

**Comment by himeshr** [comment]
![Screenshot 2022-12-06 at 7.03.16 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/31dd940c-0c19-4c44-962c-cba5c1c998cb)
Fix for single-select text overflow issue is available in lfe internal testing track app version 4227910 (3.36.6)
