### ISSUE TITLE
More page should work without internet connectivity

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#754]
Currently token is fetched in More page for fetching extensions. But extensions are not used by all clients. Hence fetching token should be localised to that Menu item, so that clients need not require internet to see More page.

**Comment by petmongrels** [comment]
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-d14c-2022-12-07-12-03-58.apk
