### ISSUE TITLE
Do not show timers on draft encounters

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#759]
(LFE app only).

**Comment by AchalaBelokar** [comment]
currently it is showing a timer

**Comment by himeshr** [comment]
Please make use of LFE app 4234305 (4.0.1), for testing this.
Playstore links to join:
Android: https://play.google.com/store/apps/details?id=org.lfeteach.openchsclient
Web: https://play.google.com/apps/testing/org.lfeteach.openchsclient
