### ISSUE TITLE
Ability to apply filter on custom dashboards

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/avni-client#763]
### Potential solution
- Push My Dashboard to the list of dashboards. 
- Add the ability to configure Filters of the same form as the My Dashboard filters
- Provide the ability on the client to apply filters if necessary
- Add these filters to default cards where they are not yet configured (Tasks, Approvals etc)
Estimates - 1, 1, 1, 2

**Comment by vinayvenu** [comment]
Closing in favor of https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-product/1292
