### ISSUE TITLE
Timer issues

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#767]
- Vibrate not working on timers.
- Fix discrepancy between timer and stay timer - Eg: when stay timer has decreased only for 5 secs, timer would have increased by 7 secs. This provides less time for the next observation in LFE.
- Stay timer is starting one sec less.

**Comment by AchalaBelokar** [comment]
Vibrate not working on timers.

**Comment by AchalaBelokar** [comment]
Vibrate not working on timers.

**Comment by mahalakshme** [comment]
APK for testing this is available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-c2503-2022-12-27-09-09-46.apk
