### ISSUE TITLE
editing a time question in a draft encounter gives fatal error

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#769]
![IMG-20221220-WA0007 (1).jpg](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/d033d57b-7062-4ee2-add8-5df46a8ecc73)In LFE to reproduce the issue please follow below steps -

1. Start an observation, complete the first screen 
2. Proceed to the next screen
3. Get out from the from
4. Edit the draft encounter
5. try editing the time questions, the app gives a fatal error as below --

**Comment by vinayvenu** [comment]
This was already reported and fixed on 3.36 branch. Needs a new apk.

**Comment by vinayvenu** [comment]
Closing. This was testing only.
