### ISSUE TITLE
[RWB NITI] Unable to register  farmer in RWB Niti [Prerelease]

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#773]
[RWB NITI] 
1. Unable to register  farmer in RWB Niti 
steps to reproduce 
1. click on register 
2. click on farmer 
3.enter farmer name 
4. error is coming  Another Farmer has same name .
this is happen on prerelease platform.![Screenshot 2022-12-22 at 12.02.48 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/211e48cb-028e-414c-ba0b-69e45c747f34)

2. same for work order registration
3. In Farmer Endline Encounter, for "Aadhar number" field in "Farmer details" FEG, we get Validation error always.

Fix Info:
=======

In general Unique Constraint Validation fail always, as post RealmDB version upgrade, the FIltered List _.isEmpty() check fails as the response is an object and we should additionally check for its length.

**Comment by himeshr** [comment]
After realm upgrade, savedSubjectsWithSameName is now a realm object and _.isEmpty(savedSubjectsWithSameName) always evaluates to true.
Fixed it by adding additional check on length of savedSubjectsWithSameName.
https://images.zenhubusercontent.com/64590403/657ed22b-eb7d-4cd7-bfa9-df3df953d22f/screen_recording_2022_12_22_at_1_10_57_pm.mov

**Comment by himeshr** [comment]
This Unique constraint causes an issue even for Form fields that are marked Unique. Need to fix them as well, so moving it back to in-progress.
Ex: RWB NitiAayogUAT, Farmer Endline Encounter, for "Aadhar number" field in "Farmer details" FEG, we get Validation error always.

**Comment by petmongrels** [comment]
Two comments.
1. Collections returned by realm filtered method, should only be checked with length for clarity. isEmpty is not required that is.
2. for Changes in GroupAffliationsActions. lodash returns an object or nil. we should not check for isEmpty there.

@himeshr
