### ISSUE TITLE
Observations with concept datatype Time is stored incorrectly

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#775]
Observations of Time concept used to be stored in the form of a string (eg: "05:30") in the database. Now it is being erroneously stored in the form of a date (eg: "2022-12-21T05:30:38.693Z"). 

-- This fix needs to be pushed to LFE branch, 3.36 and master. 
-- We need a way to handle existing data in LFE production for this.

**Comment by petmongrels** [comment]
commits in LFE repo and avni-client
