### ISSUE TITLE
Old rules are not working

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-client#777]
**Describe the bug**
Old rules (deployed via CLI) are not working on the latest update. IHMP Organisation ppl have confirmed that, only users who have updated their Avni App to latest version(1082280 (3.37.4)) are facing the issue.

Related Support ticket:
==================
https://avni.freshdesk.com/a/tickets/2289

**To Reproduce**
Steps to reproduce the behaviour:
IHMP 
in individual registration: the question "Date of marriage" should show only if the answer to "Marital status" is Currently married 

User: Sachink@Ihmp
Register a new user with age < 49 with marital status currently married

**Comment by himeshr** [comment]
Regression caused by https://app.zenhub.com/workspaces/product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/749

**Comment by himeshr** [comment]
Code changes done in avni-client : 'origin/3.36-hotfix'.
GIThub commit link: https://github.com/avniproject/avni-client/commit/5efc4bcc557227c2d021a3d3ee79143df1e51ca6

Dev info:

When we do not have a rule defined for a FormElement,check if a FormElementStatus is available for the same in mapOfBundleFormElementStatuses.If yes, return that, else return a newly created default FormElementStatus.

Priority ordering for obtaining final FormElementsStatus of a FormElement is as follows:
1. create a default FormElementsStatus
2. from rulesFromTheBundle
3. from rule defined using AppDesigner

**Comment by himeshr** [comment]
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/prod-apks/prod-arm-5efc4-2022-12-26-21-34-56.apk
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/prod-apks/prod-arm-arm64-v8a-5efc4-2022-12-26-21-40-26.apk

**Comment by petmongrels** [comment]
@himeshr do merge your changes to master.

**Comment by himeshr** [comment]
@AchalaBelokar Impact area to be covered during testing is all methods of specifying "Rules" configuration.
1. Rules via App designer: Rahi UAT : livelihood encounter for Houshold
2. Rules configured via bundle: Subject registration in IHMP
3. Any other..
