### ISSUE TITLE
Custom Dashboard numbers are getting cut

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#778]
To reproduce
Use app pointed to Prerelease environment
Login: AchalaB@sakhiapp

![WhatsApp Image 2022-12-22 at 16.14.14.jpeg](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/c072f50a-b6d5-4017-a80c-6a060d0a4b3c)

**Comment by mahalakshme** [comment]
works fine on smaller dimensions phones also
