### ISSUE TITLE
Drop-down to select type does not work

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#780]
To reproduce
Login to Prerelease - AchalaB@rwbnitiuat
Click on one of the approval cards. 

Select Type does not expand

**Comment by mahalakshme** [comment]
why should allFilterItems be part of state? And I think default placeholder should be 'All'/'All types' not 'Select type'

**Comment by petmongrels** [comment]
@mahalakshme allFilterItems cannot be constructed in constructor of the component hence it has to be loaded after componentMount from the db. state is the only place to keep dynamic data.

since this is a bug fix I don't want to change behavior hence select type as it is.
