### ISSUE TITLE
Media download from Subject dashboard does not work

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#782]
To Reproduce

Prerelease - AchalaB@rwbnitiuat
Go to subject type WorkOrder named "TEST WORK 03"
Workorder endline - Press on the download icon

Note: Same issue also present when trying to download from the form edit page.

**Comment by mahalakshme** [comment]
working when uploaded for a new subject. But for the existing "TEST WORK 03" still unable to download. Am I checking something wrong?

![Screenshot 2022-12-28 at 3.42.30 PM.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/38e0266e-f713-4280-8cc8-e310ab3df4e4)

**Comment by mahalakshme** [comment]
[Uploading... Screenshot 2022-12-28 at 3.42.30 PM.png]

**Comment by petmongrels** [comment]
@mahalakshme you will have to upload a new image to test this. pre existing images would not work because they are prod S3 whereas pre release db is from prod. if you upload new image it will go to pre release s3.
