### ISSUE TITLE
[UI] Text field not wrapped

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#784]
![image.png](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/d8011f44-cd0a-4404-ad8b-506bf65e981e)

Location: Approval screen
To reproduce, login to prerelease as AchalaB@rwbnitiuat

Issues: 
1. Wrap the text field saying "Showing 18 Approved ..."

**Comment by petmongrels** [comment]
commit same as #780
