### ISSUE TITLE
Calendar widget on Dashboard does not work

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#787]
### Environment
Prerelease - AchalaB@jsscpuat

Try pressing on the calendar widget on the top

**Comment by mahalakshme** [comment]
The no on the overdue card is not correct for the first time alone. when used calendar to set it the no is fixed. Not sure if bug related to this card since was unable to find the commit for this card.

**Comment by mahalakshme** [comment]
looks like some initial state for the date is missing which is related to calendar, so added it here.
