### ISSUE TITLE
Not able to sync for users assigned to the catchment "Delhi"

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-client#790]
Org :- poweruat
username :- taqi@poweruat
build version of the app :- 3.37.5-5efc4

What's happening :
When I try to login with my user or any user assigned to the catchment "Delhi", I get a message saying **null is not an object (Evaluating 'this.subject.uuid')**

So I created a new catchment, called it "Test", and added a few locations, assigned it to a new user and fresh synced it again.
The new user with the new catchment seems to work perfectly fine.

So I think there is something wrong with the subjects assigned to the previous catchment (i.e, "Delhi").

![Screenshot from 2022-12-28 10-50-17.png](https://images.zenhubusercontent.com/627c9e38b2b7107ec1888b53/3ffcaa62-af13-4270-ab25-e25bbe0b5ff0)

**Comment by AchalaBelokar** [comment]
Currently this issue is happening  with below organisation.
1. poweruat(AchalaB@poweruat)
2. Apfodisha(nupoork@apfodisha)
3. stccvuat(vinay@stccvuat)
4. lahiuat (AchalaB@lahiuat)
5. rahiuat (AchalaB@rahiuat)

**Comment by vinayvenu** [comment]
individual uuid not present in the db dump attached here. Other organisations do not have this issue. This is only for AchalaB/taqi@poweruat

[https://app.zenhub.com/files/64590403/79cc05ed-a00e-4650-8bb6-0794709424c5/download](https://app.zenhub.com/files/64590403/79cc05ed-a00e-4650-8bb6-0794709424c5/download)

**Comment by vinayvenu** [comment]
individual uuid not present in the db dump attached here. Other organisations do not have this issue. 

[https://app.zenhub.com/files/64590403/79cc05ed-a00e-4650-8bb6-0794709424c5/download](https://app.zenhub.com/files/64590403/79cc05ed-a00e-4650-8bb6-0794709424c5/download)

**Comment by vinayvenu** [comment]
Fast sync db for the catchment has been deleted. Users should be able to login now. Will relook at this issue if this issue recurs.
