### ISSUE TITLE
UI fixes

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#792]
To reproduce:
Login to Prerelease - AchalaB@rwbnitiuat
try out comments on some subject
click on the menu on a comment 
- In delete - 'd' should be caps - translation is missing for it
- The profile pic slightly is getting cut(except for first comment)
- date and time can display in single line

![Screenshot 2022-12-28 at 1.41.18 PM.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/8edaaae4-c825-4020-b843-90ee15d13b00)

- In the below subject profile screen, Edit should display in single line.![Screenshot 2022-12-28 at 3.38.18 PM.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/8dcb1726-ad8f-47b2-a2f4-4ffa915a5ea1)

**Comment by sachsk** [comment]
Fixed and checked for the normal font size.
Added minWidth for some elements.
