### ISSUE TITLE
Change the primary color to avni green at all places

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#793]
Change the color from blue to green at below places and any other places that involves primary action and selections:
	

- [x] - Buttons on new comment dialog
- [ ] 	- Show password selection
- [x] 	- Radio button selection in subject type in search
- [x] 	- Form element selections like checkbox and radio
- [x] 	- Next and wizard form buttons
- [x]  Save  and next form buttons
- [x] 	- Close on image button, when image uploaded viewed
- [x]         - Click on filter in dashboard. Selections of elements there in filter.

**Comment by sachsk** [comment]
Not able to change the colour of checkboxes because its a native-base component and it doesn’t allow to set a custom colour tried various ways but not worked.

**Comment by AchalaBelokar** [comment]
- [x] Delete relative button in the household having different  colour 

- [x] verify  Number diff colour 

- [ ] Date of birth radio button years moths

- [ ]  document  read more text is having diff colour

**Comment by vinayvenu** [comment]
@sachsk We had decided to move all these into 3.38 branch, right? Can you make sure it is in the right branch so we can proceed with the release?

**Comment by sachsk** [comment]
@vinayvenu Done.

**Comment by AchalaBelokar** [comment]
- [x] In power Check eligibility engine button
- [x] Start button on timer page
