### ISSUE TITLE
Hierarchical Location in registration from is not showing proper format

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#796]
when I am clicking on child location parent location is de select .currently it is happening with some organisation:
orgnization: CHETNA  SNEHA
Chetana sneha having a location type 
1. Area lavel1
2. User area reporting level 2
![![Screenshot 2022-12-29 at 12.14.13 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/49fa37b8-20d7-419e-b76a-9e88ee2eea71)Screenshot 2022-12-29 at 12.13.26 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/d0012205-48a0-484e-ab20-3fa2b7b98204)
LFE 
![Screenshot 2022-12-29 at 12.15.28 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/1a2f65c6-7877-426b-a217-bb2f621a6385)

**Comment by petmongrels** [comment]
This isssue is due to data setup of location. The location mapping doesn't exist due to some data migration reasons. Both these organisations are dormant so probably the data was not migrated for them.
