### ISSUE TITLE
Last letter getting cropped for certain users

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-client#800]
![WhatsApp Image 2022-12-29 at 17.17.07.jpeg](https://images.zenhubusercontent.com/5ce7c98fd8501ed6b9d2d1f8/446fd4e6-fded-4631-9114-0de16b7ed7c3)

![WhatsApp Image 2022-12-29 at 17.17.08 (1).jpeg](https://images.zenhubusercontent.com/5ce7c98fd8501ed6b9d2d1f8/064bdf7a-4c01-4637-891d-ad46cfcb278c)![WhatsApp Image 2022-12-29 at 17.17.08.jpeg](https://images.zenhubusercontent.com/5ce7c98fd8501ed6b9d2d1f8/86be7b91-714a-43aa-bcd5-9ad4ab44a219)![WhatsApp Image 2022-12-29 at 17.17.09 (1).jpeg](https://images.zenhubusercontent.com/5ce7c98fd8501ed6b9d2d1f8/a8a80614-3155-4900-806d-058d4968cd11)

![WhatsApp Image 2022-12-29 at 18.04.35.jpeg](https://images.zenhubusercontent.com/5ce7c98fd8501ed6b9d2d1f8/4daaeaa4-104e-4ab9-b3f0-5381a3f3ab26)

More details here https://avni.freshdesk.com/a/tickets/2304

**Comment by sachsk** [comment]
This was device specific issue and its fixed now.

**Comment by sachsk** [comment]
This was device specific issue and its fixed now.
