### ISSUE TITLE
Allow multiple enrolments

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#806]
### Acceptance criteria
When multiple enrolments is configured for a program, 
- Allow user to be enrolled into the same program more than once (depending on program eligibility)
- Show the program name only once on Search Results

### Tech tasks
- Sync to client
- ~~Change to avni-models and repository~~ (Expected to have been done by now)
- Change to subject dashboard
- Change to search results

**Comment by AchalaBelokar** [comment]
- [ ] when we enrolled  in program  the visit is scheduled only one time. I am entering the different date

**Comment by AchalaBelokar** [comment]
- [ ] when we enrolled  in program  the visit is scheduled only one time. I am entering the different date
