### ISSUE TITLE
Cannot change status of a task

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#807]
### To reproduce

- Use poweruat organisation
- Assign a task
- Try to change status (button does not work)

**Comment by AchalaBelokar** [comment]
Organisation Name: PoWER
after clicking on complete app crashed.
where other organisation : PoWERtest it is working fine.[https://app.zenhub.com/files/64590403/256fc635-c494-4023-8530-24726a2454e2/download](https://app.zenhub.com/files/64590403/256fc635-c494-4023-8530-24726a2454e2/download)

**Comment by vinayvenu** [comment]
Issues
- [x] 1. As provided by Achala before, when there is no form mapping, touching on the task status fails. See above video for details
- [x] 2. Status change is not happening for the entity that was selected. It is instead happening for a different task altogether
- [x] 3. In Task filter screen, clicking on any of the checkboxes to select "Status" option doesnot work
- [x] 4. In Task filter screen, fix functionality of filter by "Scheduled date" and "completion date"
- [ ] 5. In Task filter screen, filter by coded concepts works, but the display is not show actual selected values //Could not fix (Caused due to PresetOptionView.shouldComponentUpdate() not allowing refresh. Removing that method, breaks the current behaviour where state has correct values.

**Comment by AchalaBelokar** [comment]
- [ ] n Task filter screen, fix functionality of filter by "Scheduled date" and "completion date" not showing any result
