### ISSUE TITLE
App slowness issues

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#808]
To verify the issue fix, please check the videos and test against the same env. For calcutta_kids use the catchment Avni test as it has the dump. When the dialog is shown for sync reset press No otherwise sync will start from scratch.

Calcutta Kids
---
https://avni.freshdesk.com/a/tickets/2356
1. Selection of filters (Some of it should be fixed as part of the other card that dealt with radio/checkbox selection. A few small react control optimisations done.)
2. Pressing the filter button on the dashboard (The slowdown happens when encounter types with many encounters are selected. There is other minor slowness that can be fixed. This is happening due to a slowdown in the performance of realm query execution time. There are no performance fixes provided by realm so far. The resolution could be - using the custom dashboard instead of the default dashboard where we have better control of the query).
3. Radio button press in the form (already fixed in another card)

JSSCP
------
https://avni.freshdesk.com/a/tickets/2358
- Selection of filters (JSSCP has a hierarchy of filters setup and they have many programs/encounter types/phulwaris, The render of each checkbox takes about 50-60 milliseconds, I think this has deteriorated in recent version of native base and it may be dependent on device (not verified). Hence when a SubjectType=Individual is chosen about 70-80 checkbox has to be brought onto the screen which means several seconds of wait. The UI performance is significantly better when leaf checkboxes are checked, especially after adding customer shouldComponentUpdate. I have tried latest version of native-base but that doesn't change the perf much.)
- Pressing Filter button (Since we remember filters, if the chosen filter is of type Individual it would load all the phulwaris and hence it takes additional time to open)
- Pressing the filter button on the dashboard - Same as Calcutta kids

Shelter
-----
https://avni.freshdesk.com/a/tickets/2344
- Selection of radio button (fixed as separate card)

Not Reported by Anyone
---------
- In CK Search individual (ListView data source behavior has changed. replaced with FlatList and a few other optimisation react control).

**Comment by petmongrels** [comment]
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-ea6b66-2023-01-25-11-10-30.apk

**Comment by petmongrels** [comment]
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/prod-apks/prod-ea6b66-2023-01-25-11-37-57.apk

**Comment by AchalaBelokar** [comment]
- [ ] When User is login 1st time fresh user.It is taking a lot of time.More than 15 min

- [ ] screen overlapping  
![Screenshot 2023-01-25 at 7.03.26 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/86882c9a-9199-492a-8062-e9ea1789a168)

**Comment by AchalaBelokar** [comment]
- [ ]  In the  Calcutta kids Pregnancy Enrolment form Pregnancy History the que 
age of youngest child 
Enter Duration Months and year year is cutting down.
![Screenshot 2023-01-27 at 12.26.54 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/a8a9c6c3-cb0f-414c-ad37-91bd652ab772)
