### ISSUE TITLE
Build staging apk on CircleCI

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#811]
We had stopped generation of apks earlier because it was time consuming. We now have a paid account, and generating apks is becoming harder. As part of this card, we will generate the apk through CircleCI. 

### Acceptance criteria
- Staging apk is created on every CircleCI build
- Platform translations are deployed to staging database

**Comment by 1t5j0y** [comment]
![image.png](https://images.zenhubusercontent.com/5d8a51c647755200010d2fda/5eec0343-82e0-4830-840e-fa7f205d7f65)
APK for each build is available under the "release_android_staging" job -> Artifacts tab
https://app.circleci.com/pipelines/github/avniproject/avni-client/1409/workflows/b58c4f44-8989-4bd0-bfe3-f3328932f6de/jobs/9520/artifacts for example
