### ISSUE TITLE
Screen overlapping  happen in multiple orgnization

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#814]
When we are going to one page to another page. screen overlapping is happen. and also performance  is very slow.
Process of going to one page to another page is very slow.
https://images.zenhubusercontent.com/64590403/ee76b213-dd47-4d34-9c64-d5bc263d4ad4/az_recorder_20230123_145257.mp4

**Comment by himeshr** [comment]
Fixed as part of performance fixes done in 3.37
