### ISSUE TITLE
Strange behaviour on editing registration form

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-client#815]
Name of org :- sakhiapp
version of app :- latest from playstore

https://images.zenhubusercontent.com/64590403/3888171b-7fae-43f6-8352-77a2f285ef09/record_2023_01_23_17_42_54_e67de974eab1ae435bf1faa372eb4549.mp4

**Comment by vinayvenu** [comment]
Interestingly, this happens only when you hit the form element group's edit button, not the general edit button.
