### ISSUE TITLE
Search is not visible even though all privileges toggle is turned on

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-client#816]
Name of the org :- rahi
username :- utkarsh@rahi (prod environment)
version of the app :- latest from playstore

Note :- This is a prod environment, please don't sync.

I turned on the all privileges button in all the user groups(Field user, Everyone) this user is in, and I am not able to see the search icon in the home screen.
![Screenshot from 2023-01-24 11-44-52.png](https://images.zenhubusercontent.com/627c9e38b2b7107ec1888b53/42f02959-6fbd-4bef-b2a8-308cc0ad3c19)
![Screenshot from 2023-01-24 11-45-11.png](https://images.zenhubusercontent.com/627c9e38b2b7107ec1888b53/68f31ca2-7903-43ac-9f89-9d3fcf9bb26b)

**Comment by vinayvenu** [comment]
@Gojo-Taqi The Search screen will be hidden if there are no search filters AND if the number of subjects is less than 5. If you want to see the search filter, either add 5 subjects, or add a search filter.
