### ISSUE TITLE
[PoWERUat] Unable to click on status in filter tab

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#820]
[PoWERUat] Unable to click on status in filter tab
steps to reproduce :
Click on tasks 
click on filter
there is status field  where we can multi-select.
Currently  it is not working
[https://app.zenhub.com/files/64590403/cf598399-d2da-4a99-b9e5-51ca0f07157e/download](https://app.zenhub.com/files/64590403/cf598399-d2da-4a99-b9e5-51ca0f07157e/download)

**Comment by vinayvenu** [comment]
This is already reported and taken care as part of https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/807

Closing as duplicate.
