### ISSUE TITLE
Remove persistence of LatestApprovalStatus in the database

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#826]
Currently, the latest entityApprovalStatus of an entity is attached to an entity. This makes it easy to get the current approval status of an entity. However, this is duplicate information that is being stored in the database, and has caused consistency issues. 

To fix this, we will
- Remove the latestEntityApprovalStatus from entities
- Remove the code in sync that links entities to the latest approval status
- Change all usages of entity approval status
- Provide a mechanism for rules to use the latestEntityApprovalStatus

**Comment by petmongrels** [comment]
changes in models, client, rules-server, avni-server

**Comment by vinayvenu** [comment]
- It will be good if ```EntityApprovalStatusService.createPendingStatus()``` also performs ```Entity.addUpdateApprovalStatus```  keeping the model intact. This logic is repeated multiple times in the code, and can potentially cause mistakes in the future. 
- There could be confusion between ```latestApprovalStatus get()``` and the property that is available only to Realm queries
- Don't we now need to remove all ```approvalStatuses``` objects in SubjectMigrationService.removeEntitiesFor() since they are now related?

**Comment by petmongrels** [comment]
1, 3 fixed.
latestApprovalStatus could be used from reports rule from the db and from entity in other type of rules, hence left it like that.
