### ISSUE TITLE
ability to set a default subject as default fro mobile app dashboard filter

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#828]
https://avni.freshdesk.com/a/tickets/2368

Ideally, user should have ability to set/select the default subject type as filter for the mobile home dashboard.

**Comment by vinayvenu** [comment]
Subject types are shown based on privileges as well, so the default for one user need not be the same as another user's default. 

We can potentially add this as a user property that the user can set up

**Comment by vinayvenu** [comment]
Closing in favor of https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-product/1292
