### ISSUE TITLE
[PoWER Uat] Reschedule tab is not woking in the open task tab. 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#833]
[PoWER Uat] Reschedule tab is not woking in the open task tab. 
There is reschedule  tab  I am trying to click on that tab it is not clickable.
Before this it was working fine. after clicking  on that tab call should be schedule for that particular time . 

Orgnisation: Power Uat

**Comment by himeshr** [comment]
Fix has been done as part of avni-client commit : 
https://github.com/avniproject/avni-client/commit/47927e4ee9846e693c591f5dba4a983989daeec9

**Comment by AchalaBelokar** [comment]
- [ ]  reshedule button is not clickable

**Comment by AchalaBelokar** [comment]
- [ ] still button is clickable

**Comment by himeshr** [comment]
Yes, this needs a new apk, will provide once other fixes are ready.

**Comment by himeshr** [comment]
Pre-release APK for testing Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/prerelease-apks/prerelease-b3b1-2023-02-03-12-35-38.apk
