### ISSUE TITLE
Sakhi App [Search by mobile number, rch, etc are not working]

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#834]
In the sakhi app organisation there  is option through  which we can search the Individual  and Household but currently there are field  which is not working.
1. Mobile Number. after filling mobile number we click on submit  the no result is showing. 
 same for others
2. RCH no
3. ABHA no.
This happen with other organisation also
Lahi Uat
https://drive.google.com/file/d/13NbNBLG3nbAl-JkfGxUufH3b3LM15wH-/view?usp=sharing

**Comment by 1t5j0y** [comment]
Looks like there are a couple of issues here:
1. Search by partial mobile number does not work if concept data type is Phone Number
2. Search results are not getting shown at all for search by custom filters.

**Comment by 1t5j0y** [comment]
Fixed point 2. Looking at point 1.

**Comment by 1t5j0y** [comment]
Parking point 1. Concept data type for mobile number search in Sakhi is numeric and not phone number and doesn't look like partial search for numeric is supported.
