### ISSUE TITLE
[JSCS]App search does not work (spinner) when searching by Hemoglobin genotype

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#836]
[JSCS]App search does not work (spinner) when searching by Hemoglobin genotype.

**Comment by AchalaBelokar** [comment]
selected AA  Hemoglobin genotype 5.10pm and now it is 5.12pm app get crashed 
tested on apk which is given by you.
Similer for AS 
where ss is working fine

**Comment by petmongrels** [comment]
use it with other filters especially date.....to keep the number of records low
