### ISSUE TITLE
[JSCS]CLOSE is not translated to Hindi (In search screen in the new button that we created)

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#838]
CLOSE is not translated to Hindi (In search screen in the new button that we created)

Translations for this were added as part of commit: https://github.com/avniproject/avni-client/commit/851c97604c85c8590920b8c4c816d106ac7716a4

**Comment by himeshr** [comment]
Translations for this were added as part of commit: [851c976](https://github.com/avniproject/avni-client/commit/851c97604c85c8590920b8c4c816d106ac7716a4)

**Comment by vinayvenu** [comment]
1. Content has not been t()ed. 
2. Close is not X button (Look at text)

![image.png](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/f91ec9b3-48da-477d-97c0-736c55b8d0e5)
