### ISSUE TITLE
[JNPCT] App crashing on navigation between form screens

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#840]
This is in individual registration page. When trying to register navigate front and back the pages - the app crashes.

Reproducible in jnpctuat but not happening on jnpct.

[JNPCT] App crashing on navigation between form screens
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/63da393eb6743e0009e65613

**Comment by 1t5j0y** [comment]
Unable to simulate after performance fixes

**Comment by petmongrels** [comment]
moving it QA for checking if it is reproducible

**Comment by AchalaBelokar** [comment]
- [ ] Not able to reproduce it

**Comment by AchalaBelokar** [comment]
- [ ] Not able to reproduce it
