### ISSUE TITLE
Subject form element with displayAllGroupMembers is broken

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#845]
I am unable to select multiple group members when there is a subject form element with the flag displayAllGroupMembers turned on. 

Affected organisations (to reproduce the issue)

```select o.name, f.name, feg.name, fe.name, fe.key_values
from form_element fe
         inner join organisation o on fe.organisation_id = o.id
         inner join form_element_group feg on fe.form_element_group_id = feg.id
         inner join form f on feg.form_id = f.id
where fe.key_values::text like '[%{"key": "displayAllGroupMembers", "value": true}%]'
  and fe.is_voided is false and feg.is_voided is false and f.is_voided is false
order by o.name, f.name, feg.name, fe.name;
```

**Comment by mahalakshme** [comment]
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/prerelease-apks/prerelease-3a30-2023-02-05-19-57-06.apk

Go to attendance encounter of any LAHI organisation. U should be able to multiselect children and save. The below were not happening as expected:
- On edit, previous selection should be retained. 
- Checking should work when clicked on name as well, not just the checkbox.

**Comment by AchalaBelokar** [comment]
Unable to find attendance encounter

**Comment by AchalaBelokar** [comment]
AchalaB@lahiuat
password
