### ISSUE TITLE
Basic anonymised realm data file for reporting to realm team

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#847]
https://github.com/realm/realm-core/issues/6327

In response to the issue raised by us about subquery performance, the realm team has asked if we can provide a database file where they can reproduce the issue. Since our data contains personal information we need to remove it. The fields that hold the people's information are:
- first name, last name, date of birth on individual
- sometimes in observation's value JSON as value and answer (all entities which has obs)

To further remove meaning from the database we could remove the following:
- concept name field
- form, form element group, form element field name
- encounter type name, program name, subject type name
- location title field
- Groups name

There are a few other fields that can be done later as the JSCS db doesn't have them.
- comment and comment thread fields
- task objects
- user's email, phone, and name

Acceptance Criteria
------------------
- Add a Dev Menu option to create a realm file copy that is anonymised as described above
- makefile target to pull the anon db to the host machine
- The resulting db should also have the performance issue visible, if not then we could analyse further in a separate card (as that may provide some visibility into the perf issue to use without going to the realm team)
- Get the resulting db reviewed by another person before giving to realm team

Technical notes
------------
- Use JSCS db dump created by syncing for user viveks@jscs from prereleease. if prerelease env is not there create another user in prod with anuppur catchment.
We could use https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.html#writeCopyTo method to achieve this. The Configuration.schema parameter taken by this call can be a mutated current config and with object fields removed.
- Under performing queries (we have reported only one but we could send the other one also)
- While testing in realm studio, studio will become unresponsive and CPU usage will go high (which indicates the perf issue)

OBJECT TYPE = Individual
subjectType.uuid = '9f2af1f9-e150-4f8e-aad3-40bb7eb05aa3' AND SUBQUERY(observations, $observation, (concept.uuid = 'e19e68fd-97f1-4803-a1b2-bb850836ff54' and valueJSON contains '11111111') ).@count > 0

voided = false AND subjectType.uuid = '9f2af1f9-e150-4f8e-aad3-40bb7eb05aa3' AND SUBQUERY(enrolments, $enrolment, ( $enrolment.program.uuid = 'e93303fa-f465-4db7-a945-d4fd6295f2b9' ) AND ( $enrolment.encounters.encounterType.uuid = 'e99184ad-9082-43d0-9726-7644e37543dd' ) AND $enrolment.voided = false and $enrolment.programExitDateTime = null ).@count > 0

**Comment by 1t5j0y** [comment]
Dev notes:
1. The approach to use `Configuration.schema` in the `writeCopyTo` method did not work as `writeCopyTo` always creates a complete copy of the DB
2. The approach was changed to make a copy of the DB and then overwrite the fields containing PII in the copy
3. Realm leaves around some hanging .lock files etc which interfere with creating a file with the same name again so a temp file name has been used while creating a copy which is then renamed to anonymized.realm after the anonymization
4. Use make get_anon_db to fetch the anonymized realm. This also deletes the file from the device.
