### ISSUE TITLE
Improve performance of RadioButton and Checkbox

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#855]
This should improve performance of the app throughout the app. 

(Expected to go in a patch release)

What has been been changed
------------------------------
- Search/Dashboard filters (minus group subject types) - tested(except custom dashboard)
- Form wizard (expect those mentioned below)
- Address/Location levels
- Member addition to household - 
- Addition of relatives - tested

What has been not been changed
--------------------------
- Group subject selection
- Gender
- Group affiliation
- Encounter, Subject select in the form
- Task filters
- Settings, DevSettings

Testing
-------
Edit of enrolment, encounter and registration details raised as part of #854 need to be tested here

**Comment by vinayvenu** [comment]
To remember - usage of setState on RadioGroup has no purpose, and can be removed

**Comment by petmongrels** [comment]
- render single value
- disabled value
- Single selected value which cannot be un-selected
- large text wrapping
- not changeable/pressable when disabled

**Comment by mahalakshme** [comment]
Edit of enrolment, encounter and registration details raised as part of #854 need to be tested here

**Comment by mahalakshme** [comment]
Edit of enrolment, encounter and registration details raised as part of #854 need to be tested here

**Comment by mahalakshme** [comment]
Testing:
**in JSCS:** - viveks@jscs - Anuppur catchment
Old:
- Edit of registration details: 10-15 secs
- 6 secs to select a radio button in(block form element) JSCS registration form -
      - not sure if clicked properly since no feedback
      - Also sometimes not getting selected
- Transition to next page(has radio button and checkboxes) in registration details - 5 secs

New:
- Edit of registration details: 3secs - 3-5 times faster
- Faster feedback when selecting radio/checkbox button(block form element) - 3 sec - in JSCS registration form - 50% faster
- Transition to next page in registration details - 2 secs - 2 times faster
     - Slow transition issues now not happening

**in Ashwini:** - sachink@ashwini, Gudulur catchment
Old: 
Edit of previous completed visit(the first page has checkboxes and radio buttons): 3s
Edit of program enrolment(the first page has checkboxes and radio buttons): 3s

New:
Edit of previous completed visit: 1.5s - 50% faster
Edit of program enrolment: 1.5s - 50% faster

**Comment by himeshr** [comment]
Additional Testing info for JSCS: - viveks@jscs

While editing Subject registration details, in AddressLevel Block section, switching from "Pushparajgarh" from "Anuppur" took 39 seconds with RadioGroup(Old), but took only 13 seconds with SelectableItemGroup(New).
