### ISSUE TITLE
[APF Odisha]Unable to edit the Registration  of individual .

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#859]
I am trying to edit the individual  but unable to save it.
Steps To reproduce 
1. create a individual  
2. save it
3. try to edit it  not able to save it
Environment  prerelease .
User: sachink@apfodisha
 [https://app.zenhub.com/files/64590403/5f601311-e281-410a-a4ad-4c833bf54f4a/download](https://app.zenhub.com/files/64590403/5f601311-e281-410a-a4ad-4c833bf54f4a/download)

after click on save and register screen overlapping is happening.
 steps to reproduce  overlapping .
1. click on save button.
2.click on save and register another individual .

![Screenshot 2023-02-09 at 3.07.49 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/3ba34e6f-8799-4e7e-8e3d-0661801a57cf)

Testing::
All forms navigations need to be tested.

**Comment by vinayvenu** [comment]
Issues noticed in navigation
1. Edit of registration does not take to any page
2. Save and proceed button behaves inconsistently in many scenarios.

**Comment by petmongrels** [comment]
I am not able to reproduce, but I have the radio fix. This may be happening because the first screen of household registration takes a lot of time to load which causes this behavior.

**Comment by mahalakshme** [comment]
Also clicking on back on top bar, on individual registration page is not taking me out of the form.
