### ISSUE TITLE
Navigation of editing a completed program encounter is behaving unexpectedly

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#861]
Environment: prerelease
Login: sachink@ashwini,

Go to a individual profile -> click on edit of a completed program encounter -> Click Next -> Click Previous -> Press Back button on the top bar -> Will ask if ready to lose form changes -> Click yes -> There is a page transition, but we remain in the same page.

Guess: on clicking previous button, the page transition seems like we are not popping from the navigation stack, but pushing into the stack. Thats y on clicking the back button on top, we remain in the same page.

**Comment by petmongrels** [comment]
On previous from the SRV, we are pushing another ProgramEncounterView to the routes instead of going back. On Back button in header we pop and we still have another PEV.

**Comment by 1t5j0y** [comment]
APK available at https://app.circleci.com/pipelines/github/avniproject/avni-client/1545/workflows/f7b6538a-0d34-4025-bebe-e80495074907/jobs/9863/artifacts
