### ISSUE TITLE
Relations shown twice

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#863]
9/2:
prerelease, viveks@jscs, testing of 3.37

- Click on Add relative
- When a male relative selected - under relation, all male relations shown twice
- When a female relative selected - under relation, all female relations shown twice

11/5:
**Steps to reproduce:**
- create a relation say "sister" and associate it with gender "Female" and "Other"
- delete sister relation 
- create a relation say "Sister"(with capital S) and associate it with gender "Female" and "Other"
- in relationship types, create Sister <-> Sister relationship type
- now sync in avni client
- click on add relation for a female individual
- both sister and Sister gets displayed
- when the sister(deleted) one is selected "Non determinate relationship type" error gets displayed.

**Analysis details:**
- The issue came as a ticket: https://avni.freshdesk.com/a/tickets/2613 in Power org
- The issue has caused because deleting a relation from webapp is only voiding it in individual_relation table not in individual_relation_gender_mapping table
          - As a result of this when trying to do like the above as shown in the [video](https://drive.google.com/file/d/1Lf1jAytUU3aGrJ3kRzq4Kxz4_cktiRpB/view?usp=share_link) in the ticket:  getRelationsForGender in getRelationshipType function also gets the voided relations from individual_relation_gender_mapping table. But since this relation is not existing in IndividualRelationshipType table it shows the error: "Non determinate relationship type".
- For fixing the ticket, manual voiding of entries from individual_relation_gender_mapping table will be done.

**Acceptance criteria:**
When deleting a relation, the corresponding mapping from individual_relation_gender_mapping also need to be voided.

**Testing notes:**
Before deleted relations were displaying and when they are selected, the issue in the video was happening. After the fix deleted relations will not appear in the field app.

**Comment by vinayvenu** [comment]
@mahalakshme would you be able to tell if this is a problem with the implementation, or if it can be reproduced elsewhere.

**Comment by 1t5j0y** [comment]
@mahalakshme Please start using the avniproject/[repo]#[issue number] format in the commit message to refer to the issue when the fix is in a repo different from the one in which the github issue is.

Testing notes also can be clearer to mention that the fix is to delete underlying gender mappings when a relation is deleted.
