### ISSUE TITLE
Remove RadioButton and Checkbox from codebase

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#865]
This is to finish the work of moving Checkbox and RadioButton to all components, and retire the old RadioButton and Checkbox from the codebase. 

https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/855

**Comment by himeshr** [comment]
Staging apk available in circle ci. APK limk: https://output.circle-artifacts.com/output/job/7a90bd19-055b-4431-b277-9d7702ec1363/artifacts/0/avni.apk

**Comment by vinayvenu** [comment]
@sachsk @himeshr can you add the areas this was impacted so we know the scope of testing.

**Comment by himeshr** [comment]
All Native-base RadioButtons and Checkboxes have been replaced with SelectableItemGroup.
Test the entire app across multiple organizations for working of RadioButtons and Checkboxes.

As part of development we have tested each of the replacements done as part of this task.

Impacted areas:
---------------
 - CustomFilter for Filter Individual by GroupSubject 
 - Task Filter screen (Power) 
 - "More" section -> Dev Settings screen RadioButtons and Checkboxes
 - "More" section -> Settings screen RadioButtons and Checkboxes (Top user name)
 - NumericFormElement with rule specifying "allowedValues"
 - TextFormElement with rule specifying "allowedValues"
 - SingleSelectSubjectFormElement
 - SingleSelectEncounterFormElement
 - MultiSelectSubjectFormElement
 - MultiSelectEncounterFormElement
 - GroupAffiliationFormElement
 - GenderFormElement
