### ISSUE TITLE
[PoWER UAT]  Search by number giving fatel error

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#867]
"when I am trying to search a individual by Mobile number occures fatal error
steps
click on search Icon
click on Individual 
enter a mobile Number 9404375389 then error occurred for this no Radhe Krishana is present "

**Comment by himeshr** [comment]
Validated the bug fix on prod, poweruat org.. as seen in attached screenrecording. https://images.zenhubusercontent.com/64590403/bfe5daa3-e26b-4372-9196-0d38979f1795/screen_recording_2023_02_11_at_3_49_07_pm.mov
