### ISSUE TITLE
"Totals" is not shown when user selects any "Program" in Dashboard filters

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-client#868]
"Totals" is not shown when user selects any "Program" in Dashboard filters. This change was done on purpose after looking at the performance impact it had.

After feedback from several projects, we have decided to make this a configurable feature.
We'll store a flag "hideTotalForProgram" in orgConfig.settings, with a default value of false.

Post implementation of CustomDashboards filters feature, we'll do away with this Program filter capability in MyDashboard.

Related tickets:
https://avni.freshdesk.com/a/tickets/2411
https://avni.freshdesk.com/a/tickets/2403

Testing Info:
-------------
-- AchalaB@jnpctuat : "hideTotalForProgram": false -> Total should be shown on selecting program
-- AchalaB@iph_ctrith : "hideTotalForProgram": true -> Total should not be shown on selecting program
-- any other org : "hideTotalForProgram" is not set, equivalent to "hideTotalForProgram": true -> Total should not be seen on selecting program

## Note to Implementation team:
--------------------------------
In-order to show totals even when we have selected one or more programs, we should make use of below sql command to update the Organisation config settings for that organisation_id.

update organisation_config
set settings = settings || '{"hideTotalForProgram": false}' ::jsonb,
last_modified_date_time=now()
where organisation_id = <org_id>;

**Comment by himeshr** [comment]
Code changes for the fix have been pushed to 3.37 branch on avni-client.
![Screenshot 2023-02-13 at 4.59.05 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/05e94a60-8a4d-4fe6-9ee1-9842662e42ff)

**Comment by petmongrels** [comment]
@himeshr so the users will be okay with performance issue, do they know

**Comment by himeshr** [comment]
After internal discussion,  we have decided to no longer make this code change as it has severe performance impact for implementations like CalcuttaKids, etc..

**Comment by himeshr** [comment]
After repeated complaints from several implementation folks, we have decided to make the code change along with the capability to switch it off based on a flag in orgConfig.

**Comment by himeshr** [comment]
Truth table for MyDashboardView.renderableVisits()

h p e => t

1 1 1 0
1 1 0 0
1 0 1 0
0 1 1 0
0 0 1 0
0 1 0 1
1 0 0 1
0 0 0 1

**Comment by himeshr** [comment]
In-order to show totals even when we have selected one or more programs, we should make use of below sql command to update the Organisation config settings for that organisation_id.

update organisation_config
set settings = settings || '{"hideTotalForProgram": false}' ::jsonb,
    last_modified_date_time=now()
where organisation_id = <org_id>;

**Comment by himeshr** [comment]
Code changes are done only in avni-client.
@AchalaBelokar Avni-client apks with these code changes has been published to OpenTesting release version (3.37.13).

**Comment by AchalaBelokar** [comment]
- [ ] Count of total no is not showing.after selecting the program.

- [ ] and also after selecting the encounter  it is showing total

**Comment by himeshr** [comment]
Fixed both issues found during QA:
1. Count of total no is not showing after selecting the program, immediately after sync where value for "hideTotalForProgram" has been set to false
2. Totals with value 0 is shown on selecting Program Visits

Code changes are done only in avni-client.
Avni-client apks with these code changes has been published to OpenTesting release version (3.37.14).
