### ISSUE TITLE
Time input controls should be in 12 hour format

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#869]
https://avni.freshdesk.com/a/tickets/2414

Present status:
- For selecting of time in form elements, we have by mistake changed it from 12 hour format to 24 hour format.
- For displaying time in observations, we were always displaying in 24 hour format, which is inconsistent with the selection format.

What to do:
As part of this card, both selection and display of time will be changed to 12 hour format.

Things to test:
- Everywhere where date time is displayed - like filters, custom dashboard filters, group membership start date, task reschedule, etc.,
- date and Time related Concepts like date, datetime, time, duration, etc., need to be tested
- Displaying in forms, observations, and on the datetime picker widget

**Comment by AchalaBelokar** [comment]
tested on lahi and jsscp
