### ISSUE TITLE
Growth chart and its graph indicators doesn't use the translations.

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#870]
In APF, we have added english translation for Grade 1, Grade 2 and Grade 3 and still there are not getting translated. 

https://avni.freshdesk.com/a/tickets/2388

![WhatsApp Image 2023-02-14 at 11.19.57.jpeg](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/b1cb276d-89a2-4714-8daa-747e22a5b453)

**Comment by himeshr** [comment]
Made use of following translation update command for adding transaltions in Odiay in Pre-release environment:

set role apfodisha;
update translation set translation_json=translation_json || '{"Growth Chart": "ଅଭିବୃଦ୍ଧି ଚାର୍ଟ",
"Grade 1": "Normal",
"Grade 2": "Moderate",
"Grade 3": "Severe",
"Weight For Age": "ବୟସ ପାଇଁ ଓଜନ",
"Height For Age": "ବୟସ ପାଇଁ ଉଚ୍ଚତା",
"Weight For Height": "ଉଚ୍ଚତା ପାଇଁ ଓଜନ"
}', last_modified_date_time = now() where id = 117;

**Comment by himeshr** [comment]
Code changes are done in avni-client 3.37 branch.
Here-in attached screen-recording of the translated growth-chart.
https://images.zenhubusercontent.com/64590403/ccc7bf97-e824-4e5a-b4d5-4ee1f8ca7aef/screen_recording_2023_02_14_at_6_03_51_pm.mov

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-02-15 at 5.12.52 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/d3de633e-49ad-4a1e-bfb1-3f258cfca46d)

not translated  normal moderate severe

**Comment by himeshr** [comment]
@AchalaBelokar, those are the translated values that i've specified in pre-release .. they have replaced "Grade 1", "Grade 2" and "Grade 3" respectively. as stated in one of the above comments.
In prod, Implementation team will upload appropriate translations in Odia language.
