### ISSUE TITLE
Merge code to lfe branch

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#872]
### Purpose

- Performance improvements
- Glific messaging

Need to figure out how the merge flow has been working until now and do this appropriately.

**Comment by sachsk** [comment]
We have done basic testing of app for lfeteachuat and teachap org. 
We have also verified build and release of the app on lfe branch.

**Comment by vinayvenu** [comment]
Need apk for QA

**Comment by himeshr** [comment]
LFE APK available at https://samanvay.s3.ap-south-1.amazonaws.com/openchs/lfe-apks/LFE_27_FEB_2023.apk

test user : sachink@teachap / contact sachin for password

**Comment by himeshr** [comment]
LFE APK available at https://samanvay.s3.ap-south-1.amazonaws.com/openchs/lfe-apks/LFE_27_FEB_2023.apk

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-03-01 at 9.37.13 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/ab957296-b2fc-495f-8422-2379637b5084)
In search tab last individual value is cutting

**Comment by sachsk** [comment]
@AchalaBelokar create a separate bug card for this.
