### ISSUE TITLE
Search results dont show the last seach result

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#873]
Steps to reproduce:

- Login to mahatest with maha@maha login id
- Click on search
- Select beneficiary. Enter w in the "All registration and enrolment text fields". Click Submit
- The total matching results is displayed as 26 but displays only 25 cards, with the 25th card cut at the bottom.

FreshDesk : https://avni.freshdesk.com/a/tickets/2445

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-03-01 at 11.58.09 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/29598380-daeb-421a-9477-af155ec188c4)


LFE teach  
userid: sachink@teachap
