### ISSUE TITLE
Approval screen is not scrollable

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#879]
On smaller screens, the Approval page goes beyond the viewport, so the user is now not able to approve entities. 

https://avni.freshdesk.com/a/tickets/2429

**Comment by himeshr** [comment]
Code changes in avni-client 3.37 branch.
Fixed the issue by adding scrollView to ApprovalDetailsView. Also made few styling corrections to ApprovalDialog buttons. Refer screenrecording attached here in for more info.
https://images.zenhubusercontent.com/64590403/2ee26f5d-cd0e-473f-9422-b8ad30b11a0d/screen_recording_2023_02_28_at_5_52_05_pm.mov

**Comment by himeshr** [comment]
Prod APK for testing https://drive.google.com/file/d/1F5QLshS2KMorhmmhlqgY0dka7O5VMupR/view?usp=share_link

**Comment by himeshr** [comment]
Dev testing video of Approval Screen alignment and styling fix https://drive.google.com/file/d/16wTYJQXfTz49oEUph5MfRAJMO3ZgB5Vn/view?usp=share_link
