### ISSUE TITLE
Show totals on selecting encounter filters

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#880]
https://avni.freshdesk.com/a/tickets/2447

This is a feature that we had removed earlier, but needs to be brought back due to popular demand. 

The queries will be slow, however, and will be behind a feature toggle. It will be enabled only to those who absolutely need it.

**Comment by himeshr** [comment]
Dev testing recordings for following scenarios are available:
- Dont show totals on selection of prog / encounter if "hideTotal" flag is enabled: https://drive.google.com/file/d/1vTzoaPSLwvGcCmtw_RgGBnk0ucQikmaY/view?usp=share_link
- Show totals on selection of prog and progEncounter if "hideTotal" flag is disabled: https://drive.google.com/file/d/1JYATATnDRfin_ZnREMg08IDIhLkGvgP1/view?usp=share_link
- Show totals on selection of generalEncounter if "hideTotal" flag is disabled: https://drive.google.com/file/d/1StTz-99nHEgalY4gAXqZ9DK_NM8IZnhk/view?usp=share_link

Testing was done for IHMP and Calcutta_kids orgs with "hideTotalForProgram" flag set to enabled and then for disabled.

**Comment by himeshr** [comment]
Prod APK for testing https://drive.google.com/file/d/1F5QLshS2KMorhmmhlqgY0dka7O5VMupR/view?usp=share_link

**Comment by himeshr** [comment]
Truth table for reference:
h p e => t

1 1 1 0
1 1 0 0
1 0 1 0
0 1 1 1
0 0 1 1
0 1 0 1
1 0 0 1
0 0 0 1
