### ISSUE TITLE
Sync is failing and data entry app not loading, logout not working

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#883]
All these issues occurred with latest avni-server deployment. I feel they are related to getting organisation_config since it happens after that.

After going to data entry app in webapp(error will display), press back button and click on logout. Logout ll not work.

Steps to reproduce sync issue:
Login to maha@maha in staging
after sync the below error page appears
![Screenshot 2023-03-03 at 8.56.42 AM.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/31ed68be-3fec-4aee-826d-d13ebf4794ed)

Steps to reproduce sync issue: in perf
Login to maha@mobilecreches in perf
after sync the below error page appears
![Screenshot 2023-03-03 at 8.56.42 AM.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/31ed68be-3fec-4aee-826d-d13ebf4794ed)

Error log:
 DEBUG  [7:03:27:408] [Requests][Debug] GET: https://staging.avniproject.org/organisationConfig/search/lastModified?lastModifiedDateTime=1900-01-01T00:00:00.000Z&now=2023-03-03T03:24:15.163Z&size=100&page=0
 INFO  [7:03:27:409] [AuthService][Info] Found token
 ERROR  SyncComponent-Sync [object Object], {"errorCode":"Http 500","errorText":{"_x":0,"_y":0,"_z":null,"_A":null},"line":164338,"column":29,"sourceURL":"http://localhost:8081/index.android.bundle?platform=android&dev=true&minify=false&app=com.openchsclient&modulesOnly=false&runModule=true"}
 DEBUG  [7:03:27:633] [SyncComponent::AC][Debug] Dispatching action: "SyncTelemetryActions.SYNC_FAILED"
 DEBUG  [7:03:27:649] [SyncComponent::AC][Debug] Dispatched action completed: "SyncTelemetryActions.SYNC_FAILED"

Note:
As part of this card,  updated the code to display logs for exceptions it was not displaying,

**Comment by petmongrels** [comment]
/organisationConfig is failing but /web/organisationConfig is working
not able to check the issue because perf environment doesn't have all organisations setup
