### ISSUE TITLE
Introduce Draft Encounter feature to Avni

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#887]
### Motivation
Because we are automating creation of apks for multiple installations of Avni, we first need to be able to generate this from the same branch. We currently have the TeachAP app being deployed from a different branch, and one feature - Draft Encounter just in this branch. As part of this story, we will be adding the Draft Encounter Feature to Avni

### Acceptance criteria
- Draft Encounter Feature is merged to Avni from the lfe branch
- Draft Encounters is available as a feature in Organisation Config and is switched off by default for all organisations (changes required to the Organistion Config page and migration for all organisations)
- Ensure Draft Encounters is enabled for LFE (prod task)

### Testing
- Ensure switching on the feature enables Draft Encounter to organisations
- Ensure switching off the feature does not cause any trouble to organisations

**Comment by vinayvenu** [comment]
Comments on the commit - https://github.com/avniproject/avni-client/commit/903dbe6ece0785b1b57fce2a810f3b1b46528054

**Comment by AchalaBelokar** [comment]
- [ ] I entered the data in sakhi organisation which have general encounter fill the cbac form still the draft encounter is not working..

**Comment by sachsk** [comment]
Please test it on master apk
