### ISSUE TITLE
CI for app generation

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#889]
See earlier story that generates apks and app bundles. As part of this story, we have the ability to generate apks via CI

### Acceptance criteria
- Staging and prod app bundles are generated per app specified in configuration
- Both Avni and LFE apps work fine

**Comment by 1t5j0y** [comment]
CI builds generic flavor by default. In order to build other flavors, the flavor needs to be passed as a parameter to the circleci pipeline. Video detailing how to trigger pipeline with flavor parameter:
https://drive.google.com/file/d/1f9hRbNzcWQsYRwIJdDbSr_0OP-3T_eCp/view?usp=share_link
