### ISSUE TITLE
Delete LFE branch

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#890]
Now that the TeachAP app is generated from the main branch, we can delete the LFE branch

**Comment by himeshr** [comment]
We haven't done any LFE release using the TeachAP app generated from the main branch.
@mahalakshme and @vinayvenu should we hold off till we do that.?

**Comment by vinayvenu** [comment]
Moving out of Ready lane for now.

**Comment by vinayvenu** [comment]
This is not important enough to keep this card. Let the branch remain for posterity
