### ISSUE TITLE
Remove full data sync for those with media observations

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#892]
Remove a full data sync for those with media observations. This will reduce the number of calls made to this service (easy)

If there are media observations
1. Upload media files
2. Upload data
3. Download data

If there are no media observations
1. Upload data
2. Download data

- If a media sync fails due to the absence of a local file, then ignore it

- Modify performance test suite to account for this

**Comment by petmongrels** [comment]
nothing to do in avni-perf

**Comment by vinayvenu** [comment]
@petmongrels some minor comments on the commit.
