### ISSUE TITLE
Add template content instead of name in "Scheduled Messages" section

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#895]
The template on the "Scheduled Messages" section of Whatsapp does not convey enough information. Instead, it will be useful to replace it with the content of that template. 

Done for scheduled and sent messages of subject, user and group.
Code changes are to be done for both Avni Android app and Webapp.

**Comment by himeshr** [comment]
Code changes done in avni-server, avni-webapp and avni-client.

Tested for the following urls to verify that sentMessages and ScheduledMessages screens were working as expected:

- http://localhost:6010/#/broadcast/whatsApp/contactGroup/2362
- http://localhost:6010/#/broadcast/whatsApp/subjects/0d4a09dd-dd1a-421c-822d-8f28288c017f/messages
- http://localhost:6010/#/broadcast/whatsApp/users/637/messages

Also, the send message and search screens were functional.

User and Subject search screen do not filter based on input criteria. Need to look into it as part of separate bug.![Screenshot 2023-03-17 at 10.47.40 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/059a1af3-271c-44fc-9e1e-5b7559f5db27)![Screenshot 2023-03-17 at 10.47.12 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/54008f42-fa4c-4777-a7ef-ca7f978f652f)![Screenshot 2023-03-17 at 10.46.42 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/f86a603b-ccac-4f98-8a44-1fc5cc38928a)

**Comment by himeshr** [comment]
![Screenshot 2023-03-20 at 1.11.39 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/afd64a70-c580-42db-952d-f22151a93732)
