### ISSUE TITLE
Timestamps for sent/scheduled messages are incorrect

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-client#896]
![image.png](https://images.zenhubusercontent.com/5d8a51c647755200010d2fda/7f8e728d-352c-4be4-b3b0-7bd697102df7)

**Comment by Dinesh2019** [comment]
Still we face the timestamp message mismatch or incorrect
Refrences:
Screenshot from glific:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/59f82c74-0b4c-4a26-a9a3-c0c036bec875)
Screenshot from Avni app:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/1ea5cc37-3b9b-45ef-82b8-fc75b5f5d202)

**Comment by 1t5j0y** [comment]
As discussed, please retest with the APK from this build
https://app.circleci.com/pipelines/github/avniproject/avni-client/1560/workflows/44803a59-d75e-4cf9-98d7-a970e68f93e7/jobs/9941/artifacts

**Comment by Dinesh2019** [comment]
We got the new build to retest and issue got fixed.Attached sample for references.
Refrences;
Screenshot of glific 1:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/06f756d1-2225-44b3-8e70-e9f06cccec61)
Screenshot of avni app-1 : 
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/dcc3f0df-a7f6-49c8-a429-6f4a41a2c041)
Screenshot of glific 2:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/5672f595-c5b7-4544-868c-8c252b3e03a7)
Screenshot of Avni app:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/0bf0af7c-48ae-44c8-adbb-6c8696d58a89)
