### ISSUE TITLE
Ihmp - error:undefined is not object (evaluating 'n.privilageEntity')

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#902]
"when I am login through the mobile app it ask me to restart the app
fatal error:undefined is not object (evaluating 'n.privilageEntity')"

"adb log :-
Sync completed dispatching reset
Notifying Bugsnag TypeError: Fatal error: undefined is not an object (evaluating 'n.privilegeEntity')
03-24 14:51:57.550 27389 27433 I ReactNativeJS: 'App', 'renderError', 'Fatal error: undefined is not an object (evaluating \'n.privilegeEntity\')\nStacktrace:[{""columnNumber"":3261,""lineNumber"":941,""functionName"":""i"",""source"":""i@index.android.bundle:941:3261"",""fileName"":""index.android.bundle:941:3261""},{""columnNumber"":4028,""lineNumber"":941,""source"":""index.android.bundle:941:4028"",""fileName"":""index.android.bundle:941:4028""},{""columnNumber"":29369,""lineNumber"":449,""source"":""index.android.bundle:449:29369"",""fileName"":""index.android.bundle:449:29369""},{""columnNumber"":20003,""lineNumber"":449,""functionName"":""uu"",""source"":""uu@index.android.bundle:449:20003"",""fileName"":""index.android.bundle:449:20003""},{""columnNumber"":29174,""lineNumber"":449,""source"":""index.android.bundle:449:29174"",""fileName"":""index.android.bundle:449:29174""},{""columnNumber"":43597,""lineNumber"":449,""functionName"":""Ef"",""source"":""Ef@index.android.bundle:449:43597"",""fileName"":""index.android.bundle:449:43597""},{""columnNumber"":3947,""lineNumber"":941,""functionName"":""value"",""source"":""value@index.android.bundle:941:3947"",""fileName"":""index.android.bundle:941:3947""},{""columnNumber"":1739,""lineNumber"":732,""functionName"":""value"",""source"":""value@index.android.bundle:732:1739"",""fileName"":""index.android.bundle:732:1739""},{""columnNumber"":2259,""lineNumber"":732,""source"":""index.android.bundle:732:2259"",""fileName"":""index.android.bundle:732:2259""},{""columnNumber"":1277,""lineNumber"":76,""source"":""index.android.bundle:76:1277"",""fileName"":""index.android.bundle:76:1277""},{""columnNumber"":528,""lineNumber"":76,""functionName"":""p"",""source"":""p@index.android.bundle:76:528"",""fileName"":""index.android.bundle:76:528""},{""columnNumber"":2671,""lineNumber"":76,""functionName"":""callTimers"",""source"":""callTimers@index.android.bundle:76:2671"",""fileName"":""index.android.bundle:76:2671""},{""columnNumber"":3580,""lineNumber"":54,""functionName"":""value"",""source"":""value@index.android.bundle:54:3580"",""fileName"":""index.android.bundle:54:3580""},{""columnNumber"":759,""lineNumber"":54,""source"":""index.android.bundle:54:759"",""fileName"":""index.android.bundle:54:759""},{""columnNumber"":2583,""lineNumber"":54,""functionName"":""value"",""source"":""value@index.android.bundle:54:2583"",""fileName"":""index.android.bundle:54:2583""},{""columnNumber"":731,""lineNumber"":54,""functionName"":""value"",""source"":""value@index.android.bundle:54:731"",""fileName"":""index.android.bundle:54:731""},{""functionName"":""value"",""source"":""value@[native code]"",""fileName"":""[native code]:0:0""}]'"

**Comment by vinayvenu** [comment]
Duplicate
