### ISSUE TITLE
apfodishauat - Associate error

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#905]
Association error on sync for qrtuser@apfodishauat as well as utkarsh@apfodishauat
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/9bc944dd-0646-4f19-b42a-5586f29ca5eb)

**Comment by sachsk** [comment]
@Dinesh2019 is it happening on prod?
Please share username and password.

**Comment by Dinesh2019** [comment]
it is happening in prerelease and build version is 1-326e 
Username :  utkarsh@apfodishauat
Password : Audhdpassword

**Comment by sachsk** [comment]
@Dinesh2019 This is an implementation-specific issue explained to @utkarshavni .
Sync concept value is not updated for the individual.
