### ISSUE TITLE
Sync setting error 

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#907]
As per criteria if we create the individual under this user ID : beulah_poshansathi@apfodhisha by default the high risk is No.Hence it should not reflect in the beulah_qrt@apfodhisa in this account. 

Step to Reproduce:
1. Login to poshansathi account.
2.Register the individual.
3.High risk default No
4.Sync the data in the database
5.After login to qrt account.
6.search for the Individual name
Expected result : The individual ID should not displayed.
Actual : The Individual ID is displayed in the qrt account.

Sample Data : Test Din1

Poshansathi
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/bdfca63b-fcf6-4d43-99d1-61557306a560)

qrt;
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/94ea30a3-58aa-4760-b7eb-24380624172b)

![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/67a9c012-e989-4ca0-af48-ab49d7e72733)

**Comment by sachsk** [comment]
@Dinesh2019  this is an implementation-specific issue.
In this implementation sync on concept is not configured.
