### ISSUE TITLE
Workflow broken when filling form

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#909]
### Details
Environment - Prerelease
Login - AchalaB@rwbnitiuat
To reproduce
1. Login and sync
2. Choose any subject of type "Work Order". Try adding an encounter of type "Work Order Daily Recording - Machine"
3. Choose a machine. 
Expected - Machine should be chosen
Actual - "Selected Machine Registration is not approved"

Hopefully this is not caused by the recent changes in sync of approvals.

**Comment by himeshr** [comment]
Unable to reproduce this issue with either AchalaB@rwbnitiuat or himeshr@rwb users.
Was able to select a Excavation machine and create "Work Order Daily Recording - Machine" for both the users mentioned above using latest code pre-release apk.
