### ISSUE TITLE
Implementation of filters on non-standard report card types

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#913]
### Story
As an implementer, I would like to use the filters I defined on a custom dashboard so that I can mix and match multiple dashboard cards and apply filters consistently on the same dashboard

### Acceptance criteria
- Sync of dashboard filter to app
- Dashboard filters are available as a parameter to all custom report card types to be used
- Dashboard filters can be accessed through the "Filter" button that will be introduced on the top right of the screen
- Filter option is available on both home screen and the dashboard screen

### Testing
- Create custom report card types, and ensure filters can be used there (check with @utkarshavni for typical use cases)

**Comment by petmongrels** [comment]
Not making the filters smart in the mobile app. One example encountered so far:
- Earlier custom filters used to hide SubjectTypes that didn't have any subjects in the local database. Not making this optimisation (https://github.com/avniproject/avni-client/blob/2b01b926330bc22d3a3bc826fbf8cb92cf30cef2/packages/openchs-android/src/views/filter/CustomFilters.js#L124)

Secondly it is not clear from the above code - that this filter can be used in general because of the number of subjects of a particular type can be too many.

**Comment by petmongrels** [comment]
Documentation link
https://avni.readme.io/docs/writing-rules#14-dashboard-card-rule

**Comment by petmongrels** [comment]
About commits:
- the dashboard filter structure has been refactored from what it was earlier. commits under this story number only.
- changes in models, client, web app, and server

Testing
- the other stories should be tested
- there is likely defects because there are too many ways in which filters can be made. a lot of testing required to make sure all different types of filter are working fine.

**Comment by Dinesh2019** [comment]
When we add all filters in the dashboard of webapp.After i we login to client app dashboard we can able to see the filter option in the right corner when we click the filter the app is getting crashed.
Step to reproduce:
1.Login to Webapp
2.Click on the app designer 
3.click on the offline dashboard
4.Add the all the filters
5.After saving login to client app 
6.click on the more
7.Click on the dashboard 
8.Click on the filter in the right corner
Excepted : result should be displayed as per the filter 
Actual : app getting crash
Web App:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/b4b55b61-6c48-43dd-a4df-344b87ef2dcb)  
Client app :
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/48a96f34-3ba6-4e29-aabc-3ec080f08e29)

After clicking filter ;
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/2b126adf-2af0-4707-a06a-9353ac0df6ed)

**Comment by Dinesh2019** [comment]
we have the name field mismatch in the web app and client app dashboard
example ; for encounter in the field name we given the name as "Test" and same name is displayed in the app but for address and Gender we are getting the field type is displayed in the app.
Web app
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/035564e4-eae0-4e70-902a-ee78baedc1d0)
Client app :
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/f52660af-5ed4-4b58-abdc-42c48db602f9)
And if we add only concepts in the dashboard filter and try to apply the filter the app showing Fatal error:
User : dinesh@lahip
env : staging
Steps to reproduce:
1.Login to app
2.Click on more:
3.Click on dashboard
4.click on lahi intern
5.Type and click on apply
below error is displayed
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/73324aa1-7824-4761-bac7-5155858dd442)

**Comment by Dinesh2019** [comment]
Still we face the same issue

**Comment by mahalakshme** [comment]
moved back this card to cover untested cases related to access of filters in report cards query. Found that, access of filters in report card query not yet tested.

**Comment by mahalakshme** [comment]
need to test for APF usecase shared by Arjun: The main type of user who needs filters currently is called "Supervisor"
Supervisors are responsible for providing supportive supervision to "Poshan Sathi".  One supervisor can supervise 1-5 Poshan Sathis. 
Poshan Sathis are responsible for registering beneficiaries and completing visits on time.
Supervisors need to check regularly whether visits are being completed on time. If they are in a particular area, they need to filter the dashboard cards for a particular Poshan Sathi. We do not have filter for user right now. So they will filter by location (mapped to user usually one is to one). They may also want to see just a particular type of visit or just a particular type of beneficiary. 

Example If Poshan Sathi is Arjun and supervisor is Dinesh, Dinesh may want to see all the ANC visits that are overdue to be performed by Arjun.

**Comment by Dinesh2019** [comment]
We have dependency to figure out how we can write the qwery and check the behavior of the filter.

**Comment by 1t5j0y** [comment]
Discussion on standup: For this story, sufficient to test that the filter configuration is available in the rule to use.
Separate story avniproject/avni-client#1002 needs to be implemented before the APF use case can be tested.

**Comment by Dinesh2019** [comment]
- [ ] We are getting the empty params if we select the dateandtime
User : dineshg@APF
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/5d1cf724-c6ae-474d-8918-14c4f9789618)
Actual results 'params:::', '[]'
Excepeted results : 'params:::', '[{"type":"ProgramEncounterDate","dataType":"Default","filterValue":{"minValue":"2023-06-02T08:20:34.250Z"}}]'

And also if we use the data filter as default we are getting the same error 
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/7b3dd130-fd32-48e4-9e45-65c29111f1c9)
Actual result is 'params:::', '[]'

**Comment by petmongrels** [comment]
fixed in - https://github.com/avniproject/avni-client/commit/6e7c6b944d59aac87279d080f6ae037be6d73ca9
