### ISSUE TITLE
Eligiblity field is not displayed in the program eligbility forn for HCL

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#918]
Eligibility field is not displaying "Yes" in the Program eligibility form for HCL Techbee program - "Student name - Test Immutable". 

![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/ce74f96a-7bce-433d-9525-80012abc0880)

**Comment by sachsk** [comment]
@Dinesh2019 It was an implementation issue. I have fixed the rule now its working fine.

**Comment by Dinesh2019** [comment]
Retested the bug and it looks fine 
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/9f443e05-14b9-4779-9830-6c1f8f3c6d68)
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/badca8fe-942a-4d25-90ca-4ab08f68e42a)
