### ISSUE TITLE
Search issues

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#922]
env: prod, maha@jscs

1. When age is entered, results show individuals with other ages as well beyond +/- 4.  
2. on individual search results page, when no of search results is larger, the last no of displayed is cut. Is displayed even needed since we show all the results.
3. Sorting when custom filters applied are done case-insensitive, but when there are no custom filters, realm sorting(Eg: aya, Aab, Aya, bye, Bav, etc.,) is used. Another column in realm might need to be inserted with lowercase name, to achieve case-insensitive sorting. May be we can do the sorting outside realm or need to add a second field: https://stackoverflow.com/questions/49811087/how-can-i-sorting-case-insensitive-by-realm

**Comment by vinayvenu** [comment]
@mahalakshme 
1. We add a buffer of +/- 4 years for search. This working as designed. 
2. The last items are not cut anymore. Can you confirm this still happens? 
3. Sorting is costly. If there are a lot of results, the default behaviour should be to reduce the search output so that the results is lesser. For a few thousand beneficiaries in a catchment, the filter can be pretty specific

I am thinking of closing this card unless you feel otherwise.

**Comment by mahalakshme** [comment]
1. for 1st, yes it is not a bug
2. ![Screenshot 2023-05-23 at 11.09.07 AM.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/268160a2-d129-4de4-9921-f85a1e54bb0d) - Here 'total matching results' and displayed show the same count. before in displayed I remember, we used to show 20. I thought the "Displayed" field can be removed if it doesn't serve any purpose.
3. ![Screenshot 2023-05-23 at 11.09.52 AM.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/97875b31-1bd6-4696-acff-250182d9971f) - After asmita, Aadhaarwati is getting displayed which might be confusing for users when searching for someone after filtering. Sorting can be done outside realm(need to make sure this should not affect performance) or add another field - https://stackoverflow.com/questions/49811087/how-can-i-sorting-case-insensitive-by-realm

**Comment by vinayvenu** [comment]
Summarizing after discussion with Maha. 

1 is no longer an issue
2 is no longer an issue. The component is used in multiple places, and will help in consistency
3 will be left as is for now. The search code has high complexity, and this new behaviour does not seem to bring in a lot of benefit. 

Closing this issue.
