### ISSUE TITLE
Sync failed issue with different catchment

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#924]
For the account JSCS i have created the user for the different catchment and tried to login we facing an issue with the sync.
Step to reproduce:
1.Login to Avin app.
2.After the entering the app get automatically sync to the database.
3.while doing so we are getting the below error.
Login data:
1.dineshsh@jscs
2.dinesh@jscs
Screenshot :

![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/9dc1cabc-02fc-47b3-9867-c02ba18fb17e)

**Comment by vinayvenu** [comment]
Closing as this is a known issue. Id prefix needs to be provided when creating users.
