### ISSUE TITLE
Immutable encounter - user navigated to subject profile on clicking "Previous"

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/avni-client#925]
**Environment:**
https://prerelease.avniproject.org/
**Build version:**
1-a12db

**Organization**: Lend a Hand India.

**Steps to reproduce:**
1. Register a Student  (12th-HSC, Passed Out, Academic year as 2020-21/2021-22/2022-23)
2. Complete Program eligibility encounter.  (i.e. Mark Student interested in for HCL Techbee, )
3. Enroll student in the program.
4. Complete first follow-up.
5. Click on "Do" to perform second follow-up from planned visits.
6. Summary is displayed, click on Previous.
7. User navigated back to subject profile screen. 

**Expected:**
On clicking previous, it should take to the last filled page which shows the follow-up questions.

Things to test:
Navigation of Individual encounter, program encounter - both immutable and mutable

**Comment by AchalaBelokar** [comment]
- [ ] I tried with AchalaB@lahi.
Individual Nasha Nasha.
Attached one video[https://app.zenhub.com/files/64590403/b2eae4e1-3e7b-4a4c-b713-5f735e2e4e31/download](https://app.zenhub.com/files/64590403/b2eae4e1-3e7b-4a4c-b713-5f735e2e4e31/download)
