### ISSUE TITLE
RuleFailureTelemetry for ReportCard

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#928]
We can introduce type in RuleFailureTelemetry for such type of errors and make these fields conditionally optional.

Acceptance Criteria
-----
- When ReportCard fails, rule failure telemetry should be logged
- The logged telemetry should be synced to the server
- Enter report card uuid in the rule_uuid column
- rename rule_uuid to source_uuid
- Add a column called 'Source Type' which can have the values 'Old Rule', 'Form', 'Form Element', 'Report Card'
- Remove not null constraint from individual uuid.

**Comment by mahalakshme** [comment]
@petmongrels have merged this into this: https://github.com/avniproject/avni-client/issues/1172
