### ISSUE TITLE
Disable Forgot password for Keycloak

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#932]
### Story
We currently are not planning to build Reset password functionality for Keycloak because we are not clear how SMS integration would work. It is important to remove the Forgot Password option in this scenario because it can otherwise lead to incorrect UX

### Acceptance criteria
- When only Keycloak is enabled in the server, the "Forgot Password " button is not shown on the Login page
- When both Keycloak and Cognito are enabled on the server, show Forgot Password if "Use Keycloak" is not checked (This is useful to convey the fact that Forgot Password is not available when using Keycloak to testers, demonstration etc)
- When only Cognito is enabled, then the Forgot Password option is shown, and works.

**Comment by himeshr** [comment]
https://images.zenhubusercontent.com/64590403/5438ac74-4043-4db3-b79a-220e88c7d64d/screen_recording_2023_04_10_at_3_18_41_pm.mov

**Comment by 1t5j0y** [comment]
Not part of original story scope but for 'None' idp type, there is no password to reset so the link should not be shown in this case either.

**Comment by himeshr** [comment]
Made the change to only show "Forgot password" if settings.idpType is cognito or both(with userIdpType=cognito)
