### ISSUE TITLE
Sync getting failed when message rule have error and error also not getting save/logged

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#937]
Right now, when LAHI team tried to write down the rule for Glific message, the app sync was giving sync error. Ideally instead it should have logged the rule failure to the telemetry as it happens for other rules.

**Comment by vinayvenu** [comment]
@nupoorkhandelwal can you provide organisation details, expected message rule etc.

**Comment by sachsk** [comment]
Now the log is getting saved in the "rule_failure_log" table.
