### ISSUE TITLE
Sync refactorings

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#940]
- get Api for videotelemetry, synctelemetry  that returns empty pageableResource in server can be removed - not used. check if there are any other such telemetry apis.
- Simplify code introduced as part of #824  
             - in models: remove parentOfVirtualTxData and it can be made as just txData and handled in the same way as videotelemetry. update client code accordingly
             - remove virtualTxData and update entityName based on a condition. update client code accordingly

**Things to be tested:**
RWB approval sync - push and pull across user logins need to be tested
working of approvals with usergroups
backward compatibility with immediate older version
working of 3.37 apk

**Comment by mahalakshme** [comment]
changes in models, server and client

**Comment by AchalaBelokar** [comment]
two user same catchments which is having same permissions . need to test 3.40 apk

**Comment by mahalakshme** [comment]
3.37 apk link: https://drive.google.com/file/d/12FMDPe_UI5BQufGIaQwIGE96-T5ws3Yi/view?usp=sharing
