### ISSUE TITLE
On enrolment, not able to schedule a general encounter

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-client#949]
## Details to help reproduce the issue
Org name :- iphctrith_uat
version of the app :- Latest from playstore
programName :- Substance use
I am trying to schedule a general encounter called "Collect blood sample details" on the date of enrolment of program "Substance use" . 

## Visit Schedule rule
`
"use strict";
({ params, imports }) => {
  const programEnrolment = params.entity;
  const moment = imports.moment;
  const scheduleBuilder = new imports.rulesConfig.VisitScheduleBuilder({programEnrolment});
  const condition11 = new imports.rulesConfig.RuleCondition({programEnrolment}).when.lowestAddressLevel.defined.matches();
  if(condition11 ){
    const earliestDate = moment(programEnrolment.enrolmentDateTime).add(0, 'days').toDate();
    const maxDate = moment(programEnrolment.enrolmentDateTime).add(3, 'days').toDate();
    scheduleBuilder.add({name: "Collect blood sample details 1", encounterType: "Collect blood sample details", earliestDate, maxDate});  
}
  return scheduleBuilder.getAll();
};
`
## Error from avni-client log
I get an error saying "Fatal error: Can't find variable enrolment"
Stacktrace:- 
'Fatal error: Can\'t find variable: enrolment\nStacktrace:[{"columnNumber":2485,"lineNumber":775,"functionName":"value","source":"value@index.android.bundle:775:2485","fileName":"index.android.bundle:775:2485"},{"columnNumber":3177,"lineNumber":775,"source":"index.android.bundle:775:3177","fileName":"index.android.bundle:775:3177"},{"functionName":"map","source":"map@[native code]","fileName":"[native code]:0:0"}....

## Tech analysis details
The issue is caused due to code changes done as part of #884
ProgramEncounterService.saveScheduledVisit() //line no 66 still uses enrolment, whereas the method arg enrolment was renamed to programEnrolment.

**Comment by himeshr** [comment]
Code changes done in 3.38 branch

**Comment by himeshr** [comment]
Use apk from https://app.circleci.com/pipelines/github/avniproject/avni-client/1636
