### ISSUE TITLE
Last unplanned program encounter not visible

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#954]
Ticket: https://avni.freshdesk.com/a/tickets/2571. Was already raised as part of this: https://avni.freshdesk.com/a/tickets/2362 - but was marked resolved without solving it.

- Env: prod
- Login to maha@calcutta_kids
- Go to search
- Click Submit
- Open any individual enrolled in Child program
- Click on "New Program Visit"
- "Doctor Visit" doesn't display under "Unplanned Visits".  But on doing console.log like below in NewVisitMenuView its name displays. 
`console.log("NVMV::::", _.map(encounterTypes, (programEncounterType) => {
            return programEncounterType.encounterType.name
        }));`

Analysis:
Adding ScrollView tag might fix this issue.-didnt fix
tried this: https://github.com/necolas/react-native-web/issues/1462 - didnt work

![Screenshot 2023-04-20 at 3.45.32 PM.png](https://images.zenhubusercontent.com/62ff301d2acde40fdafa4566/34934910-6e4b-4c98-a91d-1d6e9211e91e)

**Comment by 1t5j0y** [comment]
Adding ScrollView to the parent component fixed this.
