### ISSUE TITLE
Visits are getting scheduled, but it doesn't appear on the UI

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-client#960]
Org :- iphctrith_uat
Env :- prod
Version of app :- latest from playstore

**Describe the bug**
Visits are getting scheduled, but it doesn't appear on the UI

**To Reproduce**
- Register an individual of age greater than 12 years.
- Enroll into the program called "Substance use".
- On enroling, a general encounter called "Collect blood sample details" is scheduled.
- Complete the visit "Collect blood sample details".
- On completion, 2 visits are being scheduled, one called "Record blood sample result" and other called "Collect blood sample details 2".
- The encounter "Record blood sample result" is present, but the other is not.

**To verify if the encounter is getting stored in the db, run the below scripts**

`set role iphctrith_uat;`
`select * from individual i where first_name like 'asdfdsf' ; --1320424`
`select * from encounter_type et ; -- blood sample details = 1921`
`select * from encounter e where individual_id = 1320424 and encounter_type_id = 1921 ;`

![Screenshot from 2023-04-28 10-36-42.png](https://images.zenhubusercontent.com/627c9e38b2b7107ec1888b53/e0114d34-3bee-4468-8033-71f34c1357d4)
![Screenshot from 2023-04-28 10-37-07.png](https://images.zenhubusercontent.com/627c9e38b2b7107ec1888b53/639a5de5-06ad-406c-b33c-9a833dcb75ec)

**Comment by vinayvenu** [comment]
probably related to https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/884

**Comment by vinayvenu** [comment]
Also check https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/954

**Comment by Dinesh2019** [comment]
still the schedule is not appeared in UI
env : prod
org : iphctrith_uat
User : dineshg@iphctrith_uat
steps to reproduce :
- Register an individual of age greater than 12 years.
- Enroll into the program called "Substance use".
- On enrolling, a general encounter called "Collect blood sample details" is scheduled.
- Complete the visit "Collect blood sample details".
- On completion, 2 visits are being scheduled, one called "Record blood sample result" and other called "Collect blood sample details 2".
- The encounter "Record blood sample result" is present, but the other is not.
After completing the first collect blood sample details
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/caa5aac0-0eb4-40d7-8363-65955372bce4)
After saved (collect blood sample details is missing)
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/11f65da2-8428-4746-b1e6-dc2b7d211b46)
