### ISSUE TITLE
Client not resetting the value when form elements value reset

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#963]
Env: prod, login name: saeed@lahi

Issue:
LAHI Alumni Status value is updated based on the values of form elements. When value of "Educational Qualifications" is Doctorate it got updated correctly as "Higher Education". But when value of "Educational Qualifications" is reset, it should have got updated to "Not Known Yet". 

https://images.zenhubusercontent.com/64590403/5166fc50-f90f-439b-b634-b9f804c246d4/issue.mov

Analysis:
When the value is logged in the rule, it prints the right value as and when values of form elements are updated. So seems like the issue is in client codebase. We are not updating the value when reset happens.

**Comment by himeshr** [comment]
## Analysis:

The rule written to determine value of the concept "LAHI Alumni Status", has a default value of null.
When we reset the value of the concept "Educational Qualifications", the FormElementStatus(FES) returned has the value "null".

This in avni-client is treated as a No-action operation and hence we do not reset the value of the concept.

Changing this behaviour in client, i.e. to reset on "null" value for FES is not feasible, at it would break the default No-action behaviour assumed in majority of FormElements.

This leads us to a discussion on the Criteria and conventions to be followed with Rule definition and evaluation.

**Comment by himeshr** [comment]
### Baaed on discussion on Skype chat, one of the suggestion was to:

When the FormElementStatus default value is set to null, it is trying to say that "I am not setting the value".
There are two things getting mixed up in one "value" field - a) what is the value and b) whether I am actually providing the value

Communicating these two things should be done via two separate fields. Both need not be expected from the rule.

FormElementStatus could have another field which is used in the platform only which indicates whether the value is being set or not. And another field to communicate the value. I think we can implement this in a way that backward compatibility is maintained.

In fact looking at other fields like answersToSkip, answersToShow etc can have the same problem. We can one additional internal field which assigns responsibility about whether it is being set or not.

**Comment by himeshr** [comment]
Code changes in FormElementStatus file in rules-config and avni-models repos.
The new rules-config and models will be used in avni-client, avni-webapp and rules-server.

**Comment by himeshr** [comment]
TODO:

- [x] * Update rules-config and models version in avni-client, avni-webapp and rules-server.
- [x] .* Add tests in ObservationHolderTest (Tests could only be added for PrimitiveDataTypes, couldnt add for QuestionGroupObservation and Encounter/Subject Type observations.)
