### ISSUE TITLE
Unable sync data in this organisation (sakhi, message to gliffic) this happen on staging

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#964]
Unable sync data in this organisation (sakhi, message to gliffic)
Login credentials AchalaB@sakhi

![Screenshot 2023-05-03 at 4.55.01 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/55b263d2-2523-4fad-b8a0-ed44bc7b59e0)

This was calling  /programEnrolment
[CognitoAuthService][Info] Found token
05-03 16:17:28.756  4315  4364 D ReactNativeJS: [4:17:28:756] [SyncService][Debug] Creating entity create functions for schema ProgramEnrolment
05-03 16:17:28.781  4315  4364 E ReactNativeJS: 'SyncComponent-Sync', 'undefined is not an object (evaluating \'u[e].forEach\'), {"line":451,"column":1634,"sourceURL":"index.android.bundle"}', 'index.android.bundle:451:1634\nreduce@[native code]\nindex.android.bundle:981:9433\nmap@[native code]\nvalue@index.android.bundle:981:9372\nvalue:981:10651\nvalue@[native code]\np@index.android.bundle:982:2038\nindex.android.bundle:982:2346\nu:54:1004\nvalue@[native code]\nvalue@[native code]'
05-03 16:17:28.793  4315  4365 E unknown:ReactNative: console.error: SyncComponent-Sync undefined is not an object (evaluating 'u[e].forEach'), {"line":451,"column":1634,"sourceURL":"index.android.bundle"} index.android.bundle:451:1634

**Comment by himeshr** [comment]
Fix done in avni-models version. 1.29.9.

**Comment by vinayvenu** [comment]
- Code similar to the change is also found in other places, such as Individual.js. Would these places also cause issues similar to the error mentioned, and if so, should we apply similar changes there as well? 
- We should prefer strings over classes/class names because the names need not be same after minification. One reason for this failure is that we were using classes. Should we move away from classes in maps so that we don't have to guess expected behaviour? 
-

**Comment by himeshr** [comment]
- Uniformly moved all mappings to mergeMap in models files
- Modified avni-models to move away from entityClass to entityClass.schemaName (string values instead of Classes) as recommended by Vinay in previous commit.

Modified client to send entityClass.schema.name instead of entityClass.
Updated webapp and client to use the 1.30.6 models version.

**Comment by AchalaBelokar** [comment]
- [ ] Facing same issue for AchalaB@rwb_test 
- [ ] Used latest  showing this error

**Comment by AchalaBelokar** [comment]
- [ ] Facing same issue for AchalaB@rwb_test 
- [ ] Used latest  showing this error

**Comment by himeshr** [comment]
The issue was due to code replace discrepancy while migrating from entityClass to SchemaName in Individual.js.

**Comment by AchalaBelokar** [comment]
Unable to sync  user maha@rwbniti

- [ ] 05-23 14:22:28.682  3593  3688 I ReactNativeJS: [2:22:28:682] [CognitoAuthService][Info] Found token
05-23 14:22:28.823  3593  3688 D ReactNativeJS: [2:22:28:822] [H::AC][Debug] Dispatching action: "SYNC.ON_UPDATE"
05-23 14:22:28.923  3593  3688 D ReactNativeJS: [2:22:28:923] [H::AC][Debug] Dispatched action completed: "SYNC.ON_UPDATE"
05-23 14:22:28.923  3593  3688 D ReactNativeJS: [2:22:28:923] [BaseService][Debug] Dispatching action: "SyncTelemetryActions.RECORD_FIRST_PAGE_OF_PULL"
05-23 14:22:28.984  3593  3688 D ReactNativeJS: [2:22:28:984] [Requests][Debug] GET: https://staging.avniproject.org/entityApprovalStatus?encounterTypeUuid=e36cfe15-5963-42b2-95b3-fea314c8b667&entityTypeUuid=e36cfe15-5963-42b2-95b3-fea314c8b667&entityType=Encounter&lastModifiedDateTime=1900-01-01T00:00:00.000Z&now=2023-05-23T08:51:35.570Z&size=100&page=0
05-23 14:22:28.987  3593  3688 I ReactNativeJS: [2:22:28:987] [CognitoAuthService][Info] Found token
05-23 14:22:29.171  3593  3688 D ReactNativeJS: [2:22:29:170] [SyncService][Debug] Creating entity create functions for schema EntityApprovalStatus
05-23 14:22:29.199  3593  3688 D ReactNativeJS: [2:22:29:198] [SyncService][Debug] SingleAssociation: Creating entity create functions for parent schema Encounter
05-23 14:22:29.205  3593  3688 D ReactNativeJS: [2:22:29:204] [SyncService][Debug] Creating entity create functions for [object Object]
05-23 14:22:29.284  3593  3688 E ReactNativeJS: 'SyncComponent-Sync', 'Exception in HostFunction: JS value must be of type \'object\', got (undefined), {"line":580,"column":1108,"sourceURL":"index.android.bundle"}', '[native code]\nvalue@index.android.bundle:580:1108\nindex.android.bundle:593:3105\nindex.android.bundle:593:2979\nmap@[native code]\nindex.android.bundle:593:2958\n[native code]\nvalue@index.android.bundle:580:1634\nvalue@index.android.bundle:593:2941\nvalue@[native code]\nvalue@index.android.bundle:985:11421\nvalue@[native code]\np@index.android.bundle:986:2038\nindex.android.bundle:986:2346\nu@index.android.bundle:69:157\nindex.android.bundle:69:866\nindex.android.bundle:76:1692\np@index.android.bundle:76:528\nN@index.android.bundle:76:918\ncallReactNativeMicrotasks@index.android.bundle:76:3079\nvalue@index.android.bundle:54:2935\nindex.android.bundle:54:1045\nvalue@index.android.bundle:54:2583\nvalue@index.android.bundle:54:1004\nvalue@[native code]\nvalue@[native code]'
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: console.error: SyncComponent-Sync Exception in HostFunction: JS value must be of type 'object', got (undefined), {"line":580,"column":1108,"sourceURL":"index.android.bundle"} [native code]
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@index.android.bundle:580:1108
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: index.android.bundle:593:3105
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: index.android.bundle:593:2979
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: map@[native code]
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: index.android.bundle:593:2958
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: [native code]
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@index.android.bundle:580:1634
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@index.android.bundle:593:2941
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@[native code]
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@index.android.bundle:985:11421
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@[native code]
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: p@index.android.bundle:986:2038
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: index.android.bundle:986:2346
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: u@index.android.bundle:69:157
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: index.android.bundle:69:866
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: index.android.bundle:76:1692
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: p@index.android.bundle:76:528
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: N@index.android.bundle:76:918
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: callReactNativeMicrotasks@index.android.bundle:76:3079
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@index.android.bundle:54:2935
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: index.android.bundle:54:1045
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@index.android.bundle:54:2583
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@index.android.bundle:54:1004
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@[native code]
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@[native code], stack:
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: Error@-1
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: p@39:268
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: p@39:359
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: s@37:362
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: construct@-1
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: <unknown>@35:481
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: v@35:669
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: h@35:1807
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@446:4992
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@738:2453
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@-1
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: u@69:156
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: <unknown>@69:865
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: <unknown>@76:1691
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: p@76:527
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: N@76:917
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: callReactNativeMicrotasks@76:3078
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@54:2934
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: <unknown>@54:1044
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@54:2582
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@54:1003
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@-1
05-23 14:22:29.311  3593  3689 E unknown:ReactNative: value@-1
05-23 14:22:29.397  3593  3688 D ReactNativeJS: [2:22:29:397] [H::AC][Debug] Dispatching action: "SyncTelemetryActions.SYNC_FAILED"
05-23 14:22:29.467  3593  3688 D ReactNativeJS: [2:22:29:467] [H::AC][Debug] Dispatched action completed: "SyncTelemetryActions.SYNC_FAILED"
05-23 14:22:29.472  3593  3688 D ReactNativeJS: [2:22:29:472] [H::AC][Debug] Dispatching action: "SYNC.ON_ERROR"
05-23 14:22:29.492  3593  3689 I bugsnag-react-native: callReactNativeMicrotasks@index.android.bundle:76:3079
05-23 14:22:29.524  3593  3688 D ReactNativeJS: [2:22:29:524] [H::AC][Debug] Dispatched action completed: "SYNC.ON_ERROR"
05-23 14:22:29.526  3593  3688 W ReactNativeJS: registerHeadlessTask or registerCancellableHeadlessTask called multiple times for same key 'syncJob'
05-23 14:22:29.533  3593  3688 I ReactNativeJS: [2:22:29:532] [AvniBackgroundJob-SyncJobSchedule][Info] Successfully scheduled
05-23 14:22:29.735  3593  3688 I ReactNativeJS: [2:22:29:735] [Sync][Info] Starting SyncService
05-23 14:22:29.736  3593  3688 I ReactNativeJS: [2:22:29:735] [Sync][Info] Getting SyncService
05-23 14:22:29.736  3593  3688 I ReactNativeJS: [2:22:29:736] [Sync][Info] Getting connection info
05-23 14:22:29.737  3593  3688 I ReactNativeJS: [2:22:29:737] [Sync][Info] Calling syncService.sync
05-23 14:22:29.738  3593  3688 D ReactNativeJS: [2:22:29:738] [SyncService][Debug] sync
05-23 14:22:29.756  3593  3688 D ReactNativeJS: [2:22:29:755] [BaseService][Debug] Dispatching action: "SyncTelemetryActions.START_SYNC"
05-23 14:22:29.849  3593  3688 D ReactNativeJS: [2:22:29:849] [mediaUploadRequired][Debug] false
05-23 14:22:29.886  3593  3688 D ReactNativeJS: [2:22:29:886] [BaseService][Debug] Dispatching action: "SyncTelemetryActions.RECORD_PUSH_TODO_TELEMETRY"
05-23 14:22:29.968  3593  3688 D ReactNativeJS: [2:22:29:967] [Requests][Debug] POST: https://staging.avniproject.org/syncTelemetry
05-23 14:22:29.972  3593  3688 I ReactNativeJS: [2:22:29:972] [CognitoAuthService][Info] Found token
05-23 14:22:30.085  3593  3688 D ReactNativeJS: [2:22:30:084] [BaseService][Debug] Dispatching action: "SyncTelemetryActions.ENTITY_PUSH_COMPLETED"
05-23 14:22:30.168  3593  3688 I ReactNativeJS: [2:22:30:168] [Sync][Info] 0.005
05-23 14:22:30.168  3593  3688 I ReactNativeJS: [2:22:30:168] [Sync][Info] 0.005
05-23 14:22:30.169  3593  3688 D ReactNativeJS: [2:22:30:169] [BaseService][Debug] Dispatching action: "SyncTelemetryActions.SYNC_COMPLETED"
05-23 14:22:30.250  3593  3688 D ReactNativeJS: [2:22:30:250] [Requests][Debug] POST: https://staging.avniproject.org/syncTelemetry
05-23 14:22:30.254  3593  3688 I ReactNativeJS: [2:22:30:253] [CognitoAuthService][Info] Found token
05-23 14:22:30.377  3593  3688 I ReactNativeJS: [2:22:30:377] [Sync][Info] 0.01
05-23 14:22:30.377  3593  3688 I ReactNativeJS: [2:22:30:377] [Sync][Info] 1


[Uploading... Screenshot 2023-05-23 at 2.28.59 PM.png]

**Comment by AchalaBelokar** [comment]
- [ ] failing for himeshr@jsscp user
Entities to sync News,,UserInfo,,ProgramEncounter,86ab0906-ec4c-49b7-adbc-da75197a7f6b,ProgramEncounter,1d8ccbb2-f4bb-4b19-979e-730ccd1514d2,Encounter,b751dbf5-fa3a-4ffb-9bfd-8ffded1c38a4,Individual,a2eee202-b440-4120-ada1-f3a820820f9c,ProgramEncounter,0619e2bc-5f08-4553-b9fc-a059bd847a9f,ProgramEnrolment,20016e73-3115-439d-8d8b-3bd4ab5c24b1,ProgramEncounter,84e99d1e-de73-41aa-85c6-3e1b780dd52b,ProgramEncounter,9c7d7e6a-d4ee-49c8-b798-bfa2ee16343b,ChecklistItem,223b48b2-326d-4d8f-addb-5c29cbe5ed96,ProgramEncounter,307197bf-6b71-49b1-9a1b-b2c12532e34f,ProgramEncounter,98dc3b51-c3d6-4e40-aebc-58e6ec051200,Individual,c3e43b29-2a63-49bf-870b-8365d2dd9251,ProgramEncounter,ab963eab-805d-4714-ad78-1e8a5fa164b2,ProgramEncounter,bb2ea3b7-55c8-4bab-8ee5-b71eec633408,Encounter,4427abc6-a7a3-4571-98e4-b16b742254d2,ProgramEncounter,0345e233-479c-4dff-a7b9-c1325a5c0493,ProgramEnrolment,6bb43253-7611-47be-9c11-bae31de76091,Checklist,223b48b2-326d-4d8f-addb-5c29cbe5ed96,Encounter,21b9968d-4ec1-405b-bde6-69a5b8dfe615,ProgramEncounter,856c06ea-1f1a-4316-80e3-23cd8eea810f,IndividualRelationship,c3e43b29-2a63-49bf-870b-8365d2dd9251,Encounter,4e4e9ff7-a977-4224-ad75-6fd80fd4578a,GroupSubject,a2eee202-b440-4120-ada1-f3a820820f9c,ProgramEncounter,e35551ec-811b-4291-8eb3-f36dbaa79c48
05-26 14:39:08.079  7132  7214 D ReactNativeJS: [2:39:08:079] [H::AC][Debug] Dispatching action: "SYNC.ON_MESSAGE_CALLBACK"
05-26 14:39:08.152  7132  7214 D ReactNativeJS: [2:39:08:152] [H::AC][Debug] Dispatched action completed: "SYNC.ON_MESSAGE_CALLBACK"
05-26 14:39:08.476  7132  7214 D ReactNativeJS: [2:39:08:475] [H::AC][Debug] Dispatching action: "SYNC.ON_MESSAGE_CALLBACK"
05-26 14:39:08.539  7132  7214 D ReactNativeJS: [2:39:08:539] [H::AC][Debug] Dispatched action completed: "SYNC.ON_MESSAGE_CALLBACK"
05-26 14:39:08.553  7132  7214 D ReactNativeJS: [2:39:08:553] [Requests][Debug] GET: https://prerelease.avniproject.org/subject/1b201cd0-de35-4ddb-b0ab-b53ad8a2b20f/allEntities
05-26 14:39:08.556  7132  7214 I ReactNativeJS: [2:39:08:556] [CognitoAuthService][Info] Found token
05-26 14:39:09.311  7132  7214 E ReactNativeJS: 'SyncComponent-Sync', 'undefined is not an object (evaluating \'u[e].forEach\'), {"line":451,"column":1634,"sourceURL":"index.android.bundle"}', 'index.android.bundle:451:1634\nreduce@[native code]\nmap@[native code]\nvalue@index.android.bundle:995:3166\nvalue@index.android.bundle:995:4194\nvalue@index.android.bundle:995:2353\nindex.android.bundle:995:1737\nu@index.android.bundle:69:157\nindex.android.bundle:69:866\nindex.android.bundle:76:1692\np@index.android.bundle:76:528\nN@index.android.bundle:76:918\ncallReactNativeMicrotasks@index.android.bundle:76:3079\nvalue@index.android.bundle:54:2935\nindex.android.bundle:54:1045\nvalue@index.android.bundle:54:2583\nvalue@index.android.bundle:54:1004\nvalue@[native code]\nvalue@[native code]'
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: console.error: SyncComponent-Sync undefined is not an object (evaluating 'u[e].forEach'), {"line":451,"column":1634,"sourceURL":"index.android.bundle"} index.android.bundle:451:1634
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: reduce@[native code]
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: map@[native code]
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@index.android.bundle:995:3166
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@index.android.bundle:995:4194
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@index.android.bundle:995:2353
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: index.android.bundle:995:1737
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: u@index.android.bundle:69:157
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: index.android.bundle:69:866
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: index.android.bundle:76:1692
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: p@index.android.bundle:76:528
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: N@index.android.bundle:76:918
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: callReactNativeMicrotasks@index.android.bundle:76:3079
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@index.android.bundle:54:2935
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: index.android.bundle:54:1045
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@index.android.bundle:54:2583
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@index.android.bundle:54:1004
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@[native code]
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@[native code], stack:
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: Error@-1
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: p@39:268
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: p@39:359
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: s@37:362
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: construct@-1
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: <unknown>@35:481
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: v@35:669
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: h@35:1807
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@446:4992
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@738:2453
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@-1
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: u@69:156
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: <unknown>@69:865
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: <unknown>@76:1691
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: p@76:527
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: N@76:917
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: callReactNativeMicrotasks@76:3078
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@54:2934
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: <unknown>@54:1044
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@54:2582
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@54:1003
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@-1
05-26 14:39:09.320  7132  7216 E unknown:ReactNative: value@-1
05-26 14:39:09.371  7132  7214 D ReactNativeJS: [2:39:09:370] [H::AC][Debug] Dispatching action: "SyncTelemetryActions.SYNC_FAILED"
05-26 14:39:09.451  7132  7214 D ReactNativeJS: [2:39:09:451] [H::AC][Debug] Dispatched action completed: "SyncTelemetryActions.SYNC_FAILED"
05-26 14:39:09.452  7132  7214 D ReactNativeJS: [2:39:09:452] [H::AC][Debug] Dispatching action: "SYNC.ON_ERROR"
05-26 14:39:09.509  7132  7214 D ReactNativeJS: [2:39:09:509] [H::AC][Debug] Dispatched action completed: "SYNC.ON_ERROR"
05-26 14:39:09.510  7132  7214 W ReactNativeJS: registerHeadlessTask or registerCancellableHeadlessTask called multiple times for same key 'syncJob'
05-26 14:39:09.515  7132  7216 I bugsnag-react-native: callReactNativeMicrotasks@index.android.bundle:76:3079
05-26 14:39:09.533  7132  7214 I ReactNativeJS: [2:39:09:533] [AvniBackgroundJob-SyncJobSchedule][Info] Successfully scheduled
05-26 14:39:09.765  7132  7214 I ReactNativeJS: [2:39:09:762] [Sync][Info] Starting SyncService
05-26 14:39:09.765  7132  7214 I ReactNativeJS: [2:39:09:765] [Sync][Info] Getting SyncService
05-26 14:39:09.766  7132  7214 I ReactNativeJS: [2:39:09:766] [Sync][Info] Getting connection info
05-26 14:39:09.767  7132  7214 I ReactNativeJS: [2:39:09:767] [Sync][Info] Calling syncService.sync
05-26 14:39:09.768  7132  7214 D ReactNativeJS: [2:39:09:767] [SyncService][Debug] sync
05-26 14:39:09.796  7132  7214 D ReactNativeJS: [2:39:09:796] [BaseService][Debug] Dispatching action: "SyncTelemetryActions.START_SYNC"
05-26 14:39:09.909  7132  7214 D ReactNativeJS: [2:39:09:909] [mediaUploadRequired][Debug] false
05-26 14:39:09.940  7132  7214 D ReactNativeJS: [2:39:09:939] [BaseService][Debug] Dispatching action: "SyncTelemetryActions.RECORD_PUSH_TODO_TELEMETRY"
05-26 14:39:10.014  7132  7214 D ReactNativeJS: [2:39:10:014] [Requests][Debug] POST: https://prerelease.avniproject.org/syncTelemetry
05-26 14:39:10.016  7132  7214 I ReactNativeJS: [2:39:10:016] [CognitoAuthService][Info] Found token
05-26 14:39:10.133  7132  7214 D ReactNativeJS: [2:39:10:132] [BaseService][Debug] Dispatching action: "SyncTelemetryActions.ENTITY_PUSH_COMPLETED"
05-26 14:39:10.202  7132  7214 I ReactNativeJS: [2:39:10:201] [Sync][Info] 0.005
05-26 14:39:10.202  7132  7214 I ReactNativeJS: [2:39:10:202] [Sync][Info] 0.005
05-26 14:39:10.202  7132  7214 D ReactNativeJS: [2:39:10:202] [BaseService][Debug] Dispatching action: "SyncTelemetryActions.SYNC_COMPLETED"
05-26 14:39:10.312  7132  7214 D ReactNativeJS: [2:39:10:312] [Requests][Debug] POST: https://prerelease.avniproject.org/syncTelemetry
05-26 14:39:10.316  7132  7214 I ReactNativeJS: [2:39:10:316] [CognitoAuthService][Info] Found token
05-26 14:39:10.438  7132  7214 I ReactNativeJS: [2:39:10:437] [Sync][Info] 0.01
05-26 14:39:10.438  7132  7214 I ReactNativeJS: [2:39:10:438] [Sync][Info] 1
05-26 14:39:10.439  7132  7214 D ReactNativeJS: [2:39:10:438] [BaseService][Debug] Deleting all data from RuleFailureTelemetry
05-26 14:39:10.447  7132  7214 I ReactNativeJS: [2:39:10:447] [Sync][Info] Sync completed

**Comment by himeshr** [comment]
The sync for himeshr@jsscp was successful for me using 3.39 branch latest avni-client apk. So moving it to QA Ready again.
