### ISSUE TITLE
Ability to turn off background sync

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#966]
### Purpose
Often, during development someone might use a production system. In this case, they need to be able to disable automatic sync so that changes they make in local are not pushed to the server. 

### Acceptance criteria
- On Settings, there is an option to turn off automatic sync
- Default value is "ON"
- If turned on, then automated sync does not happen on the device, and existing jobs are cancelled
- Automatic sync settings are saved to server
- Add the above ability in webapp also

### Testing notes
- Ensure that save of user on the UI does not cause unintended consequences
- Verify job after ensuring that background sync actually works on the device where the test is performed

**Comment by mahalakshme** [comment]
changes in webapp and client

**Comment by AchalaBelokar** [comment]
- [ ] I tried to click to enable trun off automatic syn but showing this error.

https://github.com/avniproject/avni-client/assets/104890488/53df65fa-1150-4be5-9ef3-301d3c30f818


n][Debug] Route size: 1
07-19 06:29:56.861  4054  4540 D ReactNativeJS: [6:29:56:860] [Router][Debug] renderScene: Current Routes: /landingView,/settingsView. Route: /landingView
07-19 06:29:56.861  4054  4540 D ReactNativeJS: [6:29:56:861] [Router][Debug] Using cached route: /landingView. Element map path: /landingView
07-19 06:29:56.862  4054  4540 D ReactNativeJS: [6:29:56:862] [Router][Debug] renderScene: Current Routes: /landingView,/settingsView. Route: /settingsView
07-19 06:29:59.009  4054  4540 D ReactNativeJS: [6:29:59:009] [U::AC][Debug] Dispatching action: "S.ON_CAPTURE_AUTO_SYNC_CHANGE"
07-19 06:29:59.014  4054  4540 D ReactNativeJS: [6:29:59:014] [ErrorHandler][Debug] IsFatal=true Error: Exception in HostFunction: Missing value for property 'UserInfo.uuid'
07-19 06:29:59.014  4054  4540 D ReactNativeJS: [6:29:59:014] [ErrorHandler][Debug] Exception in HostFunction: Missing value for property 'UserInfo.uuid'
07-19 06:29:59.021  4054  4540 D ReactNativeJS: [6:29:59:021] [ErrorHandler][Debug] Creating frame array
07-19 06:29:59.021  4054  4540 D ReactNativeJS: [6:29:59:021] [ErrorHandler][Debug] Notifying Bugsnag Error: Fatal error: Exception in HostFunction: Missing value for property 'UserInfo.uuid'
07-19 06:29:59.026  4054  4540 I ReactNativeJS: 'App', 'renderError', 'Fatal error: Exception in HostFunction: Missing value for property \'UserInfo.uuid\'\nStacktrace:[{"columnNumber":1108,"lineNumber":584,"functionName":"value","source":"value@index.android.bundle:584:1108","fileName":"index.android.bundle:584:1108"},{"columnNumber":1203,"lineNumber":949,"source":"index.android.bundle:949:1203","fileName":"index.android.bundle:949:1203"},{"columnNumber":1634,"lineNumber":584,"functionName":"value","source":"value@index.android.bundle:584:1634","fileName":"index.android.bundle:584:1634"},{"columnNumber":1180,"lineNumber":949,"functionName":"value","source":"value@index.android.bundle:949:1180","fileName":"index.android.bundle:949:1180"},{"columnNumber":1850,"lineNumber":1076,"functionName":"value","source":"value@index.android.bundle:1076:1850","fileName":"index.android.bundle:1076:1850"},{"columnNumber":2872,"lineNumber":1076,"functionName":"value","source":"value@index.android.bundle:1076:2872","fileName":"index.android.bundle:1076:2872"},{"columnNumber":648,"lineNumber":1031,"source":"index.android.bundle:1031:648","fileName":"index.android.bundle:1031:648"},{"columnNumber":3442,"lineNumber":1119,"source":"index.android.bundle:1119:3442","fileName":"index.android.bundle:1119:3442"},{"columnNumber":1557,"lineNumber":1119,"functionName":"b","source":"b@index.android.bundle:1119:1557","fileName":"index.android.bundle:1119:1557"},{"columnNumber":2758,"lineNumber":595,"functionName":"value","source":"value@index.android.bundle:595:2758","fileName":"index.android.bundle:595:2758"},{"columnNumber":1971,"lineNumber":2451,"functionName":"onValueChange","source":"onValueChange@index.android.bundle:2451:1971","fileName":"index.android.bundle:2451:1971"},{"columnNumber":1914,"lineNumber":316,"functionName":"L","source":"L@index.android.bundle:316:1914","fileName":"index.android.bundle:316:1914"},{"columnNumber":171,"lineNumber":27,"functionName":"c","source":"c@index.android.bundle:27:171","fileName":"index.android.bundle:27:171"},{"columnNumber":314,"lineNumber":27,"functionName":"m","source":"m@index.android.bundle:27:314","fileName":"index.android.bundle:27:314"},{"columnNumber":368,"lineNumber":27,"functionName":"v","source":"v@index.android.bundle:27:368","fileName":"index.android.bundle:27:368"},{"columnNumber":679,"lineNumber":27,"functionName":"w","source":"w@index.android.bundle:27:679","fileName":"index.android.bundle:27:679"},{"columnNumber":14319,"lineNumber":27,"functionName":"Le","source":"Le@index.android.bundle:27:14319","fileName":"index.android.bundle:27:14319"},{"columnNumber":5361,"lineNumber":27,"functionName":"X","source":"X@index.android.bundle:27:5361","fileName":"index.android.bundle:27:5361"},{"columnNumber":14667,"lineNumber":27,"source":"index.android.bundle:27:14667","fileName":"index.android.bundle:27:14667"},{"columnNumber":95482,"lineNumber":27,"functionName":"Ce","source":"Ce@index.android.bundle:27:95482","fileName":"index.android.bundle:27:95482"},{"columnNumber":14129,"lineNumber":27,"functionName":"ze","source":"ze@index.android.bundle:27:14129","fileName":"index.android.bundle:27:14129"},{"columnNumber":14506,"lineNumber":27,"functionName":"Me","source":"Me@index.android.bundle:27:14506","fileName":"index.android.bundle:27:14506"},{"columnNumber":14916,"lineNumber":27,"functionName":"receiveEvent","source":"receiveEvent@index.android.bundle:27:14916","fileName":"index.android.bundle:27:14916"},{"columnNumber":3580,"lineNumber":54,"functionName":"value","source":"value@index.android.bundle:54:3580","fileName":"index.android.bundle:54:3580"},{"columnNumber":759,"lineNumber":54,"source":"index.android.bundle:54:759","fileName":"index.android.bundle:54:759"},{"columnNumber":2583,"lineNumber":54,"functionName":"value","source":"value@index.android.bundle:54:2583","fileName":"index.android.bundle:54:2583"},{"columnNumber":731,"lineNumber":54,"functionName":"value","source":"value@index.android.bundle:54:731","fileName":"index.android.bundle:54:731"},{"functionName":"value","source":"value@[native code

**Comment by himeshr** [comment]
Issue caused due to code changes done related to Privileges story..
Fix done in Models, used that in client.
Use [apk](https://app.circleci.com/pipelines/github/avniproject/avni-client/1833/workflows/39f87495-821d-41bf-a528-af26220f64ee/jobs/11430/artifacts) or later ones
