### ISSUE TITLE
Issues with search

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#967]
Please see video in https://avni.freshdesk.com/a/tickets/2634

**Comment by himeshr** [comment]
1. On search page, when you switch between subjectTypes, after selecting includeVoided flags, query didnt have includeVoided set.
2. Custom SearchFilter has isVoided hardcoded: After discussion, we decided to use isVoided check only at Individual level.

**Comment by 1t5j0y** [comment]
**Test steps in video:**
Individual Search -> Name: Test, Include Voided: Checked -> 9 Search results, all voided all contain test
Back to search
Change to Household search -> Name: field disappeared, Include Voided: (remains) checked -> 4 search results, none voided
Back to search
Stay on Household search -> Include voided: unchecked -> 7 search results, 3 voided 4 unvoided
Back to search
Change to Individual search -> Include voided: (remains) unchecked, Mobile number: 9834 -> 13 search results
Back to search
Stay on Individual search -> Mobile number: (remains) 9834, Include voided: check -> 13 search results (none voided)
Back to search
Stay on Individual search -> Mobile number: change to empty, Include voided: uncheck -> 13 search results
Back to search
Select household search, then select individual search -> Mobile number: (remains) empty, Include voided: (remains) unchecked -> 162 search results
Back to search
Stay on Individual search -> Include voided: checked -> 175 search results


**Issues:**
1. includeVoided on UI and in actual search go out of sync when includeVoided is selected and the subject type is changed
2. includeVoided not respected when performing custom filter search
