### ISSUE TITLE
Numeric concepts accepts space and stores space

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#968]
Steps to reproduce:
- Use a concept of this type Numeric: https://app.avniproject.org/#/appDesigner/concept/51f90d12-e4fb-4cb9-89d4-0c0b45629dbe/show in a form.(org name: JNPCT) Dont mark the input mandatory in the form.
- Input space as the value
- Its saves value of concept as " " in db
- Since this is unexpected etl for jnpct failed and resulted in this ticket: https://avni.freshdesk.com/a/tickets/2646.

Note: The above issue doesn't occur when the field is marked mandatory. It stores 0 as the value.

Expectation:
Numeric concepts should store only nos and not spaces.

**Comment by vedfordev** [comment]
In numeric field text also allowed
check for below
org : rwbnitiuat
encounter : Work order daily Recording - Machine

**Comment by 1t5j0y** [comment]
Unable to simulate this on either android or DEA in multiple implementations. Moving to on hold.

**Comment by mahalakshme** [comment]
looks like some changes in 3.39 has fixed this issue. closing this card.

**Comment by vinayvenu** [comment]
For history, the card that fixed this caused other issues in the numeric form element, and was again fixed in 3.39. Marking this as 3.39 since the card came in last minute
