### ISSUE TITLE
Default subject type on dashboard should not be random

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-client#969]
### Acceptance criteria
- The last selected subject type is shown everytime a user opens the dashboard
- Ensure this does not get overridden when settings are changed in the server

There is a feedback from production related to this. Please check the ticket
https://avni.freshdesk.com/a/tickets/2368

**Comment by himeshr** [comment]
Code changes in master branch, avni-client repo.

**Comment by petmongrels** [comment]
General.getPreviouslySelectedSubjectType
this should be in LocalCacheService (General is non-domain stuff)

**Comment by himeshr** [comment]
> General.getPreviouslySelectedSubjectType this should be in LocalCacheService (General is non-domain stuff)

Will move it back to LocalCacheService.

**Comment by AchalaBelokar** [comment]
@himeshr 

https://github.com/avniproject/avni-client/assets/104890488/d3c3f11f-298c-4eaa-a02c-6a5d5e4de578

filter is not showing after we back to the app is this scope of this card
