### ISSUE TITLE
Translations not possible to be done at some places and for some terms

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/avni-client#972]
Org - AKRSP UAT

Attaching screenshots for reference:

1. Card headings in dashboard are not getting translated.
2.  Registration date in Registration details is not translated.

For 1st:
![WhatsApp Image 2023-05-15 at 17.36.41.jpg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/a43c58d6-4d89-4712-b5a6-6337d4b6d2b4)

For 2nd:
![WhatsApp Image 2023-05-15 at 17.36.40.jpg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/26d73a29-1bef-4d29-87b8-9184360ba734)

Fix details:
- 1st issue was bcoz we are not searching for the translations when displaying section name. Fixed that for section name and description
- 2nd issue was bcoz translation was not defined for it.
- have also added translations for wordings in "Edit Settings" page - 
- when translations are defined in platform as well as in implementation, it is implementation(lokalise) defined translation need to be considered. - already existing fnality

**Comment by mahalakshme** [comment]
have also added translations for wordings in "Edit Settings" page

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-05-17 at 1.43.35 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/bff4aeb8-63b5-43dc-8b45-71e2a6244ab2)


Translation is missing for this

**Comment by AchalaBelokar** [comment]
- [ ]  ward Name should be in hindi
![Screenshot 2023-05-17 at 1.46.38 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/e2498735-a6cc-4620-9511-97238133d074)
