### ISSUE TITLE
Authentication error should not be reported to bugsnag - BugSnag Error (Avni Client)

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#975]
**BugSnag Error**
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/6464b25415ac3d0008e3cdb1

**Management of BugSnag error and BugSnag**
https://avni.readme.io/docs/how-to-use-bugsnag

**Comment by vinayvenu** [comment]
Error is invalid. However, the error heading is clear. Adding to 4.0.0 release

**Comment by ashusvnath** [comment]
Authentication Error is not being sent to Bugsnag.
I debugged the flow for authentication failure and bugsnag.notify was never invoked either asynchronously or synchronously in after a failed login attempt.

Rejecting this card as it can't be reproduced.
