### ISSUE TITLE
Change  the  filtering  sequence ..

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#977]
On the Image Viewer listing page user should be able to filter image
the sequence of filter  should be like this
Subject Type
Program
Encounter

**Comment by AchalaBelokar** [comment]
- [ ] after selecting the  concept name show text concept reset not
 ![Screenshot 2023-06-05 at 10.50.19 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/fad38db8-b9d5-49ae-9bdf-fec5ee871d12)

**Comment by AchalaBelokar** [comment]
- [ ] Text Concept is not visible in the filter.. thats th reason we are not able filter by text
- [ ]

**Comment by AchalaBelokar** [comment]
- [ ] Text Concept is not visible in the filter.. thats the reason we are not able filter by text
- [ ] there are lots of concept is present still it is not reflecting
- [ ]

**Comment by brajesh-lab** [comment]
@AchalaBelokar I have fixed it, please test.

**Comment by AchalaBelokar** [comment]
[ ] @brajesh-lab coded concept filter is not working
 [ ]also number concept filter is not working
 [ ]  text filter is not 
 [ ]  basically  filter is nit working for concepts

@vinayvenu pls look at this they need to api for that

**Comment by AchalaBelokar** [comment]
- [ ] When I am selected location and sub type and prog , encounter type , and concept type but it is showing me wrong value
- [ ] When I am moving to one sub type to another the result is not appearing 

[Screen Recording 2023-06-22 at 3.10.59 PM.zip](https://github.com/avniproject/avni-client/files/11832547/Screen.Recording.2023-06-22.at.3.10.59.PM.zip)
