### ISSUE TITLE
Introduce encryption of local database

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#978]
### Story
Data on the android client often contains PII, and it is good to encrypt the database on disk so that loss of storage does not lead to data leaks. With this card, we will be enabling this encryption. 

### Tech notes
- Realm files can be encrypted (see https://www.mongodb.com/docs/realm/sdk/react-native/realm-files/encrypt/)
- Existing unencrypted Realm files need to be copied over to an encrypted database to encrypt them (see (https://stackoverflow.com/questions/31204890/how-to-apply-encryption-on-existing-realm-database)). This might not be required right away
- Upload database and setting up fast sync will not work with encrypted databases
- DB can be copied over to a new encrypted  database if it is detected that an organisation has enabled encryption
- We get to know about encryption via calls to organisation config or /me, and then encrypt the database before proceeding forward with sync
- react-native-keychain can be used to store and retrieve the key
- Try to depend on as low a number of data points to figure out if the db is encrypted or not

### Acceptance criteria
- There is a flag to "Enable encryption of Local Database on the app" that can be enabled through the Organisation Config screen
- The default value of this field is "off"
- The user is provided a warning about side-effects when encryption is enabled (that this will hide some features)
- When encryption is enabled, fast sync and upload data are disabled on devices
- Encryption key is stored in Android Keychain
- Encryption can be either turned on or off, and the local db will behave accordingly after sync

### Testing notes
- Test with existing client and encryption enabled as well

**Comment by ashusvnath** [comment]
https://github.com/realm/realm-swift/issues/8081

**Comment by ashusvnath** [comment]
Decrypting an encrypted realm database and using that file leads to a an error:
```
Error: Exception in HostFunction: Unable to open a realm at path '/data/data/com.openchsclient/files/default.realm': Realm file decryption failed Path:Exception backtrace:
<backtrace not supported on this platform>.
Error: Exception in HostFunction: Unable to open a realm at path '/data/data/com.openchsclient/files/default.realm': Realm file decryption failed Path:Exception backtrace:
```

**Comment by vinayvenu** [comment]
@ashusvnath the linked bug looks ios related
