### ISSUE TITLE
Longitudinal export Date range issue

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#979]
Issue : 
In the web console, the Excel report generated through Longitudinal Export contains records outside of the given date range.

Might have something to do with date times. The report brings in some extra rows at the beginning of the date range. 
![ReportRecords_issue - Ajit Mangrule](https://github.com/avniproject/avni-client/assets/426156/586ae4ed-00d0-4016-85e0-ce4aee58b601)

https://avni.freshdesk.com/a/tickets/2682

**Comment by himeshr** [comment]
Root cause of the issue was that start-date inference from export API request was not done by applying the timezone specified in the request.
Code fix done in Avni-server, 3.39 branch.
