### ISSUE TITLE
Standard offline report card not showing up visits for some of the subject types

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#981]
**Describe the bug**
Currently the standard offline report card for Overdue visits is not showing up overdue visits (general encounters) from certain subject types

**Ticket reference** 
https://avni.freshdesk.com/a/tickets/2680

**To Reproduce**
1. Go to STCATP prod org
2. Click on Overdue visit card on custom dashboard
3. Scroll down and check there are not overdue visits for Monthly planner subject type
4. While if you look into Monthly planner subjects, then there are multiple subject having overdue visits.

**Screenshots**
![16845074475683420996695518772327.jpg](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/12472948-3345-431e-bb31-7cbe403dff3d)![16845074194279152100437042706743.jpg](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/dfaaf073-1bf7-4f9b-b40a-e0fe0d302457)

**Comment by mahalakshme** [comment]
not a product bug, have replied to the ticket - permission issue.
