### ISSUE TITLE
Translations not possible to be done at some places.

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#982]
Org -AKRSP UAT
- [x]  After saving the encounter/ProgramEncounter , a message appears for bit that "form name" is not translated
- [x]  In the Competed encounters there is "scheduled": date  scheduled is not translated.
- [x]  More tab there is change password  tab :  change password is not translated
- [x]  Add translations to User login, ResetForgottenPassword and SetPassword screens that are accessible before login
- [x]  Add translations for Program Encounter cancel as well, now that we are right here.
- [x]  Add translations for ForgotPassword view

Attaching the screenshots:

![Screenshot 2023-05-25 at 2.25.47 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/017e70a1-09bb-4fcd-a69d-3166c9713185)

![Screenshot 2023-05-25 at 2.29.24 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/98842527-f218-4504-ac93-858ec1356005)

![Screenshot 2023-05-25 at 2.31.16 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/94ad87e0-ca9d-41df-aab6-7d87d69ab327)

**Comment by vinayvenu** [comment]
Add for Program Encounter cancel as well, now that we are right here.

**Comment by himeshr** [comment]
Added translations for Program Encounter cancel as well.
