### ISSUE TITLE
Facing  the issue related Previous and next button

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#983]
- [ ] Fix alignment of Previous and next button
- [ ] Previous and next buttons are enabled even when there are no more search results / pages
-![Screenshot 2023-05-26 at 9.43.59 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/29b2a4a6-61f6-4e11-b095-6e2536d6d216)

**Comment by vinayvenu** [comment]
@AchalaBelokar can you move this to avni-media repository?
