### ISSUE TITLE
News button does not work

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#986]
1. Ensure that News is set up for an organisation
2. Sync and go to More section
3. Press on News

Expected: News to be shown
Actual: App crashes. Error below

"05-25 16:38:52.734  7373  7413 D ReactNativeJS: [4:38:52:734] [Router][Debug] renderScene: Current Routes: /landingView,/newsListView,/newsDetailView. Route: /newsDetailView
05-25 16:38:52.758  7373  7413 E ReactNativeJS: TypeError: undefined is not an object (evaluating 't.slice')
05-25 16:38:52.758  7373  7413 E ReactNativeJS: 
05-25 16:38:52.758  7373  7413 E ReactNativeJS: This error is located at:
05-25 16:38:52.758  7373  7413 E ReactNativeJS:     in h
05-25 16:38:52.758  7373  7413 E ReactNativeJS:     in RCTView
05-25 16:38:52.758  7373  7413 E ReactNativeJS:     in Unknown
05-25 16:38:52.758  7373  7413 E ReactNativeJS:     in RCTView
05-25 16:38:52.758  7373  7413 E ReactNativeJS:     in Unknown
05-25 16:38:52.758  7373  7413 E ReactNativeJS:     in RCTView
05-25 16:38:52.758  7373  7413 E ReactNativeJS:     in Unknown
05-25 16:38:52.758  7373  7413 E ReactNativeJS:     in Navigator
05-25 16:38:52.758  7373  7413 E ReactNativeJS:     in k
05-25 16:38:52.758  7373  7413 E ReactNativeJS:     in w
05-25 16:38:52.758  7373  7413 E ReactNativeJS:     in RCTView
05-25 16:38:52.758  7373  7413 E ReactNativeJS:     in Unknown
05-25 16:38:52.758  7373  7413 E ReactNativeJS:     in RCTView
05-25 16:38:52.758  7373  7413 E ReactNativeJS:     in Unknown
05-25 16:38:52.758  7373  7413 E ReactNativeJS:     in E
05-25 16:38:52.762  7373  7413 D ReactNativeJS: [4:38:52:762] [ErrorHandler][Debug] IsFatal=true TypeError: undefined is not an object (evaluating 't.slice')
05-25 16:38:52.763  7373  7413 D ReactNativeJS: [4:38:52:763] [ErrorHandler][Debug] undefined is not an object (evaluating 't.slice')
05-25 16:38:52.774  7373  7413 D ReactNativeJS: [4:38:52:773] [ErrorHandler][Debug] Creating frame array
05-25 16:38:52.776  7373  7413 D ReactNativeJS: [4:38:52:776] [ErrorHandler][Debug] Notifying Bugsnag TypeError: Fatal error: undefined is not an object (evaluating 't.slice')"

**Comment by shashwatm1111** [comment]
Hey , I would like to work upon this issue . Kindly assign me this under C4GT .
