### ISSUE TITLE
Older fast sync uploads do not work with new app

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#988]
### How to reproduce
- Try setting up fast sync using an apk with release 3.38
- Install version 3.39 and start sync
- 
Expectation: Sync should work
Actual - Failure with error "unsupported idp type : null)"

(unsupported idp type : null)
![Fast sync failed.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/4bf12171-3320-4e7f-8989-1770853b12a0)

**Comment by vinayvenu** [comment]
@himeshr has put in a temp fix. We should ideally be replacing the contents of IdpType, url etc on the device once the db is replaced by a fast sync

**Comment by himeshr** [comment]
Reverted the temp fix and made code change to replace the settings with init values post applying fast-sync realm-db file.
Diff between prevSettings and newSettings after applying the fastSync realm file were as follows:
![Screenshot 2023-05-29 at 7.16.17 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/2b5f4531-1d47-423b-8b43-5d454c17540f)

**Comment by himeshr** [comment]
Code changes in avni-models and avni-client(3.39 branch).
Tested in pre-release using test@guat user.
