### ISSUE TITLE
[RWB] Not Updating the value in approval status cards 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#989]
[RWB] Not Updating the value in approval status cards 

Was not able to see approval statsus updated for entities after creating them - checked with Farmer, Workorder and Machine. No count is getting updated in Pending, so not able to proceed further with Approval itself.

Organisation:
RWB
user:
Utkarsh - primaryuser@rwb2023, utkarsh@rwb2023

**Comment by vinayvenu** [comment]
@AchalaBelokar can you please reproduce the issue, see if you can add a video, and clarify the card a bit more?

**Comment by AchalaBelokar** [comment]
@vinayvenu uploaded the video

https://images.zenhubusercontent.com/64590403/3fb2f51f-0801-44ed-a809-491d435abbcd/whatsapp_video_2023_05_31_at_12_57_43_pm__1_.mp4

**Comment by himeshr** [comment]
Possible regression caused due to Improve Approval sync, latestEntityApprovalStatus code changes.

**Comment by AchalaBelokar** [comment]
- [ ] I used this apk https://app.circleci.com/pipelines/github/avniproject/avni-client/1701/workflows/bc93e27f-0f59-4067-98dc-5b2df2b77a03/jobs/10708/artifacts
- [ ] still it is not reflecting

**Comment by petmongrels** [comment]
take the apk for this commit
#989 - call set method to update latest entity approval status
