### ISSUE TITLE
Fix UI for "Change Password" Screen (More section)

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-client#990]
The UI for "More" section -> "Change Password" Screen is not user-friendly, it lacks order and borders.
![Screenshot 2023-05-26 at 4.48.04 PM.png](https://images.zenhubusercontent.com/6261483184a61f6d60f9114a/24622102-962f-40e9-a11e-2145352d0f6c)

**Comment by shashwatm1111** [comment]
Hey , I would like to work upon this issue . Kindly assign me this under C4GT .

**Comment by vinayvenu** [comment]
Hi @shashwatm1111 there is no "Assign under C4GT". I have marked this as a good first issue, you can work on it if you want to.

**Comment by himeshr** [comment]
@sachsk pls add a screenshot of the end result after your code change..
to help with PR approval

**Comment by sachsk** [comment]
@himeshr 
<img width="489" alt="Screenshot 2024-01-29 at 2 24 25 PM" src="https://github.com/avniproject/avni-client/assets/36296658/44e22122-d290-4e8d-a257-1b30cb64b642">
