### ISSUE TITLE
 Incomplete Display of Encounter Types and concepts in Dashboard Card Filter

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#991]
When accessing the dashboard in the web app , the encounter types in the card filter are not fully visible in the drop down
Steps to reproduce:
Scenario 1:
1. login to avin app
2. click on the app designer
3. go to offline dasboard
4. click on edit
5. below we have the add filter option
6. it will popup the window named as create filter
7. Enter the filter name ,Select type as concept 
8. select the concept and scope as Encounter
9. Select Encounter type.
Excepted Result :  data listed in proper manner will not cutting the words
Actual Result : list is fully displayed in the dropdown 
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/20f70db6-7fef-490b-aac0-8ab18c72d78d)
Scenario 2:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/79552a1f-ed9d-4c7f-8711-fff17386047a)

**Comment by 1t5j0y** [comment]
@Dinesh2019 there will always be a limit to how many values in a drop down we can show. The user can scroll or search to get the required value. @vinayvenu please confirm if anything needs to be done about this and priority.

**Comment by mahalakshme** [comment]
@1t5j0y u r right. There is a scroll in the overlay popup which can be used to see all encounter types. But it took me some time to realise, I thought it is cut. So I ll add a scroll to the drop down, like we have for the Type.
