### ISSUE TITLE
ProgramEncounter{uuid='xxx'} is unable to find ProgramEnrolment{uuid='yyy'} = BugSnag Error (Avni Client)

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#995]
**BugSnag Error**
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/6467039ef7addb0007def7b2

**Management of BugSnag error and BugSnag**
https://avni.readme.io/docs/how-to-use-bugsnag

**Comment by vinayvenu** [comment]
Closing. Invalid link
