### ISSUE TITLE
Unknown ServerError should be handled instead of thrown to bugsnag - BugSnag Error (Avni Client)

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#996]
**BugSnag Error**
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/64672a5299ba2b00080b3a51

https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/646726a40f4cbc000882387a

**Management of BugSnag error and BugSnag**
https://avni.readme.io/docs/how-to-use-bugsnag

**Comment by vinayvenu** [comment]
Closing. Invalid link
