### ISSUE TITLE
Verify Number is not working for some orgnization..

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#997]
There is Organisation which contains verification for phone number.. 
When I am clicking on Verify number I got this msg.. "Error while sending The otp" 
env: pre-relese 
org name: Rwbniti

![Screenshot 2023-05-29 at 1.54.15 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/e26e5ea3-7a6a-40c2-8316-d7cd0fc8e4ab)

received application context.
05-29 13:53:31.302 10867 10867 D ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
05-29 13:53:32.057  5379  8163 W ActivityManager: Background start not allowed: service Intent { cmp=com.locon.housing/io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService (has extras) } to com.locon.housing/io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService from pid=10867 uid=10813 pkg=com.locon.housing startFg?=false
05-29 13:53:32.059 10867 10867 E RNFirebaseMsgReceiver: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.locon.housing/io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService (has extras) }: app is in background uid UidRecord{f6ac047 u0a813 RCVR idle change:idle|uncached procs:0 seq(0,0,0)}
05-29 13:53:32.059 10867 10867 E RNFirebaseMsgReceiver: 	at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingReceiver.onReceive(ReactNativeFirebaseMessagingReceiver.java:16)
05-29 13:58:33.856 18017 18063 D ReactNativeJS: [1:58:33:852] [Router][Debug] renderScene: Current Routes: /landingView,/personRegister,/PersonRegisterFormView. Route: /PersonRegisterFormView
05-29 13:58:33.861 18017 18063 D ReactNativeJS: [1:58:33:860] [PersonRegisterFormView][Debug] render
05-29 13:58:36.660 18017 18063 D ReactNativeJS: [1:58:36:660] [TypedTransition][Debug] Route size: 3
05-29 13:58:36.664 18017 18063 D ReactNativeJS: [1:58:36:663] [Router][Debug] renderScene: Current Routes: /landingView,/personRegister,/PersonRegisterFormView,/phoneNumberVerificationView. Route: /PersonRegisterFormView
05-29 13:58:36.665 18017 18063 D ReactNativeJS: [1:58:36:664] [Router][Debug] Using cached route: /PersonRegisterFormView. Element map path: /PersonRegisterFormView
05-29 13:58:36.666 18017 18063 D ReactNativeJS: [1:58:36:665] [Router][Debug] renderScene: Current Routes: /landingView,/personRegister,/PersonRegisterFormView,/phoneNumberVerificationView. Route: /phoneNumberVerificationView
05-29 13:58:36.685 18017 18063 D ReactNativeJS: [1:58:36:684] [Requests][Debug] POST: https://prerelease.avniproject.org/phoneNumberVerification/otp/send
05-29 13:58:36.768 18017 18064 W unknown:ReactNative: Attempt to set local data for view with unknown tag: -1
05-29 13:58:36.769 18017 18064 W unknown:ReactNative: Attempt to set local data for view with unknown tag: -1
05-29 13:58:36.770 18017 18063 I ReactNativeJS: [1:58:36:769] [CognitoAuthService][Info] Found token

**Comment by vinayvenu** [comment]
@AchalaBelokar is msg91 setup for this organisation?

**Comment by mahalakshme** [comment]
@AchalaBelokar I see msg91 is not setup for the mentioned org. try again after setting it up. or try in an organisation where it is already setup.  moving this card to in analysis and assigning ur name.

**Comment by mahalakshme** [comment]
The issue was we were using data dump of prod in prerelease env, but were using different msg91 encryption keys. Correcting it in openchs.conf fixed the issue. No code changes done.

**Comment by mahalakshme** [comment]
changed this to 3.39 release since this was identified in prerelease and env issue.
