### ISSUE TITLE
Translation are missing on forgot password field 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#998]
Translation are missing on forgot password field 
steps to reproduce 

- On login page click on forgot password.
- Enter the wrong  username and client id 

Expectation : the translation should be there
Actual: username/ Client id combination  not found.
![Screenshot 2023-05-30 at 10.54.44 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/eb800bd2-f96b-4d18-9145-7f3302996b0e)

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-05-30 at 4.40.33 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/57a6cb13-6cf6-4c01-bba8-77240127f441)

- [ ] can you fix this also

**Comment by 1t5j0y** [comment]
done.
