### ISSUE TITLE
Reduce spacing between cards in the dashboard

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#999]
Reducing space will result in lesser scrolling

![Too much space.jpeg](https://images.zenhubusercontent.com/5d0b1ec92fff8629577fc2ef/b45c4838-c54f-4e5c-8381-857105637ed5)

**Comment by 1t5j0y** [comment]
![Screenshot_1685517431.png](https://images.zenhubusercontent.com/5d8a51c647755200010d2fda/4b64256f-8176-410e-a5aa-c4b7e3546524)

**Comment by arjunk** [comment]
the padding in the cards also seem extra, expecially top and bottom padding. we should also reduce that. it's towards the same goal of reducing the scroll for the user.

**Comment by 1t5j0y** [comment]
done.
![Screenshot_1685528370.png](https://images.zenhubusercontent.com/5d8a51c647755200010d2fda/b8e0160e-cb69-4bed-962e-16b51432c1ce)

**Comment by vinayvenu** [comment]
This needs to be tested with slightly longer text so we are sure we don't
cut any text.

Also do this with primary and secondary values to be sure.
